// Planning de chantier — screen texts (no React Native import: also used
// by the PDF builder in tests). The hook is in ./useCopy.

const fr = {
  title: 'Planning de chantier',
  hubHint: 'Phases, tâches, dépendances et avancement (Gantt).',
  emptyTitle: 'Pas encore de planning pour ce chantier',
  planNeeded: 'Le planning de chantier est disponible dès le plan Équipe, pour les entreprises du bâtiment.',
  emptyText: 'Créez un planning vide ou partez du modèle « Villa » (13 étapes, durées indicatives, dépendances déjà reliées) — tout reste modifiable.',
  startDate: 'Début du chantier',
  createEmpty: 'Planning vide',
  createVilla: 'Modèle Villa',
  addPhase: 'Phase',
  addTask: 'Tâche',
  addMilestone: 'Jalon',
  zoomDay: 'Jour',
  zoomWeek: 'Semaine',
  zoomMonth: 'Mois',
  today: 'Aujourd’hui',
  hideDone: 'Masquer terminées',
  arrows: 'Flèches',
  allTrades: 'Tous les corps de métier',
  allStatus: 'Tous les statuts',
  lateOnly: 'En retard',
  exportPdf: 'Export PDF',
  exportAll: 'Exporter',
  fmtHintPdf: 'A3 paysage, prêt à imprimer ou à envoyer.',
  fmtHintExcel: 'Une ligne par phase, tâche et jalon : numéros, dates, durées, « après », avancement.',
  fmtHintProject: 'Fichier XML à ouvrir dans MS Project (ou ProjectLibre) : hiérarchie, durées, liens et calendrier.',
  fileDownload: 'Télécharger le fichier',
  history: 'Historique',
  calendar: 'Calendrier',
  calendarIntro: 'Jours travaillés, jours fériés et jours fermés : les durées et les enchaînements en tiennent compte.',
  workdaysLabel: 'Jours travaillés',
  weekdaysShort: ['Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa', 'Di'],
  cantonLabel: 'Jours fériés du canton',
  cantonGuessed: 'Déduit de l’adresse du chantier — modifiable',
  holidaysOn: 'Appliquer les jours fériés',
  closuresTitle: 'Vacances d’entreprise',
  closuresHint: 'Valables pour tous les plannings de l’entreprise (ex. congés du bâtiment).',
  closureDefault: 'Congés du bâtiment',
  addClosure: 'Ajouter une période',
  extraTitle: 'Jours fermés de ce chantier',
  addDay: 'Ajouter un jour',
  upcomingOff: 'Jours fermés des 12 prochains mois',
  noDaysOff: 'Aucun jour fermé.',
  remove: 'Retirer',
  calendarRecalc: 'Le calendrier a changé : les dates des tâches peuvent être recalculées.',
  saveTemplate: 'Enregistrer comme modèle',
  saveTemplateText: 'Le modèle garde les phases, tâches, jalons, corps de métier, durées et liens « après ». Pas les dates réelles, les entreprises ni l’avancement. Il apparaît dans le Catalogue.',
  templateName: 'Nom du modèle',
  templateDesc: 'Description (facultatif)',
  templateSaved: 'Modèle « {{name}} » enregistré dans le Catalogue.',
  yourTemplates: 'Vos modèles',
  catalogTab: 'Plannings',
  catalogHint: 'Pour créer un modèle : ouvrez le planning d’un chantier, puis « Enregistrer comme modèle ». Vos modèles sont proposés à la création de chaque nouveau planning.',
  builtIn: 'Modèle Cantia',
  rename: 'Renommer',
  noTemplates: 'Aucun modèle d’entreprise pour l’instant.',
  fromTemplate: 'Partir d’un modèle',
  templateStats: '{{p}} phases · {{t}} tâches · {{d}} jours ouvrables',
  workdays: 'Jours travaillés',
  colName: 'Phase / tâche',
  colTrade: 'Corps de métier',
  colStart: 'Début',
  colEnd: 'Fin',
  colDuration: 'Durée',
  colStatus: 'Statut',
  days: 'j',
  daysLate: '{{n}} j de retard',
  status: { todo: 'À planifier', planned: 'Planifié', in_progress: 'En cours', done: 'Terminé', blocked: 'Bloqué' },
  kind: { phase: 'Phase', task: 'Tâche', milestone: 'Jalon' },
  // form
  newItem: 'Nouvelle ligne',
  editItem: 'Modifier',
  name: 'Nom',
  type: 'Type',
  parent: 'Dans la phase',
  topLevel: '— Niveau principal —',
  start: 'Début',
  end: 'Fin',
  duration: 'Durée (jours ouvrables)',
  trade: 'Corps de métier',
  addTrade: 'Ajouter « {{name}} »',
  snapAfter: 'à la suite de « {{name}} »',
  addInPhase: 'Ajouter une tâche dans cette phase',
  snapped: 'Placée à la suite de « {{name}} ».',
  linkToo: 'Relier aussi',
  linked: 'Relié : « {{name}} » doit se terminer avant.',
  afterHint: 'Commence le {{date}}, juste après « {{name}} ».',
  tradeSearch: 'Chercher ou ajouter un corps de métier…',
  company: 'Entreprise intervenante',
  responsible: 'Responsable',
  nobody: 'Personne',
  team: 'Taille d’équipe',
  progress: 'Avancement',
  progressAuto: 'Calculé à partir des tâches',
  progressManual: 'Saisir à la main',
  predecessors: 'Commence après (fin → début)',
  noPredecessor: 'Aucune',
  fixed: 'Date fixe (ne pas décaler automatiquement)',
  notes: 'Notes',
  save: 'Enregistrer',
  cancel: 'Annuler',
  delete: 'Supprimer',
  duplicate: 'Dupliquer',
  moveUp: 'Monter',
  moveDown: 'Descendre',
  indent: 'Mettre dans la phase au-dessus',
  outdent: 'Remonter d’un niveau',
  deletePhaseConfirm: 'Cette phase contient {{n}} lignes : elles seront supprimées aussi.',
  deleteConfirm: 'Supprimer « {{name}} » ?',
  confirmDelete: 'Supprimer définitivement',
  crossesWeekend: 'Traverse une période non travaillée',
  planned: 'Prévu',
  actual: 'Réel',
  baseline: 'Plan initial : {{start}} → {{end}}',
  nameRequired: 'Le nom est obligatoire.',
  cycle: 'Ce lien créerait une boucle : une tâche ne peut pas dépendre d’elle-même.',
  // cascade
  cascadeTitle: 'Décaler la suite ?',
  cascadeSummary: 'Pour garder l’ordre des travaux, {{n}} tâche(s) qui suivent doivent être décalée(s).',
  cascadeSummaryBy: 'Pour garder l’ordre des travaux, {{n}} tâche(s) qui suivent seront décalée(s) de {{d}} jour(s) ouvrable(s).',
  cascadeIntro: 'Ces tâches dépendent de ce que vous venez de changer et commencent maintenant trop tôt :',
  cascadeConflicts: 'Dates fixes ou tâches terminées : non décalées, à vérifier :',
  cascadeNeeds: 'devrait commencer le {{date}}',
  cascadeApply: 'Décaler ces tâches',
  cascadeSkip: 'Ne rien décaler',
  conflictBadge: 'Conflit de dépendance',
  // phone / misc
  phoneHint: 'Consultation : l’édition du planning se fait sur ordinateur ou tablette.',
  readOnly: 'Lecture seule',
  pdfTitle: 'Planning de chantier',
  pdfGenerated: 'Généré le {{date}}',
  pdfPeriod: 'Période',
  pdfPhases: 'Phases à imprimer',
  pdfAll: 'Tout le planning',
  pdfFrom: 'Du',
  pdfTo: 'Au',
  pdfDownload: 'Télécharger le PDF',
  pdfBrand: 'Ajouter le logo et le nom de l’entreprise',
  pdfBrandHint: 'En-tête à vos couleurs, pour envoyer le planning au client ou aux entreprises.',
  pdfLegend: 'Légende',
  pdfLate: 'En retard',
  pdfDone: 'Terminé',
  pdfMilestone: 'Jalon',
  historyEmpty: 'Aucune modification enregistrée.',
  field: { created: 'créé', deleted: 'supprimé', start_date: 'début', end_date: 'fin', duration: 'durée', status: 'statut', progress: 'avancement', company: 'entreprise', responsible_user_id: 'responsable', trade: 'corps de métier', name: 'nom', dependency: 'dépendance' },
  weekdays: ['Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa', 'Di'],
  months: ['janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin', 'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.'],
  weekShort: 'S',
  saving: 'Enregistrement…',
};

type Copy = typeof fr;

const de: Copy = {
  ...fr,
  title: 'Bauprogramm',
  hubHint: 'Phasen, Aufgaben, Abhängigkeiten und Fortschritt (Gantt).',
  emptyTitle: 'Noch kein Bauprogramm für diese Baustelle',
  planNeeded: 'Das Bauprogramm ist ab dem Plan Team für Baufirmen verfügbar.',
  emptyText: 'Leeres Programm erstellen oder mit der Vorlage « Einfamilienhaus » starten (13 Schritte, Richtdauern, Abhängigkeiten verknüpft) — alles bleibt änderbar.',
  startDate: 'Baubeginn',
  createEmpty: 'Leeres Programm',
  createVilla: 'Vorlage Einfamilienhaus',
  addPhase: 'Phase',
  addTask: 'Aufgabe',
  addMilestone: 'Meilenstein',
  zoomDay: 'Tag',
  zoomWeek: 'Woche',
  zoomMonth: 'Monat',
  today: 'Heute',
  hideDone: 'Erledigte ausblenden',
  arrows: 'Pfeile',
  allTrades: 'Alle Gewerke',
  allStatus: 'Alle Status',
  lateOnly: 'Verspätet',
  exportPdf: 'PDF-Export',
  exportAll: 'Exportieren',
  fmtHintPdf: 'A3 quer, bereit zum Drucken oder Versenden.',
  fmtHintExcel: 'Eine Zeile pro Phase, Aufgabe und Meilenstein: Nummern, Daten, Dauern, „nach“, Fortschritt.',
  fmtHintProject: 'XML-Datei für MS Project (oder ProjectLibre): Struktur, Dauern, Verknüpfungen und Kalender.',
  fileDownload: 'Datei herunterladen',
  history: 'Verlauf',
  calendar: 'Kalender',
  calendarIntro: 'Arbeitstage, Feiertage und Betriebsferien: Dauern und Abfolgen berücksichtigen sie.',
  workdaysLabel: 'Arbeitstage',
  weekdaysShort: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
  cantonLabel: 'Feiertage des Kantons',
  cantonGuessed: 'Aus der Baustellenadresse abgeleitet — änderbar',
  holidaysOn: 'Feiertage berücksichtigen',
  closuresTitle: 'Betriebsferien',
  closuresHint: 'Gelten für alle Bauprogramme des Unternehmens (z. B. Bauferien).',
  closureDefault: 'Bauferien',
  addClosure: 'Zeitraum hinzufügen',
  extraTitle: 'Freie Tage dieser Baustelle',
  addDay: 'Tag hinzufügen',
  upcomingOff: 'Freie Tage der nächsten 12 Monate',
  noDaysOff: 'Keine freien Tage.',
  remove: 'Entfernen',
  calendarRecalc: 'Der Kalender hat sich geändert: Die Daten der Aufgaben können neu berechnet werden.',
  saveTemplate: 'Als Vorlage speichern',
  saveTemplateText: 'Die Vorlage behält Phasen, Aufgaben, Meilensteine, Gewerke, Dauern und „nach“-Verknüpfungen. Keine echten Daten, Unternehmen oder Fortschritt. Sie erscheint im Katalog.',
  templateName: 'Name der Vorlage',
  templateDesc: 'Beschreibung (optional)',
  templateSaved: 'Vorlage „{{name}}“ im Katalog gespeichert.',
  yourTemplates: 'Ihre Vorlagen',
  catalogTab: 'Bauprogramme',
  catalogHint: 'Um eine Vorlage zu erstellen: Bauprogramm einer Baustelle öffnen, dann „Als Vorlage speichern“. Ihre Vorlagen werden bei jedem neuen Programm angeboten.',
  builtIn: 'Cantia-Vorlage',
  rename: 'Umbenennen',
  noTemplates: 'Noch keine Firmenvorlage.',
  fromTemplate: 'Von einer Vorlage ausgehen',
  templateStats: '{{p}} Phasen · {{t}} Aufgaben · {{d}} Arbeitstage',
  workdays: 'Arbeitstage',
  colName: 'Phase / Aufgabe',
  colTrade: 'Gewerk',
  colStart: 'Beginn',
  colEnd: 'Ende',
  colDuration: 'Dauer',
  colStatus: 'Status',
  days: 'T',
  daysLate: '{{n}} T Verzug',
  status: { todo: 'Zu planen', planned: 'Geplant', in_progress: 'In Arbeit', done: 'Erledigt', blocked: 'Blockiert' },
  kind: { phase: 'Phase', task: 'Aufgabe', milestone: 'Meilenstein' },
  newItem: 'Neue Zeile',
  editItem: 'Bearbeiten',
  name: 'Name',
  type: 'Typ',
  parent: 'In der Phase',
  topLevel: '— Oberste Ebene —',
  start: 'Beginn',
  end: 'Ende',
  duration: 'Dauer (Arbeitstage)',
  trade: 'Gewerk',
  addTrade: '« {{name}} » hinzufügen',
  snapAfter: 'direkt nach « {{name}} »',
  addInPhase: 'Aufgabe in dieser Phase hinzufügen',
  snapped: 'Direkt nach « {{name}} » platziert.',
  linkToo: 'Auch verknüpfen',
  linked: 'Verknüpft: « {{name}} » muss vorher fertig sein.',
  afterHint: 'Beginnt am {{date}}, direkt nach « {{name}} ».',
  tradeSearch: 'Gewerk suchen oder hinzufügen…',
  company: 'Ausführende Firma',
  responsible: 'Verantwortlich',
  nobody: 'Niemand',
  team: 'Teamgrösse',
  progress: 'Fortschritt',
  progressAuto: 'Aus den Aufgaben berechnet',
  progressManual: 'Von Hand eingeben',
  predecessors: 'Beginnt nach (Ende → Beginn)',
  noPredecessor: 'Keine',
  fixed: 'Fixes Datum (nicht automatisch verschieben)',
  notes: 'Notizen',
  save: 'Speichern',
  cancel: 'Abbrechen',
  delete: 'Löschen',
  duplicate: 'Duplizieren',
  moveUp: 'Nach oben',
  moveDown: 'Nach unten',
  indent: 'In die Phase darüber',
  outdent: 'Eine Ebene höher',
  deletePhaseConfirm: 'Diese Phase enthält {{n}} Zeilen: Sie werden ebenfalls gelöscht.',
  deleteConfirm: '« {{name}} » löschen?',
  confirmDelete: 'Endgültig löschen',
  crossesWeekend: 'Überspannt arbeitsfreie Tage',
  planned: 'Geplant',
  actual: 'Effektiv',
  baseline: 'Ursprünglicher Plan: {{start}} → {{end}}',
  nameRequired: 'Der Name ist erforderlich.',
  cycle: 'Diese Verknüpfung würde eine Schleife bilden.',
  cascadeTitle: 'Nachfolgendes verschieben?',
  cascadeSummary: 'Damit die Reihenfolge stimmt, müssen {{n}} nachfolgende Aufgabe(n) verschoben werden.',
  cascadeSummaryBy: 'Damit die Reihenfolge stimmt, werden {{n}} nachfolgende Aufgabe(n) um {{d}} Arbeitstag(e) verschoben.',
  cascadeIntro: 'Diese Aufgaben hängen von Ihrer Änderung ab und beginnen jetzt zu früh:',
  cascadeConflicts: 'Fixe Daten oder erledigte Aufgaben: nicht verschoben, bitte prüfen:',
  cascadeNeeds: 'sollte am {{date}} beginnen',
  cascadeApply: 'Diese Aufgaben verschieben',
  cascadeSkip: 'Nichts verschieben',
  conflictBadge: 'Abhängigkeitskonflikt',
  phoneHint: 'Ansicht: Das Programm wird am Computer oder Tablet bearbeitet.',
  readOnly: 'Nur Ansicht',
  pdfTitle: 'Bauprogramm',
  pdfGenerated: 'Erstellt am {{date}}',
  pdfPeriod: 'Zeitraum',
  pdfPhases: 'Zu druckende Phasen',
  pdfAll: 'Ganzes Programm',
  pdfFrom: 'Von',
  pdfTo: 'Bis',
  pdfDownload: 'PDF herunterladen',
  pdfBrand: 'Logo und Firmennamen hinzufügen',
  pdfBrandHint: 'Kopfzeile mit Ihrem Logo, um das Programm an Bauherrschaft oder Unternehmen zu senden.',
  pdfLegend: 'Legende',
  pdfLate: 'Verspätet',
  pdfDone: 'Erledigt',
  pdfMilestone: 'Meilenstein',
  historyEmpty: 'Keine Änderungen erfasst.',
  field: { created: 'erstellt', deleted: 'gelöscht', start_date: 'Beginn', end_date: 'Ende', duration: 'Dauer', status: 'Status', progress: 'Fortschritt', company: 'Firma', responsible_user_id: 'Verantwortlich', trade: 'Gewerk', name: 'Name', dependency: 'Abhängigkeit' },
  weekdays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
  months: ['Jan.', 'Feb.', 'März', 'Apr.', 'Mai', 'Juni', 'Juli', 'Aug.', 'Sept.', 'Okt.', 'Nov.', 'Dez.'],
  weekShort: 'KW',
  saving: 'Speichern…',
};

const it: Copy = {
  ...fr,
  title: 'Programma lavori',
  hubHint: 'Fasi, attività, dipendenze e avanzamento (Gantt).',
  emptyTitle: 'Ancora nessun programma per questo cantiere',
  planNeeded: 'Il programma lavori è disponibile dal piano Team, per le imprese edili.',
  emptyText: 'Create un programma vuoto o partite dal modello « Villa » (13 fasi, durate indicative, dipendenze già collegate) — tutto resta modificabile.',
  startDate: 'Inizio del cantiere',
  createEmpty: 'Programma vuoto',
  createVilla: 'Modello Villa',
  addPhase: 'Fase',
  addTask: 'Attività',
  addMilestone: 'Traguardo',
  zoomDay: 'Giorno',
  zoomWeek: 'Settimana',
  zoomMonth: 'Mese',
  today: 'Oggi',
  hideDone: 'Nascondere terminate',
  arrows: 'Frecce',
  allTrades: 'Tutti i mestieri',
  allStatus: 'Tutti gli stati',
  lateOnly: 'In ritardo',
  exportPdf: 'Esporta PDF',
  exportAll: 'Esportare',
  fmtHintPdf: 'A3 orizzontale, pronto da stampare o inviare.',
  fmtHintExcel: 'Una riga per fase, attività e milestone: numeri, date, durate, « dopo », avanzamento.',
  fmtHintProject: 'File XML da aprire in MS Project (o ProjectLibre): struttura, durate, collegamenti e calendario.',
  fileDownload: 'Scaricare il file',
  history: 'Cronologia',
  calendar: 'Calendario',
  calendarIntro: 'Giorni lavorativi, festivi e chiusure: durate e sequenze ne tengono conto.',
  workdaysLabel: 'Giorni lavorativi',
  weekdaysShort: ['Lu', 'Ma', 'Me', 'Gi', 'Ve', 'Sa', 'Do'],
  cantonLabel: 'Festivi del cantone',
  cantonGuessed: 'Dedotto dall’indirizzo del cantiere — modificabile',
  holidaysOn: 'Applicare i festivi',
  closuresTitle: 'Ferie aziendali',
  closuresHint: 'Valide per tutti i programmi dell’impresa (es. ferie dell’edilizia).',
  closureDefault: 'Ferie dell’edilizia',
  addClosure: 'Aggiungere un periodo',
  extraTitle: 'Giorni di chiusura di questo cantiere',
  addDay: 'Aggiungere un giorno',
  upcomingOff: 'Giorni di chiusura dei prossimi 12 mesi',
  noDaysOff: 'Nessun giorno di chiusura.',
  remove: 'Togliere',
  calendarRecalc: 'Il calendario è cambiato: le date delle attività possono essere ricalcolate.',
  saveTemplate: 'Salvare come modello',
  saveTemplateText: 'Il modello conserva fasi, attività, milestone, categorie di lavoro, durate e collegamenti « dopo ». Non le date reali, le imprese né l’avanzamento. Appare nel Catalogo.',
  templateName: 'Nome del modello',
  templateDesc: 'Descrizione (facoltativa)',
  templateSaved: 'Modello « {{name}} » salvato nel Catalogo.',
  yourTemplates: 'I vostri modelli',
  catalogTab: 'Programmi',
  catalogHint: 'Per creare un modello: aprite il programma di un cantiere, poi « Salvare come modello ». I vostri modelli sono proposti alla creazione di ogni nuovo programma.',
  builtIn: 'Modello Cantia',
  rename: 'Rinominare',
  noTemplates: 'Ancora nessun modello aziendale.',
  fromTemplate: 'Partire da un modello',
  templateStats: '{{p}} fasi · {{t}} attività · {{d}} giorni lavorativi',
  workdays: 'Giorni lavorativi',
  colName: 'Fase / attività',
  colTrade: 'Mestiere',
  colStart: 'Inizio',
  colEnd: 'Fine',
  colDuration: 'Durata',
  colStatus: 'Stato',
  days: 'g',
  daysLate: '{{n}} g di ritardo',
  status: { todo: 'Da pianificare', planned: 'Pianificato', in_progress: 'In corso', done: 'Terminato', blocked: 'Bloccato' },
  kind: { phase: 'Fase', task: 'Attività', milestone: 'Traguardo' },
  newItem: 'Nuova riga',
  editItem: 'Modificare',
  name: 'Nome',
  type: 'Tipo',
  parent: 'Nella fase',
  topLevel: '— Livello principale —',
  start: 'Inizio',
  end: 'Fine',
  duration: 'Durata (giorni lavorativi)',
  trade: 'Mestiere',
  addTrade: 'Aggiungere « {{name}} »',
  snapAfter: 'subito dopo « {{name}} »',
  addInPhase: 'Aggiungere un’attività in questa fase',
  snapped: 'Posizionata subito dopo « {{name}} ».',
  linkToo: 'Collegare anche',
  linked: 'Collegata: « {{name}} » deve finire prima.',
  afterHint: 'Inizia il {{date}}, subito dopo « {{name}} ».',
  tradeSearch: 'Cercare o aggiungere un mestiere…',
  company: 'Impresa',
  responsible: 'Responsabile',
  nobody: 'Nessuno',
  team: 'Dimensione squadra',
  progress: 'Avanzamento',
  progressAuto: 'Calcolato dalle attività',
  progressManual: 'Inserire a mano',
  predecessors: 'Inizia dopo (fine → inizio)',
  noPredecessor: 'Nessuna',
  fixed: 'Data fissa (non spostare automaticamente)',
  notes: 'Note',
  save: 'Salvare',
  cancel: 'Annullare',
  delete: 'Eliminare',
  duplicate: 'Duplicare',
  moveUp: 'Su',
  moveDown: 'Giù',
  indent: 'Nella fase sopra',
  outdent: 'Un livello più su',
  deletePhaseConfirm: 'Questa fase contiene {{n}} righe: saranno eliminate anch’esse.',
  deleteConfirm: 'Eliminare « {{name}} »?',
  confirmDelete: 'Eliminare definitivamente',
  crossesWeekend: 'Attraversa giorni non lavorativi',
  planned: 'Previsto',
  actual: 'Effettivo',
  baseline: 'Piano iniziale: {{start}} → {{end}}',
  nameRequired: 'Il nome è obbligatorio.',
  cycle: 'Questo collegamento creerebbe un ciclo.',
  cascadeTitle: 'Spostare il seguito?',
  cascadeSummary: 'Per mantenere l’ordine dei lavori, {{n}} attività successive devono essere spostate.',
  cascadeSummaryBy: 'Per mantenere l’ordine dei lavori, {{n}} attività successive saranno spostate di {{d}} giorni lavorativi.',
  cascadeIntro: 'Queste attività dipendono dalla vostra modifica e ora iniziano troppo presto:',
  cascadeConflicts: 'Date fisse o attività terminate: non spostate, da verificare:',
  cascadeNeeds: 'dovrebbe iniziare il {{date}}',
  cascadeApply: 'Spostare queste attività',
  cascadeSkip: 'Non spostare nulla',
  conflictBadge: 'Conflitto di dipendenza',
  phoneHint: 'Consultazione: il programma si modifica su computer o tablet.',
  readOnly: 'Sola lettura',
  pdfTitle: 'Programma lavori',
  pdfGenerated: 'Generato il {{date}}',
  pdfPeriod: 'Periodo',
  pdfPhases: 'Fasi da stampare',
  pdfAll: 'Tutto il programma',
  pdfFrom: 'Dal',
  pdfTo: 'Al',
  pdfDownload: 'Scaricare il PDF',
  pdfBrand: 'Aggiungere logo e nome dell’impresa',
  pdfBrandHint: 'Intestazione con il vostro logo, per inviare il programma al committente o alle imprese.',
  pdfLegend: 'Legenda',
  pdfLate: 'In ritardo',
  pdfDone: 'Terminato',
  pdfMilestone: 'Traguardo',
  historyEmpty: 'Nessuna modifica registrata.',
  field: { created: 'creato', deleted: 'eliminato', start_date: 'inizio', end_date: 'fine', duration: 'durata', status: 'stato', progress: 'avanzamento', company: 'impresa', responsible_user_id: 'responsabile', trade: 'mestiere', name: 'nome', dependency: 'dipendenza' },
  weekdays: ['Lu', 'Ma', 'Me', 'Gi', 'Ve', 'Sa', 'Do'],
  months: ['gen.', 'feb.', 'mar.', 'apr.', 'mag.', 'giu.', 'lug.', 'ago.', 'set.', 'ott.', 'nov.', 'dic.'],
  weekShort: 'S',
  saving: 'Salvataggio…',
};

export const SCHEDULE_COPY: Record<string, Copy> = { fr, de, it };

export type ScheduleCopy = Copy;

export function fill(t: string, vars: Record<string, string | number>): string {
  return t.replace(/\{\{(\w+)\}\}/g, (_, k) => String(vars[k] ?? ''));
}

// "12.10.26" — compact Swiss date for tables and bars.
export function shortDate(iso: string | null): string {
  if (!iso) return '—';
  return `${iso.slice(8, 10)}.${iso.slice(5, 7)}.${iso.slice(2, 4)}`;
}
