import type { AppLocale } from '../translations';

// Copy of the year-end closing assistant (app/(app)/compta/bouclement.tsx)
// and of the Fiscalité & provisions page. {{x}} = placeholders.

const fr = {
  title: 'Bouclement {{year}}',
  subtitle: 'L’assistant prépare les écritures de fin d’année. Vous les relisez, les validez, puis vous verrouillez l’exercice et le transmettez à votre fiduciaire.',
  howTitle: 'Comment ça marche',
  how: [
    'Les contrôles vérifient que la comptabilité est complète : écritures validées, banque rapprochée, TVA déclarée.',
    'Chaque étape propose une écriture de bouclement calculée à partir de vos soldes. Vous ajustez les montants si besoin.',
    '« Préparer l’écriture » la crée en brouillon : rien n’est comptabilisé tant que vous ne l’avez pas validée dans Écritures.',
    'L’analyse IA relit le tout et signale ce qui mérite une question à la fiduciaire.',
    'Quand tout est vert, vous verrouillez l’exercice et le transmettez.',
  ],
  year: 'Exercice',
  noYear: 'Aucun exercice comptable. Créez-en un dans Comptabilité pour démarrer le bouclement.',
  notSaved: 'Vos saisies ne sont pas encore enregistrées sur le serveur (mise à jour de la base en attente). Les écritures, elles, sont bien créées.',
  resultBefore: 'Résultat avant bouclement',
  impact: 'Effet des écritures proposées',
  resultAfter: 'Résultat après bouclement',
  stepDone: 'Écriture préparée',
  prepare: 'Préparer l’écriture',
  prepareAgain: 'Mettre à jour l’écriture',
  nothingToBook: 'Rien à comptabiliser pour cette étape.',
  prepared: 'Écriture créée en brouillon : validez-la dans Comptabilité › Écritures.',
  why: 'Pourquoi ?',
  account: 'Compte',
  debit: 'Débit',
  credit: 'Crédit',

  s1: 'Contrôles',
  s1why: 'Un bouclement ne se fait que sur une comptabilité complète et équilibrée. Les points rouges bloquent le verrouillage ; les orange sont à vérifier.',
  checks: {
    drafts: { ok: 'Toutes les écritures de l’exercice sont validées', bad: '{{n}} écriture(s) encore en brouillon' },
    bank_matching: { ok: 'Mouvements bancaires tous rapprochés', bad: '{{n}} mouvement(s) bancaire(s) non rapproché(s)' },
    trial_balance: { ok: 'La balance est équilibrée (débit = crédit)', bad: 'Écart débit / crédit de CHF {{v}}' },
    bank_reconciliation: { ok: 'Le compte 1020 Banque correspond au relevé', bad: 'Écart de CHF {{v}} entre le compte 1020 et le dernier relevé' },
    vat: { ok: 'Toutes les périodes de TVA échues sont déclarées', bad: '{{n}} période(s) de TVA échue(s) non déclarée(s)' },
    balance_sheet: { ok: 'Le bilan est équilibré', bad: 'Écart au bilan de CHF {{v}}' },
  },
  openEntries: 'Ouvrir les écritures',
  openVat: 'Ouvrir le décompte TVA',

  s2: 'Forme juridique',
  s2why: 'Elle détermine l’impôt : une Sàrl ou une SA paie l’impôt sur le bénéfice ; une raison individuelle ne paie pas d’impôt d’entreprise, le titulaire est imposé personnellement et paie l’AVS d’indépendant.',
  forms: { ri: 'Raison individuelle', sarl: 'Sàrl', sa: 'SA' },

  s3: 'Débiteurs douteux (ducroire)',
  s3why: 'Une partie des factures ouvertes ne sera jamais payée. L’administration fiscale admet sans justificatif une provision forfaitaire de 5 % des débiteurs suisses et 10 % des débiteurs étrangers. Seule la variation par rapport à l’an passé est comptabilisée.',
  swissDebtors: 'Débiteurs suisses (compte 1100)',
  foreignDebtors: 'Dont débiteurs étrangers',
  currentProvision: 'Ducroire actuel (1109)',
  targetProvision: 'Ducroire cible',

  s4: 'Amortissements',
  s4why: 'Les machines, véhicules et l’informatique perdent de la valeur chaque année. Les taux ci-dessous sont les taux maximaux admis par l’AFC (méthode dégressive, sur la valeur comptable). Répartissez la valeur de vos immobilisations (compte 1600, net des amortissements cumulés) par catégorie.',
  netAssets: 'Valeur nette des immobilisations : CHF {{v}}',
  bookValue: 'Valeur comptable',
  rate: 'Taux %',
  depreciationTotal: 'Amortissement de l’exercice',

  s5: 'Transitoires',
  s5why: 'Rattachez chaque charge et chaque produit à la bonne année : une assurance payée en décembre pour l’année suivante, une facture de décembre reçue en janvier, un travail fait mais pas encore facturé, un acompte encaissé pour l’an prochain.',
  accrualKinds: {
    prepaid_expense: 'Charge payée d’avance',
    accrued_expense: 'Charge à payer',
    accrued_income: 'Produit à recevoir',
    deferred_income: 'Produit encaissé d’avance',
  },
  accrualLabel: 'Libellé (p. ex. Assurance RC 2027)',
  amount: 'Montant',
  addAccrual: 'Ajouter',

  s6: 'Travaux en cours',
  s6why: 'Les chantiers commencés et pas encore facturés au 31 décembre ont une valeur (heures et matériel engagés). Indiquez leur valeur au prix de revient ; l’écriture ajuste le compte 1300.',
  wipValue: 'Valeur des travaux en cours au {{date}}',
  wipCurrent: 'Solde actuel du compte 1300 : CHF {{v}}',

  s7: 'Impôts',
  s7why: 'Provision pour les impôts sur le bénéfice (et le capital) de l’exercice, payés l’année suivante. Le taux proposé est un taux effectif indicatif du chef-lieu de votre canton (Confédération + canton + commune) : confirmez-le avec votre fiduciaire.',
  taxRate: 'Taux effectif (%)',
  capitalTax: 'Impôt sur le capital estimé (CHF)',
  profitBeforeTax: 'Bénéfice avant impôts : CHF {{v}}',
  taxDue: 'Impôts estimés : CHF {{v}}',
  riTax: 'Raison individuelle : pas d’impôt d’entreprise. Prévoyez l’impôt sur le revenu du titulaire et ses cotisations AVS d’indépendant (jusqu’à 10 % du bénéfice, soit environ CHF {{v}}).',

  s8: 'Analyse IA',
  s8why: 'Une relecture automatique de votre balance et des écritures préparées, comme le ferait un comptable : soldes inhabituels, provisions manquantes, questions à poser à la fiduciaire. Indicatif, rien n’est modifié.',
  runAi: 'Lancer l’analyse',
  aiRunning: 'Analyse en cours…',
  aiAt: 'Analyse du {{date}}',

  s9: 'Verrouiller et transmettre',
  s9why: 'Le verrouillage empêche toute nouvelle écriture sur l’exercice. Votre fiduciaire reçoit ensuite le dossier (balance, écritures, bouclement) et voit votre comptabilité en direct sur sa plateforme.',
  lock: 'Verrouiller l’exercice',
  lockConfirm: 'Verrouiller l’exercice {{year}} ?',
  lockConfirmText: 'Plus aucune écriture ne pourra être passée sur cet exercice. Votre fiduciaire pourra le rouvrir si nécessaire.',
  locked: 'Exercice verrouillé',
  blocked: 'Corrigez d’abord les points rouges des contrôles.',
  transmit: 'Transmettre à {{name}}',
  transmitNoFiduciary: 'Aucune fiduciaire connectée. Invitez la vôtre dans Paramètres › Fiduciaire, ou téléchargez le dossier.',
  transmitted: 'Transmis le {{date}}',
  download: 'Télécharger le dossier (CSV)',
  inviteFiduciary: 'Inviter ma fiduciaire',
};

export type ClosingCopy = typeof fr;

const de: ClosingCopy = {
  ...fr,
  title: 'Jahresabschluss {{year}}',
  subtitle: 'Der Assistent bereitet die Abschlussbuchungen vor. Sie prüfen und verbuchen sie, schliessen dann das Geschäftsjahr ab und übermitteln es Ihrem Treuhänder.',
  howTitle: 'So funktioniert es',
  how: [
    'Die Kontrollen prüfen, ob die Buchhaltung vollständig ist: Buchungen verbucht, Bank abgestimmt, MWST deklariert.',
    'Jeder Schritt schlägt eine Abschlussbuchung vor, berechnet aus Ihren Saldi. Sie passen die Beträge bei Bedarf an.',
    '«Buchung vorbereiten» erstellt sie als Entwurf: nichts wird verbucht, bevor Sie es unter Buchungen bestätigen.',
    'Die KI-Analyse liest alles durch und zeigt, was Sie mit dem Treuhänder klären sollten.',
    'Wenn alles grün ist, schliessen Sie das Geschäftsjahr ab und übermitteln es.',
  ],
  year: 'Geschäftsjahr',
  noYear: 'Kein Geschäftsjahr. Erstellen Sie eines in der Buchhaltung, um den Abschluss zu starten.',
  notSaved: 'Ihre Eingaben sind noch nicht auf dem Server gespeichert (Datenbank-Update ausstehend). Die Buchungen werden aber erstellt.',
  resultBefore: 'Ergebnis vor Abschluss',
  impact: 'Wirkung der vorgeschlagenen Buchungen',
  resultAfter: 'Ergebnis nach Abschluss',
  stepDone: 'Buchung vorbereitet',
  prepare: 'Buchung vorbereiten',
  prepareAgain: 'Buchung aktualisieren',
  nothingToBook: 'Für diesen Schritt ist nichts zu buchen.',
  prepared: 'Buchung als Entwurf erstellt: bestätigen Sie sie unter Buchhaltung › Buchungen.',
  why: 'Warum?',
  account: 'Konto',
  debit: 'Soll',
  credit: 'Haben',
  s1: 'Kontrollen',
  s1why: 'Ein Abschluss setzt eine vollständige, ausgeglichene Buchhaltung voraus. Rote Punkte blockieren den Abschluss, orange sind zu prüfen.',
  checks: {
    drafts: { ok: 'Alle Buchungen des Jahres sind verbucht', bad: '{{n}} Buchung(en) noch im Entwurf' },
    bank_matching: { ok: 'Alle Bankbewegungen abgestimmt', bad: '{{n}} Bankbewegung(en) nicht abgestimmt' },
    trial_balance: { ok: 'Die Saldenbilanz ist ausgeglichen (Soll = Haben)', bad: 'Differenz Soll / Haben von CHF {{v}}' },
    bank_reconciliation: { ok: 'Konto 1020 Bank stimmt mit dem Auszug überein', bad: 'Differenz von CHF {{v}} zwischen Konto 1020 und dem letzten Auszug' },
    vat: { ok: 'Alle fälligen MWST-Perioden sind deklariert', bad: '{{n}} fällige MWST-Periode(n) nicht deklariert' },
    balance_sheet: { ok: 'Die Bilanz ist ausgeglichen', bad: 'Bilanzdifferenz von CHF {{v}}' },
  },
  openEntries: 'Buchungen öffnen',
  openVat: 'MWST-Abrechnung öffnen',
  s2: 'Rechtsform',
  s2why: 'Sie bestimmt die Steuer: eine GmbH oder AG zahlt Gewinnsteuer; ein Einzelunternehmen zahlt keine Unternehmenssteuer, der Inhaber wird persönlich besteuert und zahlt AHV als Selbständigerwerbender.',
  forms: { ri: 'Einzelunternehmen', sarl: 'GmbH', sa: 'AG' },
  s3: 'Delkredere',
  s3why: 'Ein Teil der offenen Rechnungen wird nie bezahlt. Die Steuerverwaltung akzeptiert ohne Nachweis eine Pauschale von 5 % der inländischen und 10 % der ausländischen Debitoren. Gebucht wird nur die Veränderung gegenüber dem Vorjahr.',
  swissDebtors: 'Debitoren Inland (Konto 1100)',
  foreignDebtors: 'Davon ausländische Debitoren',
  currentProvision: 'Aktuelles Delkredere (1109)',
  targetProvision: 'Ziel-Delkredere',
  s4: 'Abschreibungen',
  s4why: 'Maschinen, Fahrzeuge und Informatik verlieren jedes Jahr an Wert. Die Sätze unten sind die von der ESTV zugelassenen Höchstsätze (degressiv, auf dem Buchwert). Verteilen Sie den Wert Ihrer Anlagen (Konto 1600, abzüglich kumulierter Abschreibungen) nach Kategorie.',
  netAssets: 'Nettowert der Anlagen: CHF {{v}}',
  bookValue: 'Buchwert',
  rate: 'Satz %',
  depreciationTotal: 'Abschreibung des Jahres',
  s5: 'Rechnungsabgrenzungen',
  s5why: 'Ordnen Sie jeden Aufwand und Ertrag dem richtigen Jahr zu: eine im Dezember für das Folgejahr bezahlte Versicherung, eine Dezemberrechnung, die im Januar eintrifft, eine erbrachte, noch nicht fakturierte Leistung, eine Anzahlung für das nächste Jahr.',
  accrualKinds: {
    prepaid_expense: 'Vorausbezahlter Aufwand',
    accrued_expense: 'Noch zu zahlender Aufwand',
    accrued_income: 'Noch nicht erhaltener Ertrag',
    deferred_income: 'Im Voraus erhaltener Ertrag',
  },
  accrualLabel: 'Bezeichnung (z. B. Haftpflichtversicherung 2027)',
  amount: 'Betrag',
  addAccrual: 'Hinzufügen',
  s6: 'Angefangene Arbeiten',
  s6why: 'Begonnene, am 31. Dezember noch nicht fakturierte Baustellen haben einen Wert (geleistete Stunden und Material). Geben Sie ihren Wert zu Herstellkosten an; die Buchung passt Konto 1300 an.',
  wipValue: 'Wert der angefangenen Arbeiten am {{date}}',
  wipCurrent: 'Aktueller Saldo Konto 1300: CHF {{v}}',
  s7: 'Steuern',
  s7why: 'Rückstellung für die Gewinn- (und Kapital-)steuern des Jahres, die im Folgejahr bezahlt werden. Der vorgeschlagene Satz ist ein indikativer effektiver Satz des Kantonshauptorts (Bund + Kanton + Gemeinde): bestätigen Sie ihn mit Ihrem Treuhänder.',
  taxRate: 'Effektiver Satz (%)',
  capitalTax: 'Geschätzte Kapitalsteuer (CHF)',
  profitBeforeTax: 'Gewinn vor Steuern: CHF {{v}}',
  taxDue: 'Geschätzte Steuern: CHF {{v}}',
  riTax: 'Einzelunternehmen: keine Unternehmenssteuer. Planen Sie die Einkommenssteuer des Inhabers und seine AHV-Beiträge als Selbständigerwerbender ein (bis 10 % des Gewinns, rund CHF {{v}}).',
  s8: 'KI-Analyse',
  s8why: 'Eine automatische Durchsicht Ihrer Saldenbilanz und der vorbereiteten Buchungen, wie sie ein Buchhalter machen würde: ungewöhnliche Saldi, fehlende Rückstellungen, Fragen an den Treuhänder. Indikativ, nichts wird geändert.',
  runAi: 'Analyse starten',
  aiRunning: 'Analyse läuft…',
  aiAt: 'Analyse vom {{date}}',
  s9: 'Abschliessen und übermitteln',
  s9why: 'Der Abschluss verhindert jede weitere Buchung im Geschäftsjahr. Ihr Treuhänder erhält danach das Dossier (Saldenbilanz, Buchungen, Abschluss) und sieht Ihre Buchhaltung live auf seiner Plattform.',
  lock: 'Geschäftsjahr abschliessen',
  lockConfirm: 'Geschäftsjahr {{year}} abschliessen?',
  lockConfirmText: 'Danach kann nichts mehr in diesem Geschäftsjahr gebucht werden. Ihr Treuhänder kann es bei Bedarf wieder öffnen.',
  locked: 'Geschäftsjahr abgeschlossen',
  blocked: 'Beheben Sie zuerst die roten Punkte der Kontrollen.',
  transmit: 'An {{name}} übermitteln',
  transmitNoFiduciary: 'Kein Treuhänder verbunden. Laden Sie Ihren unter Einstellungen › Treuhänder ein oder laden Sie das Dossier herunter.',
  transmitted: 'Übermittelt am {{date}}',
  download: 'Dossier herunterladen (CSV)',
  inviteFiduciary: 'Meinen Treuhänder einladen',
};

const it: ClosingCopy = {
  ...fr,
  title: 'Chiusura {{year}}',
  subtitle: 'L’assistente prepara le registrazioni di fine anno. Voi le rileggete e le convalidate, poi chiudete l’esercizio e lo trasmettete alla vostra fiduciaria.',
  howTitle: 'Come funziona',
  how: [
    'I controlli verificano che la contabilità sia completa: registrazioni convalidate, banca riconciliata, IVA dichiarata.',
    'Ogni passo propone una registrazione di chiusura calcolata dai vostri saldi. Adattate gli importi se necessario.',
    '«Preparare la registrazione» la crea in bozza: nulla è contabilizzato finché non la convalidate in Registrazioni.',
    'L’analisi IA rilegge tutto e segnala ciò che merita una domanda alla fiduciaria.',
    'Quando tutto è verde, chiudete l’esercizio e lo trasmettete.',
  ],
  year: 'Esercizio',
  noYear: 'Nessun esercizio contabile. Createne uno in Contabilità per iniziare la chiusura.',
  notSaved: 'I vostri dati non sono ancora salvati sul server (aggiornamento del database in attesa). Le registrazioni invece vengono create.',
  resultBefore: 'Risultato prima della chiusura',
  impact: 'Effetto delle registrazioni proposte',
  resultAfter: 'Risultato dopo la chiusura',
  stepDone: 'Registrazione preparata',
  prepare: 'Preparare la registrazione',
  prepareAgain: 'Aggiornare la registrazione',
  nothingToBook: 'Nulla da contabilizzare per questo passo.',
  prepared: 'Registrazione creata in bozza: convalidatela in Contabilità › Registrazioni.',
  why: 'Perché?',
  account: 'Conto',
  debit: 'Dare',
  credit: 'Avere',
  s1: 'Controlli',
  s1why: 'Una chiusura si fa solo su una contabilità completa ed equilibrata. I punti rossi bloccano la chiusura; quelli arancioni vanno verificati.',
  checks: {
    drafts: { ok: 'Tutte le registrazioni dell’esercizio sono convalidate', bad: '{{n}} registrazione/i ancora in bozza' },
    bank_matching: { ok: 'Movimenti bancari tutti riconciliati', bad: '{{n}} movimento/i bancario/i non riconciliato/i' },
    trial_balance: { ok: 'Il bilancio di verifica è equilibrato (dare = avere)', bad: 'Differenza dare / avere di CHF {{v}}' },
    bank_reconciliation: { ok: 'Il conto 1020 Banca corrisponde all’estratto', bad: 'Differenza di CHF {{v}} tra il conto 1020 e l’ultimo estratto' },
    vat: { ok: 'Tutti i periodi IVA scaduti sono dichiarati', bad: '{{n}} periodo/i IVA scaduto/i non dichiarato/i' },
    balance_sheet: { ok: 'Il bilancio è equilibrato', bad: 'Differenza di bilancio di CHF {{v}}' },
  },
  openEntries: 'Aprire le registrazioni',
  openVat: 'Aprire il rendiconto IVA',
  s2: 'Forma giuridica',
  s2why: 'Determina l’imposta: una Sagl o una SA paga l’imposta sull’utile; una ditta individuale non paga imposte d’impresa, il titolare è tassato personalmente e paga l’AVS come indipendente.',
  forms: { ri: 'Ditta individuale', sarl: 'Sagl', sa: 'SA' },
  s3: 'Delcredere',
  s3why: 'Una parte delle fatture aperte non sarà mai pagata. L’amministrazione fiscale ammette senza giustificativi un accantonamento forfettario del 5 % dei debitori svizzeri e del 10 % di quelli esteri. Si contabilizza solo la variazione rispetto all’anno precedente.',
  swissDebtors: 'Debitori svizzeri (conto 1100)',
  foreignDebtors: 'Di cui debitori esteri',
  currentProvision: 'Delcredere attuale (1109)',
  targetProvision: 'Delcredere obiettivo',
  s4: 'Ammortamenti',
  s4why: 'Macchine, veicoli e informatica perdono valore ogni anno. Le aliquote sotto sono le aliquote massime ammesse dall’AFC (metodo decrescente, sul valore contabile). Ripartite il valore delle immobilizzazioni (conto 1600, al netto degli ammortamenti cumulati) per categoria.',
  netAssets: 'Valore netto delle immobilizzazioni: CHF {{v}}',
  bookValue: 'Valore contabile',
  rate: 'Aliquota %',
  depreciationTotal: 'Ammortamento dell’esercizio',
  s5: 'Ratei e risconti',
  s5why: 'Attribuite ogni costo e ricavo all’anno giusto: un’assicurazione pagata a dicembre per l’anno seguente, una fattura di dicembre ricevuta a gennaio, un lavoro fatto ma non ancora fatturato, un acconto incassato per l’anno prossimo.',
  accrualKinds: {
    prepaid_expense: 'Costo pagato in anticipo',
    accrued_expense: 'Costo da pagare',
    accrued_income: 'Ricavo da ricevere',
    deferred_income: 'Ricavo incassato in anticipo',
  },
  accrualLabel: 'Descrizione (p. es. Assicurazione RC 2027)',
  amount: 'Importo',
  addAccrual: 'Aggiungere',
  s6: 'Lavori in corso',
  s6why: 'I cantieri iniziati e non ancora fatturati al 31 dicembre hanno un valore (ore e materiale impiegati). Indicatene il valore al costo; la registrazione adegua il conto 1300.',
  wipValue: 'Valore dei lavori in corso al {{date}}',
  wipCurrent: 'Saldo attuale del conto 1300: CHF {{v}}',
  s7: 'Imposte',
  s7why: 'Accantonamento per le imposte sull’utile (e sul capitale) dell’esercizio, pagate l’anno seguente. L’aliquota proposta è un’aliquota effettiva indicativa del capoluogo del vostro cantone (Confederazione + cantone + comune): confermatela con la vostra fiduciaria.',
  taxRate: 'Aliquota effettiva (%)',
  capitalTax: 'Imposta sul capitale stimata (CHF)',
  profitBeforeTax: 'Utile prima delle imposte: CHF {{v}}',
  taxDue: 'Imposte stimate: CHF {{v}}',
  riTax: 'Ditta individuale: nessuna imposta d’impresa. Prevedete l’imposta sul reddito del titolare e i suoi contributi AVS da indipendente (fino al 10 % dell’utile, circa CHF {{v}}).',
  s8: 'Analisi IA',
  s8why: 'Una rilettura automatica del bilancio di verifica e delle registrazioni preparate, come farebbe un contabile: saldi insoliti, accantonamenti mancanti, domande da porre alla fiduciaria. Indicativa, nulla viene modificato.',
  runAi: 'Avviare l’analisi',
  aiRunning: 'Analisi in corso…',
  aiAt: 'Analisi del {{date}}',
  s9: 'Chiudere e trasmettere',
  s9why: 'La chiusura impedisce ogni nuova registrazione sull’esercizio. La fiduciaria riceve poi il dossier (bilancio di verifica, registrazioni, chiusura) e vede la vostra contabilità in tempo reale sulla sua piattaforma.',
  lock: 'Chiudere l’esercizio',
  lockConfirm: 'Chiudere l’esercizio {{year}}?',
  lockConfirmText: 'Non sarà più possibile registrare nulla su questo esercizio. La fiduciaria potrà riaprirlo se necessario.',
  locked: 'Esercizio chiuso',
  blocked: 'Correggete prima i punti rossi dei controlli.',
  transmit: 'Trasmettere a {{name}}',
  transmitNoFiduciary: 'Nessuna fiduciaria collegata. Invitate la vostra in Impostazioni › Fiduciaria, o scaricate il dossier.',
  transmitted: 'Trasmesso il {{date}}',
  download: 'Scaricare il dossier (CSV)',
  inviteFiduciary: 'Invitare la mia fiduciaria',
};

export const CLOSING_COPY: Record<AppLocale, ClosingCopy> = { fr, de, it };

export const ASSET_LABELS: Record<AppLocale, Record<string, string>> = {
  fr: { machines: 'Machines et outillage', vehicules: 'Véhicules', informatique: 'Informatique et logiciels', mobilier: 'Mobilier et installations', outillage: 'Petit outillage, appareils', batiments: 'Bâtiments d’exploitation' },
  de: { machines: 'Maschinen und Werkzeuge', vehicules: 'Fahrzeuge', informatique: 'Informatik und Software', mobilier: 'Mobiliar und Einrichtungen', outillage: 'Kleinwerkzeuge, Geräte', batiments: 'Betriebsgebäude' },
  it: { machines: 'Macchine e attrezzature', vehicules: 'Veicoli', informatique: 'Informatica e software', mobilier: 'Mobilio e installazioni', outillage: 'Piccoli attrezzi, apparecchi', batiments: 'Edifici aziendali' },
};
