// Every string of accounting.cantia.ch (Cantia Accounting / Treuhand /
// Fiduciari), in the three languages of the site. Kept apart from
// lib/translations: the accounting build doesn't load the app's i18n.
export type AccLocale = 'fr' | 'de' | 'it';
export const ACC_LOCALES: AccLocale[] = ['fr', 'de', 'it'];

export const SOFTWARE = ['BEXIO', 'WINBIZ', 'CRESUS', 'ODOO', 'ABACUS', 'KLARA', 'OTHER'] as const;
export const MANDATES = ['1-10', '11-50', '51-100', '100+'] as const;
export const PERMISSIONS = [
  'VIEW_INVOICES',
  'VIEW_PAYMENT_STATUS',
  'VIEW_CUSTOMERS',
  'VIEW_ACCOUNTING_DOCUMENTS',
  'DOWNLOAD_DOCUMENTS',
  'VIEW_EXPORTS',
  'VIEW_QUOTES',
  'VIEW_WORK_HOURS',
  'VIEW_PAYROLL_DATA',
  'PROPOSE_ENTRIES',
] as const;
export type Permission = (typeof PERMISSIONS)[number];

const fr = {
  brand: 'Cantia Accounting',
  brandShort: 'Accounting',
  nav: { login: 'Se connecter', signup: 'Créer mon espace', space: 'Mon espace', logout: 'Se déconnecter', admin: 'Administration' },
  hero: {
    eyebrow: 'Pour les fiduciaires',
    title: 'Tous vos clients Cantia.\nUn seul espace.',
    text: 'Collaborez avec vos clients du bâtiment directement depuis Cantia. Retrouvez les informations comptables dont vous avez besoin depuis un seul cockpit.',
    cta: 'Créer mon espace gratuitement',
    secondary: 'Se connecter',
    note: 'Gratuit pour les fiduciaires. Sans carte bancaire, sans engagement.',
  },
  value: {
    title: 'Fini les factures envoyées par e-mail',
    items: [
      { title: 'Demandes de pièces, sans relances', text: 'Demandez un relevé ou un justificatif en deux clics. Le mandant répond depuis son Cantia avec ses fichiers, vous êtes averti. Rappel en un clic si besoin.' },
      { title: 'Échéances de chaque dossier', text: 'Décomptes TVA (effective ou TDFN), déclaration AVS, certificats de salaire, impôts, bouclement : calculés pour chaque mandant et suivis par toute l’équipe.' },
      { title: 'Données à jour, exports prêts', text: 'Factures, paiements, écritures, TVA et justificatifs directement depuis Cantia. Écritures en CSV, TVA par code, bilan et compte de résultat.' },
    ],
  },
  trust: {
    title: 'Le client garde la main',
    items: [
      'Aucun accès sans l’accord explicite du client.',
      'Le client choisit ce que vous voyez : factures, comptabilité, devis, heures, salaires.',
      'Lecture seule. Les photos de chantier, le planning et les notes internes restent privés.',
      'Accès révocable à tout moment, avec effet immédiat. Chaque accès est journalisé.',
    ],
  },
  steps: {
    title: 'Comment ça marche',
    items: [
      { title: 'Créez votre espace', text: 'Deux minutes, gratuitement. Invitez vos collaborateurs.' },
      { title: 'Ajoutez vos mandants', text: 'Entrez l’e-mail de votre client. S’il utilise Cantia, il reçoit une demande d’accès. Sinon, une invitation à rejoindre Cantia.' },
      { title: 'Travaillez sur des données propres', text: 'Dès que le client accepte, ses données comptables sont dans votre cockpit.' },
    ],
  },
  partner: {
    title: 'Recommandez Cantia à vos mandants',
    text: 'Activez Cantia Partners depuis votre espace : quand un mandant que vous invitez devient client payant, vous touchez une commission. Avec le même compte, sans formalité.',
    cta: 'Découvrir Cantia Partners',
  },
  facts: ['Gratuit, sans limite de mandants', 'Données hébergées en Suisse', 'Lecture seule, accès révocable', 'Chaque accès journalisé'],
  faq: {
    title: 'Questions fréquentes',
    items: [
      { q: 'Combien ça coûte ?', a: 'Rien. L’espace fiduciaire est gratuit, sans limite de mandants. Vos clients paient leur abonnement Cantia habituel.' },
      { q: 'Mes clients doivent-ils utiliser Cantia ?', a: 'Oui, les données viennent de leur Cantia. Vous pouvez les inviter depuis votre espace, avec un essai gratuit.' },
      { q: 'Puis-je modifier les données ?', a: 'Non. L’accès est en lecture seule : vous consultez et exportez, le client garde la maîtrise de ses documents.' },
      { q: 'J’ai déjà un compte Cantia.', a: 'Connectez-vous avec les mêmes identifiants : l’espace fiduciaire s’ajoute à votre compte.' },
      { q: 'Et WinBiz, Crésus, Abacus ?', a: 'Aujourd’hui, Cantia se synchronise avec Bexio et exporte en CSV. D’autres connexions sont prévues ; nous ne les affichons jamais comme actives avant qu’elles le soient.' },
    ],
  },
  finalCta: { title: 'Simplifiez la collaboration avec vos clients du bâtiment.', cta: 'Créer mon espace gratuitement' },
  footer: { tagline: 'L’espace des fiduciaires qui travaillent avec des entreprises du bâtiment sur Cantia.', site: 'Cantia', partners: 'Cantia Partners', privacy: 'Confidentialité', terms: 'Conditions', status: 'Statut' },
  auth: {
    loginTitle: 'Se connecter',
    signupTitle: 'Créer votre espace',
    codeTitle: 'Vérifiez votre e-mail',
    sameAccount: 'Vous utilisez déjà Cantia ou Cantia Partners ? Les mêmes identifiants fonctionnent ici.',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'E-mail',
    password: 'Mot de passe',
    passwordHint: '8 caractères minimum',
    login: 'Se connecter',
    signup: 'Créer mon compte',
    toSignup: 'Pas encore de compte ? Créer un espace',
    toLogin: 'Déjà un compte ? Se connecter',
    forgot: 'Mot de passe oublié',
    code: 'Code reçu par e-mail',
    codeText: 'Nous avons envoyé un code à {email}.',
    verify: 'Valider',
    resend: 'Renvoyer le code',
    resent: 'Code renvoyé.',
    back: 'Retour',
    or: 'ou',
    google: 'Continuer avec Google',
    missing: 'Remplissez tous les champs.',
    shortPassword: 'Le mot de passe doit contenir au moins 8 caractères.',
    exists: 'Un compte existe déjà avec cette adresse e-mail. Connectez-vous avec vos identifiants (ou « Mot de passe oublié ? »).',
    sideTitle: 'Vos mandants du bâtiment, enfin organisés.',
    sideText: 'Factures, paiements, écritures et justificatifs de vos clients Cantia, au même endroit.',
  },
  onboarding: {
    title: 'Votre fiduciaire',
    intro: 'Quelques informations pour créer votre espace. Vous pourrez les modifier plus tard.',
    firmName: 'Nom de la fiduciaire',
    firstName: 'Prénom',
    lastName: 'Nom',
    phone: 'Téléphone',
    address: 'Adresse',
    postalCode: 'NPA',
    city: 'Ville',
    country: 'Pays',
    ide: 'IDE (facultatif)',
    website: 'Site web (facultatif)',
    mandates: 'Nombre approximatif de mandats',
    software: 'Logiciels utilisés',
    softwareNames: { BEXIO: 'Bexio', WINBIZ: 'WinBiz', CRESUS: 'Crésus', ODOO: 'Odoo', ABACUS: 'Abacus', KLARA: 'Klara', OTHER: 'Autre' },
    submit: 'Créer mon espace',
    required: 'Nom de la fiduciaire, prénom et nom sont requis.',
  },
  tabs: { dashboard: 'Tableau de bord', clients: 'Mandants', documents: 'Documents', team: 'Équipe', partner: 'Programme partenaire', settings: 'Fiduciaire' },
  dashboard: {
    hello: 'Bonjour {name}',
    kpis: { active: 'Mandants actifs', invitations: 'Invitations en attente', requests: 'Demandes d’accès', documents: 'Documents', overdue: 'Factures en retard' },
    open: 'CHF {amount} à encaisser chez vos mandants',
    pendingFirmTitle: 'Des clients vous ont invité',
    pendingFirmText: '{name} vous donne accès à ses données comptables.',
    accept: 'Accepter',
    decline: 'Décliner',
    recentDocs: 'Documents récents',
    noDocs: 'Aucun document pour l’instant.',
    emptyTitle: 'Ajoutez votre premier mandant',
    emptyText: 'Entrez l’e-mail de votre client : s’il utilise Cantia, il reçoit une demande d’accès ; sinon, une invitation gratuite.',
  },
  clients: {
    title: 'Mes mandants',
    add: 'Ajouter un mandant',
    search: 'Rechercher un mandant…',
    filters: { all: 'Tous', active: 'Actifs', pending: 'En attente', attention: 'À surveiller' },
    sort: { name: 'Nom', activity: 'Activité', open: 'À encaisser' },
    columns: { company: 'Entreprise', status: 'Statut Cantia', plan: 'Plan', activity: 'Dernière activité', documents: 'Documents', invoices: 'Factures', payments: 'Paiements 30 j', actions: '' },
    statuses: { ACTIVE: 'Accès actif', PENDING_CLIENT: 'En attente du client', PENDING_FIRM: 'À accepter' },
    subscription: { active: 'Abonné', trialing: 'Essai', canceled: 'Résilié', past_due: 'Paiement en retard', none: '—' },
    overdue: '{count} en retard',
    open: 'Ouvrir',
    cancelRequest: 'Annuler la demande',
    empty: 'Aucun mandant pour l’instant.',
    noMatch: 'Aucun mandant ne correspond.',
    invitationsTitle: 'Invitations à rejoindre Cantia',
    invitationStatuses: { PENDING: 'Envoyée', ACCEPTED: 'Inscrit', CANCELLED: 'Annulée', EXPIRED: 'Expirée' },
    resend: 'Renvoyer',
    cancel: 'Annuler',
  },
  addClient: {
    title: 'Ajouter un mandant',
    text: 'S’il utilise déjà Cantia, votre client reçoit une demande d’accès. Sinon, il reçoit une invitation à rejoindre Cantia, puis la demande d’accès une fois inscrit.',
    email: 'E-mail du responsable',
    company: 'Nom de l’entreprise (si nouveau client)',
    contact: 'Nom du responsable (facultatif)',
    submit: 'Envoyer',
    sentRequest: 'Demande d’accès envoyée. Le client doit l’accepter dans Cantia.',
    sentInvitation: 'Invitation envoyée. Dès son inscription, votre client pourra accepter votre accès.',
    withPartner: 'Votre code partenaire est inclus : s’il devient client payant, vous touchez votre commission.',
  },
  client: {
    back: 'Mes mandants',
    notFound: 'Ce mandant n’est pas accessible. L’accès a peut-être été révoqué.',
    sections: { summary: 'Résumé', invoices: 'Factures', payments: 'Paiements', customers: 'Clients', accounting: 'Comptabilité', documents: 'Documents', quotes: 'Devis', hours: 'Heures', payroll: 'Salaires', integrations: 'Intégrations' },
    accessSince: 'Accès depuis le {date}',
    permissions: 'Accès accordé',
    ide: 'IDE',
    noPermission: 'Le client n’a pas ouvert cette partie. Il peut le faire dans Cantia, Paramètres › Fiduciaire.',
    period: 'Période',
    periods: { month: 'Ce mois', quarter: 'Ce trimestre', year: 'Cette année', lastYear: 'Année précédente' },
    invoices: { number: 'N°', client: 'Client', date: 'Date', due: 'Échéance', total: 'Total TTC', paid: 'Payé', status: 'Statut', pdf: 'PDF', none: 'Aucune facture sur la période.' },
    invoiceStatuses: { draft: 'Brouillon', ready: 'Prête', sent: 'Envoyée', partial: 'Partiellement payée', paid: 'Payée', cancelled: 'Annulée' },
    payments: { date: 'Date', invoice: 'Facture', amount: 'Montant', none: 'Aucun paiement sur la période.' },
    customers: { name: 'Nom', email: 'E-mail', phone: 'Téléphone', address: 'Adresse', none: 'Aucun client.' },
    quotes: { number: 'N°', client: 'Client', date: 'Date', status: 'Statut', none: 'Aucun devis sur la période.' },
    hours: { date: 'Date', hours: 'Heures', total: 'Total', none: 'Aucune heure sur la période.' },
    payroll: { period: 'Période', status: 'Statut', gross: 'Brut', net: 'Net', none: 'Aucun salaire sur la période.' },
    summary: { revenue: 'Facturé (TTC)', collected: 'Encaissé', open: 'À encaisser', overdue: 'En retard', result: 'Résultat comptable', entries: 'Écritures' },
    accounting: {
      income: 'Compte de résultat',
      revenue: 'Produits',
      expenses: 'Charges',
      result: 'Résultat',
      balance: 'Bilan',
      assets: 'Actifs',
      liabilities: 'Passifs',
      vat: 'TVA par code',
      vatDue: 'TVA nette due',
      exports: 'Exports',
      exportEntries: 'Écritures (CSV)',
      exportTrial: 'Balance (CSV)',
      exportVat: 'Feuille de travail TVA (CSV)',
      empty: 'Pas encore d’écritures sur la période.',
    },
    integrations: { bexio: 'Bexio', connected: 'Connecté', notConnected: 'Non connecté', lastSync: 'Dernière synchronisation : {date}', error: 'Dernière erreur : {error}', others: 'WinBiz, Crésus, Abacus, Klara : pas encore disponibles. Export CSV possible dès aujourd’hui.' },
    endMandate: 'Mettre fin au mandat',
    endMandateConfirm: 'Confirmer : vous perdez l’accès à ce client',
  },
  documents: {
    title: 'Documents',
    text: 'Factures et justificatifs de tous vos mandants.',
    search: 'Rechercher…',
    allClients: 'Tous les mandants',
    kinds: { all: 'Tout', invoice: 'Factures', receipt: 'Justificatifs', shared: 'Envoyés par le client' },
    download: 'Télécharger',
    noFile: 'PDF pas encore généré',
    none: 'Aucun document.',
  },
  team: {
    title: 'Équipe',
    invite: 'Inviter un collaborateur',
    email: 'E-mail',
    roles: { OWNER: 'Propriétaire', ADMIN: 'Administrateur', MEMBER: 'Collaborateur' },
    send: 'Inviter',
    sent: 'Invitation envoyée.',
    pending: 'Invitations en attente',
    remove: 'Retirer',
    removeConfirm: 'Confirmer le retrait',
    leave: 'Quitter la fiduciaire',
    you: 'vous',
    historyTitle: 'Journal des accès',
    historyEmpty: 'Aucun événement.',
  },
  partnerTab: {
    title: 'Programme partenaire',
    inactiveText: 'Recommandez Cantia à vos nouveaux mandants et recevez 25 % de commission pendant leurs 12 premiers mois.',
    activate: 'Activer Cantia Partners',
    activeText: 'Vos invitations de nouveaux mandants incluent automatiquement votre code partenaire.',
    brought: 'Clients apportés',
    earned: 'Total gagné',
    available: 'Commission disponible',
    see: 'Voir mes commissions',
    code: 'Votre lien',
  },
  settings: {
    title: 'Votre fiduciaire',
    save: 'Enregistrer',
    saved: 'Enregistré.',
    language: 'Langue des e-mails',
  },
  invitation: {
    title: 'Invitation',
    loading: 'Chargement…',
    invalid: 'Cette invitation n’existe pas ou a expiré.',
    staff: '{firm} vous invite à rejoindre son espace Cantia Accounting.',
    client: '{org} vous donne accès à ses données comptables sur Cantia.',
    signInFirst: 'Connectez-vous ou créez votre compte avec {email} pour accepter.',
    accept: 'Accepter',
    needsFirm: 'Créez d’abord votre espace fiduciaire : l’accès sera ajouté automatiquement.',
    done: 'C’est fait.',
    open: 'Ouvrir mon espace',
  },
  admin: {
    title: 'Fiduciaires',
    kpis: { firms: 'Fiduciaires', active: 'Actives', linked: 'Mandants liés', acquired: 'Clients acquis', mrr: 'MRR acquis', partners: 'Partenaires', suspicious: 'Suspectes' },
  },
  permissions: {
    VIEW_INVOICES: 'Factures',
    VIEW_PAYMENT_STATUS: 'Paiements',
    VIEW_CUSTOMERS: 'Clients',
    VIEW_ACCOUNTING_DOCUMENTS: 'Comptabilité et justificatifs',
    DOWNLOAD_DOCUMENTS: 'Téléchargements',
    VIEW_EXPORTS: 'Exports',
    VIEW_QUOTES: 'Devis',
    VIEW_WORK_HOURS: 'Heures',
    VIEW_PAYROLL_DATA: 'Salaires',
    PROPOSE_ENTRIES: 'Proposer des écritures',
  },
  common: { loading: 'Chargement…', error: 'Une erreur est survenue.', never: 'jamais', yes: 'Oui', no: 'Non' },
};

type AccCopy = typeof fr;

const de: AccCopy = {
  brand: 'Cantia Accounting',
  brandShort: 'Accounting',
  nav: { login: 'Anmelden', signup: 'Bereich erstellen', space: 'Mein Bereich', logout: 'Abmelden', admin: 'Administration' },
  hero: {
    eyebrow: 'Für Treuhänder',
    title: 'Alle Ihre Cantia-Kunden.\nEin einziger Bereich.',
    text: 'Arbeiten Sie direkt in Cantia mit Ihren Kunden aus dem Baugewerbe zusammen. Finden Sie die benötigten Buchhaltungsinformationen in einem einzigen Cockpit.',
    cta: 'Kostenlos Bereich erstellen',
    secondary: 'Anmelden',
    note: 'Kostenlos für Treuhänder. Ohne Kreditkarte, ohne Verpflichtung.',
  },
  value: {
    title: 'Schluss mit Rechnungen per E-Mail',
    items: [
      { title: 'Belege anfordern, ohne Nachfassen', text: 'Fordern Sie einen Auszug oder Beleg mit zwei Klicks an. Der Mandant antwortet in seinem Cantia mit seinen Dateien, Sie werden benachrichtigt. Erinnerung mit einem Klick.' },
      { title: 'Fristen jedes Dossiers', text: 'MWST-Abrechnungen (effektiv oder Saldosteuersatz), AHV-Lohnmeldung, Lohnausweise, Steuern, Abschluss: für jeden Mandanten berechnet und vom ganzen Team verfolgt.' },
      { title: 'Aktuelle Daten, fertige Exporte', text: 'Rechnungen, Zahlungen, Buchungen, MWST und Belege direkt aus Cantia. Buchungen als CSV, MWST nach Code, Bilanz und Erfolgsrechnung.' },
    ],
  },
  trust: {
    title: 'Der Kunde behält die Kontrolle',
    items: [
      'Kein Zugriff ohne ausdrückliche Zustimmung des Kunden.',
      'Der Kunde wählt, was Sie sehen: Rechnungen, Buchhaltung, Offerten, Stunden, Löhne.',
      'Nur Lesezugriff. Baustellenfotos, Planung und interne Notizen bleiben privat.',
      'Jederzeit mit sofortiger Wirkung widerrufbar. Jeder Zugriff wird protokolliert.',
    ],
  },
  steps: {
    title: 'So funktioniert es',
    items: [
      { title: 'Bereich erstellen', text: 'Zwei Minuten, kostenlos. Laden Sie Ihre Mitarbeitenden ein.' },
      { title: 'Mandanten hinzufügen', text: 'Geben Sie die E-Mail Ihres Kunden ein. Nutzt er Cantia, erhält er eine Zugriffsanfrage. Sonst eine Einladung zu Cantia.' },
      { title: 'Mit sauberen Daten arbeiten', text: 'Sobald der Kunde zustimmt, sind seine Buchhaltungsdaten in Ihrem Cockpit.' },
    ],
  },
  partner: {
    title: 'Empfehlen Sie Cantia Ihren Mandanten',
    text: 'Aktivieren Sie Cantia Partners in Ihrem Bereich: Wird ein eingeladener Mandant zahlender Kunde, erhalten Sie eine Provision. Mit demselben Konto, ohne Formalitäten.',
    cta: 'Cantia Partners entdecken',
  },
  facts: ['Kostenlos, beliebig viele Mandanten', 'Daten in der Schweiz gehostet', 'Nur Lesezugriff, jederzeit widerrufbar', 'Jeder Zugriff protokolliert'],
  faq: {
    title: 'Häufige Fragen',
    items: [
      { q: 'Was kostet es?', a: 'Nichts. Der Treuhandbereich ist kostenlos, ohne Mandantenlimit. Ihre Kunden bezahlen ihr übliches Cantia-Abonnement.' },
      { q: 'Müssen meine Kunden Cantia nutzen?', a: 'Ja, die Daten stammen aus ihrem Cantia. Sie können sie aus Ihrem Bereich einladen, mit kostenloser Testphase.' },
      { q: 'Kann ich Daten ändern?', a: 'Nein. Der Zugriff ist schreibgeschützt: Sie sehen und exportieren, der Kunde behält die Kontrolle über seine Dokumente.' },
      { q: 'Ich habe bereits ein Cantia-Konto.', a: 'Melden Sie sich mit denselben Zugangsdaten an: Der Treuhandbereich wird Ihrem Konto hinzugefügt.' },
      { q: 'Und WinBiz, Crésus, Abacus?', a: 'Heute synchronisiert Cantia mit Bexio und exportiert als CSV. Weitere Anbindungen sind geplant; wir zeigen sie nie als aktiv an, bevor sie es sind.' },
    ],
  },
  finalCta: { title: 'Vereinfachen Sie die Zusammenarbeit mit Ihren Baukunden.', cta: 'Kostenlos Bereich erstellen' },
  footer: { tagline: 'Der Bereich für Treuhänder, die mit Bauunternehmen auf Cantia arbeiten.', site: 'Cantia', partners: 'Cantia Partners', privacy: 'Datenschutz', terms: 'AGB', status: 'Status' },
  auth: {
    loginTitle: 'Anmelden',
    signupTitle: 'Bereich erstellen',
    codeTitle: 'E-Mail bestätigen',
    sameAccount: 'Sie nutzen bereits Cantia oder Cantia Partners? Dieselben Zugangsdaten funktionieren hier.',
    firstName: 'Vorname',
    lastName: 'Nachname',
    email: 'E-Mail',
    password: 'Passwort',
    passwordHint: 'Mindestens 8 Zeichen',
    login: 'Anmelden',
    signup: 'Konto erstellen',
    toSignup: 'Noch kein Konto? Bereich erstellen',
    toLogin: 'Bereits ein Konto? Anmelden',
    forgot: 'Passwort vergessen',
    code: 'Code aus der E-Mail',
    codeText: 'Wir haben einen Code an {email} gesendet.',
    verify: 'Bestätigen',
    resend: 'Code erneut senden',
    resent: 'Code erneut gesendet.',
    back: 'Zurück',
    or: 'oder',
    google: 'Mit Google fortfahren',
    missing: 'Bitte alle Felder ausfüllen.',
    shortPassword: 'Das Passwort muss mindestens 8 Zeichen lang sein.',
    exists: 'Für diese E-Mail-Adresse besteht bereits ein Konto. Melden Sie sich mit Ihren Zugangsdaten an (oder « Passwort vergessen? »).',
    sideTitle: 'Ihre Baumandanten, endlich geordnet.',
    sideText: 'Rechnungen, Zahlungen, Buchungen und Belege Ihrer Cantia-Kunden an einem Ort.',
  },
  onboarding: {
    title: 'Ihre Treuhand',
    intro: 'Einige Angaben, um Ihren Bereich zu erstellen. Sie können sie später ändern.',
    firmName: 'Name der Treuhand',
    firstName: 'Vorname',
    lastName: 'Nachname',
    phone: 'Telefon',
    address: 'Adresse',
    postalCode: 'PLZ',
    city: 'Ort',
    country: 'Land',
    ide: 'UID (optional)',
    website: 'Website (optional)',
    mandates: 'Ungefähre Anzahl Mandate',
    software: 'Verwendete Software',
    softwareNames: { BEXIO: 'Bexio', WINBIZ: 'WinBiz', CRESUS: 'Crésus', ODOO: 'Odoo', ABACUS: 'Abacus', KLARA: 'Klara', OTHER: 'Andere' },
    submit: 'Bereich erstellen',
    required: 'Name der Treuhand, Vorname und Nachname sind erforderlich.',
  },
  tabs: { dashboard: 'Übersicht', clients: 'Mandanten', documents: 'Dokumente', team: 'Team', partner: 'Partnerprogramm', settings: 'Treuhand' },
  dashboard: {
    hello: 'Guten Tag {name}',
    kpis: { active: 'Aktive Mandanten', invitations: 'Offene Einladungen', requests: 'Zugriffsanfragen', documents: 'Dokumente', overdue: 'Überfällige Rechnungen' },
    open: 'CHF {amount} offen bei Ihren Mandanten',
    pendingFirmTitle: 'Kunden haben Sie eingeladen',
    pendingFirmText: '{name} gibt Ihnen Zugriff auf seine Buchhaltungsdaten.',
    accept: 'Annehmen',
    decline: 'Ablehnen',
    recentDocs: 'Neue Dokumente',
    noDocs: 'Noch keine Dokumente.',
    emptyTitle: 'Ersten Mandanten hinzufügen',
    emptyText: 'Geben Sie die E-Mail Ihres Kunden ein: Nutzt er Cantia, erhält er eine Zugriffsanfrage; sonst eine kostenlose Einladung.',
  },
  clients: {
    title: 'Meine Mandanten',
    add: 'Mandanten hinzufügen',
    search: 'Mandanten suchen…',
    filters: { all: 'Alle', active: 'Aktiv', pending: 'Offen', attention: 'Zu beachten' },
    sort: { name: 'Name', activity: 'Aktivität', open: 'Offen' },
    columns: { company: 'Unternehmen', status: 'Cantia-Status', plan: 'Plan', activity: 'Letzte Aktivität', documents: 'Dokumente', invoices: 'Rechnungen', payments: 'Zahlungen 30 T.', actions: '' },
    statuses: { ACTIVE: 'Zugriff aktiv', PENDING_CLIENT: 'Wartet auf Kunde', PENDING_FIRM: 'Anzunehmen' },
    subscription: { active: 'Abonniert', trialing: 'Test', canceled: 'Gekündigt', past_due: 'Zahlung überfällig', none: '—' },
    overdue: '{count} überfällig',
    open: 'Öffnen',
    cancelRequest: 'Anfrage zurückziehen',
    empty: 'Noch keine Mandanten.',
    noMatch: 'Kein passender Mandant.',
    invitationsTitle: 'Einladungen zu Cantia',
    invitationStatuses: { PENDING: 'Gesendet', ACCEPTED: 'Registriert', CANCELLED: 'Abgebrochen', EXPIRED: 'Abgelaufen' },
    resend: 'Erneut senden',
    cancel: 'Abbrechen',
  },
  addClient: {
    title: 'Mandanten hinzufügen',
    text: 'Nutzt Ihr Kunde bereits Cantia, erhält er eine Zugriffsanfrage. Sonst erhält er eine Einladung zu Cantia und nach der Registrierung die Zugriffsanfrage.',
    email: 'E-Mail der verantwortlichen Person',
    company: 'Name des Unternehmens (bei neuem Kunden)',
    contact: 'Name der verantwortlichen Person (optional)',
    submit: 'Senden',
    sentRequest: 'Zugriffsanfrage gesendet. Der Kunde muss sie in Cantia annehmen.',
    sentInvitation: 'Einladung gesendet. Nach der Registrierung kann Ihr Kunde Ihren Zugriff annehmen.',
    withPartner: 'Ihr Partnercode ist enthalten: Wird er zahlender Kunde, erhalten Sie Ihre Provision.',
  },
  client: {
    back: 'Meine Mandanten',
    notFound: 'Dieser Mandant ist nicht zugänglich. Der Zugriff wurde möglicherweise widerrufen.',
    sections: { summary: 'Übersicht', invoices: 'Rechnungen', payments: 'Zahlungen', customers: 'Kunden', accounting: 'Buchhaltung', documents: 'Dokumente', quotes: 'Offerten', hours: 'Stunden', payroll: 'Löhne', integrations: 'Integrationen' },
    accessSince: 'Zugriff seit {date}',
    permissions: 'Gewährter Zugriff',
    ide: 'UID',
    noPermission: 'Der Kunde hat diesen Bereich nicht freigegeben. Er kann dies in Cantia unter Einstellungen › Treuhand tun.',
    period: 'Zeitraum',
    periods: { month: 'Dieser Monat', quarter: 'Dieses Quartal', year: 'Dieses Jahr', lastYear: 'Vorjahr' },
    invoices: { number: 'Nr.', client: 'Kunde', date: 'Datum', due: 'Fällig', total: 'Total inkl. MWST', paid: 'Bezahlt', status: 'Status', pdf: 'PDF', none: 'Keine Rechnungen im Zeitraum.' },
    invoiceStatuses: { draft: 'Entwurf', ready: 'Bereit', sent: 'Versendet', partial: 'Teilbezahlt', paid: 'Bezahlt', cancelled: 'Storniert' },
    payments: { date: 'Datum', invoice: 'Rechnung', amount: 'Betrag', none: 'Keine Zahlungen im Zeitraum.' },
    customers: { name: 'Name', email: 'E-Mail', phone: 'Telefon', address: 'Adresse', none: 'Keine Kunden.' },
    quotes: { number: 'Nr.', client: 'Kunde', date: 'Datum', status: 'Status', none: 'Keine Offerten im Zeitraum.' },
    hours: { date: 'Datum', hours: 'Stunden', total: 'Total', none: 'Keine Stunden im Zeitraum.' },
    payroll: { period: 'Periode', status: 'Status', gross: 'Brutto', net: 'Netto', none: 'Keine Löhne im Zeitraum.' },
    summary: { revenue: 'Fakturiert (inkl. MWST)', collected: 'Eingenommen', open: 'Offen', overdue: 'Überfällig', result: 'Buchhalterisches Ergebnis', entries: 'Buchungen' },
    accounting: {
      income: 'Erfolgsrechnung',
      revenue: 'Ertrag',
      expenses: 'Aufwand',
      result: 'Ergebnis',
      balance: 'Bilanz',
      assets: 'Aktiven',
      liabilities: 'Passiven',
      vat: 'MWST nach Code',
      vatDue: 'Geschuldete MWST netto',
      exports: 'Exporte',
      exportEntries: 'Buchungen (CSV)',
      exportTrial: 'Saldenliste (CSV)',
      exportVat: 'MWST-Arbeitsblatt (CSV)',
      empty: 'Noch keine Buchungen im Zeitraum.',
    },
    integrations: { bexio: 'Bexio', connected: 'Verbunden', notConnected: 'Nicht verbunden', lastSync: 'Letzte Synchronisation: {date}', error: 'Letzter Fehler: {error}', others: 'WinBiz, Crésus, Abacus, Klara: noch nicht verfügbar. CSV-Export ist schon heute möglich.' },
    endMandate: 'Mandat beenden',
    endMandateConfirm: 'Bestätigen: Sie verlieren den Zugriff auf diesen Kunden',
  },
  documents: {
    title: 'Dokumente',
    text: 'Rechnungen und Belege aller Mandanten.',
    search: 'Suchen…',
    allClients: 'Alle Mandanten',
    kinds: { all: 'Alles', invoice: 'Rechnungen', receipt: 'Belege', shared: 'Vom Kunden gesendet' },
    download: 'Herunterladen',
    noFile: 'PDF noch nicht erstellt',
    none: 'Keine Dokumente.',
  },
  team: {
    title: 'Team',
    invite: 'Mitarbeitende einladen',
    email: 'E-Mail',
    roles: { OWNER: 'Inhaber/in', ADMIN: 'Administrator/in', MEMBER: 'Mitarbeitende/r' },
    send: 'Einladen',
    sent: 'Einladung gesendet.',
    pending: 'Offene Einladungen',
    remove: 'Entfernen',
    removeConfirm: 'Entfernen bestätigen',
    leave: 'Treuhand verlassen',
    you: 'Sie',
    historyTitle: 'Zugriffsprotokoll',
    historyEmpty: 'Keine Ereignisse.',
  },
  partnerTab: {
    title: 'Partnerprogramm',
    inactiveText: 'Empfehlen Sie Cantia Ihren neuen Mandanten und erhalten Sie in den ersten 12 Monaten 25 % Provision.',
    activate: 'Cantia Partners aktivieren',
    activeText: 'Ihre Einladungen an neue Mandanten enthalten automatisch Ihren Partnercode.',
    brought: 'Gebrachte Kunden',
    earned: 'Total verdient',
    available: 'Verfügbare Provision',
    see: 'Meine Provisionen ansehen',
    code: 'Ihr Link',
  },
  settings: { title: 'Ihre Treuhand', save: 'Speichern', saved: 'Gespeichert.', language: 'Sprache der E-Mails' },
  invitation: {
    title: 'Einladung',
    loading: 'Wird geladen…',
    invalid: 'Diese Einladung existiert nicht oder ist abgelaufen.',
    staff: '{firm} lädt Sie in den Cantia-Treuhandbereich ein.',
    client: '{org} gibt Ihnen Zugriff auf seine Buchhaltungsdaten in Cantia.',
    signInFirst: 'Melden Sie sich mit {email} an oder erstellen Sie ein Konto, um anzunehmen.',
    accept: 'Annehmen',
    needsFirm: 'Erstellen Sie zuerst Ihren Treuhandbereich: Der Zugriff wird automatisch hinzugefügt.',
    done: 'Erledigt.',
    open: 'Meinen Bereich öffnen',
  },
  admin: { title: 'Treuhänder', kpis: { firms: 'Treuhänder', active: 'Aktiv', linked: 'Verknüpfte Mandanten', acquired: 'Gewonnene Kunden', mrr: 'Gewonnener MRR', partners: 'Partner', suspicious: 'Verdächtig' } },
  permissions: {
    VIEW_INVOICES: 'Rechnungen',
    VIEW_PAYMENT_STATUS: 'Zahlungen',
    VIEW_CUSTOMERS: 'Kunden',
    VIEW_ACCOUNTING_DOCUMENTS: 'Buchhaltung und Belege',
    DOWNLOAD_DOCUMENTS: 'Downloads',
    VIEW_EXPORTS: 'Exporte',
    VIEW_QUOTES: 'Offerten',
    VIEW_WORK_HOURS: 'Stunden',
    VIEW_PAYROLL_DATA: 'Löhne',
    PROPOSE_ENTRIES: 'Buchungen vorschlagen',
  },
  common: { loading: 'Wird geladen…', error: 'Ein Fehler ist aufgetreten.', never: 'nie', yes: 'Ja', no: 'Nein' },
};

const it: AccCopy = {
  brand: 'Cantia Accounting',
  brandShort: 'Accounting',
  nav: { login: 'Accedi', signup: 'Crea il mio spazio', space: 'Il mio spazio', logout: 'Esci', admin: 'Amministrazione' },
  hero: {
    eyebrow: 'Per i fiduciari',
    title: 'Tutti i suoi clienti Cantia.\nUn solo spazio.',
    text: 'Collabori con i suoi clienti dell’edilizia direttamente da Cantia. Trovi le informazioni contabili di cui ha bisogno in un unico cockpit.',
    cta: 'Crea il mio spazio gratis',
    secondary: 'Accedi',
    note: 'Gratuito per i fiduciari. Senza carta di credito, senza impegno.',
  },
  value: {
    title: 'Basta fatture inviate per e-mail',
    items: [
      { title: 'Richieste di documenti, senza solleciti', text: 'Chieda un estratto o un giustificativo in due clic. Il mandante risponde dal suo Cantia con i suoi file e lei viene avvisato. Promemoria con un clic.' },
      { title: 'Scadenze di ogni dossier', text: 'Rendiconti IVA (effettivo o aliquota saldo), dichiarazione AVS, certificati di salario, imposte, chiusura: calcolati per ogni mandante e seguiti da tutto il team.' },
      { title: 'Dati aggiornati, esportazioni pronte', text: 'Fatture, pagamenti, registrazioni, IVA e giustificativi direttamente da Cantia. Registrazioni in CSV, IVA per codice, bilancio e conto economico.' },
    ],
  },
  trust: {
    title: 'Il cliente mantiene il controllo',
    items: [
      'Nessun accesso senza il consenso esplicito del cliente.',
      'Il cliente sceglie cosa vede: fatture, contabilità, preventivi, ore, salari.',
      'Sola lettura. Foto di cantiere, pianificazione e note interne restano private.',
      'Accesso revocabile in ogni momento, con effetto immediato. Ogni accesso è registrato.',
    ],
  },
  steps: {
    title: 'Come funziona',
    items: [
      { title: 'Crei il suo spazio', text: 'Due minuti, gratis. Inviti i suoi collaboratori.' },
      { title: 'Aggiunga i suoi mandanti', text: 'Inserisca l’e-mail del cliente. Se usa Cantia, riceve una richiesta di accesso. Altrimenti un invito a Cantia.' },
      { title: 'Lavori su dati puliti', text: 'Appena il cliente accetta, i suoi dati contabili sono nel suo cockpit.' },
    ],
  },
  partner: {
    title: 'Consigli Cantia ai suoi mandanti',
    text: 'Attivi Cantia Partners dal suo spazio: quando un mandante invitato diventa cliente pagante, riceve una commissione. Con lo stesso account, senza formalità.',
    cta: 'Scoprire Cantia Partners',
  },
  facts: ['Gratuito, mandanti illimitati', 'Dati ospitati in Svizzera', 'Sola lettura, accesso revocabile', 'Ogni accesso registrato'],
  faq: {
    title: 'Domande frequenti',
    items: [
      { q: 'Quanto costa?', a: 'Niente. Lo spazio fiduciario è gratuito, senza limiti di mandanti. I suoi clienti pagano il loro abbonamento Cantia abituale.' },
      { q: 'I miei clienti devono usare Cantia?', a: 'Sì, i dati provengono dal loro Cantia. Può invitarli dal suo spazio, con una prova gratuita.' },
      { q: 'Posso modificare i dati?', a: 'No. L’accesso è in sola lettura: consulta ed esporta, il cliente mantiene il controllo dei suoi documenti.' },
      { q: 'Ho già un account Cantia.', a: 'Acceda con le stesse credenziali: lo spazio fiduciario si aggiunge al suo account.' },
      { q: 'E WinBiz, Crésus, Abacus?', a: 'Oggi Cantia si sincronizza con Bexio ed esporta in CSV. Altre connessioni sono previste; non le mostriamo mai come attive prima che lo siano.' },
    ],
  },
  finalCta: { title: 'Semplifichi la collaborazione con i suoi clienti dell’edilizia.', cta: 'Crea il mio spazio gratis' },
  footer: { tagline: 'Lo spazio dei fiduciari che lavorano con imprese edili su Cantia.', site: 'Cantia', partners: 'Cantia Partners', privacy: 'Privacy', terms: 'Condizioni', status: 'Stato' },
  auth: {
    loginTitle: 'Accedi',
    signupTitle: 'Crea il suo spazio',
    codeTitle: 'Verifichi la sua e-mail',
    sameAccount: 'Usa già Cantia o Cantia Partners? Le stesse credenziali funzionano qui.',
    firstName: 'Nome',
    lastName: 'Cognome',
    email: 'E-mail',
    password: 'Password',
    passwordHint: 'Almeno 8 caratteri',
    login: 'Accedi',
    signup: 'Crea il mio account',
    toSignup: 'Non ha un account? Crei uno spazio',
    toLogin: 'Ha già un account? Acceda',
    forgot: 'Password dimenticata',
    code: 'Codice ricevuto per e-mail',
    codeText: 'Abbiamo inviato un codice a {email}.',
    verify: 'Conferma',
    resend: 'Invia di nuovo il codice',
    resent: 'Codice inviato di nuovo.',
    back: 'Indietro',
    or: 'oppure',
    google: 'Continua con Google',
    missing: 'Compili tutti i campi.',
    shortPassword: 'La password deve contenere almeno 8 caratteri.',
    exists: 'Esiste già un account con questo indirizzo e-mail. Acceda con le sue credenziali (oppure « Password dimenticata? »).',
    sideTitle: 'I suoi mandanti dell’edilizia, finalmente in ordine.',
    sideText: 'Fatture, pagamenti, registrazioni e giustificativi dei suoi clienti Cantia, in un unico posto.',
  },
  onboarding: {
    title: 'Il suo studio fiduciario',
    intro: 'Qualche informazione per creare il suo spazio. Potrà modificarle in seguito.',
    firmName: 'Nome dello studio',
    firstName: 'Nome',
    lastName: 'Cognome',
    phone: 'Telefono',
    address: 'Indirizzo',
    postalCode: 'NPA',
    city: 'Località',
    country: 'Paese',
    ide: 'IDI (facoltativo)',
    website: 'Sito web (facoltativo)',
    mandates: 'Numero approssimativo di mandati',
    software: 'Software utilizzati',
    softwareNames: { BEXIO: 'Bexio', WINBIZ: 'WinBiz', CRESUS: 'Crésus', ODOO: 'Odoo', ABACUS: 'Abacus', KLARA: 'Klara', OTHER: 'Altro' },
    submit: 'Crea il mio spazio',
    required: 'Nome dello studio, nome e cognome sono obbligatori.',
  },
  tabs: { dashboard: 'Panoramica', clients: 'Mandanti', documents: 'Documenti', team: 'Team', partner: 'Programma partner', settings: 'Studio' },
  dashboard: {
    hello: 'Buongiorno {name}',
    kpis: { active: 'Mandanti attivi', invitations: 'Inviti in attesa', requests: 'Richieste di accesso', documents: 'Documenti', overdue: 'Fatture scadute' },
    open: 'CHF {amount} da incassare presso i suoi mandanti',
    pendingFirmTitle: 'Dei clienti l’hanno invitata',
    pendingFirmText: '{name} le dà accesso ai suoi dati contabili.',
    accept: 'Accettare',
    decline: 'Rifiutare',
    recentDocs: 'Documenti recenti',
    noDocs: 'Ancora nessun documento.',
    emptyTitle: 'Aggiunga il suo primo mandante',
    emptyText: 'Inserisca l’e-mail del cliente: se usa Cantia, riceve una richiesta di accesso; altrimenti un invito gratuito.',
  },
  clients: {
    title: 'I miei mandanti',
    add: 'Aggiungere un mandante',
    search: 'Cercare un mandante…',
    filters: { all: 'Tutti', active: 'Attivi', pending: 'In attesa', attention: 'Da seguire' },
    sort: { name: 'Nome', activity: 'Attività', open: 'Da incassare' },
    columns: { company: 'Impresa', status: 'Stato Cantia', plan: 'Piano', activity: 'Ultima attività', documents: 'Documenti', invoices: 'Fatture', payments: 'Pagamenti 30 g', actions: '' },
    statuses: { ACTIVE: 'Accesso attivo', PENDING_CLIENT: 'In attesa del cliente', PENDING_FIRM: 'Da accettare' },
    subscription: { active: 'Abbonato', trialing: 'Prova', canceled: 'Disdetto', past_due: 'Pagamento in ritardo', none: '—' },
    overdue: '{count} scadute',
    open: 'Aprire',
    cancelRequest: 'Annullare la richiesta',
    empty: 'Ancora nessun mandante.',
    noMatch: 'Nessun mandante corrisponde.',
    invitationsTitle: 'Inviti a Cantia',
    invitationStatuses: { PENDING: 'Inviato', ACCEPTED: 'Iscritto', CANCELLED: 'Annullato', EXPIRED: 'Scaduto' },
    resend: 'Reinviare',
    cancel: 'Annullare',
  },
  addClient: {
    title: 'Aggiungere un mandante',
    text: 'Se usa già Cantia, il cliente riceve una richiesta di accesso. Altrimenti riceve un invito a Cantia e, dopo l’iscrizione, la richiesta di accesso.',
    email: 'E-mail del responsabile',
    company: 'Nome dell’impresa (se nuovo cliente)',
    contact: 'Nome del responsabile (facoltativo)',
    submit: 'Inviare',
    sentRequest: 'Richiesta di accesso inviata. Il cliente deve accettarla in Cantia.',
    sentInvitation: 'Invito inviato. Dopo l’iscrizione, il cliente potrà accettare il suo accesso.',
    withPartner: 'Il suo codice partner è incluso: se diventa cliente pagante, riceve la sua commissione.',
  },
  client: {
    back: 'I miei mandanti',
    notFound: 'Questo mandante non è accessibile. L’accesso potrebbe essere stato revocato.',
    sections: { summary: 'Riepilogo', invoices: 'Fatture', payments: 'Pagamenti', customers: 'Clienti', accounting: 'Contabilità', documents: 'Documenti', quotes: 'Preventivi', hours: 'Ore', payroll: 'Salari', integrations: 'Integrazioni' },
    accessSince: 'Accesso dal {date}',
    permissions: 'Accesso concesso',
    ide: 'IDI',
    noPermission: 'Il cliente non ha aperto questa parte. Può farlo in Cantia, Impostazioni › Fiduciario.',
    period: 'Periodo',
    periods: { month: 'Questo mese', quarter: 'Questo trimestre', year: 'Quest’anno', lastYear: 'Anno precedente' },
    invoices: { number: 'N.', client: 'Cliente', date: 'Data', due: 'Scadenza', total: 'Totale IVA incl.', paid: 'Pagato', status: 'Stato', pdf: 'PDF', none: 'Nessuna fattura nel periodo.' },
    invoiceStatuses: { draft: 'Bozza', ready: 'Pronta', sent: 'Inviata', partial: 'Pagata in parte', paid: 'Pagata', cancelled: 'Annullata' },
    payments: { date: 'Data', invoice: 'Fattura', amount: 'Importo', none: 'Nessun pagamento nel periodo.' },
    customers: { name: 'Nome', email: 'E-mail', phone: 'Telefono', address: 'Indirizzo', none: 'Nessun cliente.' },
    quotes: { number: 'N.', client: 'Cliente', date: 'Data', status: 'Stato', none: 'Nessun preventivo nel periodo.' },
    hours: { date: 'Data', hours: 'Ore', total: 'Totale', none: 'Nessuna ora nel periodo.' },
    payroll: { period: 'Periodo', status: 'Stato', gross: 'Lordo', net: 'Netto', none: 'Nessun salario nel periodo.' },
    summary: { revenue: 'Fatturato (IVA incl.)', collected: 'Incassato', open: 'Da incassare', overdue: 'Scaduto', result: 'Risultato contabile', entries: 'Registrazioni' },
    accounting: {
      income: 'Conto economico',
      revenue: 'Ricavi',
      expenses: 'Costi',
      result: 'Risultato',
      balance: 'Bilancio',
      assets: 'Attivi',
      liabilities: 'Passivi',
      vat: 'IVA per codice',
      vatDue: 'IVA netta dovuta',
      exports: 'Esportazioni',
      exportEntries: 'Registrazioni (CSV)',
      exportTrial: 'Bilancio di verifica (CSV)',
      exportVat: 'Foglio di lavoro IVA (CSV)',
      empty: 'Ancora nessuna registrazione nel periodo.',
    },
    integrations: { bexio: 'Bexio', connected: 'Connesso', notConnected: 'Non connesso', lastSync: 'Ultima sincronizzazione: {date}', error: 'Ultimo errore: {error}', others: 'WinBiz, Crésus, Abacus, Klara: non ancora disponibili. L’esportazione CSV è già possibile.' },
    endMandate: 'Terminare il mandato',
    endMandateConfirm: 'Confermi: perde l’accesso a questo cliente',
  },
  documents: {
    title: 'Documenti',
    text: 'Fatture e giustificativi di tutti i mandanti.',
    search: 'Cercare…',
    allClients: 'Tutti i mandanti',
    kinds: { all: 'Tutto', invoice: 'Fatture', receipt: 'Giustificativi', shared: 'Inviati dal cliente' },
    download: 'Scaricare',
    noFile: 'PDF non ancora generato',
    none: 'Nessun documento.',
  },
  team: {
    title: 'Team',
    invite: 'Invitare un collaboratore',
    email: 'E-mail',
    roles: { OWNER: 'Titolare', ADMIN: 'Amministratore', MEMBER: 'Collaboratore' },
    send: 'Invitare',
    sent: 'Invito inviato.',
    pending: 'Inviti in attesa',
    remove: 'Rimuovere',
    removeConfirm: 'Confermare la rimozione',
    leave: 'Lasciare lo studio',
    you: 'lei',
    historyTitle: 'Registro degli accessi',
    historyEmpty: 'Nessun evento.',
  },
  partnerTab: {
    title: 'Programma partner',
    inactiveText: 'Consigli Cantia ai suoi nuovi mandanti e riceva il 25 % di commissione durante i loro primi 12 mesi.',
    activate: 'Attivare Cantia Partners',
    activeText: 'I suoi inviti ai nuovi mandanti includono automaticamente il suo codice partner.',
    brought: 'Clienti portati',
    earned: 'Totale guadagnato',
    available: 'Commissione disponibile',
    see: 'Vedere le mie commissioni',
    code: 'Il suo link',
  },
  settings: { title: 'Il suo studio', save: 'Salvare', saved: 'Salvato.', language: 'Lingua delle e-mail' },
  invitation: {
    title: 'Invito',
    loading: 'Caricamento…',
    invalid: 'Questo invito non esiste o è scaduto.',
    staff: '{firm} la invita nel suo spazio Cantia Accounting.',
    client: '{org} le dà accesso ai suoi dati contabili su Cantia.',
    signInFirst: 'Acceda o crei un account con {email} per accettare.',
    accept: 'Accettare',
    needsFirm: 'Crei prima il suo spazio fiduciario: l’accesso verrà aggiunto automaticamente.',
    done: 'Fatto.',
    open: 'Aprire il mio spazio',
  },
  admin: { title: 'Fiduciari', kpis: { firms: 'Fiduciari', active: 'Attivi', linked: 'Mandanti collegati', acquired: 'Clienti acquisiti', mrr: 'MRR acquisito', partners: 'Partner', suspicious: 'Sospetti' } },
  permissions: {
    VIEW_INVOICES: 'Fatture',
    VIEW_PAYMENT_STATUS: 'Pagamenti',
    VIEW_CUSTOMERS: 'Clienti',
    VIEW_ACCOUNTING_DOCUMENTS: 'Contabilità e giustificativi',
    DOWNLOAD_DOCUMENTS: 'Download',
    VIEW_EXPORTS: 'Esportazioni',
    VIEW_QUOTES: 'Preventivi',
    VIEW_WORK_HOURS: 'Ore',
    VIEW_PAYROLL_DATA: 'Salari',
    PROPOSE_ENTRIES: 'Proporre registrazioni',
  },
  common: { loading: 'Caricamento…', error: 'Si è verificato un errore.', never: 'mai', yes: 'Sì', no: 'No' },
};

export const ACC_COPY: Record<AccLocale, AccCopy> = { fr, de, it };

export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}
