import { useAccCopy } from './locale';
import type { AccLocale } from './copy';

// Strings of the books kept for a client outside Cantia
// (supabase/migrations/20261009090000_fiduciary_ledger.sql).

const fr = {
  tab: 'Comptabilité',
  start: {
    title: 'Tenir la comptabilité de ce mandant dans Cantia',
    text: 'Saisissez ses écritures à la main ou importez celles de son ancien logiciel (Banana, Abacus, Winbiz, Excel). Vous obtenez le journal, le grand livre, la balance, le bilan, le compte de résultat, un récapitulatif TVA et les indicateurs, comme pour un client Cantia.',
    withChart: 'Ouvrir avec le plan comptable PME suisse',
    withChartHint: '87 comptes dans la langue du client, modifiables.',
    empty: 'Ouvrir sans plan comptable',
    emptyHint: 'Vous importez ensuite le plan comptable du client.',
  },
  views: { journal: 'Journal', accounts: 'Plan comptable', reports: 'Balance et états', kpis: 'Indicateurs', import: 'Importer', settings: 'Clôture' },
  periods: { month: 'Ce mois', quarter: 'Ce trimestre', fy: 'Exercice', lastFy: 'Exercice précédent', all: 'Tout' },
  journal: {
    new: 'Nouvelle écriture',
    search: 'Rechercher (libellé, pièce, n°, montant)',
    all: 'Toutes',
    drafts: 'Brouillons',
    empty: 'Aucune écriture sur cette période.',
    count: '{n} écritures',
    more: 'Afficher plus',
    draft: 'Brouillon',
    changed: 'Modifiée',
    reversal: 'Extourne',
    reversed: 'Extournée',
    imported: 'Importée',
    opening: 'Ouverture',
    edit: 'Modifier',
    reverse: 'Extourner',
    reverseConfirm: 'Confirmer l’extourne',
    reverseDate: 'Date de l’extourne',
    post: 'Comptabiliser',
    discard: 'Supprimer le brouillon',
    discardConfirm: 'Confirmer la suppression',
    by: 'saisie par {name}',
    reversedDone: 'Extourne n° {n} comptabilisée.',
    postedDone: 'Écriture n° {n} comptabilisée.',
    lockedHint: 'Période clôturée jusqu’au {date}.',
  },
  form: {
    titleNew: 'Nouvelle écriture',
    titleEdit: 'Modifier l’écriture n° {n}',
    titleDraft: 'Modifier le brouillon',
    quick: 'Simple',
    split: 'Plusieurs lignes',
    date: 'Date',
    reference: 'Pièce',
    label: 'Libellé',
    labelPlaceholder: 'Ex. Facture 2026-014 Muster SA',
    debit: 'Compte débit',
    credit: 'Compte crédit',
    amount: 'Montant (CHF)',
    amountHint: 'TVA comprise si un code TVA est choisi.',
    vat: 'TVA',
    noVat: 'Sans TVA',
    preview: 'Lignes passées',
    account: 'Compte',
    lineLabel: 'Libellé de la ligne',
    lineDebit: 'Débit',
    lineCredit: 'Crédit',
    vatCode: 'Code TVA',
    addLine: 'Ajouter une ligne',
    balanced: 'Équilibrée',
    difference: 'Écart {amount}',
    save: 'Comptabiliser',
    saveDraft: 'Enregistrer en brouillon',
    saved: 'Écriture n° {n} comptabilisée. La suivante est prête.',
    savedDraft: 'Brouillon enregistré.',
    unknownAccount: 'Compte {code} inconnu : créez-le dans le plan comptable.',
    changeNote: 'L’ancienne version est conservée dans l’historique, l’écriture garde son numéro.',
    enterHint: 'Entrée dans le montant : comptabiliser.',
  },
  vatCodes: {
    V81: 'Vente 8,1 %', V26: 'Vente 2,6 %', V38: 'Vente 3,8 % (hébergement)',
    M81: 'Achat 8,1 % (matériel, prestations)', M26: 'Achat 2,6 % (matériel, prestations)', M38: 'Achat 3,8 % (matériel, prestations)',
    I81: 'Investissement / autres charges 8,1 %', I26: 'Investissement / autres charges 2,6 %', I38: 'Investissement / autres charges 3,8 %',
  } as Record<string, string>,
  accounts: {
    search: 'Rechercher un compte',
    add: 'Ajouter un compte',
    code: 'Numéro',
    label: 'Libellé',
    type: 'Type',
    types: { actif: 'Actif', passif: 'Passif', produit: 'Produit', charge: 'Charge' },
    active: 'Actif dans la saisie',
    inactive: 'Désactivé',
    ledger: 'Grand livre',
    used: 'utilisé',
    empty: 'Aucun compte. Importez le plan comptable du client ou ajoutez vos comptes.',
    classes: {
      '1': 'Actifs', '2': 'Passifs', '3': 'Produits d’exploitation', '4': 'Charges de matériel et de marchandises', '5': 'Charges de personnel',
      '6': 'Autres charges d’exploitation, amortissements, résultat financier', '7': 'Résultats des activités annexes', '8': 'Résultats hors exploitation et impôts', '9': 'Clôture',
    } as Record<string, string>,
    other: 'Autres comptes',
  },
  ledgerView: {
    title: 'Grand livre {code} {label}',
    opening: 'Solde d’ouverture',
    closing: 'Solde final',
    date: 'Date',
    number: 'N°',
    reference: 'Pièce',
    label: 'Libellé',
    counterpart: 'Contrepartie',
    debit: 'Débit',
    credit: 'Crédit',
    balance: 'Solde',
    empty: 'Aucun mouvement sur cette période.',
    download: 'Télécharger (CSV)',
    back: 'Retour au plan comptable',
  },
  reports: {
    balanceSheet: 'Bilan au {date}',
    income: 'Compte de résultat du {from} au {to}',
    assets: 'Actifs',
    liabilities: 'Passifs',
    totalAssets: 'Total des actifs',
    totalLiabilities: 'Total des passifs',
    yearResult: 'Résultat de l’exercice en cours',
    priorResults: 'Résultats des exercices précédents non répartis',
    revenue: 'Produits',
    expenses: 'Charges',
    result: 'Résultat',
    profit: 'Bénéfice',
    loss: 'Perte',
    trial: 'Balance des comptes',
    trialCols: { account: 'Compte', opening: 'Ouverture', debit: 'Débit', credit: 'Crédit', closing: 'Solde' },
    downloadTrial: 'Télécharger la balance (CSV)',
    vat: 'Récapitulatif TVA',
    vatText: 'Montants nets par code TVA sur la période, et TVA comptabilisée. Base de votre décompte AFC.',
    vatCols: { code: 'Code', net: 'Montant net', lines: 'Lignes' },
    vatDue: 'TVA due (2200)',
    inputTax: 'Impôt préalable (1170 / 1171)',
    vatNet: 'Solde à payer à l’AFC',
    vatNone: 'Aucune écriture avec un code TVA sur cette période.',
    empty: 'Aucune écriture comptabilisée sur cette période.',
    exports: 'Exporter vers le logiciel du client',
  },
  import: {
    kinds: { journal: 'Écritures', chart: 'Plan comptable', opening: 'Soldes d’ouverture' },
    journalText: 'Fichier des écritures exporté de Banana (texte séparé par tabulations), Abacus, Winbiz, ou tout tableau CSV / Excel avec une date, une pièce, un libellé, un compte débit, un compte crédit et un montant (ou un compte par ligne avec débit et crédit).',
    chartText: 'Plan comptable : numéro et libellé (Banana : Comptes › exporter ; Abacus, Winbiz : CSV ou Excel). Les comptes existants prennent le nouveau libellé.',
    openingText: 'Soldes au dernier bouclement : compte, libellé, solde (débit − crédit, ou passifs en positif : détecté automatiquement). Une seule écriture d’ouverture est passée ; l’écart éventuel va au compte 9100.',
    pick: 'Choisir un fichier',
    reading: 'Lecture du fichier…',
    unreadable: 'Fichier illisible. Formats acceptés : .txt, .csv, .xlsx, .xls.',
    noHeader: 'Colonnes introuvables : il faut au moins une date, un compte et un montant.',
    found: '{entries} écritures trouvées · {lines} lignes · {skipped} lignes ignorées',
    foundChart: '{n} comptes trouvés · {skipped} lignes ignorées',
    foundOpening: '{n} soldes trouvés',
    inverted: 'Passifs en positif dans le fichier : signes corrigés.',
    diff: 'Écart de {amount} passé au compte 9100.',
    errors: 'Écritures déséquilibrées (non importées) :',
    errorRow: 'ligne {row} : débit {debit} ≠ crédit {credit}',
    unknown: '{n} comptes inconnus du plan comptable : {list}',
    createAccounts: 'Créer les comptes inconnus',
    post: 'Comptabiliser directement (sinon : brouillons)',
    openingDate: 'Date d’ouverture',
    confirm: 'Importer',
    done: '{n} importés.',
    partial: 'Import interrompu après {n} écritures : {error}',
    preview: 'Aperçu',
    more: '… et {n} autres',
  },
  settings: {
    lockTitle: 'Clôture de période',
    lockText: 'Une période clôturée ne peut plus être modifiée : plus de saisie ni de modification jusqu’à cette date, seulement des extournes datées après. À faire après chaque décompte TVA et au bouclement.',
    lockedUntil: 'Clôturé jusqu’au {date}.',
    notLocked: 'Aucune période clôturée.',
    lockDate: 'Clôturer jusqu’au',
    lock: 'Clôturer',
    unlock: 'Rouvrir toutes les périodes',
    unlockConfirm: 'Confirmer la réouverture',
    adminOnly: 'Seuls les administrateurs de la fiduciaire clôturent et rouvrent.',
    done: 'Enregistré.',
  },
  kpisEmpty: 'Les indicateurs apparaissent dès les premières écritures comptabilisées.',
};

type Copy = typeof fr;

const de: Copy = {
  tab: 'Buchhaltung',
  start: {
    title: 'Die Buchhaltung dieses Mandanten in Cantia führen',
    text: 'Erfassen Sie die Buchungen von Hand oder importieren Sie jene der bisherigen Software (Banana, Abacus, Winbiz, Excel). Sie erhalten Journal, Hauptbuch, Saldobilanz, Bilanz, Erfolgsrechnung, MWST-Übersicht und Kennzahlen wie bei einem Cantia-Kunden.',
    withChart: 'Mit dem Schweizer KMU-Kontenrahmen eröffnen',
    withChartHint: '87 Konten in der Sprache des Kunden, anpassbar.',
    empty: 'Ohne Kontenplan eröffnen',
    emptyHint: 'Sie importieren danach den Kontenplan des Kunden.',
  },
  views: { journal: 'Journal', accounts: 'Kontenplan', reports: 'Saldobilanz und Abschluss', kpis: 'Kennzahlen', import: 'Importieren', settings: 'Periodenabschluss' },
  periods: { month: 'Dieser Monat', quarter: 'Dieses Quartal', fy: 'Geschäftsjahr', lastFy: 'Vorjahr', all: 'Alle' },
  journal: {
    new: 'Neue Buchung',
    search: 'Suchen (Text, Beleg, Nr., Betrag)',
    all: 'Alle',
    drafts: 'Entwürfe',
    empty: 'Keine Buchungen in dieser Periode.',
    count: '{n} Buchungen',
    more: 'Mehr anzeigen',
    draft: 'Entwurf',
    changed: 'Geändert',
    reversal: 'Storno',
    reversed: 'Storniert',
    imported: 'Importiert',
    opening: 'Eröffnung',
    edit: 'Ändern',
    reverse: 'Stornieren',
    reverseConfirm: 'Storno bestätigen',
    reverseDate: 'Datum des Stornos',
    post: 'Verbuchen',
    discard: 'Entwurf löschen',
    discardConfirm: 'Löschen bestätigen',
    by: 'erfasst von {name}',
    reversedDone: 'Storno Nr. {n} verbucht.',
    postedDone: 'Buchung Nr. {n} verbucht.',
    lockedHint: 'Periode abgeschlossen bis {date}.',
  },
  form: {
    titleNew: 'Neue Buchung',
    titleEdit: 'Buchung Nr. {n} ändern',
    titleDraft: 'Entwurf ändern',
    quick: 'Einfach',
    split: 'Sammelbuchung',
    date: 'Datum',
    reference: 'Beleg',
    label: 'Text',
    labelPlaceholder: 'z. B. Rechnung 2026-014 Muster AG',
    debit: 'Soll-Konto',
    credit: 'Haben-Konto',
    amount: 'Betrag (CHF)',
    amountHint: 'Inkl. MWST, wenn ein MWST-Code gewählt ist.',
    vat: 'MWST',
    noVat: 'Ohne MWST',
    preview: 'Gebuchte Zeilen',
    account: 'Konto',
    lineLabel: 'Text der Zeile',
    lineDebit: 'Soll',
    lineCredit: 'Haben',
    vatCode: 'MWST-Code',
    addLine: 'Zeile hinzufügen',
    balanced: 'Ausgeglichen',
    difference: 'Differenz {amount}',
    save: 'Verbuchen',
    saveDraft: 'Als Entwurf speichern',
    saved: 'Buchung Nr. {n} verbucht. Die nächste ist bereit.',
    savedDraft: 'Entwurf gespeichert.',
    unknownAccount: 'Konto {code} unbekannt: im Kontenplan erstellen.',
    changeNote: 'Die alte Version bleibt im Verlauf, die Buchung behält ihre Nummer.',
    enterHint: 'Enter im Betrag: verbuchen.',
  },
  vatCodes: {
    V81: 'Umsatz 8,1 %', V26: 'Umsatz 2,6 %', V38: 'Umsatz 3,8 % (Beherbergung)',
    M81: 'Vorsteuer 8,1 % (Material, DL)', M26: 'Vorsteuer 2,6 % (Material, DL)', M38: 'Vorsteuer 3,8 % (Material, DL)',
    I81: 'Vorsteuer 8,1 % (Investitionen, übriger BA)', I26: 'Vorsteuer 2,6 % (Investitionen, übriger BA)', I38: 'Vorsteuer 3,8 % (Investitionen, übriger BA)',
  },
  accounts: {
    search: 'Konto suchen',
    add: 'Konto hinzufügen',
    code: 'Nummer',
    label: 'Bezeichnung',
    type: 'Art',
    types: { actif: 'Aktiv', passif: 'Passiv', produit: 'Ertrag', charge: 'Aufwand' },
    active: 'In der Erfassung aktiv',
    inactive: 'Deaktiviert',
    ledger: 'Hauptbuch',
    used: 'verwendet',
    empty: 'Keine Konten. Importieren Sie den Kontenplan des Kunden oder fügen Sie Konten hinzu.',
    classes: {
      '1': 'Aktiven', '2': 'Passiven', '3': 'Betrieblicher Ertrag', '4': 'Aufwand für Material und Waren', '5': 'Personalaufwand',
      '6': 'Übriger Betriebsaufwand, Abschreibungen, Finanzerfolg', '7': 'Betrieblicher Nebenerfolg', '8': 'Betriebsfremder Erfolg und Steuern', '9': 'Abschluss',
    },
    other: 'Weitere Konten',
  },
  ledgerView: {
    title: 'Hauptbuch {code} {label}',
    opening: 'Eröffnungssaldo',
    closing: 'Schlusssaldo',
    date: 'Datum',
    number: 'Nr.',
    reference: 'Beleg',
    label: 'Text',
    counterpart: 'Gegenkonto',
    debit: 'Soll',
    credit: 'Haben',
    balance: 'Saldo',
    empty: 'Keine Bewegungen in dieser Periode.',
    download: 'Herunterladen (CSV)',
    back: 'Zurück zum Kontenplan',
  },
  reports: {
    balanceSheet: 'Bilanz per {date}',
    income: 'Erfolgsrechnung vom {from} bis {to}',
    assets: 'Aktiven',
    liabilities: 'Passiven',
    totalAssets: 'Total Aktiven',
    totalLiabilities: 'Total Passiven',
    yearResult: 'Ergebnis des laufenden Jahres',
    priorResults: 'Nicht verteilte Ergebnisse der Vorjahre',
    revenue: 'Ertrag',
    expenses: 'Aufwand',
    result: 'Ergebnis',
    profit: 'Gewinn',
    loss: 'Verlust',
    trial: 'Saldobilanz',
    trialCols: { account: 'Konto', opening: 'Eröffnung', debit: 'Soll', credit: 'Haben', closing: 'Saldo' },
    downloadTrial: 'Saldobilanz herunterladen (CSV)',
    vat: 'MWST-Übersicht',
    vatText: 'Nettobeträge pro MWST-Code in der Periode und verbuchte MWST. Grundlage Ihrer ESTV-Abrechnung.',
    vatCols: { code: 'Code', net: 'Nettobetrag', lines: 'Zeilen' },
    vatDue: 'Geschuldete MWST (2200)',
    inputTax: 'Vorsteuer (1170 / 1171)',
    vatNet: 'Zahllast an die ESTV',
    vatNone: 'Keine Buchungen mit MWST-Code in dieser Periode.',
    empty: 'Keine verbuchten Buchungen in dieser Periode.',
    exports: 'In die Software des Kunden exportieren',
  },
  import: {
    kinds: { journal: 'Buchungen', chart: 'Kontenplan', opening: 'Eröffnungssaldi' },
    journalText: 'Buchungsdatei aus Banana (tabulatorgetrennt), Abacus, Winbiz oder eine CSV- / Excel-Tabelle mit Datum, Beleg, Text, Soll-Konto, Haben-Konto und Betrag (oder ein Konto pro Zeile mit Soll und Haben).',
    chartText: 'Kontenplan: Nummer und Bezeichnung (Banana: Konten › exportieren; Abacus, Winbiz: CSV oder Excel). Bestehende Konten erhalten die neue Bezeichnung.',
    openingText: 'Saldi des letzten Abschlusses: Konto, Bezeichnung, Saldo (Soll − Haben, oder Passiven positiv: wird erkannt). Es wird eine Eröffnungsbuchung erstellt; eine Differenz geht auf Konto 9100.',
    pick: 'Datei wählen',
    reading: 'Datei wird gelesen…',
    unreadable: 'Datei nicht lesbar. Formate: .txt, .csv, .xlsx, .xls.',
    noHeader: 'Spalten nicht gefunden: mindestens Datum, Konto und Betrag nötig.',
    found: '{entries} Buchungen gefunden · {lines} Zeilen · {skipped} Zeilen übersprungen',
    foundChart: '{n} Konten gefunden · {skipped} Zeilen übersprungen',
    foundOpening: '{n} Saldi gefunden',
    inverted: 'Passiven in der Datei positiv: Vorzeichen korrigiert.',
    diff: 'Differenz von {amount} auf Konto 9100 gebucht.',
    errors: 'Nicht ausgeglichene Buchungen (nicht importiert):',
    errorRow: 'Zeile {row}: Soll {debit} ≠ Haben {credit}',
    unknown: '{n} Konten fehlen im Kontenplan: {list}',
    createAccounts: 'Fehlende Konten erstellen',
    post: 'Direkt verbuchen (sonst: Entwürfe)',
    openingDate: 'Eröffnungsdatum',
    confirm: 'Importieren',
    done: '{n} importiert.',
    partial: 'Import nach {n} Buchungen abgebrochen: {error}',
    preview: 'Vorschau',
    more: '… und {n} weitere',
  },
  settings: {
    lockTitle: 'Periodenabschluss',
    lockText: 'Eine abgeschlossene Periode kann nicht mehr geändert werden: keine Erfassung und keine Änderung bis zu diesem Datum, nur Stornos mit späterem Datum. Nach jeder MWST-Abrechnung und beim Jahresabschluss.',
    lockedUntil: 'Abgeschlossen bis {date}.',
    notLocked: 'Keine Periode abgeschlossen.',
    lockDate: 'Abschliessen bis',
    lock: 'Abschliessen',
    unlock: 'Alle Perioden wieder öffnen',
    unlockConfirm: 'Wiedereröffnung bestätigen',
    adminOnly: 'Nur Administratoren der Treuhand schliessen ab und öffnen wieder.',
    done: 'Gespeichert.',
  },
  kpisEmpty: 'Die Kennzahlen erscheinen ab den ersten verbuchten Buchungen.',
};

const it: Copy = {
  tab: 'Contabilità',
  start: {
    title: 'Tenere la contabilità di questo mandante in Cantia',
    text: 'Registri le scritture a mano o importi quelle del vecchio software (Banana, Abacus, Winbiz, Excel). Ottiene giornale, mastro, bilancio di verifica, bilancio, conto economico, riepilogo IVA e indicatori, come per un cliente Cantia.',
    withChart: 'Aprire con il piano contabile PMI svizzero',
    withChartHint: '87 conti nella lingua del cliente, modificabili.',
    empty: 'Aprire senza piano contabile',
    emptyHint: 'Importerà poi il piano contabile del cliente.',
  },
  views: { journal: 'Giornale', accounts: 'Piano contabile', reports: 'Bilancio e rendiconti', kpis: 'Indicatori', import: 'Importare', settings: 'Chiusura' },
  periods: { month: 'Questo mese', quarter: 'Questo trimestre', fy: 'Esercizio', lastFy: 'Esercizio precedente', all: 'Tutto' },
  journal: {
    new: 'Nuova scrittura',
    search: 'Cercare (testo, giustificativo, n°, importo)',
    all: 'Tutte',
    drafts: 'Bozze',
    empty: 'Nessuna scrittura in questo periodo.',
    count: '{n} scritture',
    more: 'Mostrare altre',
    draft: 'Bozza',
    changed: 'Modificata',
    reversal: 'Storno',
    reversed: 'Stornata',
    imported: 'Importata',
    opening: 'Apertura',
    edit: 'Modificare',
    reverse: 'Stornare',
    reverseConfirm: 'Confermare lo storno',
    reverseDate: 'Data dello storno',
    post: 'Contabilizzare',
    discard: 'Eliminare la bozza',
    discardConfirm: 'Confermare l’eliminazione',
    by: 'registrata da {name}',
    reversedDone: 'Storno n° {n} contabilizzato.',
    postedDone: 'Scrittura n° {n} contabilizzata.',
    lockedHint: 'Periodo chiuso fino al {date}.',
  },
  form: {
    titleNew: 'Nuova scrittura',
    titleEdit: 'Modificare la scrittura n° {n}',
    titleDraft: 'Modificare la bozza',
    quick: 'Semplice',
    split: 'Più righe',
    date: 'Data',
    reference: 'Giustificativo',
    label: 'Testo',
    labelPlaceholder: 'Es. Fattura 2026-014 Muster SA',
    debit: 'Conto dare',
    credit: 'Conto avere',
    amount: 'Importo (CHF)',
    amountHint: 'IVA inclusa se è scelto un codice IVA.',
    vat: 'IVA',
    noVat: 'Senza IVA',
    preview: 'Righe registrate',
    account: 'Conto',
    lineLabel: 'Testo della riga',
    lineDebit: 'Dare',
    lineCredit: 'Avere',
    vatCode: 'Codice IVA',
    addLine: 'Aggiungere una riga',
    balanced: 'In pareggio',
    difference: 'Differenza {amount}',
    save: 'Contabilizzare',
    saveDraft: 'Salvare come bozza',
    saved: 'Scrittura n° {n} contabilizzata. La prossima è pronta.',
    savedDraft: 'Bozza salvata.',
    unknownAccount: 'Conto {code} sconosciuto: lo crei nel piano contabile.',
    changeNote: 'La vecchia versione resta nello storico, la scrittura mantiene il suo numero.',
    enterHint: 'Invio nell’importo: contabilizzare.',
  },
  vatCodes: {
    V81: 'Vendita 8,1 %', V26: 'Vendita 2,6 %', V38: 'Vendita 3,8 % (alloggio)',
    M81: 'Acquisto 8,1 % (materiale, prestazioni)', M26: 'Acquisto 2,6 % (materiale, prestazioni)', M38: 'Acquisto 3,8 % (materiale, prestazioni)',
    I81: 'Investimento / altri costi 8,1 %', I26: 'Investimento / altri costi 2,6 %', I38: 'Investimento / altri costi 3,8 %',
  },
  accounts: {
    search: 'Cercare un conto',
    add: 'Aggiungere un conto',
    code: 'Numero',
    label: 'Descrizione',
    type: 'Tipo',
    types: { actif: 'Attivo', passif: 'Passivo', produit: 'Ricavo', charge: 'Costo' },
    active: 'Attivo nella registrazione',
    inactive: 'Disattivato',
    ledger: 'Mastro',
    used: 'utilizzato',
    empty: 'Nessun conto. Importi il piano contabile del cliente o aggiunga i conti.',
    classes: {
      '1': 'Attivi', '2': 'Passivi', '3': 'Ricavi d’esercizio', '4': 'Costi per materiale e merci', '5': 'Costi del personale',
      '6': 'Altri costi d’esercizio, ammortamenti, risultato finanziario', '7': 'Risultati delle attività accessorie', '8': 'Risultati estranei all’esercizio e imposte', '9': 'Chiusura',
    },
    other: 'Altri conti',
  },
  ledgerView: {
    title: 'Mastro {code} {label}',
    opening: 'Saldo d’apertura',
    closing: 'Saldo finale',
    date: 'Data',
    number: 'N°',
    reference: 'Giustificativo',
    label: 'Testo',
    counterpart: 'Contropartita',
    debit: 'Dare',
    credit: 'Avere',
    balance: 'Saldo',
    empty: 'Nessun movimento in questo periodo.',
    download: 'Scaricare (CSV)',
    back: 'Tornare al piano contabile',
  },
  reports: {
    balanceSheet: 'Bilancio al {date}',
    income: 'Conto economico dal {from} al {to}',
    assets: 'Attivi',
    liabilities: 'Passivi',
    totalAssets: 'Totale attivi',
    totalLiabilities: 'Totale passivi',
    yearResult: 'Risultato dell’esercizio in corso',
    priorResults: 'Risultati degli esercizi precedenti non ripartiti',
    revenue: 'Ricavi',
    expenses: 'Costi',
    result: 'Risultato',
    profit: 'Utile',
    loss: 'Perdita',
    trial: 'Bilancio di verifica',
    trialCols: { account: 'Conto', opening: 'Apertura', debit: 'Dare', credit: 'Avere', closing: 'Saldo' },
    downloadTrial: 'Scaricare il bilancio di verifica (CSV)',
    vat: 'Riepilogo IVA',
    vatText: 'Importi netti per codice IVA nel periodo e IVA contabilizzata. Base del suo rendiconto AFC.',
    vatCols: { code: 'Codice', net: 'Importo netto', lines: 'Righe' },
    vatDue: 'IVA dovuta (2200)',
    inputTax: 'Imposta precedente (1170 / 1171)',
    vatNet: 'Saldo da pagare all’AFC',
    vatNone: 'Nessuna scrittura con codice IVA in questo periodo.',
    empty: 'Nessuna scrittura contabilizzata in questo periodo.',
    exports: 'Esportare verso il software del cliente',
  },
  import: {
    kinds: { journal: 'Scritture', chart: 'Piano contabile', opening: 'Saldi d’apertura' },
    journalText: 'File delle scritture esportato da Banana (testo separato da tabulazioni), Abacus, Winbiz o qualsiasi tabella CSV / Excel con data, giustificativo, testo, conto dare, conto avere e importo (o un conto per riga con dare e avere).',
    chartText: 'Piano contabile: numero e descrizione (Banana: Conti › esportare; Abacus, Winbiz: CSV o Excel). I conti esistenti prendono la nuova descrizione.',
    openingText: 'Saldi dell’ultima chiusura: conto, descrizione, saldo (dare − avere, o passivi positivi: rilevato automaticamente). Viene registrata una scrittura d’apertura; un’eventuale differenza va sul conto 9100.',
    pick: 'Scegliere un file',
    reading: 'Lettura del file…',
    unreadable: 'File illeggibile. Formati: .txt, .csv, .xlsx, .xls.',
    noHeader: 'Colonne non trovate: servono almeno data, conto e importo.',
    found: '{entries} scritture trovate · {lines} righe · {skipped} righe ignorate',
    foundChart: '{n} conti trovati · {skipped} righe ignorate',
    foundOpening: '{n} saldi trovati',
    inverted: 'Passivi positivi nel file: segni corretti.',
    diff: 'Differenza di {amount} registrata sul conto 9100.',
    errors: 'Scritture non in pareggio (non importate):',
    errorRow: 'riga {row}: dare {debit} ≠ avere {credit}',
    unknown: '{n} conti mancano nel piano contabile: {list}',
    createAccounts: 'Creare i conti mancanti',
    post: 'Contabilizzare subito (altrimenti: bozze)',
    openingDate: 'Data d’apertura',
    confirm: 'Importare',
    done: '{n} importati.',
    partial: 'Importazione interrotta dopo {n} scritture: {error}',
    preview: 'Anteprima',
    more: '… e altre {n}',
  },
  settings: {
    lockTitle: 'Chiusura del periodo',
    lockText: 'Un periodo chiuso non può più essere modificato: nessuna registrazione né modifica fino a questa data, solo storni con data successiva. Dopo ogni rendiconto IVA e alla chiusura annuale.',
    lockedUntil: 'Chiuso fino al {date}.',
    notLocked: 'Nessun periodo chiuso.',
    lockDate: 'Chiudere fino al',
    lock: 'Chiudere',
    unlock: 'Riaprire tutti i periodi',
    unlockConfirm: 'Confermare la riapertura',
    adminOnly: 'Solo gli amministratori della fiduciaria chiudono e riaprono.',
    done: 'Salvato.',
  },
  kpisEmpty: 'Gli indicatori appaiono dalle prime scritture contabilizzate.',
};

const LEDGER_COPY: Record<AccLocale, Copy> = { fr, de, it };

export function useLedgerCopy(): Copy {
  const { locale } = useAccCopy();
  return LEDGER_COPY[locale];
}
