import { useAccCopy } from './locale';
import type { AccLocale } from './copy';

// Strings of the fiduciary tools added in 20261008140000_fiduciary_pro.sql
// (clients outside Cantia, work, time, approvals, entry proposals,
// indicators, exports, brand and directory, the client's private link).

const fr = {
  shell: { work: 'Travaux', time: 'Temps', approvals: 'Signatures' },
  common: {
    save: 'Enregistrer',
    saved: 'Enregistré.',
    cancel: 'Annuler',
    edit: 'Modifier',
    remove: 'Retirer',
    add: 'Ajouter',
    copy: 'Copier le lien',
    copied: 'Lien copié',
    all: 'Tous',
    client: 'Mandant',
    chooseClient: 'Choisir un mandant',
    nobody: 'Personne',
    loading: 'Chargement…',
    invalidDate: 'Date invalide (JJ.MM.AAAA).',
    datePlaceholder: 'JJ.MM.AAAA',
    due: 'Échéance',
    noDue: 'Sans échéance',
    by: 'par {name}',
    external: 'Hors Cantia',
    cantia: 'Sur Cantia',
  },
  ext: {
    addTitle: 'Ajouter un mandant hors Cantia',
    addText: 'Pour vos clients sur Abacus, Banana, Winbiz ou Excel : vous suivez leurs échéances, leurs travaux et votre temps ici, et ils vous envoient leurs pièces par un lien privé, sans créer de compte.',
    add: 'Mandant hors Cantia',
    edit: 'Modifier la fiche',
    name: 'Nom de l’entreprise',
    contact: 'Personne de contact',
    email: 'E-mail du client',
    emailHint: 'Les demandes de documents et les documents à signer lui sont envoyés à cette adresse.',
    phone: 'Téléphone',
    address: 'Adresse',
    postalCode: 'NPA',
    city: 'Localité',
    ide: 'IDE',
    software: 'Logiciel comptable',
    rate: 'Tarif horaire (CHF)',
    rateHint: 'Vide : le tarif par défaut de la fiduciaire.',
    language: 'Langue des e-mails',
    created: 'Mandant ajouté.',
    sectionTitle: 'Mandants hors Cantia',
    sectionEmpty: 'Aucun mandant hors Cantia. Ajoutez vos clients qui utilisent un autre logiciel pour tout suivre au même endroit.',
    portalTitle: 'Lien privé du client',
    portalText: 'Le client y envoie ses documents et signe ce que vous lui soumettez, sans compte. Gardez ce lien privé.',
    newLink: 'Générer un nouveau lien',
    newLinkConfirm: 'Confirmer : l’ancien lien ne fonctionnera plus',
    newLinkDone: 'Nouveau lien créé. L’ancien ne fonctionne plus.',
    archive: 'Archiver le mandant',
    archiveConfirm: 'Confirmer l’archivage',
    archived: 'Archivé',
    restore: 'Réactiver',
    invite: 'Lui proposer Cantia',
    inviteText: 'S’il passe sur Cantia, vous voyez directement ses factures, paiements et écritures.',
    invited: 'Invitation envoyée.',
    notFound: 'Ce mandant n’existe pas ou a été archivé.',
    settings: 'Fiche',
  },
  work: {
    title: 'Travaux',
    text: 'Bouclements, décomptes TVA, salaires de fin d’année : chaque travail suit une liste d’étapes, avec un responsable et une échéance. Toute l’équipe voit où en est chaque dossier.',
    new: 'Nouveau travail',
    what: 'Travail',
    titlePlaceholder: 'Ex. Bouclement 2025',
    period: 'Période',
    periodPlaceholder: 'Ex. 2025, T3 2026',
    kind: 'Type',
    assigned: 'Responsable',
    steps: 'Étapes',
    stepsHint: 'Une étape par ligne.',
    fromTemplate: 'Partir d’un modèle',
    create: 'Créer le travail',
    created: 'Travail créé.',
    addStep: 'Ajouter une étape',
    stepPlaceholder: 'Nouvelle étape',
    empty: 'Aucun travail en cours.',
    emptyFilter: 'Aucun travail dans cette vue.',
    progress: '{done}/{total} étapes',
    timeSpent: '{time} h passées',
    mine: 'Les miens',
    filters: { open: 'En cours', late: 'En retard', waiting: 'Attente client', done: 'Terminés', all: 'Tous' },
    kinds: { closing: 'Bouclement', vat: 'TVA', payroll: 'Salaires', tax: 'Impôts', onboarding: 'Nouveau mandat', other: 'Autre' },
    statuses: { todo: 'À faire', in_progress: 'En cours', waiting_client: 'Attente client', review: 'À réviser', done: 'Terminé', cancelled: 'Annulé' },
    cancelWork: 'Annuler ce travail',
    templatesTitle: 'Modèles de la fiduciaire',
    templatesText: 'Vos listes d’étapes réutilisables. Les modèles proposés par Cantia servent de point de départ.',
    templateName: 'Nom du modèle',
    saveTemplate: 'Enregistrer le modèle',
    newTemplate: 'Nouveau modèle',
    useDefaults: 'Ajouter les modèles Cantia',
    defaultsAdded: 'Modèles ajoutés.',
    archiveTemplate: 'Retirer',
  },
  time: {
    title: 'Temps et honoraires',
    text: 'Saisissez votre temps par mandant. Le tarif du mandant (ou celui de la fiduciaire) est appliqué ; marquez les heures facturées une fois votre facture envoyée.',
    new: 'Saisir du temps',
    date: 'Date',
    duration: 'Durée',
    durationPlaceholder: 'Ex. 1:30 ou 90',
    description: 'Description',
    descriptionPlaceholder: 'Ex. Saisie des pièces T3',
    billable: 'Facturable',
    notBillable: 'Non facturable',
    work: 'Travail lié (facultatif)',
    added: 'Temps enregistré.',
    invalidDuration: 'Durée invalide (ex. 1:30 ou 90 minutes).',
    empty: 'Aucun temps sur la période.',
    periods: { week: 'Cette semaine', month: 'Ce mois', lastMonth: 'Mois passé', year: 'Cette année' },
    toBill: 'À facturer',
    billed: 'Facturé',
    total: 'Total',
    amount: 'Montant',
    markBilled: 'Marquer facturé',
    markedBilled: '{count} saisie(s) marquée(s) facturées.',
    reopen: 'Rouvrir',
    void: 'Retirer',
    byClient: 'Par mandant',
    byPerson: 'Par collaborateur',
    export: 'Exporter (CSV)',
    rateMissing: 'Tarif non défini',
    defaultRate: 'Tarif horaire par défaut (CHF)',
    clientRate: 'Tarif horaire de ce mandant (CHF)',
    clientRateHint: 'Vide : tarif par défaut de la fiduciaire.',
  },
  approvals: {
    title: 'Documents à signer',
    text: 'Envoyez des comptes annuels, une déclaration ou une lettre de mission à valider. Le client signe dans Cantia ou par son lien privé ; vous gardez la preuve (nom, date, empreinte du document).',
    new: 'Nouveau document à signer',
    kind: 'Type',
    docTitle: 'Titre',
    titlePlaceholder: 'Ex. Comptes annuels 2025',
    message: 'Message (facultatif)',
    file: 'Document (PDF)',
    pickFile: 'Choisir un fichier',
    send: 'Envoyer pour signature',
    sent: 'Document envoyé au client.',
    empty: 'Aucun document envoyé.',
    statuses: { pending: 'En attente', approved: 'Signé', rejected: 'Refusé' },
    kinds: { annual_accounts: 'Comptes annuels', tax_return: 'Déclaration d’impôt', vat_return: 'Décompte TVA', payroll: 'Salaires', engagement: 'Lettre de mission', other: 'Autre' },
    signedBy: 'Signé par {name} le {date}',
    rejectedBy: 'Refusé par {name} le {date}',
    reason: 'Motif : {reason}',
    proof: 'Preuve',
    fingerprint: 'Empreinte SHA-256',
    ip: 'Adresse IP',
    remind: 'Relancer',
    reminded: 'Rappel envoyé.',
    cancelDoc: 'Retirer',
    noEmail: 'Ce mandant n’a pas d’e-mail : envoyez-lui son lien privé vous-même.',
    open: 'Ouvrir le document',
  },
  proposals: {
    title: 'Écritures proposées',
    text: 'Préparez une écriture de correction : le client la valide dans Cantia, puis elle entre dans sa comptabilité.',
    notAllowed: 'Le mandant n’a pas activé « Proposer des écritures ». Il peut le faire dans Cantia, Paramètres › Fiduciaire.',
    new: 'Proposer une écriture',
    date: 'Date de l’écriture',
    label: 'Libellé',
    labelPlaceholder: 'Ex. Correction frais bancaires T3',
    reason: 'Explication pour le client',
    account: 'Compte',
    accountPlaceholder: 'N° ou nom',
    lineLabel: 'Texte (facultatif)',
    debit: 'Débit',
    credit: 'Crédit',
    addLine: 'Ajouter une ligne',
    balance: 'Écart : {amount}',
    balanced: 'Équilibrée',
    send: 'Envoyer au client',
    sent: 'Écriture proposée au client.',
    empty: 'Aucune écriture proposée.',
    statuses: { pending: 'En attente du client', accepted: 'Acceptée', rejected: 'Refusée' },
    posted: 'comptabilisée',
    draft: 'en brouillon chez le client',
    withdraw: 'Retirer',
  },
  kpis: {
    title: 'Indicateurs',
    from: 'Exercice au {date}',
    vsPrev: 'vs {value} l’an dernier',
    revenue: 'Chiffre d’affaires',
    gross: 'Marge brute',
    ebitda: 'EBITDA',
    ebit: 'EBIT',
    result: 'Résultat',
    liquid: 'Liquidités',
    receivables: 'Débiteurs',
    shortDebt: 'Dettes à court terme',
    equity: 'Fonds propres',
    quick: 'Liquidité réduite (quick ratio)',
    current: 'Liquidité générale',
    equityRatio: 'Taux de fonds propres',
    dso: 'Délai d’encaissement',
    days: '{n} j',
    margin: '{pct} % du CA',
    chart: 'Chiffre d’affaires et résultat, 12 derniers mois',
    none: 'Pas encore d’écritures comptabilisées.',
    noAccess: 'Le mandant n’a pas ouvert sa comptabilité.',
    hint: 'Calculés sur les écritures comptabilisées, selon le plan comptable PME suisse (3 produits, 4 matériel, 5 personnel, 6 autres charges, 68 amortissements, 69 finances, 89 impôts).',
  },
  portfolio: {
    title: 'Portefeuille',
    text: 'Tous vos mandants, sur Cantia ou non : chiffres clés quand la comptabilité est ouverte, et ce qui attend.',
    table: 'Vue portefeuille',
    list: 'Liste',
    columns: { client: 'Mandant', software: 'Logiciel', revenue: 'CA', ebit: 'EBIT', liquid: 'Liquidités', quick: 'Quick ratio', open: 'En attente', time: 'À facturer' },
    pending: '{requests} dem. · {work} trav. · {sign} sign.',
    totals: 'Total',
  },
  exports: {
    title: 'Exporter vers votre logiciel',
    text: 'Les écritures comptabilisées de la période, au format d’import de votre logiciel. Les comptes et codes TVA sont ceux du mandant : vérifiez la correspondance lors du premier import.',
    entries: 'Écritures',
    balances: 'Soldes des comptes',
    help: {
      banana: 'Banana : Actions › Importer dans la comptabilité › Écritures (fichier texte).',
      abacus: 'Abacus : import des écritures FIBU (CSV), à associer une fois dans votre définition d’import.',
      winbiz: 'Winbiz : Comptabilité › Importer des écritures (CSV).',
    },
    none: 'Aucune écriture comptabilisée sur la période.',
    done: '{count} écritures exportées.',
  },
  brand: {
    title: 'Image et annuaire',
    text: 'Votre logo et votre couleur apparaissent sur le lien privé de vos mandants. L’annuaire permet aux entreprises sur Cantia de vous trouver.',
    logo: 'Logo',
    pickLogo: 'Choisir une image',
    removeLogo: 'Retirer le logo',
    color: 'Couleur',
    directory: 'Apparaître dans l’annuaire des fiduciaires',
    directoryHint: 'Visible par les entreprises sur Cantia et sur cantia.ch.',
    description: 'Présentation (600 caractères)',
    services: 'Prestations',
    servicesHint: 'Séparées par des virgules. Ex. Comptabilité, TVA, Salaires, Fiscalité',
    languages: 'Langues',
    cantons: 'Cantons',
    publicEmail: 'E-mail de contact public',
    accepts: 'Accepte de nouveaux mandants',
    preview: 'Aperçu',
  },
  portal: {
    title: 'Espace client',
    hello: 'Bonjour {name}',
    intro: '{firm} vous demande les documents ci-dessous. Ajoutez vos fichiers : ils arrivent directement chez votre fiduciaire.',
    invalid: 'Ce lien n’est plus valable',
    invalidText: 'Demandez un nouveau lien à votre fiduciaire.',
    requests: 'Documents demandés',
    noRequests: 'Aucune demande en cours. Merci !',
    due: 'À fournir d’ici le {date}',
    addFiles: 'Ajouter des fichiers',
    uploading: 'Envoi…',
    message: 'Message (facultatif)',
    send: 'Envoyer à ma fiduciaire',
    sent: 'Envoyé. Votre fiduciaire a été prévenue.',
    answered: 'Envoyé le {date}',
    done: 'Traité',
    toSign: 'Documents à signer',
    read: 'Lire le document',
    signName: 'Votre nom et prénom',
    signHere: 'Signez ci-dessous',
    clear: 'Effacer',
    approve: 'Je valide et je signe',
    reject: 'Je refuse',
    rejectReason: 'Pourquoi ? (votre fiduciaire reçoit ce message)',
    confirmReject: 'Envoyer le refus',
    signed: 'Signé le {date}. Merci !',
    rejected: 'Refusé le {date}.',
    legal: 'En signant, vous confirmez avoir lu le document. Votre nom, la date, votre adresse IP et l’empreinte du document sont conservés comme preuve.',
    contact: 'Une question ? {firm}',
    secure: 'Lien privé et chiffré',
    tooBig: 'Fichier trop lourd (20 Mo maximum).',
    poweredBy: 'Espace sécurisé fourni par Cantia',
  },
  client: {
    tabs: { work: 'Travaux', time: 'Temps', approvals: 'Signatures', proposals: 'Écritures proposées', kpis: 'Indicateurs' },
  },
};

type Copy = typeof fr;

const de: Copy = {
  shell: { work: 'Arbeiten', time: 'Zeit', approvals: 'Unterschriften' },
  common: {
    save: 'Speichern',
    saved: 'Gespeichert.',
    cancel: 'Abbrechen',
    edit: 'Bearbeiten',
    remove: 'Entfernen',
    add: 'Hinzufügen',
    copy: 'Link kopieren',
    copied: 'Link kopiert',
    all: 'Alle',
    client: 'Mandant',
    chooseClient: 'Mandant wählen',
    nobody: 'Niemand',
    loading: 'Wird geladen…',
    invalidDate: 'Ungültiges Datum (TT.MM.JJJJ).',
    datePlaceholder: 'TT.MM.JJJJ',
    due: 'Frist',
    noDue: 'Ohne Frist',
    by: 'von {name}',
    external: 'Ausserhalb Cantia',
    cantia: 'Auf Cantia',
  },
  ext: {
    addTitle: 'Mandant ausserhalb von Cantia hinzufügen',
    addText: 'Für Kunden mit Abacus, Banana, Winbiz oder Excel: Sie verfolgen hier Fristen, Arbeiten und Ihre Zeit, und der Kunde sendet Ihnen Belege über einen privaten Link, ohne Konto.',
    add: 'Mandant ausserhalb Cantia',
    edit: 'Stammdaten bearbeiten',
    name: 'Name des Unternehmens',
    contact: 'Kontaktperson',
    email: 'E-Mail des Kunden',
    emailHint: 'Dokumentanfragen und zu unterzeichnende Dokumente gehen an diese Adresse.',
    phone: 'Telefon',
    address: 'Adresse',
    postalCode: 'PLZ',
    city: 'Ort',
    ide: 'UID',
    software: 'Buchhaltungssoftware',
    rate: 'Stundensatz (CHF)',
    rateHint: 'Leer: Standardsatz der Treuhand.',
    language: 'Sprache der E-Mails',
    created: 'Mandant hinzugefügt.',
    sectionTitle: 'Mandanten ausserhalb Cantia',
    sectionEmpty: 'Keine Mandanten ausserhalb von Cantia. Fügen Sie Kunden mit anderer Software hinzu, um alles an einem Ort zu verfolgen.',
    portalTitle: 'Privater Link des Kunden',
    portalText: 'Der Kunde sendet dort seine Dokumente und unterzeichnet, was Sie ihm vorlegen, ohne Konto. Halten Sie diesen Link privat.',
    newLink: 'Neuen Link erzeugen',
    newLinkConfirm: 'Bestätigen: Der alte Link funktioniert nicht mehr',
    newLinkDone: 'Neuer Link erstellt. Der alte funktioniert nicht mehr.',
    archive: 'Mandant archivieren',
    archiveConfirm: 'Archivierung bestätigen',
    archived: 'Archiviert',
    restore: 'Reaktivieren',
    invite: 'Cantia vorschlagen',
    inviteText: 'Wechselt er zu Cantia, sehen Sie seine Rechnungen, Zahlungen und Buchungen direkt.',
    invited: 'Einladung gesendet.',
    notFound: 'Dieser Mandant existiert nicht oder wurde archiviert.',
    settings: 'Stammdaten',
  },
  work: {
    title: 'Arbeiten',
    text: 'Abschlüsse, MWST-Abrechnungen, Lohnjahresende: Jede Arbeit folgt einer Liste von Schritten, mit Verantwortlichem und Frist. Das ganze Team sieht den Stand jedes Dossiers.',
    new: 'Neue Arbeit',
    what: 'Arbeit',
    titlePlaceholder: 'z. B. Jahresabschluss 2025',
    period: 'Periode',
    periodPlaceholder: 'z. B. 2025, Q3 2026',
    kind: 'Art',
    assigned: 'Verantwortlich',
    steps: 'Schritte',
    stepsHint: 'Ein Schritt pro Zeile.',
    fromTemplate: 'Von einer Vorlage ausgehen',
    create: 'Arbeit erstellen',
    created: 'Arbeit erstellt.',
    addStep: 'Schritt hinzufügen',
    stepPlaceholder: 'Neuer Schritt',
    empty: 'Keine laufenden Arbeiten.',
    emptyFilter: 'Keine Arbeit in dieser Ansicht.',
    progress: '{done}/{total} Schritte',
    timeSpent: '{time} h erfasst',
    mine: 'Meine',
    filters: { open: 'Laufend', late: 'Überfällig', waiting: 'Warten auf Kunde', done: 'Erledigt', all: 'Alle' },
    kinds: { closing: 'Abschluss', vat: 'MWST', payroll: 'Löhne', tax: 'Steuern', onboarding: 'Neues Mandat', other: 'Andere' },
    statuses: { todo: 'Offen', in_progress: 'In Arbeit', waiting_client: 'Warten auf Kunde', review: 'Zur Prüfung', done: 'Erledigt', cancelled: 'Abgebrochen' },
    cancelWork: 'Diese Arbeit abbrechen',
    templatesTitle: 'Vorlagen der Treuhand',
    templatesText: 'Ihre wiederverwendbaren Schrittlisten. Die Vorlagen von Cantia dienen als Ausgangspunkt.',
    templateName: 'Name der Vorlage',
    saveTemplate: 'Vorlage speichern',
    newTemplate: 'Neue Vorlage',
    useDefaults: 'Cantia-Vorlagen hinzufügen',
    defaultsAdded: 'Vorlagen hinzugefügt.',
    archiveTemplate: 'Entfernen',
  },
  time: {
    title: 'Zeit und Honorare',
    text: 'Erfassen Sie Ihre Zeit pro Mandant. Der Satz des Mandanten (oder der Treuhand) wird angewendet; markieren Sie verrechnete Stunden nach dem Versand Ihrer Rechnung.',
    new: 'Zeit erfassen',
    date: 'Datum',
    duration: 'Dauer',
    durationPlaceholder: 'z. B. 1:30 oder 90',
    description: 'Beschreibung',
    descriptionPlaceholder: 'z. B. Belegerfassung Q3',
    billable: 'Verrechenbar',
    notBillable: 'Nicht verrechenbar',
    work: 'Verknüpfte Arbeit (optional)',
    added: 'Zeit gespeichert.',
    invalidDuration: 'Ungültige Dauer (z. B. 1:30 oder 90 Minuten).',
    empty: 'Keine Zeit in dieser Periode.',
    periods: { week: 'Diese Woche', month: 'Dieser Monat', lastMonth: 'Letzter Monat', year: 'Dieses Jahr' },
    toBill: 'Zu verrechnen',
    billed: 'Verrechnet',
    total: 'Total',
    amount: 'Betrag',
    markBilled: 'Als verrechnet markieren',
    markedBilled: '{count} Erfassung(en) als verrechnet markiert.',
    reopen: 'Wieder öffnen',
    void: 'Entfernen',
    byClient: 'Nach Mandant',
    byPerson: 'Nach Mitarbeitenden',
    export: 'Exportieren (CSV)',
    rateMissing: 'Kein Satz definiert',
    defaultRate: 'Standard-Stundensatz (CHF)',
    clientRate: 'Stundensatz dieses Mandanten (CHF)',
    clientRateHint: 'Leer: Standardsatz der Treuhand.',
  },
  approvals: {
    title: 'Zu unterzeichnende Dokumente',
    text: 'Senden Sie Jahresrechnung, Steuererklärung oder Mandatsvertrag zur Freigabe. Der Kunde unterzeichnet in Cantia oder über seinen privaten Link; Sie behalten den Nachweis (Name, Datum, Fingerabdruck des Dokuments).',
    new: 'Neues Dokument zur Unterschrift',
    kind: 'Art',
    docTitle: 'Titel',
    titlePlaceholder: 'z. B. Jahresrechnung 2025',
    message: 'Nachricht (optional)',
    file: 'Dokument (PDF)',
    pickFile: 'Datei wählen',
    send: 'Zur Unterschrift senden',
    sent: 'Dokument an den Kunden gesendet.',
    empty: 'Keine Dokumente gesendet.',
    statuses: { pending: 'Ausstehend', approved: 'Unterzeichnet', rejected: 'Abgelehnt' },
    kinds: { annual_accounts: 'Jahresrechnung', tax_return: 'Steuererklärung', vat_return: 'MWST-Abrechnung', payroll: 'Löhne', engagement: 'Mandatsvertrag', other: 'Andere' },
    signedBy: 'Unterzeichnet von {name} am {date}',
    rejectedBy: 'Abgelehnt von {name} am {date}',
    reason: 'Grund: {reason}',
    proof: 'Nachweis',
    fingerprint: 'SHA-256-Fingerabdruck',
    ip: 'IP-Adresse',
    remind: 'Erinnern',
    reminded: 'Erinnerung gesendet.',
    cancelDoc: 'Entfernen',
    noEmail: 'Dieser Mandant hat keine E-Mail: Senden Sie ihm seinen privaten Link selbst.',
    open: 'Dokument öffnen',
  },
  proposals: {
    title: 'Vorgeschlagene Buchungen',
    text: 'Bereiten Sie eine Korrekturbuchung vor: Der Kunde bestätigt sie in Cantia, danach geht sie in seine Buchhaltung.',
    notAllowed: 'Der Mandant hat «Buchungen vorschlagen» nicht aktiviert. Er kann es in Cantia unter Einstellungen › Treuhand tun.',
    new: 'Buchung vorschlagen',
    date: 'Buchungsdatum',
    label: 'Buchungstext',
    labelPlaceholder: 'z. B. Korrektur Bankspesen Q3',
    reason: 'Erklärung für den Kunden',
    account: 'Konto',
    accountPlaceholder: 'Nr. oder Name',
    lineLabel: 'Text (optional)',
    debit: 'Soll',
    credit: 'Haben',
    addLine: 'Zeile hinzufügen',
    balance: 'Differenz: {amount}',
    balanced: 'Ausgeglichen',
    send: 'An den Kunden senden',
    sent: 'Buchung dem Kunden vorgeschlagen.',
    empty: 'Keine vorgeschlagenen Buchungen.',
    statuses: { pending: 'Wartet auf den Kunden', accepted: 'Angenommen', rejected: 'Abgelehnt' },
    posted: 'verbucht',
    draft: 'als Entwurf beim Kunden',
    withdraw: 'Zurückziehen',
  },
  kpis: {
    title: 'Kennzahlen',
    from: 'Geschäftsjahr per {date}',
    vsPrev: 'vs {value} im Vorjahr',
    revenue: 'Umsatz',
    gross: 'Bruttogewinn',
    ebitda: 'EBITDA',
    ebit: 'EBIT',
    result: 'Ergebnis',
    liquid: 'Flüssige Mittel',
    receivables: 'Debitoren',
    shortDebt: 'Kurzfristige Verbindlichkeiten',
    equity: 'Eigenkapital',
    quick: 'Liquiditätsgrad 2 (Quick Ratio)',
    current: 'Liquiditätsgrad 3',
    equityRatio: 'Eigenkapitalquote',
    dso: 'Debitorenfrist',
    days: '{n} T.',
    margin: '{pct} % vom Umsatz',
    chart: 'Umsatz und Ergebnis, letzte 12 Monate',
    none: 'Noch keine verbuchten Buchungen.',
    noAccess: 'Der Mandant hat seine Buchhaltung nicht freigegeben.',
    hint: 'Berechnet aus den verbuchten Buchungen nach KMU-Kontenrahmen (3 Ertrag, 4 Material, 5 Personal, 6 übriger Aufwand, 68 Abschreibungen, 69 Finanzen, 89 Steuern).',
  },
  portfolio: {
    title: 'Portfolio',
    text: 'Alle Ihre Mandanten, auf Cantia oder nicht: Kennzahlen, wenn die Buchhaltung freigegeben ist, und was ansteht.',
    table: 'Portfolioansicht',
    list: 'Liste',
    columns: { client: 'Mandant', software: 'Software', revenue: 'Umsatz', ebit: 'EBIT', liquid: 'Flüssige Mittel', quick: 'Quick Ratio', open: 'Offen', time: 'Zu verrechnen' },
    pending: '{requests} Anfr. · {work} Arb. · {sign} Unt.',
    totals: 'Total',
  },
  exports: {
    title: 'In Ihre Software exportieren',
    text: 'Die verbuchten Buchungen der Periode im Importformat Ihrer Software. Konten und MWST-Codes sind die des Mandanten: Prüfen Sie die Zuordnung beim ersten Import.',
    entries: 'Buchungen',
    balances: 'Kontensaldi',
    help: {
      banana: 'Banana: Aktionen › In Buchhaltung importieren › Buchungen (Textdatei).',
      abacus: 'Abacus: FIBU-Buchungsimport (CSV), einmalig in Ihrer Importdefinition zuordnen.',
      winbiz: 'Winbiz: Buchhaltung › Buchungen importieren (CSV).',
    },
    none: 'Keine verbuchten Buchungen in dieser Periode.',
    done: '{count} Buchungen exportiert.',
  },
  brand: {
    title: 'Auftritt und Verzeichnis',
    text: 'Ihr Logo und Ihre Farbe erscheinen auf dem privaten Link Ihrer Mandanten. Über das Verzeichnis finden Sie Unternehmen auf Cantia.',
    logo: 'Logo',
    pickLogo: 'Bild wählen',
    removeLogo: 'Logo entfernen',
    color: 'Farbe',
    directory: 'Im Treuhandverzeichnis erscheinen',
    directoryHint: 'Sichtbar für Unternehmen auf Cantia und auf cantia.ch.',
    description: 'Vorstellung (600 Zeichen)',
    services: 'Leistungen',
    servicesHint: 'Durch Kommas getrennt. z. B. Buchhaltung, MWST, Löhne, Steuern',
    languages: 'Sprachen',
    cantons: 'Kantone',
    publicEmail: 'Öffentliche Kontakt-E-Mail',
    accepts: 'Nimmt neue Mandanten an',
    preview: 'Vorschau',
  },
  portal: {
    title: 'Kundenbereich',
    hello: 'Guten Tag {name}',
    intro: '{firm} bittet Sie um die folgenden Dokumente. Fügen Sie Ihre Dateien hinzu: Sie gehen direkt an Ihre Treuhand.',
    invalid: 'Dieser Link ist nicht mehr gültig',
    invalidText: 'Bitten Sie Ihre Treuhand um einen neuen Link.',
    requests: 'Angeforderte Dokumente',
    noRequests: 'Keine offenen Anfragen. Vielen Dank!',
    due: 'Bis {date}',
    addFiles: 'Dateien hinzufügen',
    uploading: 'Wird gesendet…',
    message: 'Nachricht (optional)',
    send: 'An meine Treuhand senden',
    sent: 'Gesendet. Ihre Treuhand wurde informiert.',
    answered: 'Gesendet am {date}',
    done: 'Erledigt',
    toSign: 'Zu unterzeichnende Dokumente',
    read: 'Dokument lesen',
    signName: 'Ihr Vor- und Nachname',
    signHere: 'Unterschreiben Sie unten',
    clear: 'Löschen',
    approve: 'Ich bestätige und unterzeichne',
    reject: 'Ich lehne ab',
    rejectReason: 'Warum? (Ihre Treuhand erhält diese Nachricht)',
    confirmReject: 'Ablehnung senden',
    signed: 'Unterzeichnet am {date}. Vielen Dank!',
    rejected: 'Abgelehnt am {date}.',
    legal: 'Mit Ihrer Unterschrift bestätigen Sie, das Dokument gelesen zu haben. Name, Datum, IP-Adresse und Fingerabdruck des Dokuments werden als Nachweis gespeichert.',
    contact: 'Eine Frage? {firm}',
    secure: 'Privater, verschlüsselter Link',
    tooBig: 'Datei zu gross (maximal 20 MB).',
    poweredBy: 'Sicherer Bereich von Cantia',
  },
  client: {
    tabs: { work: 'Arbeiten', time: 'Zeit', approvals: 'Unterschriften', proposals: 'Vorgeschlagene Buchungen', kpis: 'Kennzahlen' },
  },
};

const it: Copy = {
  shell: { work: 'Lavori', time: 'Tempo', approvals: 'Firme' },
  common: {
    save: 'Salvare',
    saved: 'Salvato.',
    cancel: 'Annullare',
    edit: 'Modificare',
    remove: 'Togliere',
    add: 'Aggiungere',
    copy: 'Copiare il link',
    copied: 'Link copiato',
    all: 'Tutti',
    client: 'Mandante',
    chooseClient: 'Scegliere un mandante',
    nobody: 'Nessuno',
    loading: 'Caricamento…',
    invalidDate: 'Data non valida (GG.MM.AAAA).',
    datePlaceholder: 'GG.MM.AAAA',
    due: 'Scadenza',
    noDue: 'Senza scadenza',
    by: 'da {name}',
    external: 'Fuori Cantia',
    cantia: 'Su Cantia',
  },
  ext: {
    addTitle: 'Aggiungere un mandante fuori Cantia',
    addText: 'Per i clienti su Abacus, Banana, Winbiz o Excel: segue qui scadenze, lavori e il suo tempo, e il cliente le invia i documenti tramite un link privato, senza account.',
    add: 'Mandante fuori Cantia',
    edit: 'Modificare la scheda',
    name: 'Nome dell’impresa',
    contact: 'Persona di contatto',
    email: 'E-mail del cliente',
    emailHint: 'Le richieste di documenti e i documenti da firmare vengono inviati a questo indirizzo.',
    phone: 'Telefono',
    address: 'Indirizzo',
    postalCode: 'NPA',
    city: 'Località',
    ide: 'IDI',
    software: 'Software contabile',
    rate: 'Tariffa oraria (CHF)',
    rateHint: 'Vuoto: tariffa predefinita della fiduciaria.',
    language: 'Lingua delle e-mail',
    created: 'Mandante aggiunto.',
    sectionTitle: 'Mandanti fuori Cantia',
    sectionEmpty: 'Nessun mandante fuori Cantia. Aggiunga i clienti che usano un altro software per seguire tutto in un solo posto.',
    portalTitle: 'Link privato del cliente',
    portalText: 'Il cliente vi invia i documenti e firma ciò che gli sottopone, senza account. Mantenga privato questo link.',
    newLink: 'Generare un nuovo link',
    newLinkConfirm: 'Confermare: il vecchio link non funzionerà più',
    newLinkDone: 'Nuovo link creato. Il vecchio non funziona più.',
    archive: 'Archiviare il mandante',
    archiveConfirm: 'Confermare l’archiviazione',
    archived: 'Archiviato',
    restore: 'Riattivare',
    invite: 'Proporgli Cantia',
    inviteText: 'Se passa a Cantia, vede direttamente fatture, pagamenti e registrazioni.',
    invited: 'Invito inviato.',
    notFound: 'Questo mandante non esiste o è stato archiviato.',
    settings: 'Scheda',
  },
  work: {
    title: 'Lavori',
    text: 'Chiusure, rendiconti IVA, salari di fine anno: ogni lavoro segue una lista di passi, con un responsabile e una scadenza. Tutto il team vede a che punto è ogni dossier.',
    new: 'Nuovo lavoro',
    what: 'Lavoro',
    titlePlaceholder: 'Es. Chiusura 2025',
    period: 'Periodo',
    periodPlaceholder: 'Es. 2025, T3 2026',
    kind: 'Tipo',
    assigned: 'Responsabile',
    steps: 'Passi',
    stepsHint: 'Un passo per riga.',
    fromTemplate: 'Partire da un modello',
    create: 'Creare il lavoro',
    created: 'Lavoro creato.',
    addStep: 'Aggiungere un passo',
    stepPlaceholder: 'Nuovo passo',
    empty: 'Nessun lavoro in corso.',
    emptyFilter: 'Nessun lavoro in questa vista.',
    progress: '{done}/{total} passi',
    timeSpent: '{time} h registrate',
    mine: 'I miei',
    filters: { open: 'In corso', late: 'In ritardo', waiting: 'Attesa cliente', done: 'Terminati', all: 'Tutti' },
    kinds: { closing: 'Chiusura', vat: 'IVA', payroll: 'Salari', tax: 'Imposte', onboarding: 'Nuovo mandato', other: 'Altro' },
    statuses: { todo: 'Da fare', in_progress: 'In corso', waiting_client: 'Attesa cliente', review: 'Da rivedere', done: 'Terminato', cancelled: 'Annullato' },
    cancelWork: 'Annullare questo lavoro',
    templatesTitle: 'Modelli della fiduciaria',
    templatesText: 'Le sue liste di passi riutilizzabili. I modelli proposti da Cantia servono da punto di partenza.',
    templateName: 'Nome del modello',
    saveTemplate: 'Salvare il modello',
    newTemplate: 'Nuovo modello',
    useDefaults: 'Aggiungere i modelli Cantia',
    defaultsAdded: 'Modelli aggiunti.',
    archiveTemplate: 'Togliere',
  },
  time: {
    title: 'Tempo e onorari',
    text: 'Registri il suo tempo per mandante. Si applica la tariffa del mandante (o della fiduciaria); segni le ore fatturate dopo l’invio della fattura.',
    new: 'Registrare tempo',
    date: 'Data',
    duration: 'Durata',
    durationPlaceholder: 'Es. 1:30 o 90',
    description: 'Descrizione',
    descriptionPlaceholder: 'Es. Registrazione documenti T3',
    billable: 'Fatturabile',
    notBillable: 'Non fatturabile',
    work: 'Lavoro collegato (facoltativo)',
    added: 'Tempo registrato.',
    invalidDuration: 'Durata non valida (es. 1:30 o 90 minuti).',
    empty: 'Nessun tempo nel periodo.',
    periods: { week: 'Questa settimana', month: 'Questo mese', lastMonth: 'Mese scorso', year: 'Quest’anno' },
    toBill: 'Da fatturare',
    billed: 'Fatturato',
    total: 'Totale',
    amount: 'Importo',
    markBilled: 'Segnare come fatturato',
    markedBilled: '{count} registrazione(i) segnate come fatturate.',
    reopen: 'Riaprire',
    void: 'Togliere',
    byClient: 'Per mandante',
    byPerson: 'Per collaboratore',
    export: 'Esportare (CSV)',
    rateMissing: 'Tariffa non definita',
    defaultRate: 'Tariffa oraria predefinita (CHF)',
    clientRate: 'Tariffa oraria di questo mandante (CHF)',
    clientRateHint: 'Vuoto: tariffa predefinita della fiduciaria.',
  },
  approvals: {
    title: 'Documenti da firmare',
    text: 'Invii conti annuali, dichiarazione o lettera d’incarico da convalidare. Il cliente firma in Cantia o tramite il suo link privato; lei conserva la prova (nome, data, impronta del documento).',
    new: 'Nuovo documento da firmare',
    kind: 'Tipo',
    docTitle: 'Titolo',
    titlePlaceholder: 'Es. Conti annuali 2025',
    message: 'Messaggio (facoltativo)',
    file: 'Documento (PDF)',
    pickFile: 'Scegliere un file',
    send: 'Inviare per firma',
    sent: 'Documento inviato al cliente.',
    empty: 'Nessun documento inviato.',
    statuses: { pending: 'In attesa', approved: 'Firmato', rejected: 'Rifiutato' },
    kinds: { annual_accounts: 'Conti annuali', tax_return: 'Dichiarazione d’imposta', vat_return: 'Rendiconto IVA', payroll: 'Salari', engagement: 'Lettera d’incarico', other: 'Altro' },
    signedBy: 'Firmato da {name} il {date}',
    rejectedBy: 'Rifiutato da {name} il {date}',
    reason: 'Motivo: {reason}',
    proof: 'Prova',
    fingerprint: 'Impronta SHA-256',
    ip: 'Indirizzo IP',
    remind: 'Sollecitare',
    reminded: 'Promemoria inviato.',
    cancelDoc: 'Togliere',
    noEmail: 'Questo mandante non ha e-mail: gli invii lei il suo link privato.',
    open: 'Aprire il documento',
  },
  proposals: {
    title: 'Registrazioni proposte',
    text: 'Prepari una registrazione di correzione: il cliente la convalida in Cantia, poi entra nella sua contabilità.',
    notAllowed: 'Il mandante non ha attivato «Proporre registrazioni». Può farlo in Cantia, Impostazioni › Fiduciario.',
    new: 'Proporre una registrazione',
    date: 'Data della registrazione',
    label: 'Descrizione',
    labelPlaceholder: 'Es. Correzione spese bancarie T3',
    reason: 'Spiegazione per il cliente',
    account: 'Conto',
    accountPlaceholder: 'N° o nome',
    lineLabel: 'Testo (facoltativo)',
    debit: 'Dare',
    credit: 'Avere',
    addLine: 'Aggiungere una riga',
    balance: 'Differenza: {amount}',
    balanced: 'Bilanciata',
    send: 'Inviare al cliente',
    sent: 'Registrazione proposta al cliente.',
    empty: 'Nessuna registrazione proposta.',
    statuses: { pending: 'In attesa del cliente', accepted: 'Accettata', rejected: 'Rifiutata' },
    posted: 'contabilizzata',
    draft: 'in bozza presso il cliente',
    withdraw: 'Ritirare',
  },
  kpis: {
    title: 'Indicatori',
    from: 'Esercizio al {date}',
    vsPrev: 'vs {value} l’anno scorso',
    revenue: 'Cifra d’affari',
    gross: 'Margine lordo',
    ebitda: 'EBITDA',
    ebit: 'EBIT',
    result: 'Risultato',
    liquid: 'Liquidità',
    receivables: 'Debitori',
    shortDebt: 'Debiti a breve termine',
    equity: 'Capitale proprio',
    quick: 'Liquidità ridotta (quick ratio)',
    current: 'Liquidità generale',
    equityRatio: 'Quota di capitale proprio',
    dso: 'Tempo d’incasso',
    days: '{n} g',
    margin: '{pct} % della CA',
    chart: 'Cifra d’affari e risultato, ultimi 12 mesi',
    none: 'Nessuna registrazione contabilizzata.',
    noAccess: 'Il mandante non ha aperto la sua contabilità.',
    hint: 'Calcolati sulle registrazioni contabilizzate, secondo il piano dei conti PMI svizzero (3 ricavi, 4 materiale, 5 personale, 6 altri costi, 68 ammortamenti, 69 finanze, 89 imposte).',
  },
  portfolio: {
    title: 'Portafoglio',
    text: 'Tutti i suoi mandanti, su Cantia o no: indicatori quando la contabilità è aperta, e ciò che attende.',
    table: 'Vista portafoglio',
    list: 'Lista',
    columns: { client: 'Mandante', software: 'Software', revenue: 'CA', ebit: 'EBIT', liquid: 'Liquidità', quick: 'Quick ratio', open: 'In attesa', time: 'Da fatturare' },
    pending: '{requests} rich. · {work} lav. · {sign} firme',
    totals: 'Totale',
  },
  exports: {
    title: 'Esportare verso il suo software',
    text: 'Le registrazioni contabilizzate del periodo nel formato d’importazione del suo software. Conti e codici IVA sono quelli del mandante: verifichi la corrispondenza alla prima importazione.',
    entries: 'Registrazioni',
    balances: 'Saldi dei conti',
    help: {
      banana: 'Banana: Azioni › Importare in contabilità › Registrazioni (file di testo).',
      abacus: 'Abacus: importazione registrazioni FIBU (CSV), da associare una volta nella sua definizione d’importazione.',
      winbiz: 'Winbiz: Contabilità › Importare registrazioni (CSV).',
    },
    none: 'Nessuna registrazione contabilizzata nel periodo.',
    done: '{count} registrazioni esportate.',
  },
  brand: {
    title: 'Immagine e elenco',
    text: 'Il suo logo e il suo colore appaiono sul link privato dei suoi mandanti. L’elenco permette alle imprese su Cantia di trovarla.',
    logo: 'Logo',
    pickLogo: 'Scegliere un’immagine',
    removeLogo: 'Togliere il logo',
    color: 'Colore',
    directory: 'Apparire nell’elenco delle fiduciarie',
    directoryHint: 'Visibile alle imprese su Cantia e su cantia.ch.',
    description: 'Presentazione (600 caratteri)',
    services: 'Prestazioni',
    servicesHint: 'Separate da virgole. Es. Contabilità, IVA, Salari, Fiscalità',
    languages: 'Lingue',
    cantons: 'Cantoni',
    publicEmail: 'E-mail di contatto pubblica',
    accepts: 'Accetta nuovi mandanti',
    preview: 'Anteprima',
  },
  portal: {
    title: 'Spazio cliente',
    hello: 'Buongiorno {name}',
    intro: '{firm} le chiede i documenti qui sotto. Aggiunga i suoi file: arrivano direttamente alla sua fiduciaria.',
    invalid: 'Questo link non è più valido',
    invalidText: 'Chieda un nuovo link alla sua fiduciaria.',
    requests: 'Documenti richiesti',
    noRequests: 'Nessuna richiesta in corso. Grazie!',
    due: 'Entro il {date}',
    addFiles: 'Aggiungere file',
    uploading: 'Invio…',
    message: 'Messaggio (facoltativo)',
    send: 'Inviare alla mia fiduciaria',
    sent: 'Inviato. La sua fiduciaria è stata avvisata.',
    answered: 'Inviato il {date}',
    done: 'Evaso',
    toSign: 'Documenti da firmare',
    read: 'Leggere il documento',
    signName: 'Nome e cognome',
    signHere: 'Firmi qui sotto',
    clear: 'Cancellare',
    approve: 'Convalido e firmo',
    reject: 'Rifiuto',
    rejectReason: 'Perché? (la sua fiduciaria riceve questo messaggio)',
    confirmReject: 'Inviare il rifiuto',
    signed: 'Firmato il {date}. Grazie!',
    rejected: 'Rifiutato il {date}.',
    legal: 'Firmando conferma di aver letto il documento. Nome, data, indirizzo IP e impronta del documento sono conservati come prova.',
    contact: 'Una domanda? {firm}',
    secure: 'Link privato e cifrato',
    tooBig: 'File troppo pesante (20 MB al massimo).',
    poweredBy: 'Spazio sicuro fornito da Cantia',
  },
  client: {
    tabs: { work: 'Lavori', time: 'Tempo', approvals: 'Firme', proposals: 'Registrazioni proposte', kpis: 'Indicatori' },
  },
};

export const PRO_COPY: Record<AccLocale, Copy> = { fr, de, it };
export type ProCopy = Copy;

export function useProCopy(): Copy {
  const { locale } = useAccCopy();
  return PRO_COPY[locale];
}

// "1:30", "1h30", "90", "1.5" → minutes
export function parseDuration(value: string): number | null {
  const v = value.trim().toLowerCase().replace(',', '.');
  if (!v) return null;
  let m = v.match(/^(\d{1,2})\s*[:h]\s*(\d{1,2})?\s*(min)?$/);
  if (m) return Number(m[1]) * 60 + Number(m[2] ?? 0);
  m = v.match(/^(\d+(?:\.\d+)?)\s*h$/);
  if (m) return Math.round(Number(m[1]) * 60);
  m = v.match(/^(\d+)\s*(min|m)?$/);
  if (m) return Number(m[1]);
  m = v.match(/^(\d+\.\d+)$/);
  if (m) return Math.round(Number(m[1]) * 60);
  return null;
}
