import { useAccCopy } from './locale';
import type { AccLocale } from './copy';

// Strings of the fiduciary workspace (shell, requests, deadlines, client
// file). Kept next to copy.ts, same three languages.

const fr = {
  shell: {
    overview: 'Vue d’ensemble',
    clients: 'Mandants',
    requests: 'Demandes',
    deadlines: 'Échéances',
    documents: 'Documents',
    team: 'Équipe',
    partner: 'Partenaire',
    settings: 'Fiduciaire',
    menu: 'Menu',
    logout: 'Se déconnecter',
    admin: 'Administration',
    secure: 'Accès en lecture, autorisé par chaque client et journalisé.',
  },
  overview: {
    hello: 'Bonjour {name}',
    todayTitle: 'À traiter',
    todayEmpty: 'Rien d’urgent. Tout est à jour chez vos mandants.',
    upcoming: 'Prochaines échéances',
    upcomingEmpty: 'Aucune échéance dans les semaines à venir.',
    seeAll: 'Tout voir',
    answered: '{client} a répondu : {title}',
    overdueRequest: '{client} n’a pas encore envoyé : {title}',
    overdueInvoices: '{client} : {count} facture(s) en retard, {amount}',
    accessRequest: '{client} vous donne accès à ses données',
    deadlineLate: '{kind} {period} de {client} : échéance dépassée',
    deadlineSoon: '{kind} {period} de {client} : dans {days} j',
    kpiClients: 'Mandants actifs',
    kpiRequests: 'Demandes ouvertes',
    kpiAnswered: 'Réponses à vérifier',
    kpiDeadlines: 'Échéances à 30 jours',
    kpiOverdue: 'À encaisser chez vos mandants',
  },
  requests: {
    title: 'Demandes de documents',
    text: 'Demandez une pièce à un mandant : il la reçoit par e-mail et dans son Cantia, et vous répond avec ses fichiers. Plus de relances par e-mail.',
    new: 'Nouvelle demande',
    client: 'Mandant',
    chooseClient: 'Choisir un mandant',
    what: 'Que vous faut-il ?',
    whatPlaceholder: 'Ex. Relevés bancaires juillet à septembre',
    details: 'Précisions (facultatif)',
    detailsPlaceholder: 'Ex. Compte UBS et compte PostFinance, en PDF.',
    due: 'À fournir d’ici le (facultatif)',
    duePlaceholder: 'JJ.MM.AAAA',
    send: 'Envoyer la demande',
    sent: 'Demande envoyée au mandant.',
    templates: 'Demandes fréquentes',
    templateItems: ['Relevés bancaires du trimestre', 'Justificatifs de dépenses du mois', 'Extrait de compte PostFinance', 'Décompte de l’assurance accidents', 'Contrat de leasing', 'Inventaire au 31.12'],
    filters: { active: 'En cours', answered: 'À vérifier', done: 'Traitées', all: 'Toutes' },
    status: { open: 'En attente', answered: 'Répondu', done: 'Traitée', cancelled: 'Annulée' },
    dueOn: 'Pour le {date}',
    late: 'En retard',
    askedOn: 'Demandé le {date}',
    by: 'par {name}',
    answeredOn: 'Répondu le {date}',
    clientMessage: 'Message du mandant',
    files: 'Fichiers reçus',
    noFiles: 'Aucun fichier',
    markDone: 'Marquer traitée',
    reopen: 'Rouvrir',
    remind: 'Relancer',
    reminded: 'Relance envoyée.',
    cancel: 'Annuler la demande',
    empty: 'Aucune demande pour l’instant.',
    emptyFilter: 'Aucune demande dans cette vue.',
    invalidDate: 'Date invalide (JJ.MM.AAAA).',
  },
  deadlines: {
    title: 'Échéances',
    text: 'Calculées pour chaque mandant à partir de son profil (méthode TVA, salaires, exercice). Cochez-les au fur et à mesure : toute l’équipe voit où en est chaque dossier.',
    filters: { open: 'À faire', late: 'En retard', done: 'Faites', all: 'Toutes' },
    kinds: { vat: 'Décompte TVA', salary_declaration: 'Déclaration AVS des salaires', salary_certificates: 'Certificats de salaire', tax_return: 'Déclaration d’impôt', closing: 'Bouclement annuel' },
    kindsShort: { vat: 'TVA', salary_declaration: 'AVS', salary_certificates: 'Certificats', tax_return: 'Impôts', closing: 'Bouclement' },
    status: { todo: 'À faire', in_progress: 'En cours', done: 'Fait' },
    quarter: 'T',
    semester: 'S',
    months: ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    monthsShort: ['janv', 'févr', 'mars', 'avr', 'mai', 'juin', 'juil', 'août', 'sept', 'oct', 'nov', 'déc'],
    dueIn: 'dans {days} j',
    dueToday: 'aujourd’hui',
    lateBy: 'retard {days} j',
    empty: 'Aucune échéance à afficher.',
    profileHint: 'Profil par défaut (TVA trimestrielle, salaires, exercice civil). Ajustez-le dans le dossier du mandant.',
    groupThisMonth: 'Ce mois',
    groupLate: 'En retard',
  },
  profile: {
    title: 'Profil du mandant',
    text: 'Sert à calculer ses échéances. Visible uniquement par votre fiduciaire.',
    vat: 'TVA',
    vatMethods: { effective_quarterly: 'Effective, trimestrielle', tdfn_semester: 'Taux de la dette fiscale nette (semestrielle)', effective_monthly: 'Effective, mensuelle', effective_annual: 'Effective, annuelle', none: 'Non assujetti' },
    payroll: 'Salaires (AVS, certificats)',
    legalForm: 'Forme juridique',
    legalForms: { sarl: 'Sàrl', sa: 'SA', individual: 'Raison individuelle', other: 'Autre' },
    fiscalYearEnd: 'Fin d’exercice (JJ.MM)',
    taxReturnDue: 'Déclaration d’impôt à rendre le (JJ.MM)',
    assigned: 'Responsable du dossier',
    nobody: 'Personne',
    save: 'Enregistrer le profil',
    saved: 'Profil enregistré.',
    invalid: 'Date invalide (JJ.MM).',
  },
  client: {
    overview: 'Aperçu',
    requests: 'Demandes',
    deadlines: 'Échéances',
    notes: 'Notes internes',
    insights: {
      invoiced: 'Facturé cette année',
      collected: 'Encaissé cette année',
      open: 'À encaisser',
      overdue: 'En retard',
      expenses: 'Dépenses cette année',
      lastEntry: 'Dernière écriture',
      chart: 'Chiffre d’affaires facturé, 12 derniers mois',
    },
    checks: {
      title: 'Points d’attention',
      none: 'Rien à signaler.',
      overdue: '{count} facture(s) en retard pour {amount}',
      noReceipt: '{count} écriture(s) des 90 derniers jours sans justificatif',
      drafts: '{count} écriture(s) en brouillon',
      answered: '{count} réponse(s) à vérifier',
      openRequests: '{count} demande(s) en attente du mandant',
      noEntries: 'Aucune écriture depuis le {date}',
    },
    notesText: 'Visibles par votre équipe uniquement, jamais par le mandant.',
    notePlaceholder: 'Ajouter une note (appel, convention, point à suivre…)',
    addNote: 'Ajouter',
    noNotes: 'Aucune note.',
    deleteNote: 'Supprimer',
    ask: 'Demander un document',
  },
};

type WorkCopy = typeof fr;

const de: WorkCopy = {
  shell: {
    overview: 'Übersicht',
    clients: 'Mandanten',
    requests: 'Anfragen',
    deadlines: 'Fristen',
    documents: 'Dokumente',
    team: 'Team',
    partner: 'Partner',
    settings: 'Treuhand',
    menu: 'Menü',
    logout: 'Abmelden',
    admin: 'Administration',
    secure: 'Lesezugriff, von jedem Kunden freigegeben und protokolliert.',
  },
  overview: {
    hello: 'Guten Tag {name}',
    todayTitle: 'Zu erledigen',
    todayEmpty: 'Nichts Dringendes. Bei Ihren Mandanten ist alles aktuell.',
    upcoming: 'Nächste Fristen',
    upcomingEmpty: 'Keine Fristen in den nächsten Wochen.',
    seeAll: 'Alle ansehen',
    answered: '{client} hat geantwortet: {title}',
    overdueRequest: '{client} hat noch nicht geliefert: {title}',
    overdueInvoices: '{client}: {count} überfällige Rechnung(en), {amount}',
    accessRequest: '{client} gibt Ihnen Zugriff auf seine Daten',
    deadlineLate: '{kind} {period} von {client}: Frist überschritten',
    deadlineSoon: '{kind} {period} von {client}: in {days} T.',
    kpiClients: 'Aktive Mandanten',
    kpiRequests: 'Offene Anfragen',
    kpiAnswered: 'Zu prüfende Antworten',
    kpiDeadlines: 'Fristen in 30 Tagen',
    kpiOverdue: 'Offen bei Ihren Mandanten',
  },
  requests: {
    title: 'Dokumentenanfragen',
    text: 'Fordern Sie ein Dokument bei einem Mandanten an: Er erhält die Anfrage per E-Mail und in seinem Cantia und antwortet mit seinen Dateien. Keine Nachfass-E-Mails mehr.',
    new: 'Neue Anfrage',
    client: 'Mandant',
    chooseClient: 'Mandant wählen',
    what: 'Was benötigen Sie?',
    whatPlaceholder: 'z. B. Kontoauszüge Juli bis September',
    details: 'Details (optional)',
    detailsPlaceholder: 'z. B. UBS- und PostFinance-Konto, als PDF.',
    due: 'Bis (optional)',
    duePlaceholder: 'TT.MM.JJJJ',
    send: 'Anfrage senden',
    sent: 'Anfrage an den Mandanten gesendet.',
    templates: 'Häufige Anfragen',
    templateItems: ['Kontoauszüge des Quartals', 'Spesenbelege des Monats', 'PostFinance-Kontoauszug', 'Abrechnung der Unfallversicherung', 'Leasingvertrag', 'Inventar per 31.12.'],
    filters: { active: 'Laufend', answered: 'Zu prüfen', done: 'Erledigt', all: 'Alle' },
    status: { open: 'Ausstehend', answered: 'Beantwortet', done: 'Erledigt', cancelled: 'Storniert' },
    dueOn: 'Bis {date}',
    late: 'Überfällig',
    askedOn: 'Angefragt am {date}',
    by: 'von {name}',
    answeredOn: 'Beantwortet am {date}',
    clientMessage: 'Nachricht des Mandanten',
    files: 'Erhaltene Dateien',
    noFiles: 'Keine Dateien',
    markDone: 'Als erledigt markieren',
    reopen: 'Wieder öffnen',
    remind: 'Erinnern',
    reminded: 'Erinnerung gesendet.',
    cancel: 'Anfrage stornieren',
    empty: 'Noch keine Anfragen.',
    emptyFilter: 'Keine Anfragen in dieser Ansicht.',
    invalidDate: 'Ungültiges Datum (TT.MM.JJJJ).',
  },
  deadlines: {
    title: 'Fristen',
    text: 'Für jeden Mandanten aus seinem Profil berechnet (MWST-Methode, Löhne, Geschäftsjahr). Haken Sie sie laufend ab: Das ganze Team sieht, wo jedes Dossier steht.',
    filters: { open: 'Offen', late: 'Überfällig', done: 'Erledigt', all: 'Alle' },
    kinds: { vat: 'MWST-Abrechnung', salary_declaration: 'AHV-Lohnmeldung', salary_certificates: 'Lohnausweise', tax_return: 'Steuererklärung', closing: 'Jahresabschluss' },
    kindsShort: { vat: 'MWST', salary_declaration: 'AHV', salary_certificates: 'Lohnausweise', tax_return: 'Steuern', closing: 'Abschluss' },
    status: { todo: 'Offen', in_progress: 'In Arbeit', done: 'Erledigt' },
    quarter: 'Q',
    semester: 'S',
    months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    monthsShort: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
    dueIn: 'in {days} T.',
    dueToday: 'heute',
    lateBy: '{days} T. überfällig',
    empty: 'Keine Fristen anzuzeigen.',
    profileHint: 'Standardprofil (MWST quartalsweise, Löhne, Kalenderjahr). Im Dossier des Mandanten anpassen.',
    groupThisMonth: 'Diesen Monat',
    groupLate: 'Überfällig',
  },
  profile: {
    title: 'Mandantenprofil',
    text: 'Dient zur Berechnung seiner Fristen. Nur für Ihre Treuhand sichtbar.',
    vat: 'MWST',
    vatMethods: { effective_quarterly: 'Effektiv, quartalsweise', tdfn_semester: 'Saldosteuersatz (halbjährlich)', effective_monthly: 'Effektiv, monatlich', effective_annual: 'Effektiv, jährlich', none: 'Nicht steuerpflichtig' },
    payroll: 'Löhne (AHV, Lohnausweise)',
    legalForm: 'Rechtsform',
    legalForms: { sarl: 'GmbH', sa: 'AG', individual: 'Einzelunternehmen', other: 'Andere' },
    fiscalYearEnd: 'Geschäftsjahresende (TT.MM)',
    taxReturnDue: 'Steuererklärung einzureichen bis (TT.MM)',
    assigned: 'Verantwortlich',
    nobody: 'Niemand',
    save: 'Profil speichern',
    saved: 'Profil gespeichert.',
    invalid: 'Ungültiges Datum (TT.MM).',
  },
  client: {
    overview: 'Übersicht',
    requests: 'Anfragen',
    deadlines: 'Fristen',
    notes: 'Interne Notizen',
    insights: {
      invoiced: 'Fakturiert dieses Jahr',
      collected: 'Eingenommen dieses Jahr',
      open: 'Offen',
      overdue: 'Überfällig',
      expenses: 'Ausgaben dieses Jahr',
      lastEntry: 'Letzte Buchung',
      chart: 'Fakturierter Umsatz, letzte 12 Monate',
    },
    checks: {
      title: 'Auffälligkeiten',
      none: 'Nichts zu melden.',
      overdue: '{count} überfällige Rechnung(en) über {amount}',
      noReceipt: '{count} Buchung(en) der letzten 90 Tage ohne Beleg',
      drafts: '{count} Buchung(en) im Entwurf',
      answered: '{count} Antwort(en) zu prüfen',
      openRequests: '{count} Anfrage(n) beim Mandanten ausstehend',
      noEntries: 'Keine Buchung seit {date}',
    },
    notesText: 'Nur für Ihr Team sichtbar, nie für den Mandanten.',
    notePlaceholder: 'Notiz hinzufügen (Anruf, Vereinbarung, Pendenz…)',
    addNote: 'Hinzufügen',
    noNotes: 'Keine Notizen.',
    deleteNote: 'Löschen',
    ask: 'Dokument anfordern',
  },
};

const it: WorkCopy = {
  shell: {
    overview: 'Panoramica',
    clients: 'Mandanti',
    requests: 'Richieste',
    deadlines: 'Scadenze',
    documents: 'Documenti',
    team: 'Team',
    partner: 'Partner',
    settings: 'Studio',
    menu: 'Menu',
    logout: 'Esci',
    admin: 'Amministrazione',
    secure: 'Accesso in lettura, autorizzato da ogni cliente e registrato.',
  },
  overview: {
    hello: 'Buongiorno {name}',
    todayTitle: 'Da fare',
    todayEmpty: 'Niente di urgente. Tutto è aggiornato presso i suoi mandanti.',
    upcoming: 'Prossime scadenze',
    upcomingEmpty: 'Nessuna scadenza nelle prossime settimane.',
    seeAll: 'Vedere tutto',
    answered: '{client} ha risposto: {title}',
    overdueRequest: '{client} non ha ancora inviato: {title}',
    overdueInvoices: '{client}: {count} fattura/e scaduta/e, {amount}',
    accessRequest: '{client} le dà accesso ai suoi dati',
    deadlineLate: '{kind} {period} di {client}: scadenza superata',
    deadlineSoon: '{kind} {period} di {client}: tra {days} g',
    kpiClients: 'Mandanti attivi',
    kpiRequests: 'Richieste aperte',
    kpiAnswered: 'Risposte da verificare',
    kpiDeadlines: 'Scadenze a 30 giorni',
    kpiOverdue: 'Da incassare presso i mandanti',
  },
  requests: {
    title: 'Richieste di documenti',
    text: 'Chieda un documento a un mandante: lo riceve per e-mail e nel suo Cantia e le risponde con i suoi file. Niente più solleciti per e-mail.',
    new: 'Nuova richiesta',
    client: 'Mandante',
    chooseClient: 'Scegliere un mandante',
    what: 'Di cosa ha bisogno?',
    whatPlaceholder: 'Es. Estratti bancari da luglio a settembre',
    details: 'Dettagli (facoltativo)',
    detailsPlaceholder: 'Es. Conto UBS e conto PostFinance, in PDF.',
    due: 'Entro il (facoltativo)',
    duePlaceholder: 'GG.MM.AAAA',
    send: 'Inviare la richiesta',
    sent: 'Richiesta inviata al mandante.',
    templates: 'Richieste frequenti',
    templateItems: ['Estratti bancari del trimestre', 'Giustificativi di spesa del mese', 'Estratto conto PostFinance', 'Conteggio dell’assicurazione infortuni', 'Contratto di leasing', 'Inventario al 31.12'],
    filters: { active: 'In corso', answered: 'Da verificare', done: 'Evase', all: 'Tutte' },
    status: { open: 'In attesa', answered: 'Risposta', done: 'Evasa', cancelled: 'Annullata' },
    dueOn: 'Entro il {date}',
    late: 'In ritardo',
    askedOn: 'Richiesto il {date}',
    by: 'da {name}',
    answeredOn: 'Risposto il {date}',
    clientMessage: 'Messaggio del mandante',
    files: 'File ricevuti',
    noFiles: 'Nessun file',
    markDone: 'Segnare evasa',
    reopen: 'Riaprire',
    remind: 'Sollecitare',
    reminded: 'Sollecito inviato.',
    cancel: 'Annullare la richiesta',
    empty: 'Nessuna richiesta per ora.',
    emptyFilter: 'Nessuna richiesta in questa vista.',
    invalidDate: 'Data non valida (GG.MM.AAAA).',
  },
  deadlines: {
    title: 'Scadenze',
    text: 'Calcolate per ogni mandante dal suo profilo (metodo IVA, salari, esercizio). Le spunti man mano: tutto il team vede a che punto è ogni dossier.',
    filters: { open: 'Da fare', late: 'In ritardo', done: 'Fatte', all: 'Tutte' },
    kinds: { vat: 'Rendiconto IVA', salary_declaration: 'Dichiarazione AVS dei salari', salary_certificates: 'Certificati di salario', tax_return: 'Dichiarazione d’imposta', closing: 'Chiusura annuale' },
    kindsShort: { vat: 'IVA', salary_declaration: 'AVS', salary_certificates: 'Certificati', tax_return: 'Imposte', closing: 'Chiusura' },
    status: { todo: 'Da fare', in_progress: 'In corso', done: 'Fatto' },
    quarter: 'T',
    semester: 'S',
    months: ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'],
    monthsShort: ['gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic'],
    dueIn: 'tra {days} g',
    dueToday: 'oggi',
    lateBy: 'ritardo {days} g',
    empty: 'Nessuna scadenza da mostrare.',
    profileHint: 'Profilo predefinito (IVA trimestrale, salari, anno civile). Lo adatti nel dossier del mandante.',
    groupThisMonth: 'Questo mese',
    groupLate: 'In ritardo',
  },
  profile: {
    title: 'Profilo del mandante',
    text: 'Serve a calcolare le sue scadenze. Visibile solo al suo studio.',
    vat: 'IVA',
    vatMethods: { effective_quarterly: 'Effettivo, trimestrale', tdfn_semester: 'Aliquota saldo (semestrale)', effective_monthly: 'Effettivo, mensile', effective_annual: 'Effettivo, annuale', none: 'Non assoggettato' },
    payroll: 'Salari (AVS, certificati)',
    legalForm: 'Forma giuridica',
    legalForms: { sarl: 'Sagl', sa: 'SA', individual: 'Ditta individuale', other: 'Altro' },
    fiscalYearEnd: 'Fine esercizio (GG.MM)',
    taxReturnDue: 'Dichiarazione d’imposta entro il (GG.MM)',
    assigned: 'Responsabile del dossier',
    nobody: 'Nessuno',
    save: 'Salvare il profilo',
    saved: 'Profilo salvato.',
    invalid: 'Data non valida (GG.MM).',
  },
  client: {
    overview: 'Panoramica',
    requests: 'Richieste',
    deadlines: 'Scadenze',
    notes: 'Note interne',
    insights: {
      invoiced: 'Fatturato quest’anno',
      collected: 'Incassato quest’anno',
      open: 'Da incassare',
      overdue: 'Scaduto',
      expenses: 'Spese quest’anno',
      lastEntry: 'Ultima registrazione',
      chart: 'Fatturato, ultimi 12 mesi',
    },
    checks: {
      title: 'Punti di attenzione',
      none: 'Niente da segnalare.',
      overdue: '{count} fattura/e scaduta/e per {amount}',
      noReceipt: '{count} registrazione/i degli ultimi 90 giorni senza giustificativo',
      drafts: '{count} registrazione/i in bozza',
      answered: '{count} risposta/e da verificare',
      openRequests: '{count} richiesta/e in attesa del mandante',
      noEntries: 'Nessuna registrazione dal {date}',
    },
    notesText: 'Visibili solo al suo team, mai al mandante.',
    notePlaceholder: 'Aggiungere una nota (telefonata, accordo, punto da seguire…)',
    addNote: 'Aggiungere',
    noNotes: 'Nessuna nota.',
    deleteNote: 'Eliminare',
    ask: 'Chiedere un documento',
  },
};

const WORK_COPY: Record<AccLocale, WorkCopy> = { fr, de, it };

export function useWorkCopy() {
  const { locale } = useAccCopy();
  return WORK_COPY[locale];
}

// DD.MM.YYYY <-> YYYY-MM-DD, DD.MM <-> MM-DD (Swiss input format).
export function parseSwissDate(value: string): string | null | undefined {
  const v = value.trim();
  if (!v) return null;
  const m = v.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})$/);
  if (!m) return undefined;
  const [, d, mo, y] = m;
  const date = new Date(Number(y), Number(mo) - 1, Number(d));
  if (date.getMonth() !== Number(mo) - 1) return undefined;
  return `${y}-${mo.padStart(2, '0')}-${d.padStart(2, '0')}`;
}

export function parseDayMonth(value: string): string | undefined {
  const m = value.trim().match(/^(\d{1,2})\.(\d{1,2})\.?$/);
  if (!m) return undefined;
  const d = Number(m[1]);
  const mo = Number(m[2]);
  if (mo < 1 || mo > 12 || d < 1 || d > 31) return undefined;
  return `${String(mo).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
}

export function formatDayMonth(mmdd: string): string {
  const [m, d] = mmdd.split('-');
  return `${d}.${m}`;
}
