import { getAppLocale } from '../translations';
import { LABELS_DE, LABELS_IT } from './figureLabels';

// Copy of the « Décompte TVA » page (app/(app)/compta/tva.tsx), with the
// wording of the official AFC / ESTV form figures in the three languages.

const fr = {
  title: 'Décompte TVA',
  subtitle: 'Le formulaire de l’AFC, rempli à partir de votre comptabilité. Vous contrôlez, complétez, puis déposez sur le portail de l’AFC.',
  methodEffective: 'Méthode effective',
  methodTdfn: 'Taux de la dette fiscale nette',
  periodicity: { mensuelle: 'mensuel', trimestrielle: 'trimestriel', semestrielle: 'semestriel', annuelle: 'annuel' } as Record<string, string>,
  settings: 'Réglages TVA',
  notLiableTitle: 'TVA non activée',
  notLiableText: 'Indiquez d’abord que votre entreprise est assujettie, avec sa méthode et sa périodicité.',
  openSettings: 'Ouvrir les réglages TVA',
  statusDraft: 'À déposer',
  statusLate: 'En retard',
  statusFiled: 'Déposé',
  statusPaid: 'Payé',
  statusFuture: 'À venir',
  statusOpen: 'En cours',
  dueOn: 'Délai : {{date}}',
  amountDue: 'Montant à payer',
  credit: 'Solde en votre faveur',
  nothingDue: 'Rien à payer',
  dueBy: 'À déposer et payer d’ici le {{date}}',
  filedOn: 'Déposé le {{date}}',
  paidOn: 'Payé le {{date}}',
  stepCheck: 'Contrôler',
  stepComplete: 'Compléter',
  stepFile: 'Déposer',
  stepPay: 'Payer',
  checksTitle: 'Contrôles avant dépôt',
  checkLiable: 'Entreprise assujettie, méthode et périodicité renseignées',
  checkIde: 'Numéro IDE (CHE-…) renseigné dans Mon entreprise',
  checkDrafts: '{{n}} écriture(s) de la période pas encore comptabilisée(s) : elles ne sont pas dans le décompte',
  checkDraftsOk: 'Toutes les écritures de la période sont comptabilisées',
  checkPeriodOpen: 'La période n’est pas terminée : les montants peuvent encore changer',
  checkReconciled: 'Chiffre d’affaires imposable = somme des prestations par taux',
  formTitle: 'Formulaire',
  formHint: 'Les montants grisés viennent de votre comptabilité. Les champs à compléter sont ceux que Cantia ne peut pas connaître.',
  sectionTurnover: 'I. Chiffre d’affaires',
  sectionTax: 'II. Calcul de l’impôt',
  sectionOther: 'III. Autres mouvements de fonds',
  colFigure: 'Ch.',
  colTurnover: 'Prestations CHF',
  colRate: 'Taux',
  colTax: 'Impôt CHF',
  colAmount: 'CHF',
  inputTaxTitle: 'Impôt préalable',
  editHint: 'À compléter si concerné',
  fileTitle: 'Déposer auprès de l’AFC',
  fileText: 'Connectez-vous au portail de l’AFC (ePortal), choisissez « Décompte TVA », puis téléversez le fichier XML ou reportez les chiffres ci-dessus.',
  downloadXml: 'Fichier XML pour l’AFC (eCH-0217)',
  downloadCsv: 'Feuille de travail (CSV)',
  openPortal: 'Ouvrir le portail AFC',
  xmlNeedsEffective: 'Le fichier XML n’est disponible qu’en méthode effective : reportez les chiffres à la main.',
  xmlManualNote: 'Les montants complétés à la main (ch. 205, 225, 235, 280, 383, 410 à 420) ne sont pas dans le fichier XML : reportez-les sur le portail.',
  afcReference: 'Référence AFC (facultatif)',
  markFiled: 'Marquer comme déposé',
  markPaid: 'Marquer comme payé',
  reopen: 'Rouvrir le décompte',
  frozenNote: 'Décompte déposé : les chiffres ci-dessus sont ceux déclarés le {{date}}.',
  notReady: 'Le suivi des décomptes (déposé, payé) sera disponible dès que la base de données aura été mise à jour.',
  saveError: 'Enregistrement impossible : {{error}}',
  historyTitle: 'Décomptes de l’année',
  tdfnRate: 'Taux TDFN (%)',
  tdfnRate2Turnover: 'CA TTC au 2e taux',
  ledgerLink: 'Voir le détail par code TVA',
  payInfo: 'Payez avec la facture QR que l’AFC vous envoie, ou par e-banking avec la référence indiquée sur le portail.',
};

type Copy = typeof fr;

const de: Copy = {
  ...fr,
  title: 'MWST-Abrechnung',
  subtitle: 'Das Formular der ESTV, aus Ihrer Buchhaltung ausgefüllt. Sie prüfen, ergänzen und reichen es im ESTV-Portal ein.',
  methodEffective: 'Effektive Methode',
  methodTdfn: 'Saldosteuersatz',
  periodicity: { mensuelle: 'monatlich', trimestrielle: 'quartalsweise', semestrielle: 'halbjährlich', annuelle: 'jährlich' },
  settings: 'MWST-Einstellungen',
  notLiableTitle: 'MWST nicht aktiviert',
  notLiableText: 'Geben Sie zuerst an, dass Ihr Unternehmen mehrwertsteuerpflichtig ist, mit Methode und Periodizität.',
  openSettings: 'MWST-Einstellungen öffnen',
  statusDraft: 'Einzureichen',
  statusLate: 'Verspätet',
  statusFiled: 'Eingereicht',
  statusPaid: 'Bezahlt',
  statusFuture: 'Bevorstehend',
  statusOpen: 'Laufend',
  dueOn: 'Frist: {{date}}',
  amountDue: 'Zu bezahlender Betrag',
  credit: 'Guthaben zu Ihren Gunsten',
  nothingDue: 'Nichts zu bezahlen',
  dueBy: 'Einreichen und bezahlen bis {{date}}',
  filedOn: 'Eingereicht am {{date}}',
  paidOn: 'Bezahlt am {{date}}',
  stepCheck: 'Prüfen',
  stepComplete: 'Ergänzen',
  stepFile: 'Einreichen',
  stepPay: 'Bezahlen',
  checksTitle: 'Kontrollen vor dem Einreichen',
  checkLiable: 'Steuerpflicht, Methode und Periodizität erfasst',
  checkIde: 'UID-Nummer (CHE-…) unter Mein Unternehmen erfasst',
  checkDrafts: '{{n}} Buchung(en) der Periode noch nicht verbucht: nicht in der Abrechnung',
  checkDraftsOk: 'Alle Buchungen der Periode sind verbucht',
  checkPeriodOpen: 'Die Periode ist nicht abgeschlossen: Beträge können sich noch ändern',
  checkReconciled: 'Steuerbarer Umsatz = Summe der Leistungen pro Satz',
  formTitle: 'Formular',
  formHint: 'Graue Beträge stammen aus Ihrer Buchhaltung. Zu ergänzen sind nur die Felder, die Cantia nicht kennen kann.',
  sectionTurnover: 'I. Umsatz',
  sectionTax: 'II. Steuerberechnung',
  sectionOther: 'III. Andere Mittelflüsse',
  colFigure: 'Ziff.',
  colTurnover: 'Leistungen CHF',
  colRate: 'Satz',
  colTax: 'Steuer CHF',
  inputTaxTitle: 'Vorsteuer',
  editHint: 'Falls zutreffend ergänzen',
  fileTitle: 'Bei der ESTV einreichen',
  fileText: 'Melden Sie sich im ESTV-Portal (ePortal) an, wählen Sie «MWST abrechnen» und laden Sie die XML-Datei hoch oder übertragen Sie die Ziffern.',
  downloadXml: 'XML-Datei für die ESTV (eCH-0217)',
  downloadCsv: 'Arbeitsblatt (CSV)',
  openPortal: 'ESTV-Portal öffnen',
  xmlNeedsEffective: 'Die XML-Datei gibt es nur für die effektive Methode: Ziffern bitte von Hand übertragen.',
  xmlManualNote: 'Von Hand ergänzte Beträge (Ziff. 205, 225, 235, 280, 383, 410–420) sind nicht in der XML-Datei: im Portal nachtragen.',
  afcReference: 'ESTV-Referenz (optional)',
  markFiled: 'Als eingereicht markieren',
  markPaid: 'Als bezahlt markieren',
  reopen: 'Abrechnung wieder öffnen',
  frozenNote: 'Eingereichte Abrechnung: Die Ziffern oben sind die am {{date}} deklarierten.',
  notReady: 'Die Verfolgung der Abrechnungen (eingereicht, bezahlt) ist verfügbar, sobald die Datenbank aktualisiert wurde.',
  saveError: 'Speichern nicht möglich: {{error}}',
  historyTitle: 'Abrechnungen des Jahres',
  tdfnRate: 'Saldosteuersatz (%)',
  tdfnRate2Turnover: 'Umsatz inkl. MWST zum 2. Satz',
  ledgerLink: 'Detail pro MWST-Code anzeigen',
  payInfo: 'Bezahlen Sie mit der QR-Rechnung der ESTV oder per E-Banking mit der im Portal angegebenen Referenz.',
};

const it: Copy = {
  ...fr,
  title: 'Rendiconto IVA',
  subtitle: 'Il modulo dell’AFC, compilato dalla vostra contabilità. Controllate, completate e inoltrate sul portale dell’AFC.',
  methodEffective: 'Metodo effettivo',
  methodTdfn: 'Aliquota saldo',
  periodicity: { mensuelle: 'mensile', trimestrielle: 'trimestrale', semestrielle: 'semestrale', annuelle: 'annuale' },
  settings: 'Impostazioni IVA',
  notLiableTitle: 'IVA non attivata',
  notLiableText: 'Indicate prima che la vostra impresa è assoggettata, con metodo e periodicità.',
  openSettings: 'Apri le impostazioni IVA',
  statusDraft: 'Da inoltrare',
  statusLate: 'In ritardo',
  statusFiled: 'Inoltrato',
  statusPaid: 'Pagato',
  statusFuture: 'Prossimo',
  statusOpen: 'In corso',
  dueOn: 'Termine: {{date}}',
  amountDue: 'Importo da pagare',
  credit: 'Saldo a vostro favore',
  nothingDue: 'Niente da pagare',
  dueBy: 'Da inoltrare e pagare entro il {{date}}',
  filedOn: 'Inoltrato il {{date}}',
  paidOn: 'Pagato il {{date}}',
  stepCheck: 'Controllare',
  stepComplete: 'Completare',
  stepFile: 'Inoltrare',
  stepPay: 'Pagare',
  checksTitle: 'Controlli prima dell’inoltro',
  checkLiable: 'Assoggettamento, metodo e periodicità indicati',
  checkIde: 'Numero IDI (CHE-…) indicato in La mia impresa',
  checkDrafts: '{{n}} registrazione(i) del periodo non ancora contabilizzata(e): non sono nel rendiconto',
  checkDraftsOk: 'Tutte le registrazioni del periodo sono contabilizzate',
  checkPeriodOpen: 'Il periodo non è terminato: gli importi possono ancora cambiare',
  checkReconciled: 'Cifra d’affari imponibile = somma delle prestazioni per aliquota',
  formTitle: 'Modulo',
  formHint: 'Gli importi in grigio vengono dalla vostra contabilità. Da completare solo i campi che Cantia non può conoscere.',
  sectionTurnover: 'I. Cifra d’affari',
  sectionTax: 'II. Calcolo dell’imposta',
  sectionOther: 'III. Altri flussi di mezzi',
  colFigure: 'Cifra',
  colTurnover: 'Prestazioni CHF',
  colRate: 'Aliquota',
  colTax: 'Imposta CHF',
  inputTaxTitle: 'Imposta precedente',
  editHint: 'Da completare se pertinente',
  fileTitle: 'Inoltrare all’AFC',
  fileText: 'Accedete al portale dell’AFC (ePortal), scegliete «Rendiconto IVA» e caricate il file XML o riportate le cifre.',
  downloadXml: 'File XML per l’AFC (eCH-0217)',
  downloadCsv: 'Foglio di lavoro (CSV)',
  openPortal: 'Apri il portale AFC',
  xmlNeedsEffective: 'Il file XML è disponibile solo per il metodo effettivo: riportate le cifre a mano.',
  xmlManualNote: 'Gli importi completati a mano (cifre 205, 225, 235, 280, 383, 410–420) non sono nel file XML: riportateli sul portale.',
  afcReference: 'Riferimento AFC (facoltativo)',
  markFiled: 'Segna come inoltrato',
  markPaid: 'Segna come pagato',
  reopen: 'Riapri il rendiconto',
  frozenNote: 'Rendiconto inoltrato: le cifre qui sopra sono quelle dichiarate il {{date}}.',
  notReady: 'Il monitoraggio dei rendiconti (inoltrato, pagato) sarà disponibile appena la banca dati sarà aggiornata.',
  saveError: 'Salvataggio impossibile: {{error}}',
  historyTitle: 'Rendiconti dell’anno',
  tdfnRate: 'Aliquota saldo (%)',
  tdfnRate2Turnover: 'Cifra d’affari IVA incl. alla 2a aliquota',
  ledgerLink: 'Vedi il dettaglio per codice IVA',
  payInfo: 'Pagate con la fattura QR che vi invia l’AFC o via e-banking con il riferimento indicato sul portale.',
};

export function useVatCopy(): Copy {
  const l = getAppLocale();
  return l === 'de' ? de : l === 'it' ? it : fr;
}

export { fill } from '../payroll/wizardCopy';

export function figureLabels(frLabels: Record<string, string>): Record<string, string> {
  const l = getAppLocale();
  return l === 'de' ? LABELS_DE : l === 'it' ? LABELS_IT : frLabels;
}
