import type { AppLocale } from '../translations';

// Copy of the public salary calculator (app/calculateur-salaire.tsx and
// its /de and /it twins) and of the PDF it downloads. {{x}} placeholders
// are filled with fill() from lib/payroll/wizardCopy.

export type CalculatorCopy = typeof fr;

const fr = {
  metaTitle: 'Calculateur de salaire suisse 2026 : brut, net, LPP et charges | Cantia',
  metaDescription:
    'Calculez gratuitement le salaire net et le coût employeur en Suisse : AVS, AC, LPP selon l’âge, LAA, allocations familiales et impôt à la source par canton. Montants 2026.',
  kicker: 'Outil gratuit · Montants {{year}}',
  title: 'Calculateur de salaire suisse',
  lede: 'Du brut au net et au coût employeur, en direct : AVS, chômage, LPP selon l’âge et votre caisse, accidents, allocations familiales et impôt à la source avec les barèmes officiels des 26 cantons. Gratuit, sans inscription, rien n’est enregistré.',

  salary: 'Salaire',
  grossSuffix: 'CHF brut',
  perMonth: 'par mois',
  perYear: 'par an',
  monthlyIs: 'Soit CHF {{v}} par mois (12 salaires).',
  yearlyIs: 'Soit CHF {{v}} par an (12 salaires).',
  employee: 'Employé·e',
  birthYear: 'Année de naissance',
  ageIn: '{{age}} ans en {{year}}',
  badYear: 'Année invalide',
  permit: 'Nationalité / permis',
  permits: { swiss: 'Suisse', C: 'Permis C', B: 'Permis B', L: 'Permis L', G: 'Frontalier (G)', other: 'Autre' },
  residence: 'Domicile',
  residences: { CH: 'En Suisse', FR: 'France', DE: 'Allemagne', IT: 'Italie', AT: 'Autriche' },
  marital: 'État civil',
  single: 'Célibataire',
  married: 'Marié·e / partenariat',
  spouseNoIncome: 'Conjoint·e sans revenu',
  spouseWorks: 'Conjoint·e qui travaille',
  spouseSwiss: 'Conjoint·e suisse ou permis C',
  spouseForeign: 'Conjoint·e d’une autre nationalité',
  kids: 'Enfants de moins de 16 ans',
  kidsTraining: 'Enfants en formation (16-25 ans)',
  less: 'Moins',
  more: 'Plus',
  noChurch: 'Sans impôt ecclésiastique',
  church: 'Membre d’une Église',
  company: 'Entreprise',
  workCanton: 'Canton de travail',
  pension: 'Caisse de pension (LPP)',
  legalMin: 'Minimum légal',
  fundPlan: 'Plan de ma caisse',
  fundRate: 'Taux total dès 25 ans',
  fundYoung: 'Taux de 18 à 24 ans',
  fundYoungPh: 'p. ex. 4',
  erShare: 'Part employeur',
  fundHint: 'Reprenez les taux du règlement ou de la fiche de votre caisse. Vide = minimum légal selon l’âge. La part employeur est d’au moins 50 % (art. 66 LPP).',
  laa: 'Assurance accidents (LAA)',
  aanpSuffix: '% AANP employé',
  aapSuffix: '% AAP employeur',
  laaHint: 'Taux indicatifs : ceux de votre police LAA peuvent varier selon le métier.',

  netLabel: 'SALAIRE NET / MOIS',
  netSub: 'Brut CHF {{gross}} − retenues CHF {{ded}}',
  netSubAllow: ' + allocations CHF {{v}}',
  totalCost: 'Coût total employeur',
  perMonthShort: '/ mois',
  deductions: 'Retenues sur le salaire',
  totalDeductions: 'Total des retenues',
  employerCharges: 'Charges patronales',
  totalEmployer: 'Total employeur',
  allowances: 'Allocations familiales ({{canton}})',
  of: 'de',
  pdfButton: 'Télécharger mon calcul (PDF)',
  pdfHint: 'Un récapitulatif d’une page, prêt à imprimer ou à envoyer.',

  lines: {
    avs: 'AVS / AI / APG',
    ac: 'AC (chômage)',
    lpp: 'LPP (2e pilier)',
    aanp: 'AANP (accidents non prof.)',
    aap: 'AAP (accidents prof.)',
    ijm: 'IJM (maladie)',
    cafEr: 'Allocations familiales (caisse {{canton}})',
    cafEe: 'Allocations familiales (part salarié {{canton}})',
    wht: 'Impôt à la source ({{code}})',
  },

  lppPrefix: 'LPP : ',
  lppBelowTitle: 'pas assujetti',
  lppBelow: 'Le salaire annuel (CHF {{v}}) est sous le seuil d’entrée de CHF 22’680 : l’affiliation n’est pas obligatoire. Une caisse peut quand même l’assurer si son règlement le prévoit.',
  lppMinorTitle: 'pas de LPP avant 18 ans',
  lppMinor: 'Avant le 1er janvier qui suit le 17e anniversaire, il n’y a jamais de LPP obligatoire.',
  lppYoungNoneTitle: 'rien à épargner avant 25 ans (minimum légal)',
  lppYoungNone: 'De 18 à 24 ans, la loi impose seulement la couverture décès et invalidité, sans épargne. Beaucoup de caisses prélèvent pourtant une cotisation dès 18 ans : choisissez « Plan de ma caisse » et indiquez son taux de 18 à 24 ans pour la voir ici.',
  lppBase: 'Salaire coordonné : CHF {{v}} par mois (salaire annuel plafonné à CHF 90’720, moins CHF 26’460, minimum CHF 3’780).',
  lppSplit: 'Répartition : {{er}} employeur, {{ee}} employé·e.',
  lppYoungTitle: '{{rate}} dès 18 ans (plan de la caisse)',
  lppYoung: 'Taux de la caisse pour les 18-24 ans : {{rate}}.',
  lppTitle: '{{rate}} à {{age}} ans',
  lppLegalTag: ' (minimum légal)',
  lppFundTag: ' (plan de la caisse)',
  lppLegal: 'Bonification de vieillesse légale : 7 % de 25 à 34 ans, 10 % de 35 à 44, 15 % de 45 à 54, 18 % dès 55.',
  lppFund: 'Taux du règlement de la caisse.',

  whtYes: 'Impôt à la source : oui (barème {{code}})',
  whtNo: 'Impôt à la source : non',
  whtReasons: {
    swiss: 'Nationalité suisse',
    C: 'Permis C',
    spouse: 'Marié·e à une personne suisse ou titulaire d’un permis C',
    france: 'Frontalier résidant en France (accord de 1983) : imposé en France',
    permit: 'Permis {{p}}',
    border: 'Frontalier',
  },
  whtNot: '{{reason}} : l’impôt est payé sur la déclaration d’impôt ordinaire, rien n’est retenu sur le salaire.',
  whtWhy: '{{reason}} : l’employeur retient l’impôt chaque mois et le verse au canton. Barème {{code}} ({{who}}, {{kids}} enfant(s), {{church}}), canton {{canton}}.',
  whtWho: { A: 'personne seule', B: 'marié·e, un seul revenu', C: 'marié·e, deux revenus', H: 'famille monoparentale' },
  whtChurchYes: 'avec impôt ecclésiastique',
  whtChurchNo: 'sans impôt ecclésiastique',
  whtLoading: 'Chargement du barème…',
  whtMissing: 'Le barème officiel de ce cas n’est pas disponible ici : le taux n’est pas compté dans le net.',
  whtRate: 'Taux du barème officiel {{year}} pour ce salaire : {{rate}}.',

  ctaKicker: 'DANS CANTIA, TOUT EST AUTOMATIQUE',
  ctaTitle: 'Ce calcul, Cantia le fait chaque mois à votre place',
  ctaPoints: [
    'La fiche de salaire PDF est générée chaque mois, prête à envoyer',
    'Le taux LPP change tout seul au 1er janvier selon l’âge',
    'Impôt à la source : bon barème, bon canton, mis à jour chaque année',
    'Allocations familiales, LAA, IJM et plan de votre caisse pris en compte',
    'Il vous manque une information ? Cantia vous le dit avant la première fiche',
  ],
  ctaButton: 'Essayer 14 jours',
  ctaNote: 'Sans engagement · Données hébergées en Suisse',

  sitTitle: 'Toutes les situations LPP en un coup d’œil',
  sitText: 'L’âge compte par année civile : année en cours moins année de naissance. Le taux change donc le 1er janvier, pour tout le monde né la même année. L’employeur paie toujours au moins la moitié.',
  sitHead: ['Situation', 'Minimum légal', 'Plans de caisse courants'],
  sitRows: [
    ['Moins de 18 ans', 'Aucune LPP', 'Aucune'],
    ['18 à 24 ans', 'Décès et invalidité seulement, pas d’épargne', 'Selon la caisse (souvent 1 à 5 %)'],
    ['25 à 34 ans', '7 % du salaire coordonné', 'Souvent 7 à 10 %'],
    ['35 à 44 ans', '10 %', 'Souvent 10 à 13 %'],
    ['45 à 54 ans', '15 %', 'Souvent 15 à 18 %'],
    ['55 ans à la retraite', '18 %', 'Souvent 18 à 21 %'],
    ['Salaire sous CHF 22’680 / an', 'Pas d’affiliation obligatoire', 'Possible si le règlement le prévoit'],
  ],
  sitLink: 'Le calcul de la LPP expliqué pas à pas, avec exemples →',
  sources:
    'Sources : OFAS (AVS/AI/APG {{avs}}, AC {{ac}} jusqu’à CHF 148’200 par an), LPP art. 7, 8, 16 et 66 (montants {{year}}), OFAS allocations familiales {{year}}, AFC barèmes de l’impôt à la source {{year}}. Résultat indicatif : le règlement de votre caisse de pension, votre police LAA et la décision de l’administration fiscale font foi.',

  pdfTitle: 'Calcul de salaire {{year}}',
  pdfMade: 'Calculé le {{date}} sur cantia.ch/calculateur-salaire',
  pdfSituation: 'Situation',
  pdfAge: 'Âge',
  pdfCanton: 'Canton de travail',
  pdfGross: 'Salaire brut',
  pdfNet: 'Salaire net',
  pdfMonth: 'Par mois',
  pdfYear: 'Par an',
  pdfCta: 'Générez vos fiches de salaire automatiquement avec Cantia : cantia.ch · 14 jours d’essai',
  pdfDisclaimer: 'Résultat indicatif. Le règlement de la caisse de pension, la police LAA et l’administration fiscale font foi.',
  pdfFile: 'calcul-salaire',
};

const de: CalculatorCopy = {
  metaTitle: 'Lohnrechner Schweiz 2026: Brutto, Netto, BVG und Abzüge | Cantia',
  metaDescription:
    'Berechnen Sie kostenlos Nettolohn und Arbeitgeberkosten in der Schweiz: AHV, ALV, BVG nach Alter, UVG, Familienzulagen und Quellensteuer nach Kanton. Werte 2026.',
  kicker: 'Kostenloses Tool · Werte {{year}}',
  title: 'Lohnrechner Schweiz',
  lede: 'Von brutto zu netto und zu den Arbeitgeberkosten, live: AHV, ALV, BVG nach Alter und Ihrer Kasse, Unfall, Familienzulagen und Quellensteuer nach den offiziellen Tarifen der 26 Kantone. Kostenlos, ohne Anmeldung, nichts wird gespeichert.',

  salary: 'Lohn',
  grossSuffix: 'CHF brutto',
  perMonth: 'pro Monat',
  perYear: 'pro Jahr',
  monthlyIs: 'Also CHF {{v}} pro Monat (12 Löhne).',
  yearlyIs: 'Also CHF {{v}} pro Jahr (12 Löhne).',
  employee: 'Mitarbeitende',
  birthYear: 'Geburtsjahr',
  ageIn: '{{age}} Jahre im {{year}}',
  badYear: 'Ungültiges Jahr',
  permit: 'Nationalität / Bewilligung',
  permits: { swiss: 'Schweiz', C: 'Ausweis C', B: 'Ausweis B', L: 'Ausweis L', G: 'Grenzgänger (G)', other: 'Andere' },
  residence: 'Wohnsitz',
  residences: { CH: 'In der Schweiz', FR: 'Frankreich', DE: 'Deutschland', IT: 'Italien', AT: 'Österreich' },
  marital: 'Zivilstand',
  single: 'Ledig',
  married: 'Verheiratet / Partnerschaft',
  spouseNoIncome: 'Partner/in ohne Einkommen',
  spouseWorks: 'Partner/in erwerbstätig',
  spouseSwiss: 'Partner/in Schweizer/in oder Ausweis C',
  spouseForeign: 'Partner/in andere Nationalität',
  kids: 'Kinder unter 16 Jahren',
  kidsTraining: 'Kinder in Ausbildung (16-25 Jahre)',
  less: 'Weniger',
  more: 'Mehr',
  noChurch: 'Ohne Kirchensteuer',
  church: 'Kirchenmitglied',
  company: 'Unternehmen',
  workCanton: 'Arbeitskanton',
  pension: 'Pensionskasse (BVG)',
  legalMin: 'Gesetzliches Minimum',
  fundPlan: 'Plan meiner Kasse',
  fundRate: 'Gesamtsatz ab 25',
  fundYoung: 'Satz 18 bis 24',
  fundYoungPh: 'z. B. 4',
  erShare: 'Arbeitgeberanteil',
  fundHint: 'Übernehmen Sie die Sätze aus dem Reglement oder Ausweis Ihrer Kasse. Leer = gesetzliches Minimum nach Alter. Der Arbeitgeber zahlt mindestens 50 % (Art. 66 BVG).',
  laa: 'Unfallversicherung (UVG)',
  aanpSuffix: '% NBU Arbeitnehmer',
  aapSuffix: '% BU Arbeitgeber',
  laaHint: 'Richtwerte: die Sätze Ihrer UVG-Police können je nach Beruf abweichen.',

  netLabel: 'NETTOLOHN / MONAT',
  netSub: 'Brutto CHF {{gross}} − Abzüge CHF {{ded}}',
  netSubAllow: ' + Zulagen CHF {{v}}',
  totalCost: 'Arbeitgeberkosten total',
  perMonthShort: '/ Monat',
  deductions: 'Lohnabzüge',
  totalDeductions: 'Total Abzüge',
  employerCharges: 'Arbeitgeberbeiträge',
  totalEmployer: 'Total Arbeitgeber',
  allowances: 'Familienzulagen ({{canton}})',
  of: 'von',
  pdfButton: 'Meine Berechnung herunterladen (PDF)',
  pdfHint: 'Eine Seite Zusammenfassung, bereit zum Drucken oder Versenden.',

  lines: {
    avs: 'AHV / IV / EO',
    ac: 'ALV (Arbeitslosenversicherung)',
    lpp: 'BVG (2. Säule)',
    aanp: 'NBU (Nichtberufsunfall)',
    aap: 'BU (Berufsunfall)',
    ijm: 'KTG (Krankentaggeld)',
    cafEr: 'Familienzulagen (Kasse {{canton}})',
    cafEe: 'Familienzulagen (Arbeitnehmeranteil {{canton}})',
    wht: 'Quellensteuer ({{code}})',
  },

  lppPrefix: 'BVG: ',
  lppBelowTitle: 'nicht versicherungspflichtig',
  lppBelow: 'Der Jahreslohn (CHF {{v}}) liegt unter der Eintrittsschwelle von CHF 22’680: keine obligatorische Versicherung. Eine Kasse kann trotzdem versichern, wenn ihr Reglement es vorsieht.',
  lppMinorTitle: 'kein BVG vor 18',
  lppMinor: 'Vor dem 1. Januar nach dem 17. Geburtstag gibt es nie ein obligatorisches BVG.',
  lppYoungNoneTitle: 'kein Sparen vor 25 (gesetzliches Minimum)',
  lppYoungNone: 'Von 18 bis 24 verlangt das Gesetz nur die Risikoversicherung Tod und Invalidität, ohne Sparen. Viele Kassen erheben trotzdem ab 18 einen Beitrag: wählen Sie «Plan meiner Kasse» und geben Sie den Satz 18 bis 24 ein.',
  lppBase: 'Koordinierter Lohn: CHF {{v}} pro Monat (Jahreslohn höchstens CHF 90’720, minus CHF 26’460, mindestens CHF 3’780).',
  lppSplit: 'Aufteilung: {{er}} Arbeitgeber, {{ee}} Arbeitnehmer/in.',
  lppYoungTitle: '{{rate}} ab 18 (Plan der Kasse)',
  lppYoung: 'Satz der Kasse für 18- bis 24-Jährige: {{rate}}.',
  lppTitle: '{{rate}} mit {{age}} Jahren',
  lppLegalTag: ' (gesetzliches Minimum)',
  lppFundTag: ' (Plan der Kasse)',
  lppLegal: 'Gesetzliche Altersgutschrift: 7 % von 25 bis 34, 10 % von 35 bis 44, 15 % von 45 bis 54, 18 % ab 55.',
  lppFund: 'Satz gemäss Reglement der Kasse.',

  whtYes: 'Quellensteuer: ja (Tarif {{code}})',
  whtNo: 'Quellensteuer: nein',
  whtReasons: {
    swiss: 'Schweizer Nationalität',
    C: 'Ausweis C',
    spouse: 'Verheiratet mit Schweizer/in oder Person mit Ausweis C',
    france: 'Grenzgänger mit Wohnsitz in Frankreich (Abkommen von 1983): in Frankreich besteuert',
    permit: 'Ausweis {{p}}',
    border: 'Grenzgänger',
  },
  whtNot: '{{reason}}: die Steuer wird über die ordentliche Steuererklärung bezahlt, vom Lohn wird nichts abgezogen.',
  whtWhy: '{{reason}}: der Arbeitgeber zieht die Steuer jeden Monat ab und überweist sie dem Kanton. Tarif {{code}} ({{who}}, {{kids}} Kind(er), {{church}}), Kanton {{canton}}.',
  whtWho: { A: 'alleinstehend', B: 'verheiratet, ein Einkommen', C: 'verheiratet, zwei Einkommen', H: 'alleinerziehend' },
  whtChurchYes: 'mit Kirchensteuer',
  whtChurchNo: 'ohne Kirchensteuer',
  whtLoading: 'Tarif wird geladen…',
  whtMissing: 'Der offizielle Tarif für diesen Fall ist hier nicht verfügbar: der Satz ist im Nettolohn nicht berücksichtigt.',
  whtRate: 'Satz gemäss offiziellem Tarif {{year}} für diesen Lohn: {{rate}}.',

  ctaKicker: 'IN CANTIA LÄUFT ALLES AUTOMATISCH',
  ctaTitle: 'Diese Berechnung macht Cantia jeden Monat für Sie',
  ctaPoints: [
    'Die Lohnabrechnung als PDF wird jeden Monat erstellt, bereit zum Versand',
    'Der BVG-Satz ändert sich am 1. Januar automatisch mit dem Alter',
    'Quellensteuer: richtiger Tarif, richtiger Kanton, jedes Jahr aktualisiert',
    'Familienzulagen, UVG, KTG und der Plan Ihrer Kasse werden berücksichtigt',
    'Fehlt eine Angabe? Cantia sagt es Ihnen vor der ersten Abrechnung',
  ],
  ctaButton: '14 Tage testen',
  ctaNote: 'Unverbindlich · Daten in der Schweiz gehostet',

  sitTitle: 'Alle BVG-Situationen auf einen Blick',
  sitText: 'Das Alter zählt pro Kalenderjahr: laufendes Jahr minus Geburtsjahr. Der Satz ändert also am 1. Januar, für alle mit demselben Jahrgang. Der Arbeitgeber zahlt immer mindestens die Hälfte.',
  sitHead: ['Situation', 'Gesetzliches Minimum', 'Übliche Kassenpläne'],
  sitRows: [
    ['Unter 18', 'Kein BVG', 'Keiner'],
    ['18 bis 24', 'Nur Tod und Invalidität, kein Sparen', 'Je nach Kasse (oft 1 bis 5 %)'],
    ['25 bis 34', '7 % des koordinierten Lohns', 'Oft 7 bis 10 %'],
    ['35 bis 44', '10 %', 'Oft 10 bis 13 %'],
    ['45 bis 54', '15 %', 'Oft 15 bis 18 %'],
    ['55 bis Pensionierung', '18 %', 'Oft 18 bis 21 %'],
    ['Lohn unter CHF 22’680 / Jahr', 'Keine Versicherungspflicht', 'Möglich, wenn das Reglement es vorsieht'],
  ],
  sitLink: 'Die BVG-Berechnung Schritt für Schritt erklärt (Französisch) →',
  sources:
    'Quellen: BSV (AHV/IV/EO {{avs}}, ALV {{ac}} bis CHF 148’200 pro Jahr), BVG Art. 7, 8, 16 und 66 (Werte {{year}}), BSV Familienzulagen {{year}}, ESTV Quellensteuertarife {{year}}. Unverbindliches Ergebnis: massgebend sind das Reglement Ihrer Pensionskasse, Ihre UVG-Police und der Entscheid der Steuerverwaltung.',

  pdfTitle: 'Lohnberechnung {{year}}',
  pdfMade: 'Berechnet am {{date}} auf cantia.ch/de/calculateur-salaire',
  pdfSituation: 'Situation',
  pdfAge: 'Alter',
  pdfCanton: 'Arbeitskanton',
  pdfGross: 'Bruttolohn',
  pdfNet: 'Nettolohn',
  pdfMonth: 'Pro Monat',
  pdfYear: 'Pro Jahr',
  pdfCta: 'Erstellen Sie Ihre Lohnabrechnungen automatisch mit Cantia: cantia.ch · 14 Tage gratis testen',
  pdfDisclaimer: 'Unverbindliches Ergebnis. Massgebend sind das Reglement der Pensionskasse, die UVG-Police und die Steuerverwaltung.',
  pdfFile: 'lohnberechnung',
};

const it: CalculatorCopy = {
  metaTitle: 'Calcolatore di salario svizzero 2026: lordo, netto, LPP e oneri | Cantia',
  metaDescription:
    'Calcolate gratuitamente il salario netto e il costo per il datore di lavoro in Svizzera: AVS, AD, LPP secondo l’età, LAINF, assegni familiari e imposta alla fonte per cantone. Importi 2026.',
  kicker: 'Strumento gratuito · Importi {{year}}',
  title: 'Calcolatore di salario svizzero',
  lede: 'Dal lordo al netto e al costo per il datore di lavoro, in tempo reale: AVS, disoccupazione, LPP secondo l’età e la vostra cassa, infortuni, assegni familiari e imposta alla fonte con le tariffe ufficiali dei 26 cantoni. Gratuito, senza registrazione, nulla viene salvato.',

  salary: 'Salario',
  grossSuffix: 'CHF lordo',
  perMonth: 'al mese',
  perYear: 'all’anno',
  monthlyIs: 'Cioè CHF {{v}} al mese (12 salari).',
  yearlyIs: 'Cioè CHF {{v}} all’anno (12 salari).',
  employee: 'Dipendente',
  birthYear: 'Anno di nascita',
  ageIn: '{{age}} anni nel {{year}}',
  badYear: 'Anno non valido',
  permit: 'Nazionalità / permesso',
  permits: { swiss: 'Svizzera', C: 'Permesso C', B: 'Permesso B', L: 'Permesso L', G: 'Frontaliere (G)', other: 'Altro' },
  residence: 'Domicilio',
  residences: { CH: 'In Svizzera', FR: 'Francia', DE: 'Germania', IT: 'Italia', AT: 'Austria' },
  marital: 'Stato civile',
  single: 'Celibe / nubile',
  married: 'Coniugato/a / unione domestica',
  spouseNoIncome: 'Coniuge senza reddito',
  spouseWorks: 'Coniuge che lavora',
  spouseSwiss: 'Coniuge svizzero/a o permesso C',
  spouseForeign: 'Coniuge di altra nazionalità',
  kids: 'Figli sotto i 16 anni',
  kidsTraining: 'Figli in formazione (16-25 anni)',
  less: 'Meno',
  more: 'Più',
  noChurch: 'Senza imposta ecclesiastica',
  church: 'Membro di una Chiesa',
  company: 'Impresa',
  workCanton: 'Cantone di lavoro',
  pension: 'Cassa pensione (LPP)',
  legalMin: 'Minimo legale',
  fundPlan: 'Piano della mia cassa',
  fundRate: 'Aliquota totale dai 25 anni',
  fundYoung: 'Aliquota dai 18 ai 24 anni',
  fundYoungPh: 'p. es. 4',
  erShare: 'Quota datore di lavoro',
  fundHint: 'Riprendete le aliquote dal regolamento o dal certificato della vostra cassa. Vuoto = minimo legale secondo l’età. Il datore di lavoro paga almeno il 50 % (art. 66 LPP).',
  laa: 'Assicurazione infortuni (LAINF)',
  aanpSuffix: '% INP dipendente',
  aapSuffix: '% IP datore',
  laaHint: 'Aliquote indicative: quelle della vostra polizza LAINF possono variare secondo il mestiere.',

  netLabel: 'SALARIO NETTO / MESE',
  netSub: 'Lordo CHF {{gross}} − trattenute CHF {{ded}}',
  netSubAllow: ' + assegni CHF {{v}}',
  totalCost: 'Costo totale datore di lavoro',
  perMonthShort: '/ mese',
  deductions: 'Trattenute sul salario',
  totalDeductions: 'Totale trattenute',
  employerCharges: 'Oneri del datore di lavoro',
  totalEmployer: 'Totale datore di lavoro',
  allowances: 'Assegni familiari ({{canton}})',
  of: 'di',
  pdfButton: 'Scaricare il mio calcolo (PDF)',
  pdfHint: 'Un riepilogo di una pagina, pronto da stampare o inviare.',

  lines: {
    avs: 'AVS / AI / IPG',
    ac: 'AD (disoccupazione)',
    lpp: 'LPP (2° pilastro)',
    aanp: 'INP (infortuni non prof.)',
    aap: 'IP (infortuni prof.)',
    ijm: 'IGM (malattia)',
    cafEr: 'Assegni familiari (cassa {{canton}})',
    cafEe: 'Assegni familiari (quota dipendente {{canton}})',
    wht: 'Imposta alla fonte ({{code}})',
  },

  lppPrefix: 'LPP: ',
  lppBelowTitle: 'non assoggettato',
  lppBelow: 'Il salario annuo (CHF {{v}}) è sotto la soglia d’entrata di CHF 22’680: l’affiliazione non è obbligatoria. Una cassa può comunque assicurarlo se il regolamento lo prevede.',
  lppMinorTitle: 'nessuna LPP prima dei 18 anni',
  lppMinor: 'Prima del 1° gennaio che segue il 17° compleanno, la LPP non è mai obbligatoria.',
  lppYoungNoneTitle: 'nessun risparmio prima dei 25 anni (minimo legale)',
  lppYoungNone: 'Dai 18 ai 24 anni la legge impone solo la copertura decesso e invalidità, senza risparmio. Molte casse prelevano però un contributo dai 18 anni: scegliete «Piano della mia cassa» e indicate la sua aliquota dai 18 ai 24 anni.',
  lppBase: 'Salario coordinato: CHF {{v}} al mese (salario annuo al massimo CHF 90’720, meno CHF 26’460, minimo CHF 3’780).',
  lppSplit: 'Ripartizione: {{er}} datore di lavoro, {{ee}} dipendente.',
  lppYoungTitle: '{{rate}} dai 18 anni (piano della cassa)',
  lppYoung: 'Aliquota della cassa per i 18-24 anni: {{rate}}.',
  lppTitle: '{{rate}} a {{age}} anni',
  lppLegalTag: ' (minimo legale)',
  lppFundTag: ' (piano della cassa)',
  lppLegal: 'Accredito di vecchiaia legale: 7 % dai 25 ai 34 anni, 10 % dai 35 ai 44, 15 % dai 45 ai 54, 18 % dai 55.',
  lppFund: 'Aliquota del regolamento della cassa.',

  whtYes: 'Imposta alla fonte: sì (tariffa {{code}})',
  whtNo: 'Imposta alla fonte: no',
  whtReasons: {
    swiss: 'Nazionalità svizzera',
    C: 'Permesso C',
    spouse: 'Coniugato/a con una persona svizzera o titolare di un permesso C',
    france: 'Frontaliere residente in Francia (accordo del 1983): tassato in Francia',
    permit: 'Permesso {{p}}',
    border: 'Frontaliere',
  },
  whtNot: '{{reason}}: l’imposta è pagata con la dichiarazione ordinaria, nulla è trattenuto sul salario.',
  whtWhy: '{{reason}}: il datore di lavoro trattiene l’imposta ogni mese e la versa al cantone. Tariffa {{code}} ({{who}}, {{kids}} figlio/i, {{church}}), cantone {{canton}}.',
  whtWho: { A: 'persona sola', B: 'coniugato/a, un solo reddito', C: 'coniugato/a, due redditi', H: 'famiglia monoparentale' },
  whtChurchYes: 'con imposta ecclesiastica',
  whtChurchNo: 'senza imposta ecclesiastica',
  whtLoading: 'Caricamento della tariffa…',
  whtMissing: 'La tariffa ufficiale per questo caso non è disponibile qui: l’aliquota non è contata nel netto.',
  whtRate: 'Aliquota della tariffa ufficiale {{year}} per questo salario: {{rate}}.',

  ctaKicker: 'IN CANTIA TUTTO È AUTOMATICO',
  ctaTitle: 'Questo calcolo, Cantia lo fa ogni mese al posto vostro',
  ctaPoints: [
    'Il conteggio di salario in PDF è generato ogni mese, pronto da inviare',
    'L’aliquota LPP cambia da sola il 1° gennaio secondo l’età',
    'Imposta alla fonte: tariffa giusta, cantone giusto, aggiornata ogni anno',
    'Assegni familiari, LAINF, IGM e piano della vostra cassa considerati',
    'Manca un’informazione? Cantia ve lo dice prima del primo conteggio',
  ],
  ctaButton: 'Provare 14 giorni',
  ctaNote: 'Senza impegno · Dati ospitati in Svizzera',

  sitTitle: 'Tutte le situazioni LPP in un colpo d’occhio',
  sitText: 'L’età conta per anno civile: anno in corso meno anno di nascita. L’aliquota cambia quindi il 1° gennaio, per tutti i nati nello stesso anno. Il datore di lavoro paga sempre almeno la metà.',
  sitHead: ['Situazione', 'Minimo legale', 'Piani di cassa correnti'],
  sitRows: [
    ['Meno di 18 anni', 'Nessuna LPP', 'Nessuno'],
    ['18-24 anni', 'Solo decesso e invalidità, nessun risparmio', 'Secondo la cassa (spesso 1-5 %)'],
    ['25-34 anni', '7 % del salario coordinato', 'Spesso 7-10 %'],
    ['35-44 anni', '10 %', 'Spesso 10-13 %'],
    ['45-54 anni', '15 %', 'Spesso 15-18 %'],
    ['Dai 55 anni al pensionamento', '18 %', 'Spesso 18-21 %'],
    ['Salario sotto CHF 22’680 / anno', 'Nessuna affiliazione obbligatoria', 'Possibile se il regolamento lo prevede'],
  ],
  sitLink: 'Il calcolo della LPP spiegato passo per passo (in francese) →',
  sources:
    'Fonti: UFAS (AVS/AI/IPG {{avs}}, AD {{ac}} fino a CHF 148’200 all’anno), LPP art. 7, 8, 16 e 66 (importi {{year}}), UFAS assegni familiari {{year}}, AFC tariffe dell’imposta alla fonte {{year}}. Risultato indicativo: fanno stato il regolamento della vostra cassa pensione, la vostra polizza LAINF e la decisione dell’amministrazione fiscale.',

  pdfTitle: 'Calcolo del salario {{year}}',
  pdfMade: 'Calcolato il {{date}} su cantia.ch/it/calculateur-salaire',
  pdfSituation: 'Situazione',
  pdfAge: 'Età',
  pdfCanton: 'Cantone di lavoro',
  pdfGross: 'Salario lordo',
  pdfNet: 'Salario netto',
  pdfMonth: 'Al mese',
  pdfYear: 'All’anno',
  pdfCta: 'Generate automaticamente i vostri conteggi di salario con Cantia: cantia.ch · 14 giorni di prova',
  pdfDisclaimer: 'Risultato indicativo. Fanno stato il regolamento della cassa pensione, la polizza LAINF e l’amministrazione fiscale.',
  pdfFile: 'calcolo-salario',
};

export const CALCULATOR_COPY: Record<AppLocale, CalculatorCopy> = { fr, de, it };
