import { getAppLocale } from '../translations';

// Copy of « Ajouter un employé » / « Situation & charges » and of the salary
// simulator (components/payroll/*), in the three languages of the app.

const fr = {
  addTitle: 'Ajouter un employé',
  editTitle: 'Situation & charges',
  step: 'Étape {{n}}/{{total}}',
  steps: ['Identité', 'Sa situation', 'Assurances & charges', 'Ce qui s’applique'],
  next: 'Continuer',
  back: 'Retour',
  save: 'Enregistrer',
  edit: 'Modifier',
  create: 'Créer l’employé',
  close: 'Fermer',
  // identity
  fullName: 'Nom et prénom',
  fullNamePlaceholder: 'Ex. Marie Dubois',
  email: 'E-mail',
  emailHint: 'Pour lui envoyer ses fiches de salaire.',
  birthDate: 'Date de naissance',
  birthHint: 'Sert à calculer la LPP selon l’âge.',
  address: 'Adresse',
  npa: 'NPA',
  locality: 'Localité',
  addressCountry: 'Pays de domicile',
  postalCode: 'Code postal',
  nationalityField: 'Nationalité',
  nationalityPlaceholder: 'Ex. française, portugaise…',
  salary: 'Salaire',
  monthly: 'Mensuel',
  hourly: 'Horaire',
  monthlyAmount: 'Salaire brut mensuel (CHF)',
  hourlyAmount: 'Salaire horaire brut (CHF)',
  avs: 'Numéro AVS',
  avsPlaceholder: '756.XXXX.XXXX.XX',
  iban: 'IBAN',
  optionalNow: 'Peut être ajouté plus tard, mais requis avant la première fiche de salaire.',
  // situation
  nationality: 'Quelle est sa nationalité ?',
  swiss: 'Suisse',
  otherNationality: 'Autre nationalité',
  permit: 'Quel permis ?',
  permits: { C: 'C · établissement', B: 'B · séjour', L: 'L · courte durée', G: 'G · frontalier', F: 'F · admis provisoire', N: 'N · requérant', S: 'S · protection', other: 'Autre' },
  residence: 'Où habite-t-il / elle ?',
  countries: { CH: 'Suisse', FR: 'France', DE: 'Allemagne', IT: 'Italie', AT: 'Autriche', other: 'Autre pays' },
  marital: 'État civil',
  maritals: { single: 'Célibataire', married: 'Marié·e', registered: 'Partenariat enregistré', divorced: 'Divorcé·e', separated: 'Séparé·e', widowed: 'Veuf / veuve' },
  spouseSwiss: 'Le / la conjoint·e est suisse ou a un permis C',
  spouseWorks: 'Le / la conjoint·e a aussi un revenu',
  kidsUnder16: 'Enfants de moins de 16 ans',
  kidsTraining: 'Enfants de 16 à 25 ans en formation',
  livesWithKids: 'Vit avec ses enfants (famille monoparentale)',
  church: 'Membre d’une Église reconnue (impôt ecclésiastique)',
  allowances: 'Touche les allocations familiales par votre entreprise',
  allowancesHint: 'Un seul parent les touche. Décochez si c’est l’autre parent.',
  // insurances
  autoBanner: 'Calcul automatique selon l’âge, le canton et la loi : rien à saisir, Cantia applique les bons taux.',
  lawTitle: 'Charges fixées par la loi',
  lawFoot: 'AVS art. 5 LAVS · AC art. 3 LACI · LPP art. 8 et 16 LPP. Mises à jour chaque année.',
  lppAge: 'LPP (2e pilier, {{pct}} % à {{age}} ans)',
  lppNone: 'LPP (2e pilier)',
  lppInsured: 'Assuré·e à la LPP (2e pilier)',
  lppHint: 'Obligatoire dès CHF {{threshold}} par an et 25 ans. En dessous, rien n’est prélevé de toute façon.',
  laaTitle: 'Assurance accidents (LAA)',
  laaFoot: 'Taux indicatifs : reprenez ceux de votre police LAA.',
  cafTitle: 'Allocations familiales (caisse {{canton}})',
  cafFoot: 'Taux de la caisse cantonale 2026, fonds cantonaux inclus. Votre caisse peut différer.',
  advanced: 'Ajuster les taux (avancé)',
  advancedHint: 'Seulement si vous avez les taux exacts de vos polices. Laissez vide pour le calcul automatique.',
  aanp: 'AANP, accidents non prof. (employé) %',
  aap: 'AAP, accidents prof. (employeur) %',
  ijmEmp: 'IJM maladie (employé) %',
  ijmEr: 'IJM maladie (employeur) %',
  lppTotal: 'LPP, taux total de votre caisse %',
  cafEr: 'Caisse d’allocations familiales (employeur) %',
  whtCode: 'Code barème impôt à la source',
  whtRate: 'Taux impôt à la source %',
  auto: 'auto',
  // summary
  whtTitle: 'Impôt à la source',
  whtNot: 'Non soumis',
  whtYes: 'Barème {{code}} · canton {{canton}}',
  whtRateLine: '{{rate}} % sur le salaire de ce mois',
  whtMissing: 'Barème {{code}} ({{canton}}) pas encore importé : saisissez le taux dans « avancé » en attendant.',
  famTitle: 'Allocations familiales',
  famNone: 'Aucun enfant : pas d’allocations.',
  famOther: 'Versées à l’autre parent.',
  famAmount: 'CHF {{amount}} par mois, versés avec le salaire',
  chargesTitle: 'Charges appliquées',
  // simulator
  simTitle: 'Simulateur de salaire',
  simGross: 'Salaire brut',
  simMonthly: 'Mensuel',
  simYearly: 'Annuel',
  simEmployee: 'Déductions employé',
  simTotalDed: 'Total des déductions',
  simAllowances: 'Allocations familiales',
  simNet: 'Salaire net',
  simEmployer: 'Charges employeur',
  simTotalEr: 'Total des charges',
  simCost: 'Coût total employeur',
  simFoot: 'Calcul selon les taux suisses {{year}}, l’âge et la situation. Arrondi à 5 centimes par ligne.',
  // checklist
  checklistTitle: 'À compléter avant la première fiche de salaire',
  checklistText: 'Il manque des informations pour {{name}}. Complétez-les et vous pourrez générer ses salaires.',
  checklistCta: 'Compléter',
  required: 'Requis',
  errorName: 'Le nom est requis.',
  errorSave: 'L’enregistrement a échoué. Réessayez.',
  notReady: 'La situation de l’employé ne peut pas encore être enregistrée (mise à jour de la base en cours).',
};

type Copy = typeof fr;

const de: Copy = {
  ...fr,
  addTitle: 'Mitarbeitende hinzufügen',
  editTitle: 'Situation & Abzüge',
  step: 'Schritt {{n}}/{{total}}',
  steps: ['Identität', 'Situation', 'Versicherungen & Abzüge', 'Was gilt'],
  next: 'Weiter',
  back: 'Zurück',
  save: 'Speichern',
  edit: 'Bearbeiten',
  create: 'Mitarbeitende erstellen',
  close: 'Schliessen',
  fullName: 'Vor- und Nachname',
  fullNamePlaceholder: 'Bsp. Marie Dubois',
  email: 'E-Mail',
  emailHint: 'Für den Versand der Lohnabrechnungen.',
  birthDate: 'Geburtsdatum',
  birthHint: 'Für die BVG-Beiträge nach Alter.',
  address: 'Adresse',
  npa: 'PLZ',
  locality: 'Ort',
  addressCountry: 'Wohnsitzland',
  postalCode: 'Postleitzahl',
  nationalityField: 'Nationalität',
  nationalityPlaceholder: 'Bsp. französisch, portugiesisch…',
  salary: 'Lohn',
  monthly: 'Monatlich',
  hourly: 'Stündlich',
  monthlyAmount: 'Bruttomonatslohn (CHF)',
  hourlyAmount: 'Bruttostundenlohn (CHF)',
  avs: 'AHV-Nummer',
  iban: 'IBAN',
  optionalNow: 'Kann später ergänzt werden, ist aber vor der ersten Lohnabrechnung nötig.',
  nationality: 'Welche Nationalität?',
  swiss: 'Schweiz',
  otherNationality: 'Andere Nationalität',
  permit: 'Welche Bewilligung?',
  permits: { C: 'C · Niederlassung', B: 'B · Aufenthalt', L: 'L · Kurzaufenthalt', G: 'G · Grenzgänger', F: 'F · vorläufig aufgenommen', N: 'N · Asylsuchend', S: 'S · Schutzstatus', other: 'Andere' },
  residence: 'Wohnsitz',
  countries: { CH: 'Schweiz', FR: 'Frankreich', DE: 'Deutschland', IT: 'Italien', AT: 'Österreich', other: 'Anderes Land' },
  marital: 'Zivilstand',
  maritals: { single: 'Ledig', married: 'Verheiratet', registered: 'Eingetragene Partnerschaft', divorced: 'Geschieden', separated: 'Getrennt', widowed: 'Verwitwet' },
  spouseSwiss: 'Ehepartner·in ist Schweizer·in oder hat Bewilligung C',
  spouseWorks: 'Ehepartner·in hat ebenfalls ein Einkommen',
  kidsUnder16: 'Kinder unter 16 Jahren',
  kidsTraining: 'Kinder von 16 bis 25 in Ausbildung',
  livesWithKids: 'Lebt mit den Kindern (alleinerziehend)',
  church: 'Mitglied einer anerkannten Kirche (Kirchensteuer)',
  allowances: 'Bezieht die Familienzulagen über Ihr Unternehmen',
  allowancesHint: 'Nur ein Elternteil bezieht sie. Deaktivieren, wenn der andere Elternteil sie erhält.',
  autoBanner: 'Automatische Berechnung nach Alter, Kanton und Gesetz: nichts zu erfassen, Cantia wendet die richtigen Sätze an.',
  lawTitle: 'Gesetzliche Abzüge',
  lawFoot: 'AHV Art. 5 AHVG · ALV Art. 3 AVIG · BVG Art. 8 und 16 BVG. Jährlich aktualisiert.',
  lppAge: 'BVG (2. Säule, {{pct}} % mit {{age}} Jahren)',
  lppNone: 'BVG (2. Säule)',
  lppInsured: 'BVG-versichert (2. Säule)',
  lppHint: 'Obligatorisch ab CHF {{threshold}} pro Jahr und 25 Jahren. Darunter wird ohnehin nichts abgezogen.',
  laaTitle: 'Unfallversicherung (UVG)',
  laaFoot: 'Richtwerte: übernehmen Sie die Sätze Ihrer UVG-Police.',
  cafTitle: 'Familienzulagen (Kasse {{canton}})',
  cafFoot: 'Satz der kantonalen Kasse 2026, inkl. kantonale Fonds. Ihre Kasse kann abweichen.',
  advanced: 'Sätze anpassen (erweitert)',
  advancedHint: 'Nur wenn Sie die genauen Sätze Ihrer Policen haben. Leer lassen für die automatische Berechnung.',
  aanp: 'NBU, Nichtberufsunfall (AN) %',
  aap: 'BU, Berufsunfall (AG) %',
  ijmEmp: 'KTG Krankentaggeld (AN) %',
  ijmEr: 'KTG Krankentaggeld (AG) %',
  lppTotal: 'BVG, Gesamtsatz Ihrer Kasse %',
  cafEr: 'Familienausgleichskasse (AG) %',
  whtCode: 'Quellensteuer-Tarifcode',
  whtRate: 'Quellensteuersatz %',
  whtTitle: 'Quellensteuer',
  whtNot: 'Nicht quellensteuerpflichtig',
  whtYes: 'Tarif {{code}} · Kanton {{canton}}',
  whtRateLine: '{{rate}} % auf dem Lohn dieses Monats',
  whtMissing: 'Tarif {{code}} ({{canton}}) noch nicht importiert: Satz vorläufig unter «erweitert» erfassen.',
  famTitle: 'Familienzulagen',
  famNone: 'Keine Kinder: keine Zulagen.',
  famOther: 'Werden an den anderen Elternteil ausbezahlt.',
  famAmount: 'CHF {{amount}} pro Monat, mit dem Lohn ausbezahlt',
  chargesTitle: 'Angewendete Abzüge',
  simTitle: 'Lohnrechner',
  simGross: 'Bruttolohn',
  simMonthly: 'Monatlich',
  simYearly: 'Jährlich',
  simEmployee: 'Abzüge Arbeitnehmende',
  simTotalDed: 'Total Abzüge',
  simAllowances: 'Familienzulagen',
  simNet: 'Nettolohn',
  simEmployer: 'Arbeitgeberbeiträge',
  simTotalEr: 'Total Beiträge',
  simCost: 'Total Arbeitgeberkosten',
  simFoot: 'Berechnet nach den Schweizer Sätzen {{year}}, Alter und Situation. Auf 5 Rappen pro Zeile gerundet.',
  checklistTitle: 'Vor der ersten Lohnabrechnung zu ergänzen',
  checklistText: 'Für {{name}} fehlen Angaben. Ergänzen Sie diese, dann können Sie die Löhne erstellen.',
  checklistCta: 'Ergänzen',
  required: 'Erforderlich',
  errorName: 'Der Name ist erforderlich.',
  errorSave: 'Speichern fehlgeschlagen. Bitte erneut versuchen.',
  notReady: 'Die Situation kann noch nicht gespeichert werden (Datenbank-Update läuft).',
};

const it: Copy = {
  ...fr,
  addTitle: 'Aggiungere un dipendente',
  editTitle: 'Situazione e oneri',
  step: 'Passo {{n}}/{{total}}',
  steps: ['Identità', 'Situazione', 'Assicurazioni e oneri', 'Cosa si applica'],
  next: 'Continua',
  back: 'Indietro',
  save: 'Salva',
  edit: 'Modifica',
  create: 'Crea il dipendente',
  close: 'Chiudi',
  fullName: 'Nome e cognome',
  fullNamePlaceholder: 'Es. Marie Dubois',
  email: 'E-mail',
  emailHint: 'Per inviargli le buste paga.',
  birthDate: 'Data di nascita',
  birthHint: 'Serve per calcolare la LPP secondo l’età.',
  address: 'Indirizzo',
  npa: 'NPA',
  locality: 'Località',
  addressCountry: 'Paese di domicilio',
  postalCode: 'Codice postale',
  nationalityField: 'Nazionalità',
  nationalityPlaceholder: 'Es. francese, portoghese…',
  salary: 'Salario',
  monthly: 'Mensile',
  hourly: 'Orario',
  monthlyAmount: 'Salario lordo mensile (CHF)',
  hourlyAmount: 'Salario orario lordo (CHF)',
  avs: 'Numero AVS',
  iban: 'IBAN',
  optionalNow: 'Può essere aggiunto più tardi, ma è necessario prima della prima busta paga.',
  nationality: 'Qual è la sua nazionalità?',
  swiss: 'Svizzera',
  otherNationality: 'Altra nazionalità',
  permit: 'Quale permesso?',
  permits: { C: 'C · domicilio', B: 'B · dimora', L: 'L · breve durata', G: 'G · frontaliere', F: 'F · ammissione provvisoria', N: 'N · richiedente', S: 'S · protezione', other: 'Altro' },
  residence: 'Dove abita?',
  countries: { CH: 'Svizzera', FR: 'Francia', DE: 'Germania', IT: 'Italia', AT: 'Austria', other: 'Altro paese' },
  marital: 'Stato civile',
  maritals: { single: 'Celibe / nubile', married: 'Sposato·a', registered: 'Unione domestica registrata', divorced: 'Divorziato·a', separated: 'Separato·a', widowed: 'Vedovo·a' },
  spouseSwiss: 'Il / la coniuge è svizzero·a o ha un permesso C',
  spouseWorks: 'Anche il / la coniuge ha un reddito',
  kidsUnder16: 'Figli sotto i 16 anni',
  kidsTraining: 'Figli da 16 a 25 anni in formazione',
  livesWithKids: 'Vive con i figli (famiglia monoparentale)',
  church: 'Membro di una Chiesa riconosciuta (imposta di culto)',
  allowances: 'Riceve gli assegni familiari tramite la vostra azienda',
  allowancesHint: 'Li riceve un solo genitore. Disattivi se li riceve l’altro genitore.',
  autoBanner: 'Calcolo automatico secondo l’età, il cantone e la legge: niente da inserire, Cantia applica i tassi giusti.',
  lawTitle: 'Oneri fissati dalla legge',
  lawFoot: 'AVS art. 5 LAVS · AD art. 3 LADI · LPP art. 8 e 16 LPP. Aggiornati ogni anno.',
  lppAge: 'LPP (2° pilastro, {{pct}} % a {{age}} anni)',
  lppNone: 'LPP (2° pilastro)',
  lppInsured: 'Assicurato·a LPP (2° pilastro)',
  lppHint: 'Obbligatoria da CHF {{threshold}} all’anno e 25 anni. Al di sotto non viene comunque dedotto nulla.',
  laaTitle: 'Assicurazione infortuni (LAINF)',
  laaFoot: 'Tassi indicativi: riprenda quelli della sua polizza LAINF.',
  cafTitle: 'Assegni familiari (cassa {{canton}})',
  cafFoot: 'Tasso della cassa cantonale 2026, fondi cantonali inclusi. La sua cassa può differire.',
  advanced: 'Adattare i tassi (avanzato)',
  advancedHint: 'Solo se ha i tassi esatti delle sue polizze. Lasci vuoto per il calcolo automatico.',
  aanp: 'INP, infortuni non prof. (dipendente) %',
  aap: 'IP, infortuni prof. (datore) %',
  ijmEmp: 'IGM malattia (dipendente) %',
  ijmEr: 'IGM malattia (datore) %',
  lppTotal: 'LPP, tasso totale della sua cassa %',
  cafEr: 'Cassa assegni familiari (datore) %',
  whtCode: 'Codice tariffa imposta alla fonte',
  whtRate: 'Aliquota imposta alla fonte %',
  whtTitle: 'Imposta alla fonte',
  whtNot: 'Non assoggettato',
  whtYes: 'Tariffa {{code}} · cantone {{canton}}',
  whtRateLine: '{{rate}} % sul salario di questo mese',
  whtMissing: 'Tariffa {{code}} ({{canton}}) non ancora importata: inserisca l’aliquota in «avanzato» nel frattempo.',
  famTitle: 'Assegni familiari',
  famNone: 'Nessun figlio: nessun assegno.',
  famOther: 'Versati all’altro genitore.',
  famAmount: 'CHF {{amount}} al mese, versati con il salario',
  chargesTitle: 'Oneri applicati',
  simTitle: 'Simulatore di salario',
  simGross: 'Salario lordo',
  simMonthly: 'Mensile',
  simYearly: 'Annuale',
  simEmployee: 'Deduzioni dipendente',
  simTotalDed: 'Totale deduzioni',
  simAllowances: 'Assegni familiari',
  simNet: 'Salario netto',
  simEmployer: 'Oneri datore di lavoro',
  simTotalEr: 'Totale oneri',
  simCost: 'Costo totale datore',
  simFoot: 'Calcolo secondo i tassi svizzeri {{year}}, l’età e la situazione. Arrotondato a 5 centesimi per riga.',
  checklistTitle: 'Da completare prima della prima busta paga',
  checklistText: 'Mancano informazioni per {{name}}. Le completi e potrà generare i suoi salari.',
  checklistCta: 'Completa',
  required: 'Richiesto',
  errorName: 'Il nome è richiesto.',
  errorSave: 'Salvataggio non riuscito. Riprovi.',
  notReady: 'La situazione non può ancora essere salvata (aggiornamento della banca dati in corso).',
};

const COPY = { fr, de, it };

export function useWizardCopy(): Copy {
  return COPY[getAppLocale()] ?? fr;
}

export function fill(text: string, vars: Record<string, string | number>): string {
  return text.replace(/\{\{(\w+)\}\}/g, (_, k) => String(vars[k] ?? ''));
}
