-- Generated by scripts/build-fiduciary-test-stubs.py

do $$ begin create role authenticated; exception when duplicate_object then null; end $$;
do $$ begin create role anon; exception when duplicate_object then null; end $$;
do $$ begin create role service_role bypassrls; exception when duplicate_object then null; end $$;
alter role service_role bypassrls;
create extension if not exists pgcrypto;
create schema if not exists extensions;
create or replace function extensions.gen_random_bytes(int) returns bytea language sql as $$ select public.gen_random_bytes($1) $$;
create schema auth;
create table auth.users (id uuid primary key, email text);
create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid', true), '')::uuid $$;
create schema storage;
create table storage.objects (id uuid primary key default gen_random_uuid(), bucket_id text, name text);
alter table storage.objects enable row level security;
create table public.plans (id text primary key, name text);
create table public.organizations (id uuid primary key default gen_random_uuid(), name text, locale text default 'fr', plan_id text);
create table public.organization_members (organization_id uuid, user_id uuid, role text, locale text, role_id uuid);
create table public.platform_permissions (user_id uuid, permission text);
create table public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid, user_id uuid, type text, title text, body text, link text, source_table text, source_id uuid);
create function public.is_org_admin(org uuid) returns boolean language sql stable security definer as $$ select exists(select 1 from public.organization_members where organization_id=org and user_id=auth.uid() and role in ('owner','admin')) $$;
create function public.is_org_member(org uuid) returns boolean language sql stable security definer as $$ select exists(select 1 from public.organization_members where organization_id=org and user_id=auth.uid()) $$;
create function public.can_view_org_finances(org uuid) returns boolean language sql stable security definer as $$ select public.is_org_admin(org) $$;
create function public.finance_member_user_ids(org uuid) returns setof uuid language sql stable security definer as $$ select user_id from public.organization_members where organization_id=org and role in ('owner','admin') $$;
create function public.can_manage_org_accounting_drafts(org uuid) returns boolean language sql stable security definer as $$ select public.is_org_admin(org) $$;
create function public.can_post_org_accounting_entries(org uuid) returns boolean language sql stable security definer as $$ select exists(select 1 from public.organization_members where organization_id=org and user_id=auth.uid() and role='owner') $$;

create table public.fiduciary_firms (
  id uuid primary key default gen_random_uuid(), name text not null, phone text, address text, postal_code text, city text,
  country text not null default 'CH', ide_number text, website text, mandates_range text, software text[] not null default '{}',
  locale text not null default 'fr', status text not null default 'ACTIVE', verified boolean not null default false,
  public_directory_visible boolean not null default false, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.fiduciary_members (firm_id uuid not null references public.fiduciary_firms(id), user_id uuid not null unique, role text not null default 'MEMBER',
  first_name text, last_name text, email text, all_clients boolean not null default true, created_at timestamptz default now(), primary key (firm_id, user_id));
create table public.fiduciary_member_clients (firm_id uuid, user_id uuid, organization_id uuid);
create table public.fiduciary_client_access (id uuid primary key default gen_random_uuid(), firm_id uuid not null, organization_id uuid not null, status text not null,
  permissions text[] not null default '{}', source text not null, requested_by uuid, approved_by uuid, revoked_by uuid,
  requested_at timestamptz default now(), approved_at timestamptz, refused_at timestamptz, revoked_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.fiduciary_audit_log (id uuid primary key default gen_random_uuid(), firm_id uuid, organization_id uuid, actor_id uuid, action text not null, details jsonb not null default '{}', created_at timestamptz not null default now());
create table public.fiduciary_email_outbox (id uuid primary key default gen_random_uuid(), kind text not null, to_email text not null, locale text not null default 'fr', payload jsonb not null default '{}', created_at timestamptz default now());
create table public.fiduciary_client_profiles (
  firm_id uuid not null, organization_id uuid not null,
  vat_method text not null default 'effective_quarterly', has_payroll boolean not null default true, legal_form text not null default 'sarl',
  fiscal_year_end text not null default '12-31', tax_return_due text not null default '03-31', assigned_to uuid, updated_by uuid, updated_at timestamptz not null default now(),
  primary key (firm_id, organization_id));
create table public.fiduciary_deadline_status (firm_id uuid, organization_id uuid, kind text, period_key text, status text, note text, updated_by uuid, updated_at timestamptz);
create table public.fiduciary_requests (id uuid primary key default gen_random_uuid(), firm_id uuid, organization_id uuid, title text, details text, due_date date,
  status text default 'open', client_message text, created_by uuid, created_at timestamptz default now(), answered_at timestamptz, closed_at timestamptz, last_reminded_at timestamptz);
create table public.fiduciary_request_files (id uuid primary key default gen_random_uuid(), request_id uuid, organization_id uuid, file_path text, file_name text, size_bytes bigint, created_at timestamptz default now());

create table public.accounting_fiscal_years (id uuid primary key default gen_random_uuid(), organization_id uuid, start_date date, end_date date, status text default 'open', locked_until_date date);
create table public.accounting_journals (id uuid primary key default gen_random_uuid(), organization_id uuid, code text, label text, is_active boolean default true);
create table public.accounting_accounts (id uuid primary key default gen_random_uuid(), organization_id uuid, code text, label text, type text, is_active boolean default true);
create table public.accounting_entries (id uuid primary key default gen_random_uuid(), organization_id uuid, fiscal_year_id uuid, journal_id uuid, entry_number int, entry_date date,
  label text, external_reference text, source text, status text default 'brouillon', created_by uuid, posted_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.accounting_entry_lines (id uuid primary key default gen_random_uuid(), entry_id uuid references public.accounting_entries(id), account_id uuid, debit numeric(12,2) default 0, credit numeric(12,2) default 0, label text, sort_order int default 0,
  check ((debit > 0 and credit = 0) or (credit > 0 and debit = 0)));
create table public.accounting_entry_sequences (fiscal_year_id uuid primary key, next_number integer not null default 1);
create table public.accounting_audit_events (id uuid primary key default gen_random_uuid(), organization_id uuid, user_id uuid, action text, entity_type text, entity_id uuid, new_values jsonb, source text);

create or replace function public.fiduciary_all_permissions()
returns text[]
language sql immutable as $$
  select array[
    'VIEW_INVOICES', 'VIEW_QUOTES', 'VIEW_CUSTOMERS', 'VIEW_PAYMENT_STATUS',
    'VIEW_ACCOUNTING_DOCUMENTS', 'DOWNLOAD_DOCUMENTS', 'VIEW_EXPORTS',
    'VIEW_WORK_HOURS', 'VIEW_PAYROLL_DATA'
  ]::text[];
$$;

create or replace function public.fiduciary_standard_permissions()
returns text[]
language sql immutable as $$
  select array[
    'VIEW_INVOICES', 'VIEW_CUSTOMERS', 'VIEW_PAYMENT_STATUS',
    'VIEW_ACCOUNTING_DOCUMENTS', 'DOWNLOAD_DOCUMENTS', 'VIEW_EXPORTS'
  ]::text[];
$$;

create or replace function public.fiduciary_clean_permissions(p_permissions text[])
returns text[]
language sql immutable as $$
  select coalesce(array_agg(distinct p order by p), '{}'::text[])
  from unnest(coalesce(p_permissions, '{}'::text[])) p
  where p = any (public.fiduciary_all_permissions());
$$;

create or replace function public.my_fiduciary_firm_id()
returns uuid
language sql stable security definer set search_path = public as $$
  select m.firm_id from public.fiduciary_members m
  join public.fiduciary_firms f on f.id = m.firm_id
  where m.user_id = auth.uid() and f.status <> 'BLOCKED';
$$;

create or replace function public.my_fiduciary_role()
returns text
language sql stable security definer set search_path = public as $$
  select m.role from public.fiduciary_members m where m.user_id = auth.uid();
$$;

create or replace function public.fiduciary_org_ids(p_permission text)
returns setof uuid
language sql stable security definer set search_path = public as $$
  select a.organization_id
  from public.fiduciary_members m
  join public.fiduciary_firms f on f.id = m.firm_id and f.status = 'ACTIVE'
  join public.fiduciary_client_access a on a.firm_id = m.firm_id and a.status = 'ACTIVE'
  where m.user_id = auth.uid()
    and (p_permission is null or p_permission = any (a.permissions))
    and (m.all_clients or exists (
      select 1 from public.fiduciary_member_clients s
      where s.firm_id = m.firm_id and s.user_id = m.user_id and s.organization_id = a.organization_id
    ));
$$;

create or replace function public.fiduciary_can(p_org uuid, p_permission text)
returns boolean
language sql stable security definer set search_path = public as $$
  select p_org in (select public.fiduciary_org_ids(p_permission));
$$;

create or replace function public.fiduciary_audit(p_firm uuid, p_org uuid, p_action text, p_details jsonb default '{}')
returns void
language sql security definer set search_path = public as $$
  insert into public.fiduciary_audit_log (firm_id, organization_id, actor_id, action, details)
  values (p_firm, p_org, auth.uid(), p_action, coalesce(p_details, '{}'));
$$;

create or replace function public.fiduciary_queue_email(p_kind text, p_to text, p_locale text, p_payload jsonb)
returns void
language sql security definer set search_path = public as $$
  insert into public.fiduciary_email_outbox (kind, to_email, locale, payload)
  select p_kind, lower(trim(p_to)), coalesce(nullif(p_locale, ''), 'fr'), coalesce(p_payload, '{}')
  where coalesce(trim(p_to), '') <> '';
$$;

create or replace function public.fiduciary_firm_admin_emails(p_firm uuid)
returns table (email text)
language sql stable security definer set search_path = public as $$
  select coalesce(m.email, u.email::text)
  from public.fiduciary_members m join auth.users u on u.id = m.user_id
  where m.firm_id = p_firm and m.role in ('OWNER', 'ADMIN');
$$;

create or replace function public.fiduciary_notify_firm(p_firm uuid, p_email_kind text, p_payload jsonb)
returns void
language plpgsql security definer set search_path = public as $$
declare
  v_locale text;
  r record;
begin
  select locale into v_locale from public.fiduciary_firms where id = p_firm;
  for r in select * from public.fiduciary_firm_admin_emails(p_firm) loop
    perform public.fiduciary_queue_email(p_email_kind, r.email, v_locale, p_payload);
  end loop;
end;
$$;

create or replace function public.acc_assert_client(p_org uuid)
returns uuid
language plpgsql stable security definer set search_path = public as $$
declare
  v_firm uuid := public.my_fiduciary_firm_id();
begin
  if v_firm is null or p_org is null or not (p_org in (select public.fiduciary_org_ids(null))) then
    raise exception 'Accès refusé';
  end if;
  return v_firm;
end;
$$;

create or replace function public.fiduciary_client_finance_people(p_org uuid)
returns table (user_id uuid, email text, locale text)
language sql stable security definer set search_path = public as $$
  select fm.user_id, u.email::text, coalesce(m.locale, o.locale, 'fr')
  from public.finance_member_user_ids(p_org) as fm(user_id)
  join auth.users u on u.id = fm.user_id
  join public.organizations o on o.id = p_org
  left join public.organization_members m on m.organization_id = p_org and m.user_id = fm.user_id;
$$;

create or replace function public.find_org_open_fiscal_year(p_organization_id uuid, p_date date)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from public.accounting_fiscal_years
  where organization_id = p_organization_id
    and p_date between start_date and end_date
    and status = 'open'
  limit 1;
$$;

create or replace function public.post_accounting_entry(p_entry_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry record;
  v_fiscal_year record;
  v_total_debit numeric(14, 2);
  v_total_credit numeric(14, 2);
  v_line_count integer;
  v_number integer;
begin
  select * into v_entry from public.accounting_entries where id = p_entry_id for update;
  if not found then
    raise exception 'Écriture introuvable';
  end if;
  if auth.uid() is not null and not public.can_post_org_accounting_entries(v_entry.organization_id) then
    raise exception 'Accès refusé : vous ne pouvez pas comptabiliser d''écritures pour cette organisation';
  end if;
  if v_entry.status not in ('brouillon', 'validee') then
    raise exception 'Cette écriture ne peut plus être comptabilisée (statut : %)', v_entry.status;
  end if;

  select count(*), coalesce(sum(debit), 0), coalesce(sum(credit), 0)
  into v_line_count, v_total_debit, v_total_credit
  from public.accounting_entry_lines where entry_id = p_entry_id;

  if v_line_count < 2 then
    raise exception 'Une pièce comptable doit contenir au moins deux lignes';
  end if;
  if v_total_debit <> v_total_credit then
    raise exception 'Écriture déséquilibrée : débit % ≠ crédit %', v_total_debit, v_total_credit;
  end if;

  select * into v_fiscal_year from public.accounting_fiscal_years where id = v_entry.fiscal_year_id for update;
  if v_fiscal_year.status <> 'open' then
    raise exception 'L''exercice comptable de cette pièce est fermé';
  end if;
  if v_fiscal_year.locked_until_date is not null and v_entry.entry_date <= v_fiscal_year.locked_until_date then
    raise exception 'La période du % est verrouillée (verrouillé jusqu''au %)', v_entry.entry_date, v_fiscal_year.locked_until_date;
  end if;

  insert into public.accounting_entry_sequences (fiscal_year_id, next_number)
  values (v_entry.fiscal_year_id, 2)
  on conflict (fiscal_year_id) do update set next_number = accounting_entry_sequences.next_number + 1
  returning next_number - 1 into v_number;

  update public.accounting_entries
  set status = 'comptabilisee', entry_number = v_number, posted_at = now(), updated_at = now()
  where id = p_entry_id;

  insert into public.accounting_audit_events (organization_id, user_id, action, entity_type, entity_id, new_values, source)
  values (v_entry.organization_id, auth.uid(), 'post', 'accounting_entry', p_entry_id, jsonb_build_object('entry_number', v_number), v_entry.source);

  return v_number;
end;
$$;
