-- Fil d'actualité (activity feed) per chantier: a WhatsApp-style stream of
-- text notes and photos posted by the team, from which reports can be
-- generated by selecting a set of entries.

create table public.feed_entries (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  type text not null check (type in ('note', 'photo')),
  body text,
  storage_path text,
  caption text,
  latitude double precision,
  longitude double precision,
  taken_at timestamptz,
  report_id uuid references public.reports(id) on delete set null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint feed_entries_content_check check (
    (type = 'note' and body is not null) or (type = 'photo' and storage_path is not null)
  )
);

create index on public.feed_entries (project_id, created_at);

alter table public.feed_entries enable row level security;

create policy "members can view feed entries" on public.feed_entries
  for select using (public.is_org_member(organization_id));
create policy "members can add feed entries" on public.feed_entries
  for insert with check (public.is_org_member(organization_id) and created_by = auth.uid());
create policy "members can update feed entries" on public.feed_entries
  for update using (public.is_org_member(organization_id));
create policy "authors and admins can delete feed entries" on public.feed_entries
  for delete using (created_by = auth.uid() or public.is_org_admin(organization_id));
