import type { PartnersLocale } from './copy';

// Texts of the signed-in partner space (partners.cantia.ch/espace).
const fr = {
  tabs: { overview: 'Vue d’ensemble', clients: 'Clients', commissions: 'Commissions', payouts: 'Versements', resources: 'Ressources', profile: 'Profil' },
  admin: 'Administration',
  kpis: { available: 'Disponible', pending: 'En validation', paid: 'Déjà versé', paying: 'Clients payants' },
  nextPayout: 'Prochain versement le {date}, dès CHF {min} disponibles.',
  nextAvailable: 'Prochaine commission disponible le {date}.',
  level: {
    title: 'Votre niveau',
    names: { MEMBER: 'Membre', CONFIRMED: 'Confirmé', PREMIUM: 'Premium' },
    progress: '{count} sur {target} clients payants pour devenir {level}',
    top: 'Vous avez atteint le niveau le plus élevé du programme.',
    benefitsTitle: 'Avantages de ce niveau',
    benefits: {
      MEMBER: ['25 % des paiements pendant 12 mois', 'Espace partenaire, lien et code QR', 'Versements mensuels dès CHF 30'],
      CONFIRMED: ['Démonstration de Cantia pour vos clients, avec l’équipe', 'Supports de présentation sur demande', 'Accès anticipé aux nouveautés'],
      PREMIUM: ['Interlocuteur dédié chez Cantia', 'Mise en avant de votre entreprise sur partners.cantia.ch', 'Rencontre annuelle avec l’équipe'],
    },
  },
  milestones: {
    title: 'Étapes',
    firstClick: 'Premier clic',
    firstSignup: 'Première inscription',
    firstPaying: 'Premier client payant',
    fivePaying: '5 clients payants',
    tenPaying: '10 clients payants',
    thousand: 'CHF 1’000 de commissions',
  },
  funnel: 'Le parcours de vos contacts',
  activity: 'Activité récente',
  noActivity: 'Pas encore de commission. Elles apparaissent ici dès le premier paiement d’un client recommandé.',
  seeAll: 'Tout voir',
  commissions: {
    title: 'Commissions',
    intro: '25 % du montant payé hors TVA, pendant 12 mois pour chaque client. Une commission devient disponible 30 jours après le paiement.',
    date: 'Paiement',
    client: 'Client',
    base: 'Montant payé',
    amount: 'Commission',
    status: 'Statut',
    empty: 'Aucune commission pour l’instant.',
    adjustment: 'Correction (remboursement)',
    availableOn: 'disponible le {date}',
    statuses: { PENDING: 'En validation', AVAILABLE: 'Disponible', PAID: 'Versée', CANCELLED: 'Annulée' },
    billing: { monthly: 'mensuel', yearly: 'annuel' },
  },
  payouts: {
    title: 'Versements',
    intro: 'Les commissions disponibles sont versées une fois par mois, vers le {day}, dès CHF {min}.',
    empty: 'Aucun versement pour l’instant.',
    period: 'Mois',
    amount: 'Montant',
    count: 'Commissions',
    reference: 'Référence',
    status: 'Statut',
    statuses: { TO_PAY: 'En cours', PAID: 'Versé', CANCELLED: 'Annulé' },
  },
  resources: {
    title: 'Ressources',
    campaignTitle: 'Liens de campagne',
    campaignText: 'Ajoutez un nom de campagne pour savoir d’où viennent vos visiteurs : newsletter, salon, site web, signature d’e-mail.',
    campaignPlaceholder: 'par ex. newsletter-octobre',
    copy: 'Copier',
    copied: 'Copié',
  },
  profile: {
    title: 'Profil',
    name: 'Nom',
    company: 'Entreprise',
    type: 'Activité',
    email: 'E-mail',
    since: 'Partenaire depuis',
    contact: 'Pour modifier ces informations ou pour toute question, écrivez-nous à info@cantia.ch.',
  },
};

type AppCopy = typeof fr;

const de: AppCopy = {
  tabs: { overview: 'Übersicht', clients: 'Kunden', commissions: 'Provisionen', payouts: 'Auszahlungen', resources: 'Ressourcen', profile: 'Profil' },
  admin: 'Administration',
  kpis: { available: 'Verfügbar', pending: 'In Bestätigung', paid: 'Bereits ausbezahlt', paying: 'Zahlende Kunden' },
  nextPayout: 'Nächste Auszahlung am {date}, ab CHF {min} verfügbar.',
  nextAvailable: 'Nächste Provision verfügbar am {date}.',
  level: {
    title: 'Ihre Stufe',
    names: { MEMBER: 'Mitglied', CONFIRMED: 'Bestätigt', PREMIUM: 'Premium' },
    progress: '{count} von {target} zahlenden Kunden bis zur Stufe {level}',
    top: 'Sie haben die höchste Stufe des Programms erreicht.',
    benefitsTitle: 'Vorteile dieser Stufe',
    benefits: {
      MEMBER: ['25 % der Zahlungen während 12 Monaten', 'Partnerbereich, Link und QR-Code', 'Monatliche Auszahlungen ab CHF 30'],
      CONFIRMED: ['Cantia-Demo für Ihre Kunden, mit dem Team', 'Präsentationsunterlagen auf Anfrage', 'Früher Zugang zu Neuheiten'],
      PREMIUM: ['Persönliche Ansprechperson bei Cantia', 'Präsentation Ihres Unternehmens auf partners.cantia.ch', 'Jährliches Treffen mit dem Team'],
    },
  },
  milestones: {
    title: 'Etappen',
    firstClick: 'Erster Klick',
    firstSignup: 'Erste Registrierung',
    firstPaying: 'Erster zahlender Kunde',
    fivePaying: '5 zahlende Kunden',
    tenPaying: '10 zahlende Kunden',
    thousand: 'CHF 1’000 Provisionen',
  },
  funnel: 'Der Weg Ihrer Kontakte',
  activity: 'Letzte Aktivität',
  noActivity: 'Noch keine Provision. Sie erscheinen hier ab der ersten Zahlung eines empfohlenen Kunden.',
  seeAll: 'Alle anzeigen',
  commissions: {
    title: 'Provisionen',
    intro: '25 % des bezahlten Betrags ohne MWST, während 12 Monaten pro Kunde. Eine Provision wird 30 Tage nach der Zahlung verfügbar.',
    date: 'Zahlung',
    client: 'Kunde',
    base: 'Bezahlter Betrag',
    amount: 'Provision',
    status: 'Status',
    empty: 'Noch keine Provision.',
    adjustment: 'Korrektur (Rückerstattung)',
    availableOn: 'verfügbar am {date}',
    statuses: { PENDING: 'In Bestätigung', AVAILABLE: 'Verfügbar', PAID: 'Ausbezahlt', CANCELLED: 'Storniert' },
    billing: { monthly: 'monatlich', yearly: 'jährlich' },
  },
  payouts: {
    title: 'Auszahlungen',
    intro: 'Verfügbare Provisionen werden einmal pro Monat, um den {day}., ab CHF {min} ausbezahlt.',
    empty: 'Noch keine Auszahlung.',
    period: 'Monat',
    amount: 'Betrag',
    count: 'Provisionen',
    reference: 'Referenz',
    status: 'Status',
    statuses: { TO_PAY: 'In Bearbeitung', PAID: 'Ausbezahlt', CANCELLED: 'Storniert' },
  },
  resources: {
    title: 'Ressourcen',
    campaignTitle: 'Kampagnenlinks',
    campaignText: 'Fügen Sie einen Kampagnennamen hinzu, um zu sehen, woher Ihre Besucher kommen: Newsletter, Messe, Website, E-Mail-Signatur.',
    campaignPlaceholder: 'z. B. newsletter-oktober',
    copy: 'Kopieren',
    copied: 'Kopiert',
  },
  profile: {
    title: 'Profil',
    name: 'Name',
    company: 'Unternehmen',
    type: 'Tätigkeit',
    email: 'E-Mail',
    since: 'Partner seit',
    contact: 'Um diese Angaben zu ändern oder bei Fragen schreiben Sie uns an info@cantia.ch.',
  },
};

const it: AppCopy = {
  tabs: { overview: 'Panoramica', clients: 'Clienti', commissions: 'Commissioni', payouts: 'Versamenti', resources: 'Risorse', profile: 'Profilo' },
  admin: 'Amministrazione',
  kpis: { available: 'Disponibile', pending: 'In convalida', paid: 'Già versato', paying: 'Clienti paganti' },
  nextPayout: 'Prossimo versamento il {date}, da CHF {min} disponibili.',
  nextAvailable: 'Prossima commissione disponibile il {date}.',
  level: {
    title: 'Il suo livello',
    names: { MEMBER: 'Membro', CONFIRMED: 'Confermato', PREMIUM: 'Premium' },
    progress: '{count} su {target} clienti paganti per diventare {level}',
    top: 'Ha raggiunto il livello più alto del programma.',
    benefitsTitle: 'Vantaggi di questo livello',
    benefits: {
      MEMBER: ['25 % dei pagamenti per 12 mesi', 'Spazio partner, link e codice QR', 'Versamenti mensili da CHF 30'],
      CONFIRMED: ['Dimostrazione di Cantia per i suoi clienti, con il team', 'Materiale di presentazione su richiesta', 'Accesso anticipato alle novità'],
      PREMIUM: ['Interlocutore dedicato presso Cantia', 'Presentazione della sua impresa su partners.cantia.ch', 'Incontro annuale con il team'],
    },
  },
  milestones: {
    title: 'Tappe',
    firstClick: 'Primo clic',
    firstSignup: 'Prima iscrizione',
    firstPaying: 'Primo cliente pagante',
    fivePaying: '5 clienti paganti',
    tenPaying: '10 clienti paganti',
    thousand: 'CHF 1’000 di commissioni',
  },
  funnel: 'Il percorso dei suoi contatti',
  activity: 'Attività recente',
  noActivity: 'Ancora nessuna commissione. Appaiono qui dal primo pagamento di un cliente raccomandato.',
  seeAll: 'Vedi tutto',
  commissions: {
    title: 'Commissioni',
    intro: 'Il 25 % dell’importo pagato IVA esclusa, per 12 mesi per ogni cliente. Una commissione diventa disponibile 30 giorni dopo il pagamento.',
    date: 'Pagamento',
    client: 'Cliente',
    base: 'Importo pagato',
    amount: 'Commissione',
    status: 'Stato',
    empty: 'Ancora nessuna commissione.',
    adjustment: 'Correzione (rimborso)',
    availableOn: 'disponibile il {date}',
    statuses: { PENDING: 'In convalida', AVAILABLE: 'Disponibile', PAID: 'Versata', CANCELLED: 'Annullata' },
    billing: { monthly: 'mensile', yearly: 'annuale' },
  },
  payouts: {
    title: 'Versamenti',
    intro: 'Le commissioni disponibili sono versate una volta al mese, verso il {day}, da CHF {min}.',
    empty: 'Ancora nessun versamento.',
    period: 'Mese',
    amount: 'Importo',
    count: 'Commissioni',
    reference: 'Riferimento',
    status: 'Stato',
    statuses: { TO_PAY: 'In corso', PAID: 'Versato', CANCELLED: 'Annullato' },
  },
  resources: {
    title: 'Risorse',
    campaignTitle: 'Link di campagna',
    campaignText: 'Aggiunga un nome di campagna per sapere da dove arrivano i visitatori: newsletter, fiera, sito web, firma e-mail.',
    campaignPlaceholder: 'es. newsletter-ottobre',
    copy: 'Copia',
    copied: 'Copiato',
  },
  profile: {
    title: 'Profilo',
    name: 'Nome',
    company: 'Impresa',
    type: 'Attività',
    email: 'E-mail',
    since: 'Partner dal',
    contact: 'Per modificare queste informazioni o per qualsiasi domanda, ci scriva a info@cantia.ch.',
  },
};

export const PARTNERS_APP_COPY: Record<PartnersLocale, AppCopy> = { fr, de, it };
