// Every string of partners.cantia.ch, in the three languages of the site.
// Kept apart from lib/translations: the partners build doesn't load the app's
// i18n and these texts only exist here.
export type PartnersLocale = 'fr' | 'de' | 'it';
export const PARTNERS_LOCALES: PartnersLocale[] = ['fr', 'de', 'it'];

export const PARTNER_TYPES = ['CONSULTANT', 'WEB_AGENCY', 'SOFTWARE_INTEGRATOR', 'CANTIA_CUSTOMER', 'BUSINESS', 'CONTENT_CREATOR', 'OTHER'] as const;
export type PartnerType = (typeof PARTNER_TYPES)[number];

const fr = {
  brand: 'Cantia Partners',
  nav: { login: 'Se connecter', join: 'Devenir partenaire', space: 'Mon espace' },
  hero: {
    eyebrow: 'Cantia Partners',
    title: 'Construisons\nla suite ensemble.',
    text: 'Le programme partenaire de Cantia réunit les fiduciaires, conseillers, bureaux techniques et fournisseurs qui accompagnent les entreprises suisses du bâtiment. Vous recommandez un outil en lequel vous croyez, nous construisons avec vous une relation durable.',
    cta: 'Devenir partenaire',
    secondary: 'Découvrir le programme',
    note: 'Programme ouvert aux professionnels en Suisse. Sans frais, sans engagement.',
  },
  pillars: {
    title: 'Un partenariat, pas un simple lien',
    intro: 'Nous choisissons nos partenaires comme nos clients : pour travailler ensemble dans la durée.',
    items: [
      { title: 'Une relation qui dure', text: 'Vous restez l’interlocuteur de confiance de vos clients. Cantia s’occupe du logiciel, de l’accompagnement et du support, vous gardez la relation.' },
      { title: 'Une rémunération claire', text: 'Des conditions définies avec vous, un suivi transparent et des versements mensuels.' },
      { title: 'La famille Cantia', text: 'Un contact direct avec l’équipe, vos retours pris en compte dans le produit et les nouveautés présentées en avant-première.' },
    ],
  },
  profiles: {
    title: 'Avec qui nous travaillons',
    items: [
      { title: 'Fiduciaires et conseillers', text: 'Des clients mieux organisés, des factures QR propres et des chiffres fiables à la clôture.' },
      { title: 'Architectes et bureaux techniques', text: 'Des entreprises partenaires qui livrent des devis clairs et des rapports de chantier à jour.' },
      { title: 'Fournisseurs et négoces', text: 'Un service de plus pour vos clients artisans, au-delà du matériau.' },
      { title: 'Intégrateurs et agences', text: 'Une solution suisse à proposer lors de la digitalisation d’une PME du bâtiment.' },
    ],
  },
  example: {
    title: 'Un exemple concret',
    line: '4 entreprises au plan Équipe (CHF 79 / mois)',
    calc: 'CHF 79 × 4 × 25\u00a0%',
    monthly: 'CHF 79 par mois pour vous',
    yearly: 'soit CHF 948 sur 12 mois',
    footnote: 'Commission calculée sur les montants réellement encaissés, hors TVA.',
  },
  steps: {
    title: 'Comment ça marche',
    items: [
      { title: 'Inscrivez-vous', text: 'Créez votre compte partenaire en deux minutes. Vous recevez un lien personnel et son code QR.' },
      { title: 'Recommandez', text: 'Vos contacts découvrent Cantia par votre lien. Leur inscription vous est rattachée pendant 90 jours après le clic.' },
      { title: 'Soyez payé', text: 'Selon les conditions convenues avec vous. Chaque commission est validée après 30 jours puis versée sur votre IBAN.' },
    ],
  },
  who: {
    title: 'Pour qui ?',
    items: [
      'Fiduciaires et consultants PME',
      'Architectes et bureaux techniques',
      'Fournisseurs et négoces de matériaux',
      'Agences web et intégrateurs',
      'Clients Cantia satisfaits',
      'Créateurs de contenu du bâtiment',
    ],
  },
  rules: {
    title: 'Les règles, simplement',
    items: [
      { q: 'Quand suis-je payé ?', a: 'Une fois par mois, vers le 5, par virement bancaire, dès que vous avez au moins CHF 30 de commissions disponibles. En dessous, le montant est reporté au mois suivant.' },
      { q: 'Pourquoi 30 jours d’attente ?', a: 'Une commission devient disponible 30 jours après le paiement du client. Si le paiement est remboursé ou contesté entre-temps, la commission est annulée.' },
      { q: 'Qu’est-ce que je vois de mes clients ?', a: 'Une référence anonyme (CNT-…), le plan, le statut et vos commissions. Jamais leurs données, leurs devis ou leurs chantiers.' },
      { q: 'Dois-je faire une facture ?', a: 'Non. Cantia vous envoie un relevé à chaque versement. Les commissions sont un revenu que vous déclarez vous-même.' },
      { q: 'Puis-je utiliser mon propre lien ?', a: 'Non, les auto-recommandations ne donnent pas droit à une commission. Le premier lien cliqué compte.' },
      { q: 'J’ai déjà un compte Cantia.', a: 'Connectez-vous avec les mêmes identifiants : votre espace partenaire s’ajoute à votre compte.' },
    ],
  },
  finalCta: { title: 'Rejoignez le réseau Cantia.', text: 'Parlons de vos clients et de la manière dont nous pouvons les accompagner ensemble.', cta: 'Devenir partenaire' },
  preview: {
    label: 'Aperçu de votre espace',
    example: 'Exemple',
    link: 'cantia.ch/?ref=K7M2QX',
    stats: ['Clics', 'Inscriptions', 'Clients payants'],
    rows: [
      { ref: 'CNT-1042', plan: 'Équipe', amount: '+ CHF 19.75' },
      { ref: 'CNT-1038', plan: 'Entreprise', amount: '+ CHF 32.25' },
      { ref: 'CNT-1031', plan: 'Essentiel', amount: '+ CHF 9.75' },
    ],
    available: 'Disponible le 5 novembre',
  },
  figures: [
    { value: '25\u00a0%', label: 'de chaque paiement' },
    { value: '12 mois', label: 'par client recommandé' },
    { value: '90 jours', label: 'pour que le clic compte' },
    { value: 'CHF 30', label: 'dès le premier versement' },
  ],
  simulator: {
    title: 'Rémunération',
    text: 'Une estimation selon le nombre d’entreprises que vous accompagnez vers Cantia.',
    perMonth: 'CHF {price} / mois',
    monthly: 'par mois',
    yearly: 'sur 12 mois',
    total: 'Estimation de vos commissions',
    note: 'Calcul sur les abonnements mensuels, hors TVA. Pour un abonnement annuel, vous touchez 25\u00a0% du montant payé.',
  },
  product: {
    title: 'Un logiciel facile à recommander',
    text: 'Cantia est fait en Suisse pour les entreprises du bâtiment : vos contacts gagnent du temps dès la première semaine.',
    items: [
      { title: 'Devis et factures QR', text: 'Un devis propre en quelques minutes, signé en ligne, converti en facture QR.' },
      { title: 'Rapports depuis le chantier', text: 'Photos, heures et dictée vocale depuis le téléphone, le rapport part tout seul.' },
      { title: 'Planning, heures, salaires', text: 'Toute l’équipe au même endroit, jusqu’aux fiches de salaire.' },
      { title: 'Hébergé en Suisse', text: 'Données à Zurich, en français, allemand et italien, 14 jours d’essai gratuits.' },
    ],
    cta: 'Découvrir Cantia',
  },
  footer: { tagline: 'Le programme partenaire de Cantia, logiciel suisse de gestion de chantier.', site: 'cantia.ch', privacy: 'Confidentialité', terms: 'Conditions', status: 'Statut du service' },
  auth: {
    sideTitle: 'Construisons la suite ensemble.',
    sideText: 'Recommandez un logiciel suisse en lequel vous croyez, et suivez vos clients depuis votre espace partenaire.',
    google: 'Continuer avec Google',
    or: 'ou',
    loginTitle: 'Connexion',
    signupTitle: 'Créer un compte partenaire',
    sameAccount: 'Vous avez déjà un compte Cantia ? Utilisez les mêmes identifiants.',
    firstName: 'Prénom',
    lastName: 'Nom',
    email: 'E-mail',
    password: 'Mot de passe',
    passwordHint: 'Au moins 8 caractères',
    login: 'Se connecter',
    signup: 'Créer mon compte',
    toSignup: 'Pas encore de compte ? Créer un compte',
    toLogin: 'Déjà un compte ? Se connecter',
    forgot: 'Mot de passe oublié ?',
    codeTitle: 'Vérifiez votre e-mail',
    codeText: 'Saisissez le code reçu à l’adresse {email}.',
    code: 'Code',
    verify: 'Valider',
    resend: 'Renvoyer le code',
    resent: 'Code renvoyé.',
    missing: 'Remplissez tous les champs.',
    shortPassword: 'Le mot de passe doit contenir au moins 8 caractères.',
    back: 'Retour',
  },
  onboarding: {
    title: 'Votre profil partenaire',
    text: 'Ces informations servent à vos versements et à vos relevés. Elles ne sont jamais montrées à vos clients.',
    company: 'Entreprise (facultatif)',
    type: 'Vous êtes',
    phone: 'Téléphone (facultatif)',
    address: 'Adresse',
    postalCode: 'NPA',
    city: 'Localité',
    accept: 'J’accepte les conditions du programme : commission personnelle convenue avec Cantia, validation après 30 jours, versement dès CHF 30, pas d’auto-recommandation.',
    submit: 'Activer mon espace partenaire',
    mustAccept: 'Veuillez accepter les conditions du programme.',
  },
  types: {
    CONSULTANT: 'Fiduciaire / consultant',
    WEB_AGENCY: 'Agence web',
    SOFTWARE_INTEGRATOR: 'Intégrateur logiciel',
    CANTIA_CUSTOMER: 'Client Cantia',
    BUSINESS: 'Entreprise / fournisseur',
    CONTENT_CREATOR: 'Créateur de contenu',
    OTHER: 'Autre',
  } as Record<PartnerType, string>,
  dashboard: {
    hello: 'Bonjour {name}',
    signOut: 'Se déconnecter',
    linkTitle: 'Votre lien de recommandation',
    linkText: 'Partagez-le par e-mail, sur votre site ou vos réseaux. Toute inscription dans les 90 jours suivant le clic vous est rattachée.',
    copy: 'Copier le lien',
    copied: 'Lien copié',
    code: 'Code',
    qr: 'Code QR à imprimer ou montrer',
    stats: { clicks: 'Clics', visitors: 'Visiteurs uniques', signups: 'Inscriptions', trials: 'En essai', active: 'Clients payants' },
    commissions: 'Commissions',
    pending: 'En validation',
    available: 'Disponible',
    paid: 'Versé',
    commissionsSoon: 'Chaque paiement de vos clients apparaîtra ici avec sa date de disponibilité. Les commissions sont calculées depuis le premier paiement, même avant leur affichage.',
    referrals: 'Vos recommandations',
    noReferrals: 'Aucune inscription pour l’instant. Partagez votre lien pour commencer.',
    ref: 'Référence',
    since: 'Inscrit le',
    plan: 'Plan',
    status: 'Statut',
    statuses: { SIGNED_UP: 'Inscrit', TRIAL: 'En essai', ACTIVE: 'Client payant', CANCELLED: 'Résilié' } as Record<string, string>,
    suspended: 'Votre compte partenaire est suspendu. Votre lien ne rattache plus de nouvelles inscriptions. Contactez-nous pour en savoir plus.',
    payout: 'Coordonnées de paiement',
    payoutText: 'Les versements se font par virement sur un compte suisse ou liechtensteinois.',
    holder: 'Titulaire du compte',
    iban: 'IBAN',
    saveIban: 'Enregistrer',
    changeIban: 'Modifier',
    ibanSaved: 'Coordonnées enregistrées.',
    noIban: 'Ajoutez votre IBAN pour recevoir vos versements.',
    share: {
      title: 'Kit de partage',
      text: 'Un message prêt à envoyer à vos contacts, par e-mail ou WhatsApp.',
      message: 'Bonjour,\n\nJ’utilise et recommande Cantia, un logiciel suisse pour les entreprises du bâtiment : devis, factures QR, rapports de chantier, planning et salaires au même endroit. Vous pouvez l’essayer gratuitement pendant 14 jours :\n{link}\n\nBelle journée,',
      copy: 'Copier le message',
      copied: 'Message copié',
      downloadQr: 'Télécharger le QR (PNG)',
    },
    memberSince: 'Partenaire depuis le {date}',
    active: 'Actif',
    rules: 'Règles du programme',
  },
  loading: 'Chargement…',
};

type Copy = typeof fr;

const de: Copy = {
  brand: 'Cantia Partners',
  nav: { login: 'Anmelden', join: 'Partner werden', space: 'Mein Bereich' },
  hero: {
    eyebrow: 'Cantia Partners',
    title: 'Bauen wir\ndie Zukunft gemeinsam.',
    text: 'Das Partnerprogramm von Cantia vereint Treuhänder, Berater, Ingenieurbüros und Lieferanten, die Schweizer Bauunternehmen begleiten. Sie empfehlen ein Werkzeug, von dem Sie überzeugt sind, wir bauen mit Ihnen eine langfristige Beziehung auf.',
    cta: 'Partner werden',
    secondary: 'Das Programm entdecken',
    note: 'Programm für Fachleute in der Schweiz. Kostenlos und unverbindlich.',
  },
  pillars: {
    title: 'Eine Partnerschaft, kein blosser Link',
    intro: 'Wir wählen unsere Partner wie unsere Kunden: um langfristig zusammenzuarbeiten.',
    items: [
      { title: 'Eine Beziehung, die hält', text: 'Sie bleiben die Vertrauensperson Ihrer Kunden. Cantia kümmert sich um Software, Begleitung und Support, die Beziehung bleibt bei Ihnen.' },
      { title: 'Eine klare Vergütung', text: 'Mit Ihnen vereinbarte Konditionen, transparente Übersicht und monatliche Auszahlungen.' },
      { title: 'Die Cantia-Familie', text: 'Direkter Kontakt zum Team, Ihr Feedback fliesst ins Produkt ein und Neuheiten sehen Sie zuerst.' },
    ],
  },
  profiles: {
    title: 'Mit wem wir arbeiten',
    items: [
      { title: 'Treuhänder und Berater', text: 'Besser organisierte Kunden, saubere QR-Rechnungen und verlässliche Zahlen beim Abschluss.' },
      { title: 'Architekten und Ingenieurbüros', text: 'Partnerunternehmen, die klare Offerten und aktuelle Baustellenrapporte liefern.' },
      { title: 'Lieferanten und Händler', text: 'Ein zusätzlicher Service für Ihre Handwerkskunden, über das Material hinaus.' },
      { title: 'Integratoren und Agenturen', text: 'Eine Schweizer Lösung für die Digitalisierung eines Bau-KMU.' },
    ],
  },
  example: {
    title: 'Ein konkretes Beispiel',
    line: '4 Unternehmen im Plan Team (CHF 79 / Monat)',
    calc: 'CHF 79 × 4 × 25\u00a0%',
    monthly: 'CHF 79 pro Monat für Sie',
    yearly: 'also CHF 948 in 12 Monaten',
    footnote: 'Provision auf den tatsächlich bezahlten Beträgen, ohne MWST.',
  },
  steps: {
    title: 'So funktioniert es',
    items: [
      { title: 'Registrieren', text: 'Erstellen Sie Ihr Partnerkonto in zwei Minuten. Sie erhalten einen persönlichen Link und seinen QR-Code.' },
      { title: 'Empfehlen', text: 'Ihre Kontakte entdecken Cantia über Ihren Link. Ihre Registrierung wird Ihnen während 90 Tagen nach dem Klick zugeordnet.' },
      { title: 'Bezahlt werden', text: 'Gemäss den mit Ihnen vereinbarten Konditionen. Jede Provision wird nach 30 Tagen bestätigt und dann auf Ihr IBAN überwiesen.' },
    ],
  },
  who: {
    title: 'Für wen?',
    items: [
      'Treuhänder und KMU-Berater',
      'Architekten und Ingenieurbüros',
      'Lieferanten und Baustoffhändler',
      'Webagenturen und Integratoren',
      'Zufriedene Cantia-Kunden',
      'Content Creator aus dem Bau',
    ],
  },
  rules: {
    title: 'Die Regeln, ganz einfach',
    items: [
      { q: 'Wann werde ich bezahlt?', a: 'Einmal pro Monat, um den 5., per Banküberweisung, sobald mindestens CHF 30 an Provisionen verfügbar sind. Darunter wird der Betrag auf den nächsten Monat übertragen.' },
      { q: 'Warum 30 Tage Wartezeit?', a: 'Eine Provision wird 30 Tage nach der Zahlung des Kunden verfügbar. Wird die Zahlung in der Zwischenzeit zurückerstattet oder angefochten, entfällt die Provision.' },
      { q: 'Was sehe ich von meinen Kunden?', a: 'Eine anonyme Referenz (CNT-…), den Plan, den Status und Ihre Provisionen. Nie ihre Daten, Offerten oder Baustellen.' },
      { q: 'Muss ich eine Rechnung stellen?', a: 'Nein. Cantia sendet Ihnen bei jeder Auszahlung eine Abrechnung. Die Provisionen sind ein Einkommen, das Sie selbst deklarieren.' },
      { q: 'Kann ich meinen eigenen Link nutzen?', a: 'Nein, Selbstempfehlungen geben keinen Anspruch auf Provision. Es zählt der erste angeklickte Link.' },
      { q: 'Ich habe bereits ein Cantia-Konto.', a: 'Melden Sie sich mit denselben Zugangsdaten an: Ihr Partnerbereich wird Ihrem Konto hinzugefügt.' },
    ],
  },
  finalCta: { title: 'Werden Sie Teil des Cantia-Netzwerks.', text: 'Sprechen wir über Ihre Kunden und darüber, wie wir sie gemeinsam begleiten können.', cta: 'Partner werden' },
  preview: {
    label: 'Vorschau Ihres Bereichs',
    example: 'Beispiel',
    link: 'cantia.ch/?ref=K7M2QX',
    stats: ['Klicks', 'Registrierungen', 'Zahlende Kunden'],
    rows: [
      { ref: 'CNT-1042', plan: 'Team', amount: '+ CHF 19.75' },
      { ref: 'CNT-1038', plan: 'Entreprise', amount: '+ CHF 32.25' },
      { ref: 'CNT-1031', plan: 'Basis', amount: '+ CHF 9.75' },
    ],
    available: 'Verfügbar am 5. November',
  },
  figures: [
    { value: '25\u00a0%', label: 'jeder Zahlung' },
    { value: '12 Monate', label: 'pro empfohlenem Kunden' },
    { value: '90 Tage', label: 'damit der Klick zählt' },
    { value: 'CHF 30', label: 'ab der ersten Auszahlung' },
  ],
  simulator: {
    title: 'Vergütung',
    text: 'Eine Schätzung je nach Anzahl Unternehmen, die Sie zu Cantia begleiten.',
    perMonth: 'CHF {price} / Monat',
    monthly: 'pro Monat',
    yearly: 'in 12 Monaten',
    total: 'Geschätzte Provisionen',
    note: 'Berechnet auf Monatsabonnements, ohne MWST. Bei einem Jahresabonnement erhalten Sie 25\u00a0% des bezahlten Betrags.',
  },
  product: {
    title: 'Eine Software, die man gern empfiehlt',
    text: 'Cantia ist in der Schweiz für Bauunternehmen gemacht: Ihre Kontakte sparen ab der ersten Woche Zeit.',
    items: [
      { title: 'Offerten und QR-Rechnungen', text: 'Eine saubere Offerte in wenigen Minuten, online unterschrieben, in eine QR-Rechnung umgewandelt.' },
      { title: 'Rapporte von der Baustelle', text: 'Fotos, Stunden und Sprachdiktat vom Telefon aus, der Rapport geht von selbst.' },
      { title: 'Planung, Stunden, Löhne', text: 'Das ganze Team an einem Ort, bis zur Lohnabrechnung.' },
      { title: 'In der Schweiz gehostet', text: 'Daten in Zürich, auf Deutsch, Französisch und Italienisch, 14 Tage gratis testen.' },
    ],
    cta: 'Cantia entdecken',
  },
  footer: { tagline: 'Das Partnerprogramm von Cantia, der Schweizer Software für Baustellenverwaltung.', site: 'cantia.ch', privacy: 'Datenschutz', terms: 'AGB', status: 'Systemstatus' },
  auth: {
    sideTitle: 'Bauen wir die Zukunft gemeinsam.',
    sideText: 'Empfehlen Sie eine Schweizer Software, von der Sie überzeugt sind, und verfolgen Sie Ihre Kunden in Ihrem Partnerbereich.',
    google: 'Weiter mit Google',
    or: 'oder',
    loginTitle: 'Anmelden',
    signupTitle: 'Partnerkonto erstellen',
    sameAccount: 'Sie haben bereits ein Cantia-Konto? Verwenden Sie dieselben Zugangsdaten.',
    firstName: 'Vorname',
    lastName: 'Nachname',
    email: 'E-Mail',
    password: 'Passwort',
    passwordHint: 'Mindestens 8 Zeichen',
    login: 'Anmelden',
    signup: 'Konto erstellen',
    toSignup: 'Noch kein Konto? Konto erstellen',
    toLogin: 'Bereits ein Konto? Anmelden',
    forgot: 'Passwort vergessen?',
    codeTitle: 'Bestätigen Sie Ihre E-Mail',
    codeText: 'Geben Sie den an {email} gesendeten Code ein.',
    code: 'Code',
    verify: 'Bestätigen',
    resend: 'Code erneut senden',
    resent: 'Code erneut gesendet.',
    missing: 'Bitte füllen Sie alle Felder aus.',
    shortPassword: 'Das Passwort muss mindestens 8 Zeichen enthalten.',
    back: 'Zurück',
  },
  onboarding: {
    title: 'Ihr Partnerprofil',
    text: 'Diese Angaben dienen Ihren Auszahlungen und Abrechnungen. Sie werden Ihren Kunden nie gezeigt.',
    company: 'Unternehmen (optional)',
    type: 'Sie sind',
    phone: 'Telefon (optional)',
    address: 'Adresse',
    postalCode: 'PLZ',
    city: 'Ort',
    accept: 'Ich akzeptiere die Programmbedingungen: persönliche, mit Cantia vereinbarte Provision, Bestätigung nach 30 Tagen, Auszahlung ab CHF 30, keine Selbstempfehlung.',
    submit: 'Partnerbereich aktivieren',
    mustAccept: 'Bitte akzeptieren Sie die Programmbedingungen.',
  },
  types: {
    CONSULTANT: 'Treuhänder / Berater',
    WEB_AGENCY: 'Webagentur',
    SOFTWARE_INTEGRATOR: 'Software-Integrator',
    CANTIA_CUSTOMER: 'Cantia-Kunde',
    BUSINESS: 'Unternehmen / Lieferant',
    CONTENT_CREATOR: 'Content Creator',
    OTHER: 'Andere',
  },
  dashboard: {
    hello: 'Guten Tag {name}',
    signOut: 'Abmelden',
    linkTitle: 'Ihr Empfehlungslink',
    linkText: 'Teilen Sie ihn per E-Mail, auf Ihrer Website oder in sozialen Netzwerken. Jede Registrierung innerhalb von 90 Tagen nach dem Klick wird Ihnen zugeordnet.',
    copy: 'Link kopieren',
    copied: 'Link kopiert',
    code: 'Code',
    qr: 'QR-Code zum Drucken oder Zeigen',
    stats: { clicks: 'Klicks', visitors: 'Einzelne Besucher', signups: 'Registrierungen', trials: 'Im Test', active: 'Zahlende Kunden' },
    commissions: 'Provisionen',
    pending: 'In Bestätigung',
    available: 'Verfügbar',
    paid: 'Ausbezahlt',
    commissionsSoon: 'Jede Zahlung Ihrer Kunden erscheint hier mit ihrem Verfügbarkeitsdatum. Die Provisionen werden ab der ersten Zahlung berechnet, auch vor ihrer Anzeige.',
    referrals: 'Ihre Empfehlungen',
    noReferrals: 'Noch keine Registrierung. Teilen Sie Ihren Link, um zu beginnen.',
    ref: 'Referenz',
    since: 'Registriert am',
    plan: 'Plan',
    status: 'Status',
    statuses: { SIGNED_UP: 'Registriert', TRIAL: 'Im Test', ACTIVE: 'Zahlender Kunde', CANCELLED: 'Gekündigt' },
    suspended: 'Ihr Partnerkonto ist gesperrt. Ihr Link ordnet keine neuen Registrierungen mehr zu. Kontaktieren Sie uns für mehr Informationen.',
    payout: 'Zahlungsangaben',
    payoutText: 'Die Auszahlungen erfolgen per Überweisung auf ein Schweizer oder Liechtensteiner Konto.',
    holder: 'Kontoinhaber',
    iban: 'IBAN',
    saveIban: 'Speichern',
    changeIban: 'Ändern',
    ibanSaved: 'Angaben gespeichert.',
    noIban: 'Fügen Sie Ihr IBAN hinzu, um Ihre Auszahlungen zu erhalten.',
    share: {
      title: 'Teilen-Kit',
      text: 'Eine fertige Nachricht für Ihre Kontakte, per E-Mail oder WhatsApp.',
      message: 'Guten Tag\n\nIch nutze und empfehle Cantia, eine Schweizer Software für Bauunternehmen: Offerten, QR-Rechnungen, Baustellenrapporte, Planung und Löhne an einem Ort. Sie können sie 14 Tage kostenlos testen:\n{link}\n\nFreundliche Grüsse',
      copy: 'Nachricht kopieren',
      copied: 'Nachricht kopiert',
      downloadQr: 'QR-Code herunterladen (PNG)',
    },
    memberSince: 'Partner seit {date}',
    active: 'Aktiv',
    rules: 'Programmregeln',
  },
  loading: 'Wird geladen…',
};

const it: Copy = {
  brand: 'Cantia Partners',
  nav: { login: 'Accedi', join: 'Diventa partner', space: 'Il mio spazio' },
  hero: {
    eyebrow: 'Cantia Partners',
    title: 'Costruiamo\nil futuro insieme.',
    text: 'Il programma partner di Cantia riunisce fiduciarie, consulenti, studi tecnici e fornitori che accompagnano le imprese edili svizzere. Lei raccomanda uno strumento in cui crede, noi costruiamo con lei una relazione duratura.',
    cta: 'Diventa partner',
    secondary: 'Scopri il programma',
    note: 'Programma aperto ai professionisti in Svizzera. Senza costi, senza impegno.',
  },
  pillars: {
    title: 'Una partnership, non un semplice link',
    intro: 'Scegliamo i nostri partner come i nostri clienti: per lavorare insieme a lungo.',
    items: [
      { title: 'Una relazione che dura', text: 'Lei resta l’interlocutore di fiducia dei suoi clienti. Cantia si occupa del software, dell’accompagnamento e del supporto, la relazione resta sua.' },
      { title: 'Una remunerazione chiara', text: 'Condizioni definite con lei, monitoraggio trasparente e versamenti mensili.' },
      { title: 'La famiglia Cantia', text: 'Un contatto diretto con il team, i suoi riscontri considerati nel prodotto e le novità presentate in anteprima.' },
    ],
  },
  profiles: {
    title: 'Con chi lavoriamo',
    items: [
      { title: 'Fiduciarie e consulenti', text: 'Clienti meglio organizzati, fatture QR pulite e cifre affidabili alla chiusura.' },
      { title: 'Architetti e studi tecnici', text: 'Imprese partner che consegnano preventivi chiari e rapporti di cantiere aggiornati.' },
      { title: 'Fornitori e commercianti', text: 'Un servizio in più per i suoi clienti artigiani, oltre al materiale.' },
      { title: 'Integratori e agenzie', text: 'Una soluzione svizzera da proporre nella digitalizzazione di una PMI edile.' },
    ],
  },
  example: {
    title: 'Un esempio concreto',
    line: '4 imprese con il piano Team (CHF 79 / mese)',
    calc: 'CHF 79 × 4 × 25\u00a0%',
    monthly: 'CHF 79 al mese per lei',
    yearly: 'ossia CHF 948 in 12 mesi',
    footnote: 'Commissione calcolata sugli importi effettivamente incassati, IVA esclusa.',
  },
  steps: {
    title: 'Come funziona',
    items: [
      { title: 'Si iscriva', text: 'Crei il suo conto partner in due minuti. Riceve un link personale e il relativo codice QR.' },
      { title: 'Raccomandi', text: 'I suoi contatti scoprono Cantia tramite il suo link. La loro iscrizione le viene attribuita per 90 giorni dopo il clic.' },
      { title: 'Venga pagato', text: 'Secondo le condizioni concordate con lei. Ogni commissione è convalidata dopo 30 giorni e poi versata sul suo IBAN.' },
    ],
  },
  who: {
    title: 'Per chi?',
    items: [
      'Fiduciarie e consulenti PMI',
      'Architetti e studi tecnici',
      'Fornitori e commercianti di materiali',
      'Agenzie web e integratori',
      'Clienti Cantia soddisfatti',
      'Creatori di contenuti dell’edilizia',
    ],
  },
  rules: {
    title: 'Le regole, in breve',
    items: [
      { q: 'Quando vengo pagato?', a: 'Una volta al mese, verso il 5, tramite bonifico bancario, non appena ha almeno CHF 30 di commissioni disponibili. Al di sotto, l’importo è riportato al mese successivo.' },
      { q: 'Perché 30 giorni di attesa?', a: 'Una commissione diventa disponibile 30 giorni dopo il pagamento del cliente. Se nel frattempo il pagamento è rimborsato o contestato, la commissione è annullata.' },
      { q: 'Cosa vedo dei miei clienti?', a: 'Un riferimento anonimo (CNT-…), il piano, lo stato e le sue commissioni. Mai i loro dati, preventivi o cantieri.' },
      { q: 'Devo emettere una fattura?', a: 'No. Cantia le invia un estratto a ogni versamento. Le commissioni sono un reddito che dichiara lei stesso.' },
      { q: 'Posso usare il mio link?', a: 'No, le auto-raccomandazioni non danno diritto a una commissione. Conta il primo link cliccato.' },
      { q: 'Ho già un conto Cantia.', a: 'Acceda con le stesse credenziali: il suo spazio partner si aggiunge al suo conto.' },
    ],
  },
  finalCta: { title: 'Entri nella rete Cantia.', text: 'Parliamo dei suoi clienti e di come possiamo accompagnarli insieme.', cta: 'Diventa partner' },
  preview: {
    label: 'Anteprima del suo spazio',
    example: 'Esempio',
    link: 'cantia.ch/?ref=K7M2QX',
    stats: ['Clic', 'Iscrizioni', 'Clienti paganti'],
    rows: [
      { ref: 'CNT-1042', plan: 'Team', amount: '+ CHF 19.75' },
      { ref: 'CNT-1038', plan: 'Entreprise', amount: '+ CHF 32.25' },
      { ref: 'CNT-1031', plan: 'Essenziale', amount: '+ CHF 9.75' },
    ],
    available: 'Disponibile il 5 novembre',
  },
  figures: [
    { value: '25\u00a0%', label: 'di ogni pagamento' },
    { value: '12 mesi', label: 'per cliente raccomandato' },
    { value: '90 giorni', label: 'perché il clic conti' },
    { value: 'CHF 30', label: 'dal primo versamento' },
  ],
  simulator: {
    title: 'Remunerazione',
    text: 'Una stima secondo il numero di imprese che accompagna verso Cantia.',
    perMonth: 'CHF {price} / mese',
    monthly: 'al mese',
    yearly: 'in 12 mesi',
    total: 'Stima delle sue commissioni',
    note: 'Calcolo sugli abbonamenti mensili, IVA esclusa. Per un abbonamento annuale, riceve il 25\u00a0% dell’importo pagato.',
  },
  product: {
    title: 'Un software facile da raccomandare',
    text: 'Cantia è fatto in Svizzera per le imprese edili: i suoi contatti risparmiano tempo dalla prima settimana.',
    items: [
      { title: 'Preventivi e fatture QR', text: 'Un preventivo pulito in pochi minuti, firmato online, trasformato in fattura QR.' },
      { title: 'Rapporti dal cantiere', text: 'Foto, ore e dettatura vocale dal telefono, il rapporto parte da solo.' },
      { title: 'Pianificazione, ore, salari', text: 'Tutta la squadra in un unico posto, fino alle buste paga.' },
      { title: 'Ospitato in Svizzera', text: 'Dati a Zurigo, in italiano, francese e tedesco, 14 giorni di prova gratuita.' },
    ],
    cta: 'Scopri Cantia',
  },
  footer: { tagline: 'Il programma partner di Cantia, software svizzero di gestione dei cantieri.', site: 'cantia.ch', privacy: 'Privacy', terms: 'Condizioni', status: 'Stato del servizio' },
  auth: {
    sideTitle: 'Costruiamo il futuro insieme.',
    sideText: 'Raccomandi un software svizzero in cui crede e segua i suoi clienti dal suo spazio partner.',
    google: 'Continua con Google',
    or: 'oppure',
    loginTitle: 'Accesso',
    signupTitle: 'Crea un conto partner',
    sameAccount: 'Ha già un conto Cantia? Utilizzi le stesse credenziali.',
    firstName: 'Nome',
    lastName: 'Cognome',
    email: 'E-mail',
    password: 'Password',
    passwordHint: 'Almeno 8 caratteri',
    login: 'Accedi',
    signup: 'Crea il mio conto',
    toSignup: 'Nessun conto? Crea un conto',
    toLogin: 'Ha già un conto? Accedi',
    forgot: 'Password dimenticata?',
    codeTitle: 'Verifichi la sua e-mail',
    codeText: 'Inserisca il codice ricevuto all’indirizzo {email}.',
    code: 'Codice',
    verify: 'Conferma',
    resend: 'Invia di nuovo il codice',
    resent: 'Codice inviato di nuovo.',
    missing: 'Compili tutti i campi.',
    shortPassword: 'La password deve contenere almeno 8 caratteri.',
    back: 'Indietro',
  },
  onboarding: {
    title: 'Il suo profilo partner',
    text: 'Queste informazioni servono per i suoi versamenti ed estratti. Non vengono mai mostrate ai suoi clienti.',
    company: 'Impresa (facoltativo)',
    type: 'Lei è',
    phone: 'Telefono (facoltativo)',
    address: 'Indirizzo',
    postalCode: 'NPA',
    city: 'Località',
    accept: 'Accetto le condizioni del programma: commissione personale concordata con Cantia, convalida dopo 30 giorni, versamento da CHF 30, nessuna auto-raccomandazione.',
    submit: 'Attiva il mio spazio partner',
    mustAccept: 'Accetti le condizioni del programma.',
  },
  types: {
    CONSULTANT: 'Fiduciaria / consulente',
    WEB_AGENCY: 'Agenzia web',
    SOFTWARE_INTEGRATOR: 'Integratore software',
    CANTIA_CUSTOMER: 'Cliente Cantia',
    BUSINESS: 'Impresa / fornitore',
    CONTENT_CREATOR: 'Creatore di contenuti',
    OTHER: 'Altro',
  },
  dashboard: {
    hello: 'Buongiorno {name}',
    signOut: 'Esci',
    linkTitle: 'Il suo link di raccomandazione',
    linkText: 'Lo condivida per e-mail, sul suo sito o sui social. Ogni iscrizione entro 90 giorni dal clic le viene attribuita.',
    copy: 'Copia il link',
    copied: 'Link copiato',
    code: 'Codice',
    qr: 'Codice QR da stampare o mostrare',
    stats: { clicks: 'Clic', visitors: 'Visitatori unici', signups: 'Iscrizioni', trials: 'In prova', active: 'Clienti paganti' },
    commissions: 'Commissioni',
    pending: 'In convalida',
    available: 'Disponibile',
    paid: 'Versato',
    commissionsSoon: 'Ogni pagamento dei suoi clienti apparirà qui con la sua data di disponibilità. Le commissioni sono calcolate dal primo pagamento, anche prima della loro visualizzazione.',
    referrals: 'Le sue raccomandazioni',
    noReferrals: 'Ancora nessuna iscrizione. Condivida il suo link per iniziare.',
    ref: 'Riferimento',
    since: 'Iscritto il',
    plan: 'Piano',
    status: 'Stato',
    statuses: { SIGNED_UP: 'Iscritto', TRIAL: 'In prova', ACTIVE: 'Cliente pagante', CANCELLED: 'Disdetto' },
    suspended: 'Il suo conto partner è sospeso. Il suo link non attribuisce più nuove iscrizioni. Ci contatti per saperne di più.',
    payout: 'Coordinate di pagamento',
    payoutText: 'I versamenti avvengono tramite bonifico su un conto svizzero o del Liechtenstein.',
    holder: 'Titolare del conto',
    iban: 'IBAN',
    saveIban: 'Salva',
    changeIban: 'Modifica',
    ibanSaved: 'Coordinate salvate.',
    noIban: 'Aggiunga il suo IBAN per ricevere i versamenti.',
    share: {
      title: 'Kit di condivisione',
      text: 'Un messaggio pronto da inviare ai suoi contatti, per e-mail o WhatsApp.',
      message: 'Buongiorno,\n\nUtilizzo e raccomando Cantia, un software svizzero per le imprese edili: preventivi, fatture QR, rapporti di cantiere, pianificazione e salari in un unico posto. Può provarlo gratuitamente per 14 giorni:\n{link}\n\nCordiali saluti,',
      copy: 'Copia il messaggio',
      copied: 'Messaggio copiato',
      downloadQr: 'Scarica il QR (PNG)',
    },
    memberSince: 'Partner dal {date}',
    active: 'Attivo',
    rules: 'Regole del programma',
  },
  loading: 'Caricamento…',
};

export const PARTNERS_COPY: Record<PartnersLocale, Copy> = { fr, de, it };

export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? ''));
}

// Monthly prices used by the landing simulator (CHF, excl. VAT), with each
// plan's name as shown on cantia.ch in every language.
export const SIMULATOR_PLANS: { id: string; price: number; names: Record<PartnersLocale, string> }[] = [
  { id: 'solo', price: 39, names: { fr: 'Essentiel', de: 'Basis', it: 'Essenziale' } },
  { id: 'equipe', price: 79, names: { fr: 'Équipe', de: 'Team', it: 'Team' } },
  { id: 'pro', price: 129, names: { fr: 'Entreprise', de: 'Entreprise', it: 'Entreprise' } },
];
