import { getAppLocale } from '../translations';

// Copy of the « mesure → positions du métré » panel (phase E).

const fr = {
  title: 'Affecter au métré',
  tender: 'Métré',
  noTender: 'Aucun métré sur ce chantier. Importez une soumission ou créez un métré pour y affecter vos mesures.',
  step1: '1. Qu’avez-vous mesuré ?',
  step2: '2. Dimensions',
  step2Hint: 'Saisies une fois pour cette mesure, elles servent à toutes ses positions.',
  step3: '3. Positions à alimenter',
  step3Hint: 'Cochez les positions que cette mesure alimente. Le calcul est affiché pour chacune.',
  elements: { wall: 'Mur / paroi', slab: 'Dalle / radier', footing: 'Semelle', surface: 'Surface', line: 'Longueur', items: 'Pièces' } as Record<string, string>,
  params: { height: 'Hauteur', thickness: 'Épaisseur', width: 'Largeur', faces: 'Faces', rate: 'Armature', factor: 'Nombre de fois' } as Record<string, string>,
  units: { height: 'm', thickness: 'm', width: 'm', faces: '', rate: 'kg/m³', factor: '×' } as Record<string, string>,
  factorHint: 'Ex. 7 villas identiques → 7',
  fromText: 'Lu dans la soumission : « {{q}} »',
  noSuggestion: 'Aucune position de ce métré ne correspond à ce type de mesure. Cherchez-la ci-dessous.',
  search: 'Chercher une autre position (numéro ou mot)…',
  missing: 'À indiquer : {{list}}',
  needsScale: 'Calibrez le plan pour calculer les quantités.',
  useMeasured: 'Utiliser la quantité mesurée dans le métré',
  assign1: 'Affecter à 1 position',
  pickFirst: 'Cochez au moins une position',
  assignN: 'Affecter à {{n}} positions',
  assigned: 'Déjà affecté',
  remove: 'Retirer',
  keepActive: 'Garder active',
  activeBanner: 'Position active : {{ref}} · chaque nouvelle mesure y est affectée',
  stop: 'Arrêter',
  more: 'Voir {{n}} autres',
  done: 'Affecté ✓',
  details: 'Nom, zone, note',
  measuredTotal: 'Total mesuré de la position : {{q}}',
  faces1: '1 face',
  faces2: '2 faces',
  formulas: { length: 'Longueur', perimeter: 'Périmètre', area: 'Surface', count: 'Nombre', wall_area: 'Longueur × hauteur', wall_formwork: 'Longueur × hauteur × faces', wall_volume: 'Longueur × hauteur × épaisseur', wall_rebar: 'Volume × kg/m³', strip_area: 'Longueur × largeur', strip_volume: 'Longueur × largeur × hauteur', slab_volume: 'Surface × épaisseur', slab_rebar: 'Surface × épaisseur × kg/m³', edge_formwork: 'Périmètre × hauteur', manual: 'Saisie' } as Record<string, string>,
  onPlans: 'Mesures sur plan',
  noMeasureYet: 'Pas encore mesurée. Ouvrez un plan du chantier, mesurez, puis affectez la mesure à cette position.',
  openPlan: 'Ouvrir sur le plan',
  measureOnPlan: 'Mesurer sur un plan',
};

type Copy = typeof fr;

const de: Copy = {
  title: 'Dem Ausmass zuweisen',
  tender: 'Ausmass',
  noTender: 'Kein Ausmass auf dieser Baustelle. Importieren Sie ein Leistungsverzeichnis oder erstellen Sie ein Ausmass.',
  step1: '1. Was haben Sie gemessen?',
  step2: '2. Abmessungen',
  step2Hint: 'Einmal pro Messung erfasst, gelten sie für alle ihre Positionen.',
  step3: '3. Positionen',
  step3Hint: 'Wählen Sie die Positionen, die diese Messung speist. Die Berechnung wird angezeigt.',
  elements: { wall: 'Wand', slab: 'Decke / Bodenplatte', footing: 'Fundament', surface: 'Fläche', line: 'Länge', items: 'Stück' },
  params: { height: 'Höhe', thickness: 'Stärke', width: 'Breite', faces: 'Seiten', rate: 'Bewehrung', factor: 'Anzahl' },
  units: { height: 'm', thickness: 'm', width: 'm', faces: '', rate: 'kg/m³', factor: '×' },
  factorHint: 'z. B. 7 gleiche Häuser → 7',
  fromText: 'Aus dem LV gelesen: «{{q}}»',
  noSuggestion: 'Keine Position passt zu dieser Messung. Suchen Sie sie unten.',
  search: 'Andere Position suchen (Nummer oder Wort)…',
  missing: 'Fehlt: {{list}}',
  needsScale: 'Kalibrieren Sie den Plan, um die Mengen zu berechnen.',
  useMeasured: 'Gemessene Menge im Ausmass verwenden',
  assign1: '1 Position zuweisen',
  pickFirst: 'Mindestens eine Position wählen',
  assignN: '{{n}} Positionen zuweisen',
  assigned: 'Bereits zugewiesen',
  remove: 'Entfernen',
  keepActive: 'Aktiv halten',
  activeBanner: 'Aktive Position: {{ref}} · jede neue Messung wird ihr zugewiesen',
  stop: 'Beenden',
  more: '{{n}} weitere anzeigen',
  done: 'Zugewiesen ✓',
  details: 'Name, Zone, Notiz',
  measuredTotal: 'Gemessene Gesamtmenge: {{q}}',
  faces1: '1 Seite',
  faces2: '2 Seiten',
  formulas: { length: 'Länge', perimeter: 'Umfang', area: 'Fläche', count: 'Anzahl', wall_area: 'Länge × Höhe', wall_formwork: 'Länge × Höhe × Seiten', wall_volume: 'Länge × Höhe × Stärke', wall_rebar: 'Volumen × kg/m³', strip_area: 'Länge × Breite', strip_volume: 'Länge × Breite × Höhe', slab_volume: 'Fläche × Stärke', slab_rebar: 'Fläche × Stärke × kg/m³', edge_formwork: 'Umfang × Höhe', manual: 'Eingabe' },
  onPlans: 'Messungen auf Plan',
  noMeasureYet: 'Noch nicht gemessen. Öffnen Sie einen Plan, messen Sie und weisen Sie die Messung dieser Position zu.',
  openPlan: 'Auf dem Plan öffnen',
  measureOnPlan: 'Auf einem Plan messen',
};

const it: Copy = {
  title: 'Assegna al computo',
  tender: 'Computo',
  noTender: 'Nessun computo su questo cantiere. Importate un capitolato o create un computo.',
  step1: '1. Cosa avete misurato?',
  step2: '2. Dimensioni',
  step2Hint: 'Inserite una volta per questa misura, valgono per tutte le sue posizioni.',
  step3: '3. Posizioni',
  step3Hint: 'Spuntate le posizioni alimentate da questa misura. Il calcolo è mostrato.',
  elements: { wall: 'Muro / parete', slab: 'Soletta / platea', footing: 'Fondazione', surface: 'Superficie', line: 'Lunghezza', items: 'Pezzi' },
  params: { height: 'Altezza', thickness: 'Spessore', width: 'Larghezza', faces: 'Facce', rate: 'Armatura', factor: 'Numero di volte' },
  units: { height: 'm', thickness: 'm', width: 'm', faces: '', rate: 'kg/m³', factor: '×' },
  factorHint: 'Es. 7 ville identiche → 7',
  fromText: 'Letto nel capitolato: «{{q}}»',
  noSuggestion: 'Nessuna posizione corrisponde a questa misura. Cercatela qui sotto.',
  search: 'Cerca un’altra posizione (numero o parola)…',
  missing: 'Da indicare: {{list}}',
  needsScale: 'Calibrate il piano per calcolare le quantità.',
  useMeasured: 'Usare la quantità misurata nel computo',
  assign1: 'Assegna a 1 posizione',
  pickFirst: 'Spuntate almeno una posizione',
  assignN: 'Assegna a {{n}} posizioni',
  assigned: 'Già assegnato',
  remove: 'Rimuovi',
  keepActive: 'Mantieni attiva',
  activeBanner: 'Posizione attiva: {{ref}} · ogni nuova misura le viene assegnata',
  stop: 'Interrompi',
  more: 'Mostra altre {{n}}',
  done: 'Assegnato ✓',
  details: 'Nome, zona, nota',
  measuredTotal: 'Totale misurato: {{q}}',
  faces1: '1 faccia',
  faces2: '2 facce',
  formulas: { length: 'Lunghezza', perimeter: 'Perimetro', area: 'Superficie', count: 'Numero', wall_area: 'Lunghezza × altezza', wall_formwork: 'Lunghezza × altezza × facce', wall_volume: 'Lunghezza × altezza × spessore', wall_rebar: 'Volume × kg/m³', strip_area: 'Lunghezza × larghezza', strip_volume: 'Lunghezza × larghezza × altezza', slab_volume: 'Superficie × spessore', slab_rebar: 'Superficie × spessore × kg/m³', edge_formwork: 'Perimetro × altezza', manual: 'Inserimento' },
  onPlans: 'Misure sul piano',
  noMeasureYet: 'Non ancora misurata. Aprite un piano, misurate e assegnate la misura a questa posizione.',
  openPlan: 'Apri sul piano',
  measureOnPlan: 'Misurare su un piano',
};

const COPY: Record<string, Copy> = { fr, de, it };

export function useAssignCopy(): Copy {
  return COPY[getAppLocale()] ?? fr;
}
