import { getAppLocale } from '../translations';

// Copy of the Métrés & Soumissions module (app/(app)/chantiers/[id]/metre*.tsx).

const fr = {
  moduleTitle: 'Métrés & soumissions',
  hintTitle: 'Une soumission, un métré, une offre',
  hintText: 'Importez la soumission PDF de l’architecte. Les quantités du document restent intactes : vous choisissez celles que vous offrez, ajoutez vos prix et Cantia calcule l’offre.',
  newTender: 'Nouveau métré',
  empty: 'Aucun métré sur ce chantier',
  emptyText: 'Importez la soumission PDF de l’architecte : les positions, quantités et chapitres sont repris automatiquement.',
  qtyToFill: 'Qté',
  qtyLockedHint: 'Soumission : la quantité est celle du document, vous remplissez seulement le prix.',
  qtyBlankHint: 'Le document laisse la quantité à indiquer : saisissez-la ici.',
  importOnly: 'Pour l’instant, un métré se crée uniquement en important une soumission (PDF). La création d’un métré vide arrivera plus tard.',
  positions: '{{n}} positions',
  onePosition: '1 position',
  noPosition: 'Aucune position',
  open: 'Ouvrir',
  duplicate: 'Dupliquer',
  delete: 'Supprimer',
  deleteConfirm: 'Supprimer « {{name}} » et toutes ses positions ? Cette action est définitive.',
  confirmDelete: 'Supprimer définitivement',
  cancel: 'Annuler',
  create: 'Créer',
  save: 'Enregistrer',
  name: 'Nom',
  namePlaceholder: 'Ex. 02 — Béton armé & maçonnerie',
  number: 'N° de soumission (facultatif)',
  cfc: 'CFC (facultatif)',
  kind: 'Type',
  kinds: { soumission: 'Soumission', interne: 'Métré interne', variante: 'Variante', complementaire: 'Travaux complémentaires' } as Record<string, string>,
  statuses: { draft: 'Brouillon', in_progress: 'En cours', priced: 'Chiffré', offered: 'Offre envoyée', archived: 'Archivé' } as Record<string, string>,
  sources: { manual: 'Saisie', pdf: 'PDF importé', duplicate: 'Copie', csv: 'Tableur', crbx: 'CRBX', legacy: 'Ancien métré' } as Record<string, string>,
  copySuffix: '(copie)',
  upsellTitle: 'Métrés & soumissions dès le plan Équipe',
  upsellText: 'Importez les soumissions, comparez vos quantités, chiffrez et créez l’offre. Vos métrés existants restent consultables.',
  upsellCta: 'Voir les plans',
  readOnly: 'Consultation',
  // editor
  back: 'Métrés',
  search: 'Rechercher : 241, 121.111, béton…',
  expandAll: 'Tout déplier',
  collapseAll: 'Tout replier',
  addSection: 'Chapitre',
  addPosition: 'Position',
  addSectionTitle: 'Nouveau chapitre',
  addPositionTitle: 'Nouvelle position',
  reference: 'Référence',
  title: 'Désignation',
  description: 'Description complète',
  unit: 'Unité',
  quantity: 'Quantité',
  colPosition: 'Position',
  colDescription: 'Désignation',
  colOriginal: 'Soumission',
  colMeasured: 'Métré',
  colGap: 'Écart',
  colSelected: 'Retenu',
  colUnit: 'Unité',
  colPrice: 'PU',
  colAmount: 'Montant',
  colStatus: 'Statut',
  qtyOriginal: 'Quantité soumission',
  qtyMeasured: 'Quantité mesurée',
  qtyManual: 'Quantité manuelle',
  qtySelected: 'Quantité retenue',
  qtyOriginalHint: 'Telle que reçue dans la soumission. Jamais modifiée.',
  qtyMeasuredHint: 'Somme des mesures affectées depuis les plans.',
  manualNote: 'Commentaire (ex. mesuré sur place le 12.10.2026)',
  useSource: { original: 'Soumission', measured: 'Mesurée', manual: 'Manuelle' } as Record<string, string>,
  unitPrice: 'Prix unitaire (CHF)',
  amount: 'Montant',
  priceHidden: 'Prix masqués (permission Finances requise)',
  breakdowns: 'Ventilation',
  breakdownCheckOk: 'La somme des zones correspond au total.',
  breakdownCheckBad: 'La somme des zones ({{sum}}) ne correspond pas au total ({{total}}).',
  zoneLabel: 'Que signifie « {{code}} » ?',
  provenance: 'Provenance',
  sourcePage: 'Page {{page}} du document',
  rawText: 'Texte source',
  noSource: 'Saisi dans Cantia',
  history: 'Historique',
  historyEmpty: 'Aucune modification enregistrée.',
  fields: { unit: 'Unité', quantity_manual: 'Quantité manuelle', quantity_selected_source: 'Quantité utilisée', quantity_selected: 'Quantité retenue', excluded: 'Exclue', unit_price: 'Prix unitaire', price_source: 'Source du prix', label: 'Libellé' } as Record<string, string>,
  exclude: 'Exclure de l’offre',
  excluded: 'Exclue',
  reserved: 'Position de réserve (R)',
  toReview: 'À vérifier',
  markValidated: 'Marquer comme vérifiée',
  deleteNode: 'Supprimer cette ligne',
  deleteNodeConfirm: 'Supprimer cette ligne et tout ce qu’elle contient ?',
  saving: 'Enregistrement…',
  saved: 'Enregistré',
  saveFailed: 'Échec de l’enregistrement : {{error}}',
  totals: 'Totaux',
  brut: 'Brut',
  discount: 'Rabais',
  subtotal1: 'Sous-total 1',
  escompte: 'Escompte',
  subtotal2: 'Sous-total 2',
  vat: 'TVA',
  net: 'Net',
  statPositions: 'positions',
  statPriced: 'chiffrées',
  statNoPrice: 'sans prix',
  statToReview: 'à vérifier',
  statTotal: 'Total net',
  notFound: 'Ce métré est introuvable ou vous n’y avez pas accès.',
  desktopOnly: 'La création et la modification de mesures sur plan sont actuellement disponibles sur ordinateur.',
  close: 'Fermer',
  noUnit: '—',
  // import
  importPdf: 'Importer une soumission (PDF)',
  importTitle: 'Importer une soumission',
  importIntro: 'PDF de l’architecte, CAN ou non. Le fichier original est conservé tel quel dans les documents du chantier ; rien n’est créé avant votre validation.',
  importDesktopHint: 'L’analyse se fait dans votre navigateur. Sur téléphone, préférez un ordinateur pour la vérification.',
  importPick: 'Choisir un PDF',
  importSteps: { reading: 'Lecture du fichier', uploading: 'Conservation de l’original', extracting: 'Extraction du texte', ocr: 'Lecture du PDF scanné', parsing: 'Détection des positions', saving: 'Préparation du brouillon', done: 'Analyse terminée' } as Record<string, string>,
  importStepOf: 'Étape {{n}}/5',
  importPage: 'page {{page}}/{{pages}}',
  pendingImports: 'Imports à terminer',
  resume: 'Reprendre',
  discard: 'Abandonner',
  failed: 'Échec',
  reviewTitle: 'Vérification de l’import',
  analysisDone: 'Analyse terminée',
  detected: '{{n}} positions détectées',
  ready: '{{n}} prêtes',
  toCheck: '{{n}} à vérifier',
  questionsCount: '{{n}} questions',
  reviewN: 'Vérifier les {{n}} éléments',
  filterAll: 'Tout',
  filterReview: 'À vérifier',
  questions: 'Questions',
  questionUnitApply: 'Appliqué à toutes les lignes avec cette unité ({{n}}).',
  zoneOptional: 'Facultatif — vous pourrez le compléter plus tard.',
  classificationQ: 'Ce document semble utiliser une structure CAN. Confirmer ?',
  classificationCan: 'Oui, CAN',
  classificationCustom: 'Non, structure libre',
  validated: 'Vérifiée',
  validate: 'Valider',
  removeLine: 'Ignorer cette ligne',
  restoreLine: 'Réintégrer',
  removed: 'Ignorée',
  importName: 'Nom du métré',
  importAs: 'Importer comme',
  importFinal: 'Créer le métré',
  importing: 'Création…',
  docMeta: 'Document',
  metaOwner: 'Maître d’ouvrage',
  metaArchitect: 'Architecte',
  metaEngineer: 'Ingénieur',
  metaProject: 'Projet',
  metaDate: 'Date',
  ocrBanner: 'PDF scanné lu automatiquement : vérifiez les quantités avant de valider.',
  issues: { unit_unknown: 'Unité non reconnue', unit_missing: 'Unité absente', quantity_missing: 'Quantité absente', breakdown_sum: 'Somme des zones ≠ total', amount_mismatch: 'Quantité × prix ≠ montant', orphan_quantity: 'Quantité sans position', number_ambiguous: 'Numérotation ambiguë' } as Record<string, string>,
  sourcePageShort: 'p. {{page}}',
  page: 'Page',
  prevPage: 'Page précédente',
  nextPage: 'Page suivante',
  // review v2
  suggestions: 'Prix suggérés (vos métrés et votre catalogue)',
  suggestionLabels: { document: 'Document', last_used: 'Dernier prix', history_average: 'Moyenne', catalog: 'Catalogue' } as Record<string, string>,
  priceSources: { document: 'Prix du document', manual: 'Saisi à la main', catalog: 'Depuis le catalogue', last_used: 'Dernier prix utilisé', history_average: 'Moyenne de vos métrés', external: 'Source externe' } as Record<string, string>,
  fillPrices: 'Remplir les prix',
  fillTitle: 'Remplir les prix manquants',
  fillIntro: '{{n}} positions sans prix ont un prix dans vos anciens métrés ou votre catalogue. Choisissez ceux à appliquer : vous pourrez toujours les modifier.',
  fillNone: 'Aucun prix trouvé dans vos anciens métrés ni dans votre catalogue pour les positions sans prix.',
  fillApply: 'Appliquer {{n}} prix',
  fillAll: 'Tout cocher',
  fillNoneSel: 'Tout décocher',
  exportXlsx: 'Excel',
  createDevis: 'Créer le devis',
  recapBtn: 'Récapitulatif',
  recapTitle: 'Récapitulatif de l’offre',
  recapIntro: 'Vérifiez les totaux, les conditions et la TVA, puis validez : ce sont ces chiffres qui iront dans la soumission (page de titre, récapitulatif, totaux).',
  recapChapters: 'Par chapitre',
  recapUnpriced: '{{n}} positions sans prix : elles resteront vides dans la soumission.',
  recapDocVat: 'Taux imprimé dans la soumission : {{rate}} %',
  recapSaveCatalog: 'Enregistrer mes prix au catalogue par n° CAN (repris dans les prochaines soumissions)',
  recapValidate: 'Valider le récapitulatif',
  recapValidated: 'Récapitulatif validé',
  recapSaved: '{{n}} prix enregistrés au catalogue',
  recapNext: 'Il ne reste qu’à télécharger la soumission remplie et à la renvoyer.',
  openDevis: 'Ouvrir le devis',
  offerTitle: 'Créer le devis à partir du métré',
  offerIntro: 'Un devis Cantia normal est créé avec les quantités retenues et vos prix : vous pourrez le modifier, l’envoyer et le suivre comme d’habitude.',
  offerClient: 'Client',
  offerUnpriced: 'Inclure les positions sans prix (à 0.00)',
  offerSummary: '{{n}} positions · total net CHF {{total}}',
  offerExists: 'Un devis a déjà été créé depuis ce métré.',
  filterPositions: 'Positions',
  filterTree: 'Arborescence',
  filterNoPrice: 'Sans prix',
  filterGap: 'Écarts de quantité',
  rvRemainingNote: '{{n}} point(s) encore à vérifier : ils seront importés et marqués « À vérifier » dans le métré.',
  rvTitle: 'Vérifier la soumission',
  rvPages: '{{n}} pages',
  rvFound: 'Ce que Cantia a trouvé',
  rvPositions: 'positions',
  rvReady: 'prêtes',
  rvToCheck: 'à vérifier',
  rvChapters: '{{n}} chapitres',
  rvStartOne: 'Vérifier le point restant',
  rvStartN: 'Vérifier les {{n}} points',
  rvAllGood: 'Tout est prêt. Vous pouvez créer le métré.',
  rvAnswer: 'À répondre avant de créer le métré',
  rvDocInfo: 'Informations du document',
  rvZones: 'Zones de la soumission ({{n}})',
  rvZonesHint: 'Facultatif. Exemple : A-B = Villas A et B.',
  rvContent: 'Contenu détecté',
  rvBack: 'Retour à la liste',
  rvPointOf: 'Point {{i}} sur {{n}}',
  rvOk: 'C’est bon',
  rvOkNext: 'C’est bon, suivant',
  rvIgnore: 'Ignorer cette ligne',
  rvRestore: 'Réintégrer la ligne',
  rvIgnored: 'Cette ligne ne sera pas importée.',
  rvQuantity: 'Quantité',
  rvQuantityPh: 'À compléter',
  rvShowPdf: 'Voir dans le PDF',
  rvShowSource: 'Voir le texte du document',
  rvHideSource: 'Masquer le texte du document',
  rvZoneTable: 'Répartition par zone',
  rvNoZone: '—',
  rvCreate: 'Créer le métré',
  rvCreateN: 'Créer le métré · {{n}} positions',
  rvName: 'Nom du métré',
  rvType: 'Type',
  rvCheckedAll: 'Tout est vérifié',
  rvRemaining: '{{n}} à vérifier',
  rvHelp: {
    quantity_missing: 'Le document n’indique pas de quantité{{raw}}. Saisissez-la si vous la connaissez, sinon laissez vide : vous la compléterez dans le métré.',
    unit_unknown: 'L’unité « {{unit}} » n’est pas reconnue. Choisissez la bonne unité ci-dessous.',
    unit_missing: 'Aucune unité n’est indiquée. Choisissez-la ci-dessous.',
    breakdown_sum: 'La somme des zones ne correspond pas au total imprimé. Comparez avec le PDF.',
    amount_mismatch: 'Quantité × prix ne donne pas le montant imprimé. Comparez avec le PDF.',
    orphan_quantity: 'Une quantité a été trouvée sans position claire. Vérifiez la désignation.',
    number_ambiguous: 'La numérotation de cette ligne n’est pas claire. Vérifiez sa place dans le PDF.',
  } as Record<string, string>,
  rvOk1: 'Tout semble correct. Comparez avec le PDF si besoin.',
  exportBtn: 'Exporter',
  exportTitle: 'Exporter le métré',
  exportPdf: 'PDF de la soumission, rempli',
  exportPdfHint: 'Le PDF de l’architecte, avec vos prix unitaires, montants, reports et totaux écrits dans ses propres cases. Prêt à signer et à rendre.',
  exportNoPdf: 'Pas de PDF d’origine pour ce métré (créé à la main) : utilisez Excel ou le devis.',
  basisDocument: 'Quantités de la soumission',
  basisDocumentHint: 'Recommandé : l’architecte compare les offres sur ses quantités.',
  basisSelected: 'Quantités retenues',
  basisSelectedHint: 'Vos quantités mesurées ou corrigées, si elles diffèrent.',
  exportExcel: 'Tableur Excel',
  exportExcelHint: 'Toutes les positions avec quantités, prix et montants.',
  exportGo: 'Télécharger',
  exportWorking: 'Préparation du PDF…',
  exportDone: '{{n}} positions remplies · total CHF {{total}}',
  exportUnpriced: '{{n}} positions sans prix laissées vides',
  exportNotPlaced: '{{n}} positions chiffrées sans case dans le PDF',
};

type Copy = typeof fr;

const de: Copy = {
  ...fr,
  moduleTitle: 'Ausmass & Devis',
  hintTitle: 'Ein Leistungsverzeichnis, ein Ausmass, ein Angebot',
  hintText: 'Importieren Sie das PDF-Leistungsverzeichnis des Architekten. Die Mengen des Dokuments bleiben unverändert: Sie wählen die angebotenen Mengen, ergänzen Ihre Preise und Cantia berechnet das Angebot.',
  newTender: 'Neues Ausmass',
  empty: 'Kein Ausmass auf dieser Baustelle',
  emptyText: 'Importieren Sie das PDF-Leistungsverzeichnis: Positionen, Mengen und Kapitel werden automatisch übernommen.',
  qtyToFill: 'Menge',
  qtyLockedHint: 'Leistungsverzeichnis: Die Menge ist vorgegeben, Sie ergänzen nur den Preis.',
  qtyBlankHint: 'Das LV lässt die Menge offen: geben Sie sie hier ein.',
  importOnly: 'Vorerst wird ein Ausmass nur durch Import eines Leistungsverzeichnisses (PDF) erstellt. Leere Ausmasse folgen später.',
  positions: '{{n}} Positionen',
  onePosition: '1 Position',
  noPosition: 'Keine Position',
  open: 'Öffnen',
  duplicate: 'Duplizieren',
  delete: 'Löschen',
  deleteConfirm: '«{{name}}» und alle Positionen löschen? Dies kann nicht rückgängig gemacht werden.',
  confirmDelete: 'Endgültig löschen',
  cancel: 'Abbrechen',
  create: 'Erstellen',
  save: 'Speichern',
  name: 'Name',
  namePlaceholder: 'z. B. 02 — Stahlbeton & Mauerwerk',
  number: 'Devis-Nr. (optional)',
  cfc: 'BKP (optional)',
  kind: 'Art',
  kinds: { soumission: 'Leistungsverzeichnis', interne: 'Internes Ausmass', variante: 'Variante', complementaire: 'Zusatzarbeiten' },
  statuses: { draft: 'Entwurf', in_progress: 'In Arbeit', priced: 'Kalkuliert', offered: 'Angebot gesendet', archived: 'Archiviert' },
  sources: { manual: 'Erfasst', pdf: 'PDF importiert', duplicate: 'Kopie', csv: 'Tabelle', crbx: 'CRBX', legacy: 'Altes Ausmass' },
  copySuffix: '(Kopie)',
  upsellTitle: 'Ausmass & Devis ab dem Plan Team',
  upsellText: 'Leistungsverzeichnisse importieren, Mengen vergleichen, kalkulieren und das Angebot erstellen. Bestehende Ausmasse bleiben einsehbar.',
  upsellCta: 'Pläne ansehen',
  readOnly: 'Nur Lesen',
  back: 'Ausmasse',
  search: 'Suchen: 241, 121.111, Beton…',
  expandAll: 'Alles aufklappen',
  collapseAll: 'Alles zuklappen',
  addSection: 'Kapitel',
  addPosition: 'Position',
  addSectionTitle: 'Neues Kapitel',
  addPositionTitle: 'Neue Position',
  reference: 'Referenz',
  title: 'Bezeichnung',
  description: 'Vollständige Beschreibung',
  unit: 'Einheit',
  quantity: 'Menge',
  colPosition: 'Position',
  colDescription: 'Bezeichnung',
  colOriginal: 'LV',
  colMeasured: 'Ausmass',
  colGap: 'Differenz',
  colSelected: 'Gewählt',
  colUnit: 'Einheit',
  colPrice: 'EP',
  colAmount: 'Betrag',
  colStatus: 'Status',
  qtyOriginal: 'Menge LV',
  qtyMeasured: 'Gemessene Menge',
  qtyManual: 'Manuelle Menge',
  qtySelected: 'Gewählte Menge',
  qtyOriginalHint: 'Wie im Leistungsverzeichnis erhalten. Wird nie geändert.',
  qtyMeasuredHint: 'Summe der zugewiesenen Planmessungen.',
  manualNote: 'Kommentar (z. B. vor Ort gemessen am 12.10.2026)',
  useSource: { original: 'LV', measured: 'Gemessen', manual: 'Manuell' },
  unitPrice: 'Einheitspreis (CHF)',
  amount: 'Betrag',
  priceHidden: 'Preise ausgeblendet (Berechtigung Finanzen erforderlich)',
  breakdowns: 'Aufteilung',
  breakdownCheckOk: 'Die Summe der Zonen entspricht dem Total.',
  breakdownCheckBad: 'Die Summe der Zonen ({{sum}}) entspricht nicht dem Total ({{total}}).',
  zoneLabel: 'Was bedeutet «{{code}}»?',
  provenance: 'Herkunft',
  sourcePage: 'Seite {{page}} des Dokuments',
  rawText: 'Quelltext',
  noSource: 'In Cantia erfasst',
  history: 'Verlauf',
  historyEmpty: 'Keine Änderungen erfasst.',
  fields: { unit: 'Einheit', quantity_manual: 'Manuelle Menge', quantity_selected_source: 'Verwendete Menge', quantity_selected: 'Gewählte Menge', excluded: 'Ausgeschlossen', unit_price: 'Einheitspreis', price_source: 'Preisquelle', label: 'Bezeichnung' },
  exclude: 'Vom Angebot ausschliessen',
  excluded: 'Ausgeschlossen',
  reserved: 'Reserveposition (R)',
  toReview: 'Zu prüfen',
  markValidated: 'Als geprüft markieren',
  deleteNode: 'Diese Zeile löschen',
  deleteNodeConfirm: 'Diese Zeile mit ihrem ganzen Inhalt löschen?',
  saving: 'Speichern…',
  saved: 'Gespeichert',
  saveFailed: 'Speichern fehlgeschlagen: {{error}}',
  totals: 'Totale',
  brut: 'Brutto',
  discount: 'Rabatt',
  subtotal1: 'Zwischentotal 1',
  escompte: 'Skonto',
  subtotal2: 'Zwischentotal 2',
  vat: 'MWST',
  net: 'Netto',
  statPositions: 'Positionen',
  statPriced: 'kalkuliert',
  statNoPrice: 'ohne Preis',
  statToReview: 'zu prüfen',
  statTotal: 'Total netto',
  notFound: 'Dieses Ausmass existiert nicht oder Sie haben keinen Zugriff.',
  desktopOnly: 'Messungen auf Plänen können derzeit nur am Computer erstellt und bearbeitet werden.',
  close: 'Schliessen',
  importPdf: 'Leistungsverzeichnis importieren (PDF)',
  importTitle: 'Leistungsverzeichnis importieren',
  importIntro: 'PDF des Architekten, NPK oder nicht. Die Originaldatei bleibt unverändert in den Baustellendokumenten; nichts wird vor Ihrer Bestätigung erstellt.',
  importDesktopHint: 'Die Analyse läuft in Ihrem Browser. Für die Prüfung empfehlen wir einen Computer.',
  importPick: 'PDF auswählen',
  importSteps: { reading: 'Datei lesen', uploading: 'Original sichern', extracting: 'Text extrahieren', ocr: 'Gescanntes PDF lesen', parsing: 'Positionen erkennen', saving: 'Entwurf vorbereiten', done: 'Analyse abgeschlossen' },
  importStepOf: 'Schritt {{n}}/5',
  importPage: 'Seite {{page}}/{{pages}}',
  pendingImports: 'Offene Importe',
  resume: 'Fortsetzen',
  discard: 'Verwerfen',
  failed: 'Fehlgeschlagen',
  reviewTitle: 'Import prüfen',
  analysisDone: 'Analyse abgeschlossen',
  detected: '{{n}} Positionen erkannt',
  ready: '{{n}} bereit',
  toCheck: '{{n}} zu prüfen',
  questionsCount: '{{n}} Fragen',
  reviewN: '{{n}} Elemente prüfen',
  filterAll: 'Alle',
  filterReview: 'Zu prüfen',
  questions: 'Fragen',
  questionUnitApply: 'Gilt für alle Zeilen mit dieser Einheit ({{n}}).',
  zoneOptional: 'Optional — kann später ergänzt werden.',
  classificationQ: 'Dieses Dokument scheint eine NPK-Struktur zu verwenden. Bestätigen?',
  classificationCan: 'Ja, NPK',
  classificationCustom: 'Nein, freie Struktur',
  validated: 'Geprüft',
  validate: 'Bestätigen',
  removeLine: 'Zeile ignorieren',
  restoreLine: 'Wiederherstellen',
  removed: 'Ignoriert',
  importName: 'Name des Ausmasses',
  importAs: 'Importieren als',
  importFinal: 'Ausmass erstellen',
  importing: 'Wird erstellt…',
  docMeta: 'Dokument',
  metaOwner: 'Bauherr',
  metaArchitect: 'Architekt',
  metaEngineer: 'Ingenieur',
  metaProject: 'Projekt',
  metaDate: 'Datum',
  ocrBanner: 'Gescanntes PDF automatisch gelesen: Mengen vor der Bestätigung prüfen.',
  issues: { unit_unknown: 'Einheit unbekannt', unit_missing: 'Einheit fehlt', quantity_missing: 'Menge fehlt', breakdown_sum: 'Summe der Zonen ≠ Total', amount_mismatch: 'Menge × Preis ≠ Betrag', orphan_quantity: 'Menge ohne Position', number_ambiguous: 'Nummerierung unklar' },
  sourcePageShort: 'S. {{page}}',
  page: 'Seite',
  prevPage: 'Vorherige Seite',
  nextPage: 'Nächste Seite',
  suggestions: 'Vorgeschlagene Preise (Ihre Ausmasse und Ihr Katalog)',
  suggestionLabels: { document: 'Dokument', last_used: 'Letzter Preis', history_average: 'Durchschnitt', catalog: 'Katalog' },
  priceSources: { document: 'Preis aus dem Dokument', manual: 'Manuell erfasst', catalog: 'Aus dem Katalog', last_used: 'Zuletzt verwendeter Preis', history_average: 'Durchschnitt Ihrer Ausmasse', external: 'Externe Quelle' },
  fillPrices: 'Preise ausfüllen',
  fillTitle: 'Fehlende Preise ausfüllen',
  fillIntro: '{{n}} Positionen ohne Preis haben einen Preis in früheren Ausmassen oder im Katalog. Wählen Sie, welche übernommen werden: Sie bleiben änderbar.',
  fillNone: 'Für die Positionen ohne Preis wurde weder in früheren Ausmassen noch im Katalog ein Preis gefunden.',
  fillApply: '{{n}} Preise übernehmen',
  fillAll: 'Alle wählen',
  fillNoneSel: 'Keine wählen',
  exportXlsx: 'Excel',
  createDevis: 'Offerte erstellen',
  recapBtn: 'Zusammenfassung',
  recapTitle: 'Zusammenfassung des Angebots',
  recapIntro: 'Prüfen Sie Summen, Konditionen und MWST und bestätigen Sie: Diese Zahlen kommen ins Leistungsverzeichnis.',
  recapChapters: 'Nach Kapitel',
  recapUnpriced: '{{n}} Positionen ohne Preis: Sie bleiben im LV leer.',
  recapDocVat: 'Im LV gedruckter Satz: {{rate}} %',
  recapSaveCatalog: 'Meine Preise nach NPK-Nummer im Katalog speichern (für die nächsten LV)',
  recapValidate: 'Zusammenfassung bestätigen',
  recapValidated: 'Zusammenfassung bestätigt',
  recapSaved: '{{n}} Preise im Katalog gespeichert',
  recapNext: 'Laden Sie das ausgefüllte LV herunter und senden Sie es zurück.',
  openDevis: 'Offerte öffnen',
  offerTitle: 'Offerte aus dem Ausmass erstellen',
  offerIntro: 'Es wird eine normale Cantia-Offerte mit den gewählten Mengen und Ihren Preisen erstellt: Sie können sie wie gewohnt bearbeiten, senden und verfolgen.',
  offerClient: 'Kunde',
  offerUnpriced: 'Positionen ohne Preis einschliessen (0.00)',
  offerSummary: '{{n}} Positionen · Total netto CHF {{total}}',
  offerExists: 'Aus diesem Ausmass wurde bereits eine Offerte erstellt.',
  filterPositions: 'Positionen',
  filterTree: 'Struktur',
  filterNoPrice: 'Ohne Preis',
  filterGap: 'Mengendifferenzen',
  rvRemainingNote: 'Noch {{n}} Punkt(e) zu prüfen: Sie werden importiert und im Ausmass als «Zu prüfen» markiert.',
  rvTitle: 'Leistungsverzeichnis prüfen',
  rvPages: '{{n}} Seiten',
  rvFound: 'Was Cantia gefunden hat',
  rvPositions: 'Positionen',
  rvReady: 'bereit',
  rvToCheck: 'zu prüfen',
  rvChapters: '{{n}} Kapitel',
  rvStartOne: 'Letzten Punkt prüfen',
  rvStartN: '{{n}} Punkte prüfen',
  rvAllGood: 'Alles bereit. Sie können das Ausmass erstellen.',
  rvAnswer: 'Vor dem Erstellen zu beantworten',
  rvDocInfo: 'Angaben zum Dokument',
  rvZones: 'Zonen des Leistungsverzeichnisses ({{n}})',
  rvZonesHint: 'Optional. Beispiel: A-B = Villen A und B.',
  rvContent: 'Erkannter Inhalt',
  rvBack: 'Zurück zur Liste',
  rvPointOf: 'Punkt {{i}} von {{n}}',
  rvOk: 'In Ordnung',
  rvOkNext: 'In Ordnung, weiter',
  rvIgnore: 'Zeile ignorieren',
  rvRestore: 'Zeile wiederherstellen',
  rvIgnored: 'Diese Zeile wird nicht importiert.',
  rvQuantity: 'Menge',
  rvQuantityPh: 'Zu ergänzen',
  rvShowPdf: 'Im PDF anzeigen',
  rvShowSource: 'Text des Dokuments anzeigen',
  rvHideSource: 'Text ausblenden',
  rvZoneTable: 'Aufteilung nach Zone',
  rvCreate: 'Ausmass erstellen',
  rvCreateN: 'Ausmass erstellen · {{n}} Positionen',
  rvName: 'Name des Ausmasses',
  rvType: 'Art',
  rvCheckedAll: 'Alles geprüft',
  rvRemaining: '{{n}} zu prüfen',
  rvHelp: {
    quantity_missing: 'Das Dokument nennt keine Menge{{raw}}. Tragen Sie sie ein, falls bekannt, sonst leer lassen: Sie ergänzen sie im Ausmass.',
    unit_unknown: 'Die Einheit «{{unit}}» ist unbekannt. Wählen Sie unten die richtige Einheit.',
    unit_missing: 'Keine Einheit angegeben. Wählen Sie sie unten.',
    breakdown_sum: 'Die Summe der Zonen entspricht nicht dem gedruckten Total. Vergleichen Sie mit dem PDF.',
    amount_mismatch: 'Menge × Preis ergibt nicht den gedruckten Betrag. Vergleichen Sie mit dem PDF.',
    orphan_quantity: 'Menge ohne klare Position gefunden. Bitte Bezeichnung prüfen.',
    number_ambiguous: 'Die Nummerierung ist unklar. Prüfen Sie die Stelle im PDF.',
  },
  rvOk1: 'Alles scheint korrekt. Bei Bedarf mit dem PDF vergleichen.',
  exportBtn: 'Exportieren',
  exportTitle: 'Ausmass exportieren',
  exportPdf: 'LV-PDF, ausgefüllt',
  exportPdfHint: 'Das PDF des Architekten mit Ihren Einheitspreisen, Beträgen, Überträgen und Summen in seinen eigenen Feldern.',
  exportNoPdf: 'Kein Original-PDF für dieses Ausmass: verwenden Sie Excel oder die Offerte.',
  basisDocument: 'Mengen des LV',
  basisDocumentHint: 'Empfohlen: Der Architekt vergleicht die Offerten auf seinen Mengen.',
  basisSelected: 'Gewählte Mengen',
  basisSelectedHint: 'Ihre gemessenen oder korrigierten Mengen.',
  exportExcel: 'Excel-Tabelle',
  exportExcelHint: 'Alle Positionen mit Mengen, Preisen und Beträgen.',
  exportGo: 'Herunterladen',
  exportWorking: 'PDF wird vorbereitet…',
  exportDone: '{{n}} Positionen ausgefüllt · Total CHF {{total}}',
  exportUnpriced: '{{n}} Positionen ohne Preis leer gelassen',
  exportNotPlaced: '{{n}} Positionen ohne Feld im PDF',
};

const it: Copy = {
  ...fr,
  moduleTitle: 'Computi & capitolati',
  hintTitle: 'Un capitolato, un computo, un’offerta',
  hintText: 'Importate il capitolato PDF dell’architetto. Le quantità del documento restano intatte: scegliete quelle che offrite, aggiungete i prezzi e Cantia calcola l’offerta.',
  newTender: 'Nuovo computo',
  empty: 'Nessun computo su questo cantiere',
  emptyText: 'Importate il capitolato PDF: posizioni, quantità e capitoli vengono ripresi automaticamente.',
  qtyToFill: 'Qtà',
  qtyLockedHint: 'Capitolato: la quantità è data, inserite solo il prezzo.',
  qtyBlankHint: 'Il capitolato lascia la quantità da indicare: inseritela qui.',
  importOnly: 'Per ora un computo si crea solo importando un capitolato (PDF). I computi vuoti arriveranno più tardi.',
  positions: '{{n}} posizioni',
  onePosition: '1 posizione',
  noPosition: 'Nessuna posizione',
  open: 'Apri',
  duplicate: 'Duplica',
  delete: 'Elimina',
  deleteConfirm: 'Eliminare «{{name}}» e tutte le sue posizioni? L’azione è definitiva.',
  confirmDelete: 'Elimina definitivamente',
  cancel: 'Annulla',
  create: 'Crea',
  save: 'Salva',
  name: 'Nome',
  namePlaceholder: 'Es. 02 — Cemento armato & muratura',
  number: 'N° capitolato (facoltativo)',
  cfc: 'CCC (facoltativo)',
  kind: 'Tipo',
  kinds: { soumission: 'Capitolato', interne: 'Computo interno', variante: 'Variante', complementaire: 'Lavori complementari' },
  statuses: { draft: 'Bozza', in_progress: 'In corso', priced: 'Prezzato', offered: 'Offerta inviata', archived: 'Archiviato' },
  sources: { manual: 'Inserito', pdf: 'PDF importato', duplicate: 'Copia', csv: 'Foglio di calcolo', crbx: 'CRBX', legacy: 'Vecchio computo' },
  copySuffix: '(copia)',
  upsellTitle: 'Computi & capitolati dal piano Team',
  upsellText: 'Importate i capitolati, confrontate le quantità, prezzate e create l’offerta. I computi esistenti restano consultabili.',
  upsellCta: 'Vedi i piani',
  readOnly: 'Sola lettura',
  back: 'Computi',
  search: 'Cerca: 241, 121.111, calcestruzzo…',
  expandAll: 'Espandi tutto',
  collapseAll: 'Comprimi tutto',
  addSection: 'Capitolo',
  addPosition: 'Posizione',
  addSectionTitle: 'Nuovo capitolo',
  addPositionTitle: 'Nuova posizione',
  reference: 'Riferimento',
  title: 'Designazione',
  description: 'Descrizione completa',
  unit: 'Unità',
  quantity: 'Quantità',
  colPosition: 'Posizione',
  colDescription: 'Designazione',
  colOriginal: 'Capitolato',
  colMeasured: 'Misurato',
  colGap: 'Scarto',
  colSelected: 'Scelto',
  colUnit: 'Unità',
  colPrice: 'PU',
  colAmount: 'Importo',
  colStatus: 'Stato',
  qtyOriginal: 'Quantità capitolato',
  qtyMeasured: 'Quantità misurata',
  qtyManual: 'Quantità manuale',
  qtySelected: 'Quantità scelta',
  qtyOriginalHint: 'Come ricevuta nel capitolato. Mai modificata.',
  qtyMeasuredHint: 'Somma delle misure assegnate dai piani.',
  manualNote: 'Commento (es. misurato sul posto il 12.10.2026)',
  useSource: { original: 'Capitolato', measured: 'Misurata', manual: 'Manuale' },
  unitPrice: 'Prezzo unitario (CHF)',
  amount: 'Importo',
  priceHidden: 'Prezzi nascosti (permesso Finanze richiesto)',
  breakdowns: 'Ripartizione',
  breakdownCheckOk: 'La somma delle zone corrisponde al totale.',
  breakdownCheckBad: 'La somma delle zone ({{sum}}) non corrisponde al totale ({{total}}).',
  zoneLabel: 'Cosa significa «{{code}}»?',
  provenance: 'Provenienza',
  sourcePage: 'Pagina {{page}} del documento',
  rawText: 'Testo sorgente',
  noSource: 'Inserito in Cantia',
  history: 'Cronologia',
  historyEmpty: 'Nessuna modifica registrata.',
  fields: { unit: 'Unità', quantity_manual: 'Quantità manuale', quantity_selected_source: 'Quantità usata', quantity_selected: 'Quantità scelta', excluded: 'Esclusa', unit_price: 'Prezzo unitario', price_source: 'Fonte del prezzo', label: 'Etichetta' },
  exclude: 'Escludere dall’offerta',
  excluded: 'Esclusa',
  reserved: 'Posizione di riserva (R)',
  toReview: 'Da verificare',
  markValidated: 'Segna come verificata',
  deleteNode: 'Elimina questa riga',
  deleteNodeConfirm: 'Eliminare questa riga e tutto il suo contenuto?',
  saving: 'Salvataggio…',
  saved: 'Salvato',
  saveFailed: 'Salvataggio non riuscito: {{error}}',
  totals: 'Totali',
  brut: 'Lordo',
  discount: 'Sconto',
  subtotal1: 'Subtotale 1',
  escompte: 'Sconto cassa',
  subtotal2: 'Subtotale 2',
  vat: 'IVA',
  net: 'Netto',
  statPositions: 'posizioni',
  statPriced: 'prezzate',
  statNoPrice: 'senza prezzo',
  statToReview: 'da verificare',
  statTotal: 'Totale netto',
  notFound: 'Questo computo non esiste o non avete accesso.',
  desktopOnly: 'La creazione e la modifica di misure su pianta sono attualmente disponibili solo su computer.',
  close: 'Chiudi',
  importPdf: 'Importa un capitolato (PDF)',
  importTitle: 'Importa un capitolato',
  importIntro: 'PDF dell’architetto, CPN o no. Il file originale resta invariato nei documenti del cantiere; nulla viene creato prima della vostra conferma.',
  importDesktopHint: 'L’analisi avviene nel browser. Per la verifica è preferibile un computer.',
  importPick: 'Scegli un PDF',
  importSteps: { reading: 'Lettura del file', uploading: 'Conservazione dell’originale', extracting: 'Estrazione del testo', ocr: 'Lettura del PDF scansionato', parsing: 'Riconoscimento delle posizioni', saving: 'Preparazione della bozza', done: 'Analisi terminata' },
  importStepOf: 'Passo {{n}}/5',
  importPage: 'pagina {{page}}/{{pages}}',
  pendingImports: 'Importazioni da completare',
  resume: 'Riprendi',
  discard: 'Abbandona',
  failed: 'Fallita',
  reviewTitle: 'Verifica dell’importazione',
  analysisDone: 'Analisi terminata',
  detected: '{{n}} posizioni rilevate',
  ready: '{{n}} pronte',
  toCheck: '{{n}} da verificare',
  questionsCount: '{{n}} domande',
  reviewN: 'Verifica i {{n}} elementi',
  filterAll: 'Tutto',
  filterReview: 'Da verificare',
  questions: 'Domande',
  questionUnitApply: 'Applicato a tutte le righe con questa unità ({{n}}).',
  zoneOptional: 'Facoltativo — potrete completarlo più tardi.',
  classificationQ: 'Questo documento sembra usare una struttura CPN. Confermare?',
  classificationCan: 'Sì, CPN',
  classificationCustom: 'No, struttura libera',
  validated: 'Verificata',
  validate: 'Conferma',
  removeLine: 'Ignora questa riga',
  restoreLine: 'Ripristina',
  removed: 'Ignorata',
  importName: 'Nome del computo',
  importAs: 'Importa come',
  importFinal: 'Crea il computo',
  importing: 'Creazione…',
  docMeta: 'Documento',
  metaOwner: 'Committente',
  metaArchitect: 'Architetto',
  metaEngineer: 'Ingegnere',
  metaProject: 'Progetto',
  metaDate: 'Data',
  ocrBanner: 'PDF scansionato letto automaticamente: verificate le quantità prima di confermare.',
  issues: { unit_unknown: 'Unità non riconosciuta', unit_missing: 'Unità mancante', quantity_missing: 'Quantità mancante', breakdown_sum: 'Somma delle zone ≠ totale', amount_mismatch: 'Quantità × prezzo ≠ importo', orphan_quantity: 'Quantità senza posizione', number_ambiguous: 'Numerazione ambigua' },
  sourcePageShort: 'p. {{page}}',
  page: 'Pagina',
  prevPage: 'Pagina precedente',
  nextPage: 'Pagina successiva',
  suggestions: 'Prezzi suggeriti (vostri computi e catalogo)',
  suggestionLabels: { document: 'Documento', last_used: 'Ultimo prezzo', history_average: 'Media', catalog: 'Catalogo' },
  priceSources: { document: 'Prezzo del documento', manual: 'Inserito a mano', catalog: 'Dal catalogo', last_used: 'Ultimo prezzo usato', history_average: 'Media dei vostri computi', external: 'Fonte esterna' },
  fillPrices: 'Compila i prezzi',
  fillTitle: 'Compila i prezzi mancanti',
  fillIntro: '{{n}} posizioni senza prezzo hanno un prezzo nei vostri computi precedenti o nel catalogo. Scegliete quali applicare: resteranno modificabili.',
  fillNone: 'Nessun prezzo trovato nei computi precedenti né nel catalogo per le posizioni senza prezzo.',
  fillApply: 'Applica {{n}} prezzi',
  fillAll: 'Seleziona tutto',
  fillNoneSel: 'Deseleziona tutto',
  exportXlsx: 'Excel',
  createDevis: 'Crea il preventivo',
  recapBtn: 'Riepilogo',
  recapTitle: 'Riepilogo dell’offerta',
  recapIntro: 'Verificate totali, condizioni e IVA, poi confermate: queste cifre andranno nel capitolato.',
  recapChapters: 'Per capitolo',
  recapUnpriced: '{{n}} posizioni senza prezzo: resteranno vuote nel capitolato.',
  recapDocVat: 'Aliquota stampata nel capitolato: {{rate}} %',
  recapSaveCatalog: 'Salva i miei prezzi nel catalogo per numero CPN (ripresi nei prossimi capitolati)',
  recapValidate: 'Conferma il riepilogo',
  recapValidated: 'Riepilogo confermato',
  recapSaved: '{{n}} prezzi salvati nel catalogo',
  recapNext: 'Scaricate il capitolato compilato e rinviatelo.',
  openDevis: 'Apri il preventivo',
  offerTitle: 'Crea il preventivo dal computo',
  offerIntro: 'Viene creato un normale preventivo Cantia con le quantità scelte e i vostri prezzi: potrete modificarlo, inviarlo e seguirlo come al solito.',
  offerClient: 'Cliente',
  offerUnpriced: 'Includere le posizioni senza prezzo (0.00)',
  offerSummary: '{{n}} posizioni · totale netto CHF {{total}}',
  offerExists: 'Da questo computo è già stato creato un preventivo.',
  filterPositions: 'Posizioni',
  filterTree: 'Struttura',
  filterNoPrice: 'Senza prezzo',
  filterGap: 'Scarti di quantità',
  rvRemainingNote: 'Ancora {{n}} punto/i da verificare: saranno importati e segnati «Da verificare» nel computo.',
  rvTitle: 'Verifica del capitolato',
  rvPages: '{{n}} pagine',
  rvFound: 'Cosa ha trovato Cantia',
  rvPositions: 'posizioni',
  rvReady: 'pronte',
  rvToCheck: 'da verificare',
  rvChapters: '{{n}} capitoli',
  rvStartOne: 'Verifica l’ultimo punto',
  rvStartN: 'Verifica i {{n}} punti',
  rvAllGood: 'Tutto pronto. Potete creare il computo.',
  rvAnswer: 'Da rispondere prima di creare il computo',
  rvDocInfo: 'Informazioni sul documento',
  rvZones: 'Zone del capitolato ({{n}})',
  rvZonesHint: 'Facoltativo. Esempio: A-B = Ville A e B.',
  rvContent: 'Contenuto rilevato',
  rvBack: 'Torna all’elenco',
  rvPointOf: 'Punto {{i}} di {{n}}',
  rvOk: 'Va bene',
  rvOkNext: 'Va bene, avanti',
  rvIgnore: 'Ignora questa riga',
  rvRestore: 'Ripristina la riga',
  rvIgnored: 'Questa riga non sarà importata.',
  rvQuantity: 'Quantità',
  rvQuantityPh: 'Da completare',
  rvShowPdf: 'Vedi nel PDF',
  rvShowSource: 'Vedi il testo del documento',
  rvHideSource: 'Nascondi il testo',
  rvZoneTable: 'Ripartizione per zona',
  rvCreate: 'Crea il computo',
  rvCreateN: 'Crea il computo · {{n}} posizioni',
  rvName: 'Nome del computo',
  rvType: 'Tipo',
  rvCheckedAll: 'Tutto verificato',
  rvRemaining: '{{n}} da verificare',
  rvHelp: {
    quantity_missing: 'Il documento non indica una quantità{{raw}}. Inseritela se la conoscete, altrimenti lasciate vuoto: la completerete nel computo.',
    unit_unknown: 'L’unità «{{unit}}» non è riconosciuta. Scegliete l’unità corretta qui sotto.',
    unit_missing: 'Nessuna unità indicata. Sceglietela qui sotto.',
    breakdown_sum: 'La somma delle zone non corrisponde al totale stampato. Confrontate con il PDF.',
    amount_mismatch: 'Quantità × prezzo non dà l’importo stampato. Confrontate con il PDF.',
    orphan_quantity: 'Quantità trovata senza posizione chiara. Verificate la designazione.',
    number_ambiguous: 'La numerazione non è chiara. Verificate nel PDF.',
  },
  rvOk1: 'Tutto sembra corretto. Confrontate con il PDF se necessario.',
  exportBtn: 'Esporta',
  exportTitle: 'Esporta il computo',
  exportPdf: 'PDF del capitolato, compilato',
  exportPdfHint: 'Il PDF dell’architetto, con prezzi unitari, importi, riporti e totali scritti nelle sue caselle.',
  exportNoPdf: 'Nessun PDF originale per questo computo: usate Excel o il preventivo.',
  basisDocument: 'Quantità del capitolato',
  basisDocumentHint: 'Consigliato: l’architetto confronta le offerte sulle sue quantità.',
  basisSelected: 'Quantità scelte',
  basisSelectedHint: 'Le vostre quantità misurate o corrette.',
  exportExcel: 'Foglio Excel',
  exportExcelHint: 'Tutte le posizioni con quantità, prezzi e importi.',
  exportGo: 'Scarica',
  exportWorking: 'Preparazione del PDF…',
  exportDone: '{{n}} posizioni compilate · totale CHF {{total}}',
  exportUnpriced: '{{n}} posizioni senza prezzo lasciate vuote',
  exportNotPlaced: '{{n}} posizioni senza casella nel PDF',
};

const COPY: Record<string, Copy> = { fr, de, it };

export function useTenderCopy(): Copy {
  return COPY[getAppLocale()] ?? fr;
}

export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, k) => String(vars[k] ?? ''));
}

export type TenderCopy = Copy;
