import { getAppLocale } from '../translations';

// Copy of the Métrés & Soumissions module (app/(app)/chantiers/[id]/metre*.tsx).

const fr = {
  moduleTitle: 'Métrés & soumissions',
  hintTitle: 'Une soumission, un métré, une offre',
  hintText: 'Importez la soumission de l’architecte ou partez d’un métré vide. Les quantités du document restent intactes : vous choisissez celles que vous offrez, ajoutez vos prix et Cantia calcule l’offre.',
  newTender: 'Nouveau métré',
  empty: 'Aucun métré sur ce chantier',
  emptyText: 'Importez la soumission PDF de l’architecte, créez un métré vide ou dupliquez-en un existant.',
  positions: '{{n}} positions',
  onePosition: '1 position',
  noPosition: 'Aucune position',
  open: 'Ouvrir',
  duplicate: 'Dupliquer',
  delete: 'Supprimer',
  deleteConfirm: 'Supprimer « {{name}} » et toutes ses positions ? Cette action est définitive.',
  confirmDelete: 'Supprimer définitivement',
  cancel: 'Annuler',
  create: 'Créer',
  save: 'Enregistrer',
  name: 'Nom',
  namePlaceholder: 'Ex. 02 — Béton armé & maçonnerie',
  number: 'N° de soumission (facultatif)',
  cfc: 'CFC (facultatif)',
  kind: 'Type',
  kinds: { soumission: 'Soumission', interne: 'Métré interne', variante: 'Variante', complementaire: 'Travaux complémentaires' } as Record<string, string>,
  statuses: { draft: 'Brouillon', in_progress: 'En cours', priced: 'Chiffré', offered: 'Offre envoyée', archived: 'Archivé' } as Record<string, string>,
  sources: { manual: 'Saisie', pdf: 'PDF importé', duplicate: 'Copie', csv: 'Tableur', crbx: 'CRBX', legacy: 'Ancien métré' } as Record<string, string>,
  copySuffix: '(copie)',
  upsellTitle: 'Métrés & soumissions dès le plan Équipe',
  upsellText: 'Importez les soumissions, comparez vos quantités, chiffrez et créez l’offre. Vos métrés existants restent consultables.',
  upsellCta: 'Voir les plans',
  readOnly: 'Lecture seule',
  // editor
  back: 'Métrés',
  search: 'Rechercher : 241, 121.111, béton…',
  expandAll: 'Tout déplier',
  collapseAll: 'Tout replier',
  addSection: 'Chapitre',
  addPosition: 'Position',
  addSectionTitle: 'Nouveau chapitre',
  addPositionTitle: 'Nouvelle position',
  reference: 'Référence',
  title: 'Désignation',
  description: 'Description complète',
  unit: 'Unité',
  quantity: 'Quantité',
  colPosition: 'Position',
  colDescription: 'Désignation',
  colOriginal: 'Soumission',
  colMeasured: 'Métré',
  colGap: 'Écart',
  colSelected: 'Retenu',
  colUnit: 'Unité',
  colPrice: 'PU',
  colAmount: 'Montant',
  colStatus: 'Statut',
  qtyOriginal: 'Quantité soumission',
  qtyMeasured: 'Quantité mesurée',
  qtyManual: 'Quantité manuelle',
  qtySelected: 'Quantité retenue',
  qtyOriginalHint: 'Telle que reçue dans la soumission. Jamais modifiée.',
  qtyMeasuredHint: 'Somme des mesures sur plan (bientôt).',
  manualNote: 'Commentaire (ex. mesuré sur place le 12.10.2026)',
  useSource: { original: 'Soumission', measured: 'Mesurée', manual: 'Manuelle' } as Record<string, string>,
  unitPrice: 'Prix unitaire (CHF)',
  amount: 'Montant',
  priceHidden: 'Prix masqués (permission Finances requise)',
  breakdowns: 'Ventilation',
  breakdownCheckOk: 'La somme des zones correspond au total.',
  breakdownCheckBad: 'La somme des zones ({{sum}}) ne correspond pas au total ({{total}}).',
  zoneLabel: 'Que signifie « {{code}} » ?',
  provenance: 'Provenance',
  sourcePage: 'Page {{page}} du document',
  rawText: 'Texte source',
  noSource: 'Saisi dans Cantia',
  history: 'Historique',
  historyEmpty: 'Aucune modification enregistrée.',
  fields: { unit: 'Unité', quantity_manual: 'Quantité manuelle', quantity_selected_source: 'Quantité utilisée', quantity_selected: 'Quantité retenue', excluded: 'Exclue', unit_price: 'Prix unitaire', price_source: 'Source du prix', label: 'Libellé' } as Record<string, string>,
  exclude: 'Exclure de l’offre',
  excluded: 'Exclue',
  reserved: 'Position de réserve (R)',
  toReview: 'À vérifier',
  markValidated: 'Marquer comme vérifiée',
  deleteNode: 'Supprimer cette ligne',
  deleteNodeConfirm: 'Supprimer cette ligne et tout ce qu’elle contient ?',
  saving: 'Enregistrement…',
  saved: 'Enregistré',
  saveFailed: 'Échec de l’enregistrement : {{error}}',
  totals: 'Totaux',
  brut: 'Brut',
  discount: 'Rabais',
  subtotal1: 'Sous-total 1',
  escompte: 'Escompte',
  subtotal2: 'Sous-total 2',
  vat: 'TVA',
  net: 'Net',
  statPositions: 'positions',
  statPriced: 'chiffrées',
  statNoPrice: 'sans prix',
  statToReview: 'à vérifier',
  statTotal: 'Total net',
  notFound: 'Ce métré est introuvable ou vous n’y avez pas accès.',
  desktopOnly: 'La création et la modification de mesures sur plan sont actuellement disponibles sur ordinateur.',
  close: 'Fermer',
  noUnit: '—',
  // import
  importPdf: 'Importer une soumission (PDF)',
  importTitle: 'Importer une soumission',
  importIntro: 'PDF de l’architecte, CAN ou non. Le fichier original est conservé tel quel dans les documents du chantier ; rien n’est créé avant votre validation.',
  importDesktopHint: 'L’analyse se fait dans votre navigateur. Sur téléphone, préférez un ordinateur pour la vérification.',
  importPick: 'Choisir un PDF',
  importSteps: { reading: 'Lecture du fichier', uploading: 'Conservation de l’original', extracting: 'Extraction du texte', ocr: 'Lecture du PDF scanné', parsing: 'Détection des positions', saving: 'Préparation du brouillon', done: 'Analyse terminée' } as Record<string, string>,
  importStepOf: 'Étape {{n}}/5',
  importPage: 'page {{page}}/{{pages}}',
  pendingImports: 'Imports à terminer',
  resume: 'Reprendre',
  discard: 'Abandonner',
  failed: 'Échec',
  reviewTitle: 'Vérification de l’import',
  analysisDone: 'Analyse terminée',
  detected: '{{n}} positions détectées',
  ready: '{{n}} prêtes',
  toCheck: '{{n}} à vérifier',
  questionsCount: '{{n}} questions',
  reviewN: 'Vérifier les {{n}} éléments',
  filterAll: 'Tout',
  filterReview: 'À vérifier',
  questions: 'Questions',
  questionUnitApply: 'Appliqué à toutes les lignes avec cette unité ({{n}}).',
  zoneOptional: 'Facultatif — vous pourrez le compléter plus tard.',
  classificationQ: 'Ce document semble utiliser une structure CAN. Confirmer ?',
  classificationCan: 'Oui, CAN',
  classificationCustom: 'Non, structure libre',
  validated: 'Vérifiée',
  validate: 'Valider',
  removeLine: 'Ignorer cette ligne',
  restoreLine: 'Réintégrer',
  removed: 'Ignorée',
  importName: 'Nom du métré',
  importAs: 'Importer comme',
  importFinal: 'Créer le métré',
  importing: 'Création…',
  docMeta: 'Document',
  metaOwner: 'Maître d’ouvrage',
  metaArchitect: 'Architecte',
  metaEngineer: 'Ingénieur',
  metaProject: 'Projet',
  metaDate: 'Date',
  ocrBanner: 'PDF scanné lu automatiquement : vérifiez les quantités avant de valider.',
  issues: { unit_unknown: 'Unité non reconnue', unit_missing: 'Unité absente', quantity_missing: 'Quantité absente', breakdown_sum: 'Somme des zones ≠ total', amount_mismatch: 'Quantité × prix ≠ montant', orphan_quantity: 'Quantité sans position', number_ambiguous: 'Numérotation ambiguë' } as Record<string, string>,
  sourcePageShort: 'p. {{page}}',
  page: 'Page',
  prevPage: 'Page précédente',
  nextPage: 'Page suivante',
};

type Copy = typeof fr;

const de: Copy = {
  ...fr,
  moduleTitle: 'Ausmass & Devis',
  hintTitle: 'Ein Leistungsverzeichnis, ein Ausmass, ein Angebot',
  hintText: 'Importieren Sie das Leistungsverzeichnis des Architekten oder starten Sie mit einem leeren Ausmass. Die Mengen des Dokuments bleiben unverändert: Sie wählen die angebotenen Mengen, ergänzen Ihre Preise und Cantia berechnet das Angebot.',
  newTender: 'Neues Ausmass',
  empty: 'Kein Ausmass auf dieser Baustelle',
  emptyText: 'Importieren Sie das PDF-Leistungsverzeichnis, erstellen Sie ein leeres Ausmass oder duplizieren Sie ein bestehendes.',
  positions: '{{n}} Positionen',
  onePosition: '1 Position',
  noPosition: 'Keine Position',
  open: 'Öffnen',
  duplicate: 'Duplizieren',
  delete: 'Löschen',
  deleteConfirm: '«{{name}}» und alle Positionen löschen? Dies kann nicht rückgängig gemacht werden.',
  confirmDelete: 'Endgültig löschen',
  cancel: 'Abbrechen',
  create: 'Erstellen',
  save: 'Speichern',
  name: 'Name',
  namePlaceholder: 'z. B. 02 — Stahlbeton & Mauerwerk',
  number: 'Devis-Nr. (optional)',
  cfc: 'BKP (optional)',
  kind: 'Art',
  kinds: { soumission: 'Leistungsverzeichnis', interne: 'Internes Ausmass', variante: 'Variante', complementaire: 'Zusatzarbeiten' },
  statuses: { draft: 'Entwurf', in_progress: 'In Arbeit', priced: 'Kalkuliert', offered: 'Angebot gesendet', archived: 'Archiviert' },
  sources: { manual: 'Erfasst', pdf: 'PDF importiert', duplicate: 'Kopie', csv: 'Tabelle', crbx: 'CRBX', legacy: 'Altes Ausmass' },
  copySuffix: '(Kopie)',
  upsellTitle: 'Ausmass & Devis ab dem Plan Team',
  upsellText: 'Leistungsverzeichnisse importieren, Mengen vergleichen, kalkulieren und das Angebot erstellen. Bestehende Ausmasse bleiben einsehbar.',
  upsellCta: 'Pläne ansehen',
  readOnly: 'Nur Lesen',
  back: 'Ausmasse',
  search: 'Suchen: 241, 121.111, Beton…',
  expandAll: 'Alles aufklappen',
  collapseAll: 'Alles zuklappen',
  addSection: 'Kapitel',
  addPosition: 'Position',
  addSectionTitle: 'Neues Kapitel',
  addPositionTitle: 'Neue Position',
  reference: 'Referenz',
  title: 'Bezeichnung',
  description: 'Vollständige Beschreibung',
  unit: 'Einheit',
  quantity: 'Menge',
  colPosition: 'Position',
  colDescription: 'Bezeichnung',
  colOriginal: 'LV',
  colMeasured: 'Ausmass',
  colGap: 'Differenz',
  colSelected: 'Gewählt',
  colUnit: 'Einheit',
  colPrice: 'EP',
  colAmount: 'Betrag',
  colStatus: 'Status',
  qtyOriginal: 'Menge LV',
  qtyMeasured: 'Gemessene Menge',
  qtyManual: 'Manuelle Menge',
  qtySelected: 'Gewählte Menge',
  qtyOriginalHint: 'Wie im Leistungsverzeichnis erhalten. Wird nie geändert.',
  qtyMeasuredHint: 'Summe der Planmessungen (bald).',
  manualNote: 'Kommentar (z. B. vor Ort gemessen am 12.10.2026)',
  useSource: { original: 'LV', measured: 'Gemessen', manual: 'Manuell' },
  unitPrice: 'Einheitspreis (CHF)',
  amount: 'Betrag',
  priceHidden: 'Preise ausgeblendet (Berechtigung Finanzen erforderlich)',
  breakdowns: 'Aufteilung',
  breakdownCheckOk: 'Die Summe der Zonen entspricht dem Total.',
  breakdownCheckBad: 'Die Summe der Zonen ({{sum}}) entspricht nicht dem Total ({{total}}).',
  zoneLabel: 'Was bedeutet «{{code}}»?',
  provenance: 'Herkunft',
  sourcePage: 'Seite {{page}} des Dokuments',
  rawText: 'Quelltext',
  noSource: 'In Cantia erfasst',
  history: 'Verlauf',
  historyEmpty: 'Keine Änderungen erfasst.',
  fields: { unit: 'Einheit', quantity_manual: 'Manuelle Menge', quantity_selected_source: 'Verwendete Menge', quantity_selected: 'Gewählte Menge', excluded: 'Ausgeschlossen', unit_price: 'Einheitspreis', price_source: 'Preisquelle', label: 'Bezeichnung' },
  exclude: 'Vom Angebot ausschliessen',
  excluded: 'Ausgeschlossen',
  reserved: 'Reserveposition (R)',
  toReview: 'Zu prüfen',
  markValidated: 'Als geprüft markieren',
  deleteNode: 'Diese Zeile löschen',
  deleteNodeConfirm: 'Diese Zeile mit ihrem ganzen Inhalt löschen?',
  saving: 'Speichern…',
  saved: 'Gespeichert',
  saveFailed: 'Speichern fehlgeschlagen: {{error}}',
  totals: 'Totale',
  brut: 'Brutto',
  discount: 'Rabatt',
  subtotal1: 'Zwischentotal 1',
  escompte: 'Skonto',
  subtotal2: 'Zwischentotal 2',
  vat: 'MWST',
  net: 'Netto',
  statPositions: 'Positionen',
  statPriced: 'kalkuliert',
  statNoPrice: 'ohne Preis',
  statToReview: 'zu prüfen',
  statTotal: 'Total netto',
  notFound: 'Dieses Ausmass existiert nicht oder Sie haben keinen Zugriff.',
  desktopOnly: 'Messungen auf Plänen können derzeit nur am Computer erstellt und bearbeitet werden.',
  close: 'Schliessen',
  importPdf: 'Leistungsverzeichnis importieren (PDF)',
  importTitle: 'Leistungsverzeichnis importieren',
  importIntro: 'PDF des Architekten, NPK oder nicht. Die Originaldatei bleibt unverändert in den Baustellendokumenten; nichts wird vor Ihrer Bestätigung erstellt.',
  importDesktopHint: 'Die Analyse läuft in Ihrem Browser. Für die Prüfung empfehlen wir einen Computer.',
  importPick: 'PDF auswählen',
  importSteps: { reading: 'Datei lesen', uploading: 'Original sichern', extracting: 'Text extrahieren', ocr: 'Gescanntes PDF lesen', parsing: 'Positionen erkennen', saving: 'Entwurf vorbereiten', done: 'Analyse abgeschlossen' },
  importStepOf: 'Schritt {{n}}/5',
  importPage: 'Seite {{page}}/{{pages}}',
  pendingImports: 'Offene Importe',
  resume: 'Fortsetzen',
  discard: 'Verwerfen',
  failed: 'Fehlgeschlagen',
  reviewTitle: 'Import prüfen',
  analysisDone: 'Analyse abgeschlossen',
  detected: '{{n}} Positionen erkannt',
  ready: '{{n}} bereit',
  toCheck: '{{n}} zu prüfen',
  questionsCount: '{{n}} Fragen',
  reviewN: '{{n}} Elemente prüfen',
  filterAll: 'Alle',
  filterReview: 'Zu prüfen',
  questions: 'Fragen',
  questionUnitApply: 'Gilt für alle Zeilen mit dieser Einheit ({{n}}).',
  zoneOptional: 'Optional — kann später ergänzt werden.',
  classificationQ: 'Dieses Dokument scheint eine NPK-Struktur zu verwenden. Bestätigen?',
  classificationCan: 'Ja, NPK',
  classificationCustom: 'Nein, freie Struktur',
  validated: 'Geprüft',
  validate: 'Bestätigen',
  removeLine: 'Zeile ignorieren',
  restoreLine: 'Wiederherstellen',
  removed: 'Ignoriert',
  importName: 'Name des Ausmasses',
  importAs: 'Importieren als',
  importFinal: 'Ausmass erstellen',
  importing: 'Wird erstellt…',
  docMeta: 'Dokument',
  metaOwner: 'Bauherr',
  metaArchitect: 'Architekt',
  metaEngineer: 'Ingenieur',
  metaProject: 'Projekt',
  metaDate: 'Datum',
  ocrBanner: 'Gescanntes PDF automatisch gelesen: Mengen vor der Bestätigung prüfen.',
  issues: { unit_unknown: 'Einheit unbekannt', unit_missing: 'Einheit fehlt', quantity_missing: 'Menge fehlt', breakdown_sum: 'Summe der Zonen ≠ Total', amount_mismatch: 'Menge × Preis ≠ Betrag', orphan_quantity: 'Menge ohne Position', number_ambiguous: 'Nummerierung unklar' },
  sourcePageShort: 'S. {{page}}',
  page: 'Seite',
  prevPage: 'Vorherige Seite',
  nextPage: 'Nächste Seite',
};

const it: Copy = {
  ...fr,
  moduleTitle: 'Computi & capitolati',
  hintTitle: 'Un capitolato, un computo, un’offerta',
  hintText: 'Importate il capitolato dell’architetto o partite da un computo vuoto. Le quantità del documento restano intatte: scegliete quelle che offrite, aggiungete i prezzi e Cantia calcola l’offerta.',
  newTender: 'Nuovo computo',
  empty: 'Nessun computo su questo cantiere',
  emptyText: 'Importate il capitolato PDF, create un computo vuoto o duplicatene uno esistente.',
  positions: '{{n}} posizioni',
  onePosition: '1 posizione',
  noPosition: 'Nessuna posizione',
  open: 'Apri',
  duplicate: 'Duplica',
  delete: 'Elimina',
  deleteConfirm: 'Eliminare «{{name}}» e tutte le sue posizioni? L’azione è definitiva.',
  confirmDelete: 'Elimina definitivamente',
  cancel: 'Annulla',
  create: 'Crea',
  save: 'Salva',
  name: 'Nome',
  namePlaceholder: 'Es. 02 — Cemento armato & muratura',
  number: 'N° capitolato (facoltativo)',
  cfc: 'CCC (facoltativo)',
  kind: 'Tipo',
  kinds: { soumission: 'Capitolato', interne: 'Computo interno', variante: 'Variante', complementaire: 'Lavori complementari' },
  statuses: { draft: 'Bozza', in_progress: 'In corso', priced: 'Prezzato', offered: 'Offerta inviata', archived: 'Archiviato' },
  sources: { manual: 'Inserito', pdf: 'PDF importato', duplicate: 'Copia', csv: 'Foglio di calcolo', crbx: 'CRBX', legacy: 'Vecchio computo' },
  copySuffix: '(copia)',
  upsellTitle: 'Computi & capitolati dal piano Team',
  upsellText: 'Importate i capitolati, confrontate le quantità, prezzate e create l’offerta. I computi esistenti restano consultabili.',
  upsellCta: 'Vedi i piani',
  readOnly: 'Sola lettura',
  back: 'Computi',
  search: 'Cerca: 241, 121.111, calcestruzzo…',
  expandAll: 'Espandi tutto',
  collapseAll: 'Comprimi tutto',
  addSection: 'Capitolo',
  addPosition: 'Posizione',
  addSectionTitle: 'Nuovo capitolo',
  addPositionTitle: 'Nuova posizione',
  reference: 'Riferimento',
  title: 'Designazione',
  description: 'Descrizione completa',
  unit: 'Unità',
  quantity: 'Quantità',
  colPosition: 'Posizione',
  colDescription: 'Designazione',
  colOriginal: 'Capitolato',
  colMeasured: 'Misurato',
  colGap: 'Scarto',
  colSelected: 'Scelto',
  colUnit: 'Unità',
  colPrice: 'PU',
  colAmount: 'Importo',
  colStatus: 'Stato',
  qtyOriginal: 'Quantità capitolato',
  qtyMeasured: 'Quantità misurata',
  qtyManual: 'Quantità manuale',
  qtySelected: 'Quantità scelta',
  qtyOriginalHint: 'Come ricevuta nel capitolato. Mai modificata.',
  qtyMeasuredHint: 'Somma delle misure su pianta (a breve).',
  manualNote: 'Commento (es. misurato sul posto il 12.10.2026)',
  useSource: { original: 'Capitolato', measured: 'Misurata', manual: 'Manuale' },
  unitPrice: 'Prezzo unitario (CHF)',
  amount: 'Importo',
  priceHidden: 'Prezzi nascosti (permesso Finanze richiesto)',
  breakdowns: 'Ripartizione',
  breakdownCheckOk: 'La somma delle zone corrisponde al totale.',
  breakdownCheckBad: 'La somma delle zone ({{sum}}) non corrisponde al totale ({{total}}).',
  zoneLabel: 'Cosa significa «{{code}}»?',
  provenance: 'Provenienza',
  sourcePage: 'Pagina {{page}} del documento',
  rawText: 'Testo sorgente',
  noSource: 'Inserito in Cantia',
  history: 'Cronologia',
  historyEmpty: 'Nessuna modifica registrata.',
  fields: { unit: 'Unità', quantity_manual: 'Quantità manuale', quantity_selected_source: 'Quantità usata', quantity_selected: 'Quantità scelta', excluded: 'Esclusa', unit_price: 'Prezzo unitario', price_source: 'Fonte del prezzo', label: 'Etichetta' },
  exclude: 'Escludere dall’offerta',
  excluded: 'Esclusa',
  reserved: 'Posizione di riserva (R)',
  toReview: 'Da verificare',
  markValidated: 'Segna come verificata',
  deleteNode: 'Elimina questa riga',
  deleteNodeConfirm: 'Eliminare questa riga e tutto il suo contenuto?',
  saving: 'Salvataggio…',
  saved: 'Salvato',
  saveFailed: 'Salvataggio non riuscito: {{error}}',
  totals: 'Totali',
  brut: 'Lordo',
  discount: 'Sconto',
  subtotal1: 'Subtotale 1',
  escompte: 'Sconto cassa',
  subtotal2: 'Subtotale 2',
  vat: 'IVA',
  net: 'Netto',
  statPositions: 'posizioni',
  statPriced: 'prezzate',
  statNoPrice: 'senza prezzo',
  statToReview: 'da verificare',
  statTotal: 'Totale netto',
  notFound: 'Questo computo non esiste o non avete accesso.',
  desktopOnly: 'La creazione e la modifica di misure su pianta sono attualmente disponibili solo su computer.',
  close: 'Chiudi',
  importPdf: 'Importa un capitolato (PDF)',
  importTitle: 'Importa un capitolato',
  importIntro: 'PDF dell’architetto, CPN o no. Il file originale resta invariato nei documenti del cantiere; nulla viene creato prima della vostra conferma.',
  importDesktopHint: 'L’analisi avviene nel browser. Per la verifica è preferibile un computer.',
  importPick: 'Scegli un PDF',
  importSteps: { reading: 'Lettura del file', uploading: 'Conservazione dell’originale', extracting: 'Estrazione del testo', ocr: 'Lettura del PDF scansionato', parsing: 'Riconoscimento delle posizioni', saving: 'Preparazione della bozza', done: 'Analisi terminata' },
  importStepOf: 'Passo {{n}}/5',
  importPage: 'pagina {{page}}/{{pages}}',
  pendingImports: 'Importazioni da completare',
  resume: 'Riprendi',
  discard: 'Abbandona',
  failed: 'Fallita',
  reviewTitle: 'Verifica dell’importazione',
  analysisDone: 'Analisi terminata',
  detected: '{{n}} posizioni rilevate',
  ready: '{{n}} pronte',
  toCheck: '{{n}} da verificare',
  questionsCount: '{{n}} domande',
  reviewN: 'Verifica i {{n}} elementi',
  filterAll: 'Tutto',
  filterReview: 'Da verificare',
  questions: 'Domande',
  questionUnitApply: 'Applicato a tutte le righe con questa unità ({{n}}).',
  zoneOptional: 'Facoltativo — potrete completarlo più tardi.',
  classificationQ: 'Questo documento sembra usare una struttura CPN. Confermare?',
  classificationCan: 'Sì, CPN',
  classificationCustom: 'No, struttura libera',
  validated: 'Verificata',
  validate: 'Conferma',
  removeLine: 'Ignora questa riga',
  restoreLine: 'Ripristina',
  removed: 'Ignorata',
  importName: 'Nome del computo',
  importAs: 'Importa come',
  importFinal: 'Crea il computo',
  importing: 'Creazione…',
  docMeta: 'Documento',
  metaOwner: 'Committente',
  metaArchitect: 'Architetto',
  metaEngineer: 'Ingegnere',
  metaProject: 'Progetto',
  metaDate: 'Data',
  ocrBanner: 'PDF scansionato letto automaticamente: verificate le quantità prima di confermare.',
  issues: { unit_unknown: 'Unità non riconosciuta', unit_missing: 'Unità mancante', quantity_missing: 'Quantità mancante', breakdown_sum: 'Somma delle zone ≠ totale', amount_mismatch: 'Quantità × prezzo ≠ importo', orphan_quantity: 'Quantità senza posizione', number_ambiguous: 'Numerazione ambigua' },
  sourcePageShort: 'p. {{page}}',
  page: 'Pagina',
  prevPage: 'Pagina precedente',
  nextPage: 'Pagina successiva',
};

const COPY: Record<string, Copy> = { fr, de, it };

export function useTenderCopy(): Copy {
  return COPY[getAppLocale()] ?? fr;
}

export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, k) => String(vars[k] ?? ''));
}

export type TenderCopy = Copy;
