import { getAppLocale } from '../translations';

// Copy of the plan measuring screens (phase D).

const fr = {
  plans: 'Plans',
  plansIntro: 'Importez les plans du chantier (PDF), calibrez l’échelle et mesurez longueurs, surfaces et quantités directement dessus.',
  uploadPlan: 'Importer un plan',
  newRevision: 'Nouvelle révision',
  noPlan: 'Aucun plan pour l’instant.',
  planName: 'Nom du plan',
  planNamePh: 'Rez-de-chaussée',
  planNumber: 'Numéro',
  revisionLabel: 'Révision',
  upload: 'Importer',
  cancel: 'Annuler',
  uploadSteps: { reading: 'Lecture du PDF…', uploading: 'Envoi du fichier…', saving: 'Enregistrement…' } as Record<string, string>,
  measures: '{{n}} mesures',
  oneMeasure: '1 mesure',
  noMeasure: 'Aucune mesure',
  calibrated: 'Calibré',
  notCalibrated: 'Non calibré',
  pages: '{{n}} pages',
  open: 'Ouvrir',
  delete: 'Supprimer',
  deletePlan: 'Supprimer le plan',
  deletePlanText: 'Le plan « {{name}} », toutes ses révisions et ses mesures seront supprimés.',
  confirmDelete: 'Supprimer définitivement',
  desktopOnly: 'La mesure se fait sur ordinateur. Ici, vous pouvez consulter le plan et ses mesures.',
  tools: {
    select: 'Sélection',
    calibrate: 'Calibrer',
    distance: 'Distance',
    polyline: 'Longueur',
    polygon: 'Surface',
    perimeter: 'Périmètre',
    count: 'Comptage',
  } as Record<string, string>,
  toolHelp: {
    select: 'Cliquez une mesure pour la sélectionner. Glissez ses points pour la corriger.',
    calibrate: 'Cliquez les deux extrémités d’une cote connue, puis saisissez sa longueur réelle.',
    distance: 'Cliquez le point de départ puis le point d’arrivée. Maj = horizontal / vertical.',
    polyline: 'Cliquez chaque point. Double-clic ou Entrée pour terminer. Retour arrière = dernier point.',
    polygon: 'Cliquez les angles de la surface. Cliquez le premier point, double-cliquez ou Entrée pour fermer.',
    perimeter: 'Cliquez les angles du contour. Cliquez le premier point ou Entrée pour fermer.',
    count: 'Cliquez chaque élément à compter. Entrée pour terminer.',
  } as Record<string, string>,
  scale: 'Échelle',
  scaleApprox: '≈ 1:{{n}}',
  calibrateFirst: 'Plan non calibré : les mesures seront calculées dès que l’échelle sera définie.',
  calibrateNow: 'Calibrer',
  calTitle: 'Calibrer la page',
  calByDim: 'Par une cote',
  calByScale: 'Par l’échelle',
  calRealLength: 'Longueur réelle de la cote (m)',
  calMeasuredPt: 'Longueur sur le plan : {{n}} pt',
  calScale: 'Échelle du plan',
  calScaleHint: 'Seulement si le PDF est à l’échelle d’origine (pas une copie réduite). Une cote est plus sûre.',
  calPickDim: 'Mesurer une cote sur le plan',
  calApply: 'Appliquer',
  calRemeasure: 'Les mesures existantes de cette page seront recalculées.',
  calInvalid: 'Valeur invalide',
  undo: 'Annuler',
  redo: 'Rétablir',
  zoomIn: 'Zoom avant',
  zoomOut: 'Zoom arrière',
  fit: 'Ajuster',
  saved: 'Enregistré',
  saving: 'Enregistrement…',
  list: 'Mesures',
  listEmpty: 'Choisissez un outil en haut puis cliquez sur le plan.',
  totals: 'Totaux de la page',
  name: 'Nom',
  zone: 'Zone',
  note: 'Note',
  color: 'Couleur',
  length: 'Longueur',
  area: 'Surface',
  perimeterLabel: 'Périmètre',
  countLabel: 'Nombre',
  pointsN: '{{n}} points',
  deleteMeasure: 'Supprimer la mesure',
  page: 'Page',
  pageOf: 'Page {{n}} / {{total}}',
  revision: 'Révision',
  active: 'active',
  oldRevision: 'Ancienne révision : consultation seulement.',
  makeActive: 'Rendre active',
  kindsShort: { distance: 'Distance', polyline: 'Longueur', polygon: 'Surface', perimeter: 'Périmètre', count: 'Comptage' } as Record<string, string>,
  back: 'Métrés',
  shortcuts: 'Raccourcis : Entrée terminer · Échap annuler · ⌘Z / Ctrl+Z annuler · Ctrl + molette zoom',
};

type Copy = typeof fr;

const de: Copy = {
  plans: 'Pläne',
  plansIntro: 'Importieren Sie die Pläne der Baustelle (PDF), kalibrieren Sie den Massstab und messen Sie Längen, Flächen und Stückzahlen direkt darauf.',
  uploadPlan: 'Plan importieren',
  newRevision: 'Neue Revision',
  noPlan: 'Noch keine Pläne.',
  planName: 'Planname',
  planNamePh: 'Erdgeschoss',
  planNumber: 'Nummer',
  revisionLabel: 'Revision',
  upload: 'Importieren',
  cancel: 'Abbrechen',
  uploadSteps: { reading: 'PDF wird gelesen…', uploading: 'Datei wird hochgeladen…', saving: 'Wird gespeichert…' },
  measures: '{{n}} Messungen',
  oneMeasure: '1 Messung',
  noMeasure: 'Keine Messung',
  calibrated: 'Kalibriert',
  notCalibrated: 'Nicht kalibriert',
  pages: '{{n}} Seiten',
  open: 'Öffnen',
  delete: 'Löschen',
  deletePlan: 'Plan löschen',
  deletePlanText: 'Der Plan «{{name}}», alle Revisionen und Messungen werden gelöscht.',
  confirmDelete: 'Endgültig löschen',
  desktopOnly: 'Gemessen wird am Computer. Hier können Sie den Plan und seine Messungen ansehen.',
  tools: { select: 'Auswahl', calibrate: 'Kalibrieren', distance: 'Distanz', polyline: 'Länge', polygon: 'Fläche', perimeter: 'Umfang', count: 'Zählen' },
  toolHelp: {
    select: 'Klicken Sie eine Messung an, um sie auszuwählen. Ziehen Sie die Punkte, um sie zu korrigieren.',
    calibrate: 'Klicken Sie die beiden Enden eines bekannten Masses an und geben Sie die reale Länge ein.',
    distance: 'Startpunkt und Endpunkt anklicken. Umschalt = horizontal / vertikal.',
    polyline: 'Jeden Punkt anklicken. Doppelklick oder Enter zum Beenden. Rücktaste = letzter Punkt.',
    polygon: 'Ecken der Fläche anklicken. Ersten Punkt anklicken, Doppelklick oder Enter zum Schliessen.',
    perimeter: 'Ecken des Umrisses anklicken. Ersten Punkt anklicken oder Enter zum Schliessen.',
    count: 'Jedes Element anklicken. Enter zum Beenden.',
  },
  scale: 'Massstab',
  scaleApprox: '≈ 1:{{n}}',
  calibrateFirst: 'Plan nicht kalibriert: Die Messungen werden berechnet, sobald der Massstab festgelegt ist.',
  calibrateNow: 'Kalibrieren',
  calTitle: 'Seite kalibrieren',
  calByDim: 'Über ein Mass',
  calByScale: 'Über den Massstab',
  calRealLength: 'Reale Länge des Masses (m)',
  calMeasuredPt: 'Länge auf dem Plan: {{n}} pt',
  calScale: 'Planmassstab',
  calScaleHint: 'Nur wenn das PDF im Originalmassstab ist (keine verkleinerte Kopie). Ein Mass ist sicherer.',
  calPickDim: 'Ein Mass auf dem Plan messen',
  calApply: 'Anwenden',
  calRemeasure: 'Die bestehenden Messungen dieser Seite werden neu berechnet.',
  calInvalid: 'Ungültiger Wert',
  undo: 'Rückgängig',
  redo: 'Wiederholen',
  zoomIn: 'Vergrössern',
  zoomOut: 'Verkleinern',
  fit: 'Einpassen',
  saved: 'Gespeichert',
  saving: 'Wird gespeichert…',
  list: 'Messungen',
  listEmpty: 'Wählen Sie oben ein Werkzeug und klicken Sie auf den Plan.',
  totals: 'Summen der Seite',
  name: 'Name',
  zone: 'Zone',
  note: 'Notiz',
  color: 'Farbe',
  length: 'Länge',
  area: 'Fläche',
  perimeterLabel: 'Umfang',
  countLabel: 'Anzahl',
  pointsN: '{{n}} Punkte',
  deleteMeasure: 'Messung löschen',
  page: 'Seite',
  pageOf: 'Seite {{n}} / {{total}}',
  revision: 'Revision',
  active: 'aktiv',
  oldRevision: 'Alte Revision: nur Ansicht.',
  makeActive: 'Aktiv setzen',
  kindsShort: { distance: 'Distanz', polyline: 'Länge', polygon: 'Fläche', perimeter: 'Umfang', count: 'Zählen' },
  back: 'Ausmasse',
  shortcuts: 'Tasten: Enter beenden · Esc abbrechen · ⌘Z / Ctrl+Z rückgängig · Ctrl + Mausrad Zoom',
};

const it: Copy = {
  plans: 'Piani',
  plansIntro: 'Importate i piani del cantiere (PDF), calibrate la scala e misurate lunghezze, superfici e quantità direttamente sul piano.',
  uploadPlan: 'Importa un piano',
  newRevision: 'Nuova revisione',
  noPlan: 'Ancora nessun piano.',
  planName: 'Nome del piano',
  planNamePh: 'Piano terreno',
  planNumber: 'Numero',
  revisionLabel: 'Revisione',
  upload: 'Importa',
  cancel: 'Annulla',
  uploadSteps: { reading: 'Lettura del PDF…', uploading: 'Invio del file…', saving: 'Salvataggio…' },
  measures: '{{n}} misure',
  oneMeasure: '1 misura',
  noMeasure: 'Nessuna misura',
  calibrated: 'Calibrato',
  notCalibrated: 'Non calibrato',
  pages: '{{n}} pagine',
  open: 'Apri',
  delete: 'Elimina',
  deletePlan: 'Elimina il piano',
  deletePlanText: 'Il piano «{{name}}», tutte le revisioni e le misure saranno eliminati.',
  confirmDelete: 'Elimina definitivamente',
  desktopOnly: 'Le misure si fanno al computer. Qui potete consultare il piano e le sue misure.',
  tools: { select: 'Selezione', calibrate: 'Calibra', distance: 'Distanza', polyline: 'Lunghezza', polygon: 'Superficie', perimeter: 'Perimetro', count: 'Conteggio' },
  toolHelp: {
    select: 'Cliccate una misura per selezionarla. Trascinate i punti per correggerla.',
    calibrate: 'Cliccate le due estremità di una quota nota, poi inserite la lunghezza reale.',
    distance: 'Cliccate il punto di partenza e quello di arrivo. Maiusc = orizzontale / verticale.',
    polyline: 'Cliccate ogni punto. Doppio clic o Invio per terminare. Backspace = ultimo punto.',
    polygon: 'Cliccate gli angoli della superficie. Cliccate il primo punto, doppio clic o Invio per chiudere.',
    perimeter: 'Cliccate gli angoli del contorno. Cliccate il primo punto o Invio per chiudere.',
    count: 'Cliccate ogni elemento da contare. Invio per terminare.',
  },
  scale: 'Scala',
  scaleApprox: '≈ 1:{{n}}',
  calibrateFirst: 'Piano non calibrato: le misure saranno calcolate appena la scala sarà definita.',
  calibrateNow: 'Calibra',
  calTitle: 'Calibra la pagina',
  calByDim: 'Con una quota',
  calByScale: 'Con la scala',
  calRealLength: 'Lunghezza reale della quota (m)',
  calMeasuredPt: 'Lunghezza sul piano: {{n}} pt',
  calScale: 'Scala del piano',
  calScaleHint: 'Solo se il PDF è nella scala originale (non una copia ridotta). Una quota è più sicura.',
  calPickDim: 'Misurare una quota sul piano',
  calApply: 'Applica',
  calRemeasure: 'Le misure esistenti di questa pagina saranno ricalcolate.',
  calInvalid: 'Valore non valido',
  undo: 'Annulla',
  redo: 'Ripristina',
  zoomIn: 'Ingrandisci',
  zoomOut: 'Riduci',
  fit: 'Adatta',
  saved: 'Salvato',
  saving: 'Salvataggio…',
  list: 'Misure',
  listEmpty: 'Scegliete uno strumento in alto e cliccate sul piano.',
  totals: 'Totali della pagina',
  name: 'Nome',
  zone: 'Zona',
  note: 'Nota',
  color: 'Colore',
  length: 'Lunghezza',
  area: 'Superficie',
  perimeterLabel: 'Perimetro',
  countLabel: 'Numero',
  pointsN: '{{n}} punti',
  deleteMeasure: 'Elimina la misura',
  page: 'Pagina',
  pageOf: 'Pagina {{n}} / {{total}}',
  revision: 'Revisione',
  active: 'attiva',
  oldRevision: 'Revisione precedente: solo consultazione.',
  makeActive: 'Rendi attiva',
  kindsShort: { distance: 'Distanza', polyline: 'Lunghezza', polygon: 'Superficie', perimeter: 'Perimetro', count: 'Conteggio' },
  back: 'Computi',
  shortcuts: 'Tasti: Invio terminare · Esc annullare · ⌘Z / Ctrl+Z annulla · Ctrl + rotella zoom',
};

const COPY: Record<string, Copy> = { fr, de, it };

export function usePlanCopy(): Copy {
  return COPY[getAppLocale()] ?? fr;
}
